#!/usr/bin/env python3
r"""gas_weight_areas - src/Cranberry.Zone/Generated/AugustGasWeightAreas.g.cs.

INPUT   C:\Aug2017\out\world_aug\z2-areas.json   (this repo's own tools/zone parse of Z2.zone)
OUTPUT  src/Cranberry.Zone/Generated/AugustGasWeightAreas.g.cs

WHAT IT IS (docs/118, AUDIT-gas G-a)

    The August client's own ``GasWeightArea.<Poi>`` volumes - nine axis-aligned boxes placed
    around named points of interest, and the only thing in the whole client that says anything
    at all about WHERE a safe zone should go. Daybreak rebuilt ring placement on 2017-06-29 so
    that "matches can now end almost anywhere on the map rather than just the middle", and these
    volumes are what that rework shipped into the world file.

    Everything emitted here is the CLIENT's number: the box's own min/max/centre/size, straight
    out of Z2.zone. Nothing in this file is a tuning. What Cranberry DOES with them - weight the
    endgame destination by footprint area, walk the ring toward the drawn point - is a ruling
    (rulings/gas.json GasSettings.CentrePlan / PoiWeightExponent), not a fact, and lives there.

    The vertical axis is dropped on purpose. Every gas circle in this server is horizontal
    (GasCircle compares X/Z only, because the client's own ce 01 / ce 02 readers never compare
    the vertical axis), so a box's Y extent has nothing to bear on a ring centre. It is still
    emitted as a comment so a reader can find the volume in the world file.

USAGE  python tools/world/gas_weight_areas.py [--areas z2-areas.json] [--out DIR]
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

DEFAULT_AREAS = Path(r"C:\Aug2017\out\world_aug\z2-areas.json")
DEFAULT_OUT_DIR = (
    Path(__file__).resolve().parents[2] / "src" / "Cranberry.Zone" / "Generated")
FILE_NAME = "AugustGasWeightAreas.g.cs"

PREFIX = "GasWeightArea."


def member_name(name: str) -> str:
    """``GasWeightArea.JayWildernessCamp.01`` -> ``JayWildernessCamp01``."""
    stem = name[len(PREFIX):]
    return "".join(part[:1].upper() + part[1:] for part in stem.split(".") if part)


def read(path: Path) -> list[dict]:
    areas = json.loads(path.read_text(encoding="utf-8"))
    rows = [a for a in areas if str(a.get("name", "")).startswith(PREFIX)]
    if not rows:
        raise SystemExit(f"{path}: no {PREFIX}* volume found")
    for row in rows:
        if row.get("shape") != "box":
            raise SystemExit(f"{row['name']}: shape is {row.get('shape')!r}, not 'box'")
    rows.sort(key=lambda a: a["name"])
    names = [member_name(a["name"]) for a in rows]
    if len(set(names)) != len(names):
        raise SystemExit("two volumes collapse onto the same C# member name")
    return rows


def f(value: float) -> str:
    text = repr(round(float(value), 4))
    return text + "f"


def emit(rows: list[dict]) -> str:
    total = sum((a["size"][0] * a["size"][2]) for a in rows)
    out: list[str] = []
    w = out.append
    w("// <auto-generated>")
    w(f"// Generated by tools/world/gas_weight_areas.py from out/world_aug/z2-areas.json")
    w("// (this repo's own parse of the August client's Z2.zone). Do not edit. The provenance")
    w("// header above is written by tools/pipeline/pipeline.py (docs/96).")
    w("// </auto-generated>")
    w("")
    w("#nullable enable")
    w("")
    w("using System.Numerics;")
    w("")
    w("namespace Cranberry.Zone.Generated;")
    w("")
    w("/// <summary>")
    w("/// One <c>GasWeightArea.&lt;Poi&gt;</c> volume of the August client's own Z2 world file, as an")
    w("/// axis-aligned rectangle on the horizontal plane.")
    w("/// </summary>")
    w("/// <param name=\"Name\">The volume's own name in Z2.zone, verbatim.</param>")
    w("/// <param name=\"AreaId\">The volume's own id in Z2.zone.</param>")
    w("/// <param name=\"MinX\">West edge, metres.</param>")
    w("/// <param name=\"MinZ\">South edge, metres.</param>")
    w("/// <param name=\"MaxX\">East edge, metres.</param>")
    w("/// <param name=\"MaxZ\">North edge, metres.</param>")
    w("public readonly record struct AugustGasWeightArea(")
    w("    string Name,")
    w("    uint AreaId,")
    w("    float MinX,")
    w("    float MinZ,")
    w("    float MaxX,")
    w("    float MaxZ)")
    w("{")
    w("    /// <summary>The box's centre on the horizontal plane.</summary>")
    w("    public Vector2 Centre => new((MinX + MaxX) * 0.5f, (MinZ + MaxZ) * 0.5f);")
    w("")
    w("    /// <summary>Width (X) of the box, metres.</summary>")
    w("    public float Width => MaxX - MinX;")
    w("")
    w("    /// <summary>Depth (Z) of the box, metres.</summary>")
    w("    public float Depth => MaxZ - MinZ;")
    w("")
    w("    /// <summary>Footprint, square metres - the client's own measure of how big this place is.</summary>")
    w("    public float FootprintArea => Width * Depth;")
    w("")
    w("    /// <summary>True when a horizontal point is inside (or on) this box.</summary>")
    w("    public bool Contains(float x, float z) => x >= MinX && x <= MaxX && z >= MinZ && z <= MaxZ;")
    w("}")
    w("")
    w("/// <summary>")
    w("/// The August client's own gas-weight volumes - the only statement the client makes about")
    w(f"/// where a safe zone belongs. {len(rows)} boxes, {total:,.0f} m&#178; of footprint between them,")
    w("/// read out of <c>Z2.zone</c> by <c>tools/world/gas_weight_areas.py</c>.")
    w("/// <para>")
    w("/// <b>Every number here is the client's</b> (grade CLIENT). How the server picks among them")
    w("/// is not: see <c>rulings/gas.json</c> <c>GasSettings.CentrePlan</c> and")
    w("/// <c>GasSettings.PoiWeightExponent</c>, and <c>Gas/GasWeightAreas.cs</c> for the draw.")
    w("/// </para>")
    w("/// </summary>")
    w("public static class AugustGasWeightAreas")
    w("{")
    w("    /// <summary>Every volume, ordered by the client's own name.</summary>")
    w("    public static readonly AugustGasWeightArea[] All =")
    w("    [")
    for row in rows:
        cx, cy, cz = row["center"]
        sx, sy, sz = row["size"]
        w(f"        // {row['name']}: centre ({cx:.1f}, {cz:.1f}), {sx:.1f} x {sz:.1f} m footprint")
        w(f"        //   ({sx * sz:,.0f} m2, {100.0 * sx * sz / total:.2f} % of the nine), "
          f"vertical extent {row['min'][1]:.1f}..{row['max'][1]:.1f} m")
        w(f"        new(\"{row['name']}\", {int(row['id'])}u, "
          f"{f(row['min'][0])}, {f(row['min'][2])}, {f(row['max'][0])}, {f(row['max'][2])}),")
    w("    ];")
    w("")
    w(f"    /// <summary>How many volumes the client ships: {len(rows)}.</summary>")
    w(f"    public const int Count = {len(rows)};")
    w("")
    w("    /// <summary>The sum of every volume's footprint, square metres.</summary>")
    w(f"    public const float TotalFootprintArea = {f(total)};")
    w("")
    for index, row in enumerate(rows):
        w(f"    /// <summary><c>{row['name']}</c> - index {index} of <see cref=\"All\"/>.</summary>")
        w(f"    public static ref readonly AugustGasWeightArea {member_name(row['name'])} => ref All[{index}];")
        if index != len(rows) - 1:
            w("")
    w("}")
    return "\n".join(out) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--areas", type=Path, default=DEFAULT_AREAS)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT_DIR)
    parser.add_argument("out_dir", nargs="?", type=Path, default=None,
                        help="positional staging directory (pipeline.py passes this)")
    args = parser.parse_args()

    out_dir = args.out_dir or args.out
    rows = read(args.areas)
    out_dir.mkdir(parents=True, exist_ok=True)
    target = out_dir / FILE_NAME
    target.write_text(emit(rows), encoding="utf-8", newline="\n")
    print(f"{FILE_NAME}: {len(rows)} GasWeightArea volume(s) -> {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
