#!/usr/bin/env python3
"""Derive footwear tiers from August ClientItemDefinitions.PASSIVE_ABILITY_ID."""
from pathlib import Path
import csv
import hashlib
import sys

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT.parent / "out/data_aug/ClientItemDefinitions.txt"
with SOURCE.open(encoding="utf-8-sig", newline="") as stream:
    rows = [{key.lstrip("#*"): value for key, value in row.items()}
            for row in csv.DictReader(stream, delimiter="^")]
tiers = {"1111709": "Stealth", "1111540": "Sturdy", "1111539": "Fast"}
entries = [f'        [{row["ID"]}] = FootwearTier.{tiers[row["PASSIVE_ABILITY_ID"]]},'
           for row in rows if row["ITEM_CLASS"] == "25005" and row["PASSIVE_ABILITY_ID"] in tiers]
text = f'''// Generated by tools/world/gen-footwear.py from August ClientItemDefinitions.txt.
// SHA256 {hashlib.sha256(SOURCE.read_bytes()).hexdigest()}
namespace Cranberry.Zone.Movement;

public static class FootwearItems
{{
    public static IReadOnlyDictionary<uint, FootwearTier> Tiers {{ get; }} = new Dictionary<uint, FootwearTier>
    {{
{chr(10).join(entries)}
    }};
}}
'''
destination = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "src/Cranberry.Zone/Movement"
destination.mkdir(parents=True, exist_ok=True)
(destination / "FootwearItems.g.cs").write_text(text, encoding="utf-8")
print(f"Derived {len(entries)} footwear items.")
