#!/usr/bin/env python3
"""Generate August vehicle skin choices from the client's extracted caret tables."""
from pathlib import Path
import csv
import hashlib

REPO = Path(__file__).resolve().parents[2]
DATA = REPO.parent / "out" / "data_aug"

def rows(name):
    with (DATA / name).open(encoding="utf-8-sig", newline="") as stream:
        return [{key.removeprefix("#*"): value for key, value in row.items()}
                for row in csv.DictReader(stream, delimiter="^")]

items = {int(row["ID"]): row for row in rows("ClientItemDefinitions.txt")}
choices = []
for row in rows("VehicleSkinMods.txt"):
    item = int(row["ITEM_ID"])
    choices.append(f'        new({row["VEHICLE_ID"]}, {row["MOD_POINT"]}, {item}, {items[item]["PARAM1"]}),')
sources = "\n".join(f"// {name}: SHA256 {hashlib.sha256((DATA / name).read_bytes()).hexdigest()}"
                    for name in ("VehicleSkinMods.txt", "ClientItemDefinitions.txt"))
output = f'''// Generated by tools/world/gen-vehicle-skins.py; direct owned item ids (140d10090).
{sources}
namespace Cranberry.Zone.Vehicles;

public readonly record struct VehicleSkinChoice(uint VehicleId, uint ModPoint, uint ItemId, uint ShaderGroupId);

/// <summary>August VehicleSkinMods and ClientItemDefinitions.PARAM1.</summary>
public static class VehicleSkinCatalog
{{
    public static readonly VehicleSkinChoice[] All =
    [
{chr(10).join(choices)}
    ];
    public static VehicleSkinChoice? Find(uint vehicle, uint modPoint, uint item) =>
        All.Where(s => s.VehicleId == vehicle && s.ModPoint == modPoint && s.ItemId == item)
            .Select(s => (VehicleSkinChoice?)s).FirstOrDefault();
}}
'''
(REPO / "src/Cranberry.Zone/Vehicles/VehicleSkinCatalog.cs").write_text(output, encoding="utf-8")
print(f"Generated {len(choices)} vehicle skin choices.")
