"""Generate clear Box of Destiny positions from August terrain and conservative mesh bounds.

py -3.12 tools/world/lobby_spawns.py --deps C:/Aug2017/out/gas-airdrop-20260906/python-deps
The courtyard rectangle and 2.5m body clearance are server design; source geometry is CLIENT.
"""
import argparse
import hashlib
import json
from pathlib import Path
import struct
import sys
import xml.etree.ElementTree as ET

from airdrop_terrain import height_samples
from vehicle_geometry import box, overlaps

ROOT = Path(__file__).resolve().parents[2]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--deps', type=Path, required=True)
    parser.add_argument('--world', type=Path, default=Path('C:/Aug2017/out/world_aug/z2-objects.jsonl'))
    args = parser.parse_args()
    sys.path[:0] = [str(ROOT / 'tools/pack'), str(args.deps)]
    import packread
    from cnkdec import Decompressor
    entries, _ = packread.build_index(packread.find_packs(packread.DEFAULT_ASSETS_DIR))
    index = {e.name: e for e in entries}
    sources = {}

    def asset(name):
        blob = packread.read_asset_bytes(index[name])
        sources[name] = hashlib.sha256(blob).hexdigest()
        return blob

    objects = [json.loads(line) for line in args.world.open()]
    obstacles = []
    models = {}
    for obj in objects:
        x, y, z = obj['pos']
        if not (-600 < x < 50 and -5200 < z < -4600):
            continue
        name = obj['model']
        if name not in models:
            actor = ET.fromstring(asset(name))
            base = actor.find('Base')
            # Test all rendered objects, including actor-backed doors, not just ADRs
            # with a CollisionData tag. A conservative rejection is preferable here.
            if base is None or not base.get('fileName', '').endswith('.dme'):
                models[name] = None
            else:
                blob = asset(base.get('fileName'))
                length = struct.unpack_from('<I', blob, 8)[0]
                models[name] = struct.unpack_from('<6f', blob, 12 + length)
        if models[name]:
            obstacles.append(box(models[name], obj['pos'], obj['rot'], obj['scale']))
    chunks = {}

    def sample(x, z):
        cx, cz = x // 256 * 256, z // 256 * 256
        name = f'Z2_{cz//64}_{cx//64}_0.cnk'
        if name not in chunks:
            chunks[name] = height_samples(asset(name), Decompressor().decompress)
        lx, lz = x - cx, z - cz
        i = ((lz//64)*4 + lx//64)*65*65 + (lx%64)*65 + lz%64
        h, m0, m1 = struct.unpack_from('<hBB', chunks[name], i*4)
        return h/32, (m0 & 127) == 127 or (m1 & 127) == 127

    points = []
    for z in range(-4930, -4880, 3):
        for x in range(-270, -204, 3):
            samples = [sample(x+dx, z+dz) for dx in (-1, 0, 1) for dz in (-1, 0, 1)]
            if any(hole for _, hole in samples):
                continue
            heights = [h for h, _ in samples]
            if max(heights) - min(heights) > 0.3:
                continue
            y = max(heights) + 0.12
            body = box((-1.25, 0, -1.25, 1.25, 2.2, 1.25), (x, y, z))
            if any(overlaps(body, obstacle) for obstacle in obstacles):
                continue
            points.append((x, round(y, 5), z))
    if len(points) < 150:
        raise ValueError(f'Only {len(points)} clear positions; expected capacity for 150')
    output = ROOT / 'src/Cranberry.Zone/Match/LobbySpawnPoints.cs'
    text = '// Generated by tools/world/lobby_spawns.py; see docs/lobby-spawns.provenance.json.\n'
    text += 'using System.Numerics;\n\nnamespace Cranberry.Zone.Match;\n\ninternal static class LobbySpawnPoints\n{\n    internal static readonly Vector4[] All =\n    [\n'
    text += ''.join(f'        new({x}f, {y}f, {z}f, 1f),\n' for x, y, z in points)
    text += '    ];\n}\n'
    output.write_text(text, encoding='utf-8')
    report = dict(grade='CLIENT geometry / DESIGNED selection', clientBuild='0.0.118.208059',
        generator='tools/world/lobby_spawns.py', generatorSha256=hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
        helperSha256={name: hashlib.sha256((Path(__file__).parent / name).read_bytes()).hexdigest()
            for name in ('airdrop_terrain.py', 'vehicle_geometry.py')},
        world=str(args.world), worldSha256=hashlib.sha256(args.world.read_bytes()).hexdigest(),
        outputSha256=hashlib.sha256(output.read_bytes()).hexdigest(), points=len(points),
        bounds=[-270, -204, -4930, -4880], clearanceMetres=1.25, sources=sources)
    (ROOT / 'docs/lobby-spawns.provenance.json').write_text(json.dumps(report, indent=2)+'\n', encoding='utf-8')
    print(f'{len(points)} terrain-supported clear positions; {len(obstacles)} obstacle boxes, {len(sources)} source assets')


if __name__ == '__main__':
    main()
