#!/usr/bin/env python3
r"""gen-item-class-mappings - emit the August client's SECOND item -> class table.

WHY THIS EXISTS (docs/78 4.5)
    ClientItemDefinitions.ITEM_CLASS gives every item exactly ONE class. It is not the whole
    classification: ItemClassMappings.txt is a second, many-to-many item -> class table, and
    the August client's own sheets prove it is folded into the set a loadout slot tests
    against.

    The proof is by construction, from the client's files alone. Loadout 17 names three
    slots by class:

        slot 40 (ConsumeItem1 / Q)  -> class 25080
        slot 41 (ConsumeItem2 / E)  -> class 25009
        slot  5 (Slot5)             -> class 25081

    Classes 25080 and 25081 have ZERO rows in ClientItemDefinitions with that ITEM_CLASS.
    They are reachable only through ItemClassMappings. A client that did not fold the
    mapping in could therefore never put anything in loadout 17's Q tile or its binoculars
    tile, in ANY build - so it folds it in.

    The item this actually costs Cranberry is 2423 Field Bandage / 2424 First Aid Kit:
    ITEM_CLASS 16053, a 168-row generic bucket no loadout slot in either August loadout
    accepts. ItemClassMappings additionally gives 2423 the classes 25009, 25054 and 25080 -
    i.e. exactly the quick-use tiles.

WHY A SIDE TABLE AND NOT A COLUMN ON InventoryItemFact
    Only 311 of the 2,643 item rows carry a mapping at all, and the whole table is 482
    pairs. A FrozenSet field on every InventoryItemFact would allocate 2,643 sets to express
    482 facts; this emits one flat sorted array plus a 311-entry index, and the lookup for
    an unmapped item is a single dictionary miss.

INPUT   C:\Aug2017\out\data_aug\derived\loot.json - tools/data/derive_loot.py's join;
        ``items[].mappedClassIds`` is ItemClassMappings.txt (#*ID^ITEM_ID^CLASS_ID^)
        already folded per item. docs/96 §4 pins the reconstruction as exact.
OUTPUT  src/Cranberry.Zone/Inventory/ItemClassMappings.g.cs
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

LOOT_JSON = Path(r"C:\Aug2017\out\data_aug\derived\loot.json")
DEFAULT_OUT = Path(__file__).resolve().parents[2] / "src" / "Cranberry.Zone" / "Inventory"


def read_pairs(path: Path) -> dict[int, list[int]]:
    with path.open(encoding="utf-8") as handle:
        items = json.load(handle)["items"]
    pairs = {int(item["id"]): sorted(int(c) for c in item["mappedClassIds"])
             for item in items if item.get("mappedClassIds")}
    return {item: pairs[item] for item in sorted(pairs)}


def emit(pairs: dict[int, list[int]]) -> str:
    flat: list[int] = []
    index: list[tuple[int, int, int]] = []
    for item, classes in pairs.items():
        index.append((item, len(flat), len(classes)))
        flat.extend(classes)

    rows = "\n".join(
        f"        {{ {item}u, new ClassRange({start}, {count}) }},"
        for item, start, count in index)
    values = "\n".join(
        "        " + ", ".join(f"{value}u" for value in flat[i:i + 12]) + ","
        for i in range(0, len(flat), 12))

    return f"""// <auto-generated>
// Generated by tools/data/gen-item-class-mappings.py from the August client's own
// ItemClassMappings.txt (Assets_*.pack, extracted to C:\\Aug2017\\out\\data_aug). Do not edit by
// hand; re-run the generator instead. Derivation: docs/78 4.5, docs/26 168.
// </auto-generated>

#nullable enable

using System.Collections.Frozen;

namespace Cranberry.Zone.Inventory;

/// <summary>
/// <b>The August client's SECOND item to class table</b> - <c>ItemClassMappings.txt</c>,
/// {len(flat)} many-to-many pairs over {len(pairs)} items, against
/// <c>ClientItemDefinitions.ITEM_CLASS</c>'s one class per item.
/// <para>
/// <b>Why it has to be folded into the class set a loadout slot tests.</b> Loadout 17 names three
/// slots by class - 40 (<c>ConsumeItem1</c>, Q) wants class 25080, 41 (<c>ConsumeItem2</c>, E) wants
/// 25009, 5 wants 25081 - and classes <b>25080 and 25081 have zero rows in
/// <c>ClientItemDefinitions</c> carrying them as <c>ITEM_CLASS</c></b>. They are satisfiable only
/// through this table. A client that did not fold it in could never put anything in loadout 17's Q
/// tile or its binoculars tile, in any build; so it folds it in, and so must the server, or the two
/// disagree about where a picked-up item went.
/// </para>
/// <para>
/// What it costs in practice: item 2423 (Field Bandage) and 2424 (Tactical First Aid Kit) are
/// <c>ITEM_CLASS</c> <b>16053</b>, a 168-row generic bucket no loadout slot in either August loadout
/// accepts. This table additionally gives them 25009, 25054 and 25080 - the quick-use tiles. The
/// owner's own server hit the identical trap at 1087 and called this file
/// <i>"the sheet nobody had read"</i> (docs/78 4.5).
/// </para>
/// <para>
/// <b>Shape.</b> One flat sorted array of classes plus a {len(pairs)}-entry index, rather than a set
/// per item: only {len(pairs)} of the 2,643 item rows carry a mapping at all, so a per-row
/// <c>FrozenSet</c> would allocate 2,643 collections to express {len(flat)} facts. The lookup for an
/// unmapped item is one dictionary miss and no allocation.
/// </para>
/// </summary>
public static class ItemClassMappings
{{
    private readonly record struct ClassRange(int Start, int Count);

    /// <summary>Total <c>(ITEM_ID, CLASS_ID)</c> pairs in the sheet.</summary>
    public const int PairCount = {len(flat)};

    /// <summary>Items carrying at least one mapping.</summary>
    public const int MappedItemCount = {len(pairs)};

    /// <summary>
    /// The classes <c>ItemClassMappings.txt</c> gives <paramref name="itemDefinitionId"/>, ascending,
    /// <b>not</b> including the item's own <c>ITEM_CLASS</c>. Empty for the 2,332 items with no
    /// mapping, and the returned span is a view over static data - it allocates nothing.
    /// </summary>
    public static ReadOnlySpan<uint> For(uint itemDefinitionId) =>
        ByItem.TryGetValue(itemDefinitionId, out ClassRange range)
            ? Classes.AsSpan(range.Start, range.Count)
            : ReadOnlySpan<uint>.Empty;

    /// <summary>
    /// Does <paramref name="itemDefinitionId"/> belong to <paramref name="classId"/> under the full
    /// rule - its own <c>ITEM_CLASS</c> <b>or</b> any row of this sheet?
    /// </summary>
    public static bool Matches(uint itemDefinitionId, uint primaryClass, uint classId)
    {{
        if (primaryClass == classId)
        {{
            return true;
        }}

        foreach (uint mapped in For(itemDefinitionId))
        {{
            if (mapped == classId)
            {{
                return true;
            }}
        }}

        return false;
    }}

    // Classes is declared before ByItem: static field initialisers run in declaration order, so the
    // dictionary's ranges would index a null array the other way round.
    private static readonly uint[] Classes =
    [
{values}
    ];

    private static readonly FrozenDictionary<uint, ClassRange> ByItem =
        new Dictionary<uint, ClassRange>
        {{
{rows}
        }}.ToFrozenDictionary();
}}
"""


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--loot", type=Path, default=LOOT_JSON)
    ap.add_argument("--out-dir", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--report", action="store_true", help="print the audit and write nothing")
    args = ap.parse_args(argv)

    pairs = read_pairs(args.loot)
    total = sum(len(v) for v in pairs.values())
    print(f"  {args.loot}: {total:,} pairs over {len(pairs):,} items")
    for probe in (2423, 2424, 1542, 3375):
        if probe in pairs:
            print(f"    item {probe} -> {pairs[probe]}")

    if args.report:
        return 0

    out = args.out_dir / "ItemClassMappings.g.cs"
    out.write_text(emit(pairs), encoding="utf-8", newline="\n")
    print(f"wrote {out} ({out.stat().st_size:,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
