#!/usr/bin/env python3
r"""Generate src/Cranberry.Zone/Weapons/AugustWeaponFacts.g.cs from the August client's own
ClientItemDatasheetData.txt, read through the derive layer.

INPUT   C:\Aug2017\out\data_aug\derived\weapons.json - tools/data/derive_weapons.py's join
        over ClientItemDatasheetData.txt / ClientItemDefinitions.txt / FireGroups and friends.
        The six columns this file emits are ``weaponItems[].itemId`` + ``.weaponId`` (rows
        with ``hasDatasheetRow``) joined to ``weapons[].fireGroupId`` and ``weapons[].timing``;
        docs/96 §4 pins that this reproduces all 160 sheet rows exactly.

Every value emitted is a verbatim column of the client's datasheet - nothing here is designed.
The design values (the fire-mode charge sentinel, the automatic flag) live in hand-written C#
so that the generated file stays purely extracted.  Derivation: docs/60-weapon-firegroups.md.
"""
import json
import os

DATA = os.environ.get("AUG_DATA", r"C:\Aug2017\out\data_aug")
DERIVED = os.environ.get("AUG_DERIVED", os.path.join(DATA, "derived"))
OUT = os.environ.get(
    "AUG_OUT",
    r"C:\Aug2017\Server\src\Cranberry.Zone\Weapons\AugustWeaponFacts.g.cs")

with open(os.path.join(DERIVED, "weapons.json"), encoding="utf-8") as fh:
    weapons_doc = json.load(fh)
by_weapon = {w["weaponId"]: w for w in weapons_doc["weapons"]}

rows = []
for item in weapons_doc["weaponItems"]:
    if not item.get("hasDatasheetRow"):
        continue
    weapon = by_weapon.get(item["weaponId"], {})
    timing = weapon.get("timing") or {}
    rows.append((int(item["itemId"]), int(item["weaponId"]),
                 int(weapon.get("fireGroupId") or 0),
                 int(timing.get("refireMs") or 0), int(timing.get("reloadMs") or 0),
                 int(timing.get("clipSize") or 0)))

rows.sort()
groups = sorted({r[2] for r in rows if r[2] != 0})

lines = []
w = lines.append
w("// <auto-generated>")
w("// Generated by tools/data/gen-weapon-firegroups.py from the August client's own datasheet")
w("// out\data_aug\ClientItemDatasheetData.txt (build 0.0.118.208059). Do not edit by hand;")
w("// re-run the generator instead. Derivation and citations: docs/60-weapon-firegroups.md.")
w("// </auto-generated>")
w("")
w("#nullable enable")
w("")
w("using System.Collections.Frozen;")
w("")
w("namespace Cranberry.Zone.Weapons;")
w("")
w("/// <summary>")
w("/// One row of <c>ClientItemDatasheetData.txt</c> - the client's own per-item weapon numbers.")
w("/// The header is")
w("/// <c>ITEM_ID^DATASHEET_ID^WEAPON_ID^FIRE_GROUP_ID^DIRECT_DAMAGE^INDIRECT_DAMAGE^DAMAGE_FALLOFF^")
w("/// REFIRE_TIME_MS^RELOAD_TIME_MS^CLIP_SIZE^RANGE_STRING_ID^MIN_CONE_OF_FIRE^</c>; the six columns")
w("/// kept here are the ones the fire-group wire needs. <b>Every value is EXTRACTED</b> - nothing in")
w("/// this file is a Cranberry design choice.")
w("/// </summary>")
w("/// <param name=\"ItemId\"><c>ITEM_ID</c> - a <c>ClientItemDefinitions</c> row id.</param>")
w("/// <param name=\"WeaponId\">")
w("/// <c>WEAPON_ID</c>. Equal to the item row's <c>PARAM1</c> on every weapon checked, which is the")
w("/// id <c>ClientPlayerItemManager::CreateItem</c> hashes into the weapon-definition manager")
w("/// (docs/58 §2 step 10). <c>AugustWeaponFactsTests</c> pins that equality across the whole sheet.")
w("/// </param>")
w("/// <param name=\"FireGroupId\">")
w("/// <c>FIRE_GROUP_ID</c> - the key of the <c>WeaponDefinitions</c> list-1 record the crash site")
w("/// dereferences (docs/58 §4c). <b>0 means the sheet names no fire group</b>; such an item can")
w("/// never be cleared for the active hand.")
w("/// </param>")
w("/// <param name=\"RefireTimeMs\"><c>REFIRE_TIME_MS</c>.</param>")
w("/// <param name=\"ReloadTimeMs\"><c>RELOAD_TIME_MS</c>.</param>")
w("/// <param name=\"ClipSize\"><c>CLIP_SIZE</c>. 0 on melee rows and on the fists (item 85).</param>")
w("public readonly record struct AugustWeaponFact(")
w("    uint ItemId,")
w("    uint WeaponId,")
w("    uint FireGroupId,")
w("    int RefireTimeMs,")
w("    int ReloadTimeMs,")
w("    int ClipSize);")
w("")
w("/// <summary>")
w("/// All %d rows of <c>ClientItemDatasheetData.txt</c>, keyed by item definition id, plus the %d" % (len(rows), len(groups)))
w("/// distinct non-zero fire-group ids they name.")
w("/// </summary>")
w("public static class AugustWeaponFacts")
w("{")
w("    /// <summary>Every row, in item-id order.</summary>")
w("    public static IReadOnlyList<AugustWeaponFact> All => Rows;")
w("")
w("    /// <summary>")
w("    /// The distinct non-zero <c>FIRE_GROUP_ID</c>s, ascending. This is exactly the set of records")
w("    /// the <c>WeaponDefinitions</c> list-1 table must carry for every weapon in the client's own")
w("    /// data to resolve.")
w("    /// </summary>")
w("    public static IReadOnlyList<uint> FireGroupIds => Groups;")
w("")
w("    /// <summary>Look one item up. A definition id the sheet does not carry is not an error.</summary>")
w("    public static bool TryGet(uint itemDefinitionId, out AugustWeaponFact fact) =>")
w("        ById.TryGetValue(itemDefinitionId, out fact);")
w("")
w("    // Rows is declared before ById: static field initialisers run in declaration order.")
w("    private static readonly AugustWeaponFact[] Rows =")
w("    [")
for r in rows:
    w("        new(%du, %du, %du, %d, %d, %d)," % r)
w("    ];")
w("")
w("    private static readonly uint[] Groups =")
w("    [")
for i in range(0, len(groups), 12):
    w("        " + " ".join("%du," % g for g in groups[i:i + 12]))
w("    ];")
w("")
w("    private static readonly FrozenDictionary<uint, AugustWeaponFact> ById =")
w("        Rows.ToFrozenDictionary(row => row.ItemId);")
w("}")

with open(OUT, "w", encoding="utf-8", newline="\r\n") as fh:
    fh.write("\n".join(lines) + "\n")

print("wrote %s: %d rows, %d fire groups" % (OUT, len(rows), len(groups)))
