"""Adopt Z1 pickup sounds only for matching August items and shipped August effects."""
import argparse
import csv
import hashlib
import json
from pathlib import Path
import xml.etree.ElementTree as ET


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source', type=Path, default=Path('C:/Z1/Data/2016/dataSources/ServerItemDefinitions.json'))
    parser.add_argument('--client-data', type=Path, default=Path('C:/Aug2017/out/data_aug'))
    parser.add_argument('--output', type=Path, default=Path(__file__).resolve().parents[2] / 'src/Cranberry.Zone/Loot/PickupEffects.g.cs')
    args = parser.parse_args()
    item_path = args.client_data / 'ClientItemDefinitions.txt'
    effect_path = args.client_data / 'ActorCompositeEffectDefinitions.xml'
    lines = item_path.read_text(encoding='utf-8-sig').splitlines()
    lines[0] = lines[0].lstrip('#*')
    items = {int(r['ID']): r for r in csv.DictReader(lines, delimiter='^')}
    effects = {int(e.attrib['id']): e.attrib['name'] for e in ET.parse(effect_path).iter('EffectDefinition')}
    assert effects[5151] == 'SFX_Item_PickUp_Generic'
    assert effects[5148] == 'SFX_Item_PickUp_Clothing'
    assert effects[5153] == 'SFX_Item_PickUp_Helmet'
    groups = {}
    for row in json.loads(args.source.read_text(encoding='utf-8-sig')).values():
        item_id, effect = row['ID'], row.get('PICKUP_EFFECT', 0)
        august = items.get(item_id)
        if not august or effect in (0, 5151):
            continue
        # An older build's numeric id alone does not establish item identity.
        if any(str(row.get(key)) != august[key] for key in ('NAME_ID', 'ITEM_CLASS', 'CODE_FACTORY_NAME')):
            continue
        # The imported table assigns the helmet sound to ordinary hats/cosmetic clothing too.
        # August's own IS_ARMOR flag distinguishes protective helmets from those items; keep
        # genuine helmets metallic and give non-armour headwear the shipped clothing sound.
        if effect == 5153 and august['IS_ARMOR'] != '1':
            effect = 5148
        if not effects.get(effect, '').startswith('SFX_Item_PickUp_'):
            continue
        groups.setdefault(effect, []).append(item_id)
    out = ['// <auto-generated>', '// Generator: tools/data/gen-pickup-effects.py',
           '// Grade: ADOPTED Z1 mapping, validated against August item identities and effect assets.',
           '// Correction: non-armour items (August IS_ARMOR=0) use clothing sound, not helmet sound.']
    for path in (args.source, item_path, effect_path):
        out.append(f'// Source: {path.as_posix()} sha256={hashlib.sha256(path.read_bytes()).hexdigest()}')
    out += ['// </auto-generated>', '', 'namespace Cranberry.Zone.Loot;', '',
            '/// <summary>One pickup sound per successful ground grant; unknown items use the August generic sound.</summary>',
            'public static class PickupEffects', '{', '    public const uint GenericEffectId = 5151;', '',
            '    public static uint ForItem(uint itemDefinitionId) => itemDefinitionId switch', '    {']
    for effect, ids in sorted(groups.items()):
        out.append(f'        // {effects[effect]}')
        ids = sorted(ids)
        for offset in range(0, len(ids), 8):
            chunk = ' or '.join(f'{i}u' for i in ids[offset:offset + 8])
            suffix = f' => {effect}u,' if offset + 8 >= len(ids) else ' or'
            out.append(f'        {chunk}{suffix}')
    out += ['        _ => GenericEffectId,', '    };', '}', '']
    args.output.write_text('\n'.join(out), encoding='utf-8')
    print(f'{sum(map(len, groups.values()))} item mappings, {len(groups)} sound effects: {args.output}')


if __name__ == '__main__':
    main()
