#!/usr/bin/env python3
r"""Generate the two `.g.cs` files that carry the data for `WeaponDefinitions` list 2 and for
`ReferenceData "ProjectileDefinitions"`, from the derive layer.

INPUT   C:\Aug2017\out\data_aug\derived\weapon-lists.json  (tools/data/derive_weapon_lists.py)

OUTPUT  AugustFireModeFacts.g.cs     one row per (fire group, mode index) - id, trigger charge,
                                     REFIRE_TIME_MS and RELOAD_TIME_MS
        AugustProjectileFacts.g.cs   the client's own PROJECTILE_IDs and their pen types

Every VALUE emitted here is the August client's own datasheet cell. The one thing that is not is
the fire-mode ID, which is `fireGroupId * 2 + index` (D159) because the client ships no fire-mode
table at all; the deriver computes it and this file only transcribes it. Layouts, offsets and
their [P]/[I]/[U] marks live in hand-written C# (`WeaponListLayouts`) and in docs/99, because they
come out of the binary rather than out of a sheet.

Usage:  python tools/data/gen-weapon-lists.py --out-dir src/Cranberry.Zone/Weapons
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

DEFAULT_DERIVED = Path(r"C:\Aug2017\out\data_aug\derived\weapon-lists.json")
DEFAULT_OUT_DIR = Path(r"C:\Aug2017\Server\src\Cranberry.Zone\Weapons")

AUTOGEN = [
    "// <auto-generated>",
    "// Generated by tools/data/gen-weapon-lists.py from the August client's own datasheets",
    "// (build 0.0.118.208059), read through out\\data_aug\\derived\\weapon-lists.json. Do not",
    "// edit by hand; re-run the generator instead. Derivation: docs/99-weapon-lists.md.",
    "// </auto-generated>",
    "",
    "#nullable enable",
    "",
]


def chunk(values: list[str], per_line: int, indent: str) -> list[str]:
    out = []
    for i in range(0, len(values), per_line):
        out.append(indent + " ".join(values[i:i + per_line]))
    return out


def fire_mode_facts(doc: dict) -> str:
    rows = doc["fireModes"]
    w: list[str] = list(AUTOGEN)
    w += [
        "using System.Collections.Frozen;",
        "",
        "namespace Cranberry.Zone.Weapons;",
        "",
        "/// <summary>",
        "/// One fire mode Cranberry ships in <c>WeaponDefinitions</c> list 2.",
        "/// <para>",
        "/// <b>Every timing here is the August client's own</b> - <paramref name=\"RefireTimeMs\"/>",
        "/// is <c>REFIRE_TIME_MS</c>, <paramref name=\"ReloadTimeMs\"/> is <c>RELOAD_TIME_MS</c> and",
        "/// <paramref name=\"ClipSize\"/> is <c>CLIP_SIZE</c>, all from the",
        "/// <c>ClientItemDatasheetData</c> row of the lowest-numbered item that names the fire group.",
        "/// The <paramref name=\"FireModeId\"/> is the one server-chosen number: the client ships no",
        "/// fire-mode table, so D159 numbers them <c>fireGroupId * 2 + index</c>.",
        "/// </para>",
        "/// </summary>",
        "/// <param name=\"FireModeId\">The list-2 hash key (<c>rec+0x378</c>) - D159.</param>",
        "/// <param name=\"FireGroupId\">The list-1 record that names this mode.</param>",
        "/// <param name=\"ModeIndex\">0 or 1; <c>FUN_1411ceca0</c>'s melee branch asks for index 1.</param>",
        "/// <param name=\"SourceItemId\">The datasheet row the timings came from.</param>",
        "/// <param name=\"DefinitionId\">",
        "/// <c>rec+0x18</c> - the fire mode's OWN id, and the primary key of list 4. Equal to",
        "/// <paramref name=\"FireModeId\"/>; see <c>FireModeRecord.DefinitionId</c> for the three",
        "/// functions that read it.",
        "/// </param>",
        "/// <param name=\"RefireTimeMs\"><c>rec+0x40</c> <c>FireMode.RefireTime</c> [P].</param>",
        "/// <param name=\"ReloadTimeMs\"><c>rec+0x60</c> <c>FireMode.ReloadTime</c> [P].</param>",
        "/// <param name=\"ClipSize\">",
        "/// The client's own <c>CLIP_SIZE</c> for the group's first item - what the weapon",
        "/// definition's ammo slot carries as <c>AmmoSlot.ClipSize</c>.",
        "/// </param>",
        "/// <param name=\"IronSights\">",
        "/// <c>rec+0x20</c> bit <c>0x04</c> <c>IRON_SIGHTS</c> [P]. RULING: mode index 1 is the ADS",
        "/// mode - it is the index the August client's own right-click sends in all 145 captured",
        "/// <c>82 0c</c> packets, and the owner's Z1 reads the same index as aim-down.",
        "/// </param>",
        "/// <param name=\"AmmoSlot\"><c>rec+0x30</c> <c>AMMO_SLOT</c> [P]. One slot per gun, so 0.</param>",
        "/// <param name=\"EffectGroup\">",
        "/// <c>rec+0x104</c> <c>EFFECT_GROUP</c> - the <c>FireModeEffectGroups</c> GROUP_ID the client",
        "/// resolves to a fire composite effect (the muzzle flash and the gunshot audio) when this fire",
        "/// group FIRES. It is the fire-group id itself, shipped only for a group with a non-zero",
        "/// <c>fire</c> row (groups 1..21/23/24); a group with no row (every group &gt; 24, e.g. the",
        "/// AK-47's 51) is a gap and ships 0. Shipping 0 was the owner's \"no noise of being shot\" -",
        "/// the client logs \"missing effect definition for Id #0\". RULING D234.",
        "/// </param>",
        "public readonly record struct AugustFireModeFact(",
        "    uint FireModeId,",
        "    uint FireGroupId,",
        "    int ModeIndex,",
        "    uint SourceItemId,",
        "    uint DefinitionId,",
        "    int RefireTimeMs,",
        "    int ReloadTimeMs,",
        "    int ClipSize,",
        "    bool IronSights,",
        "    int AmmoSlot,",
        "    uint EffectGroup);",
        "",
        "/// <summary>",
        f"/// The {len(rows)} fire modes of the {doc['counts']['fireGroups']} fire groups the client's own",
        "/// <c>ClientItemDatasheetData.txt</c> names, in (fire group, mode index) order.",
        "/// </summary>",
        "public static class AugustFireModeFacts",
        "{",
        f"    /// <summary>Modes per fire group - D159, and <c>AugustWeaponTable.FireModesPerGroup</c>.</summary>",
        f"    public const int ModesPerGroup = {doc['fireModesPerGroup']};",
        "",
        "    /// <summary>",
        "    /// <b>RULING - the ADS zoom multiplier</b> Cranberry writes into <c>rec+0x128</c>",
        "    /// (<c>DEFAULT_ZOOM</c> / <c>FireMode.DefaultZoom</c>) on the iron-sights mode of an",
        "    /// ARMED fire group. <c>1.0f</c> is the client's own preset and means \"no zoom\".",
        "    /// <para>",
        "    /// The mechanism is [P] - <c>FUN_141488490</c> reads that offset under the key whose",
        "    /// initialiser string is <c>\"FireMode.DefaultZoom\"</c> and <c>FUN_1411c8740</c>",
        "    /// interpolates the character's <c>+0x55a4</c> toward it - but NO August sheet carries a",
        "    /// zoom column, so the number is Cranberry's: the midpoint of the <c>(1.0, 2.0]</c> band",
        "    /// the client itself uses to choose <c>ADSMouseSensitivity</c> over",
        "    /// <c>scopedMouseSensitivity</c> (<c>_DAT_143275150 = 2.0f</c> in <c>FUN_140e40090</c>",
        "    /// and <c>FUN_140e4a010</c>). <c>CRANBERRY_WEAPON_ADS_ZOOM</c> overrides it and",
        "    /// <c>CRANBERRY_WEAPON_ADS_FOV=0</c> reverts every mode to <c>1.0f</c>.",
        "    /// </para>",
        "    /// </summary>",
        f"    public const float AdsZoom = {doc['adsZoom']}f;",
        "",
        "    /// <summary>",
        "    /// <b>RULING - the ADS FIRST-PERSON switch.</b> <c>FORCE_FP_SCOPE</c>",
        "    /// (<c>rec+0x2dc</c>) on the PRIMARY mode of an ARMED fire group. [P]:",
        "    /// <c>FUN_14158ad50:17</c> reads that byte off the LIVE fire-mode record and",
        "    /// <c>FUN_14158b700</c> - the <c>Infantry</c> / <c>SecondaryFire</c> handler, bound to",
        "    /// <c>Mouse_1</c> as <c>UI.WeaponOptic</c> - branches on it: set, it calls",
        "    /// <c>FUN_14158ab50</c>, which switches the camera to <c>0x1e</c> (first person) while",
        "    /// the button is held and back to <c>0x24</c> on release; clear, it calls the aim",
        "    /// vtable slot <c>+0x370</c> instead, which is the <c>82 0c SwitchFireModeRequest</c>",
        "    /// path. The two are EXCLUSIVE (<c>14158bb2d JZ 14158bc1f</c>), so this suppresses the",
        "    /// iron-sights mode - and with it <see cref=\"AdsZoom\"/> - while it is on.",
        "    /// </summary>",
        f"    public const bool AdsFirstPerson = {str(doc['adsFirstPerson']).lower()};",
        "",
        "    /// <summary>",
        "    /// <b>RULING - the aimed first-person field of view, in DEGREES</b>, for",
        "    /// <c>FP_CAMERA_FOV</c> / <c>FP_CR_CAMERA_FOV</c> / <c>FP_PR_CAMERA_FOV</c>",
        "    /// (<c>rec+0x2d0</c>, <c>+0x2d4</c>, <c>+0x2d8</c>) behind the gate",
        "    /// <c>FP_FORCE_CAMERA_OVERRIDES</c> (<c>rec+0x2cd</c>) that <c>FUN_140e3fff0</c> tests.",
        "    /// With <see cref=\"AdsFirstPerson\"/> on this is the ONLY field of view the aimed",
        "    /// view has. The number is the client's own default vertical FOV - <c>65</c>, the",
        "    /// default <c>FUN_1413a3e30:233-236</c> hands the <c>[Rendering] VerticalFOV</c> ini",
        "    /// read, whose clamp maximum there is <c>74</c> - over <see cref=\"AdsZoom\"/>.",
        "    /// <c>CRANBERRY_WEAPON_ADS_FP_FOV=0</c> clears the gate.",
        "    /// </summary>",
        f"    public const float AdsFpCameraFov = {doc['adsFpFov']}f;",
        "",
        "    /// <summary>",
        "    /// <b>ADOPTED under D53</b> from the owner's own Z1",
        "    /// (<c>C:\Z1\Server\Zone\ZoneWeaponDefinitions.cs:1358-1361</c>): the aim-in and",
        "    /// aim-out times, in ms, for <c>Weapon.ToIronSightsTime</c> (<c>def+0x38</c>) and",
        "    /// <c>Weapon.FromIronSightsTime</c> (<c>def+0x3c</c>), which <c>FUN_1422935d0:70-76</c>",
        "    /// takes when the mode switch is not silent. <c>0</c> means instant.",
        "    /// </summary>",
        f"    public const int IronSightsTimeMs = {doc['ironSightsMs']};",
        "",
        "    /// <summary>Every mode, in (fire group, mode index) order.</summary>",
        "    public static IReadOnlyList<AugustFireModeFact> All => Rows;",
        "",
        "    /// <summary>Lookup by fire-mode id.</summary>",
        "    public static bool TryGet(uint fireModeId, out AugustFireModeFact fact) =>",
        "        ByModeId.TryGetValue(fireModeId, out fact);",
        "",
        "    private static readonly AugustFireModeFact[] Rows =",
        "    [",
    ]
    for r in rows:
        w.append(
            f"        new({r['fireModeId']}u, {r['fireGroupId']}u, {r['modeIndex']}, "
            f"{r['sourceItemId']}u, {r['definitionId']}u, {r['refireTimeMs']}, "
            f"{r['reloadTimeMs']}, {r['clipSize']}, "
            f"{'true' if r['ironSights'] else 'false'}, {r['ammoSlot']}, "
            f"{r['effectGroup']}u),")
    w += [
        "    ];",
        "",
        "    private static readonly FrozenDictionary<uint, AugustFireModeFact> ByModeId =",
        "        Rows.ToFrozenDictionary(row => row.FireModeId);",
        "}",
        "",
    ]
    return "\n".join(w)


def projectile_facts(doc: dict) -> str:
    rows = doc["projectiles"]
    w: list[str] = list(AUTOGEN)
    w += [
        "namespace Cranberry.Zone.Weapons;",
        "",
        "/// <summary>",
        "/// The projectile ids the August client's own <c>ProjectileToPenTypes.txt</c> names, and the",
        "/// penetration type each maps to.",
        "/// <para>",
        "/// These are the keys <c>ReferenceData \"ProjectileDefinitions\"</c> is built on. Nothing here",
        "/// is invented: the client's data names these ids. What the client's data does <b>not</b>",
        "/// carry is the 55-column definition body, which is why that table ships off by default",
        "/// (<c>WeaponStageOptions.SendProjectileDefinitions</c>, docs/99 section 4.3).",
        "/// </para>",
        "/// </summary>",
        "/// <param name=\"ProjectileId\"><c>PROJECTILE_ID</c>.</param>",
        "/// <param name=\"PenTypeId\"><c>PEN_TYPE_ID</c>.</param>",
        "/// <param name=\"PenTypeName\"><c>PenTypes.DESCRIPTION</c> for that id.</param>",
        "public readonly record struct AugustProjectileFact(",
        "    uint ProjectileId,",
        "    int PenTypeId,",
        "    string PenTypeName);",
        "",
        "/// <summary>",
        f"/// All {len(rows)} rows of <c>ProjectileToPenTypes.txt</c>, in ascending projectile-id order.",
        "/// </summary>",
        "public static class AugustProjectileFacts",
        "{",
        "    /// <summary>Every row.</summary>",
        "    public static IReadOnlyList<AugustProjectileFact> All => Rows;",
        "",
        "    /// <summary>Just the ids, ascending.</summary>",
        "    public static IReadOnlyList<uint> ProjectileIds => Ids;",
        "",
        "    private static readonly AugustProjectileFact[] Rows =",
        "    [",
    ]
    for r in rows:
        name = r["penTypeName"].replace("\\", "\\\\").replace('"', '\\"')
        w.append(f"        new({r['projectileId']}u, {r['penTypeId']}, \"{name}\"),")
    w += [
        "    ];",
        "",
        "    private static readonly uint[] Ids =",
        "    [",
    ]
    w += chunk([f"{r['projectileId']}u," for r in rows], 6, "        ")
    w += [
        "    ];",
        "}",
        "",
    ]
    return "\n".join(w)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--derived", type=Path, default=DEFAULT_DERIVED)
    ap.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    args = ap.parse_args(argv)

    doc = json.loads(args.derived.read_text(encoding="utf-8"))
    args.out_dir.mkdir(parents=True, exist_ok=True)
    for name, text in (("AugustFireModeFacts.g.cs", fire_mode_facts(doc)),
                       ("AugustProjectileFacts.g.cs", projectile_facts(doc))):
        (args.out_dir / name).write_text(text, encoding="utf-8", newline="\n")
        print(f"{args.out_dir / name}: {len(text.splitlines())} lines")
    return 0


if __name__ == "__main__":
    sys.exit(main())
