#!/usr/bin/env python3
r"""gen-effect-catalog - src/Cranberry.Zone/Generated/AugustEffectCatalog.g.cs.

INPUT   C:\Aug2017\out\data_aug\derived\effects.json     (tools/data/derive_effects.py)
OUTPUT  src/Cranberry.Zone/Generated/AugustEffectCatalog.g.cs

WHAT IT IS (S8 section 6.4, overhaul plan section 3 lane 2B)

    The 1,047 composite effects this client build can resolve, by id and by name, so that

      * ``CompositeEffectGate`` can be an ALLOW list over the client's own table instead of a
        deny list seeded from one log line, and
      * any future sender (door swings, melee impacts, the parachute flare) names the effect by
        the client's own NAME - ``SFX_Door_Wood_Open`` - and never by a typed number.

    Id 0 is not in this table, so an allow list refuses it for free: exactly the D100 rule,
    now backed by the whole table rather than by four log lines.

USAGE  python tools/data/gen-effect-catalog.py [--effects effects.json] [--out-dir DIR]
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

DEFAULT_EFFECTS = Path(r"C:\Aug2017\out\data_aug\derived\effects.json")
DEFAULT_OUT_DIR = (
    Path(__file__).resolve().parents[2] / "src" / "Cranberry.Zone" / "Generated")
FILE_NAME = "AugustEffectCatalog.g.cs"


def escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace("\"", "\\\"")


def build(document: dict) -> str:
    effects = document["effects"]
    counts = document["counts"]
    source = document["source"]

    lines: list[str] = [
        "// <auto-generated>",
        "// Generated by tools/data/gen-effect-catalog.py from out/data_aug/derived/effects.json",
        "// (tools/data/derive_effects.py over the August client's own",
        "// ActorCompositeEffectDefinitions.xml). Do not edit. The provenance header above is",
        "// written by tools/pipeline/pipeline.py (docs/96).",
        "// </auto-generated>",
        "",
        "using System.Collections.Frozen;",
        "",
        "namespace Cranberry.Zone.Generated;",
        "",
        "/// <summary>One row of <see cref=\"AugustEffectCatalog\"/>: an effect this build can resolve.</summary>",
        "/// <param name=\"Id\">The composite-effect id a <c>QueueCompositeEffect*</c> call names.</param>",
        "/// <param name=\"Name\">The client's own name for it, e.g. <c>SFX_Door_Wood_Open</c>.</param>",
        "/// <param name=\"LoadType\">The definition's <c>loadType</c> attribute, carried verbatim (no recovered meaning).</param>",
        "/// <param name=\"PartCount\">How many <c>&lt;Effect&gt;</c> children it plays (particle, sound, decal, ...).</param>",
        "public readonly record struct AugustEffectDefinition(uint Id, string Name, int LoadType, int PartCount);",
        "",
        "/// <summary>",
        "/// The August client's own composite-effect table - every id it has a definition for.",
        "/// <para>",
        "/// <b>Why this exists (S8 section 6.4).</b> <c>CompositeEffectGate</c> was written as a deny",
        "/// list on the stated grounds that \"this build ships no composite-effect datasheet - the 2017",
        "/// extraction has no <c>Actor*Definitions.xml</c> at all\". That was wrong: the client's",
        "/// <c>ActorCompositeEffectDefinitions.xml</c> has been extracted since 2026-08-29 and carries",
        f"/// {counts['definitions']:,} definitions over {counts['parts']:,} effect parts. The gate is now an allow",
        "/// list over this table, and <b>id 0 is not in it</b> - so the D100 rule (0 is the no-effect",
        "/// sentinel and never a legal id at a queue call) falls out of the client's own data instead",
        "/// of out of four log lines.",
        "/// </para>",
        "/// <para>",
        "/// <b>Name, not number.</b> Every future sender should resolve through",
        "/// <see cref=\"IdOf\"/>: the door swing sounds behind <c>Doors.txt</c>",
        "/// (<c>SFX_Door_Wood_Open</c> 5048), the melee impacts behind",
        "/// <c>FireModes.MELEE_COMPOSITE_EFFECT_ID</c>, the bleed overlays",
        "/// (<c>PFX_Bleeding_Human_*</c>) and the parachute flare",
        "/// (<c>EFX_Flare_Parachute_Rocket_Red</c> 5051) are all rows in here.",
        "/// </para>",
        "/// </summary>",
        "public static class AugustEffectCatalog",
        "{",
        f"    /// <summary>How many definitions this build ships: {counts['definitions']:,}.</summary>",
        f"    public const int Count = {counts['definitions']};",
        "",
        f"    /// <summary>The lowest id in the table ({counts['minId']}). Nothing below it resolves - id 0 least of all.</summary>",
        f"    public const uint MinId = {counts['minId']};",
        "",
        f"    /// <summary>The highest id in the table ({counts['maxId']}).</summary>",
        f"    public const uint MaxId = {counts['maxId']};",
        "",
        "    /// <summary>How many <c>&lt;Effect&gt;</c> children the whole table declares.</summary>",
        f"    public const int PartCount = {counts['parts']};",
        "",
        "    /// <summary>The sha256 of the client XML this table was read from.</summary>",
        f"    public const string SourceSha256 = \"{source['sha256']}\";",
        "",
        "    /// <summary>Every definition, ascending by id.</summary>",
        "    public static readonly IReadOnlyList<AugustEffectDefinition> Definitions =",
        "    [",
    ]

    for row in effects:
        lines.append(
            f"        new({row['id']}u, \"{escape(row['name'])}\", "
            f"{row['loadType']}, {len(row['parts'])}),")

    lines += [
        "    ];",
        "",
        "    private static readonly FrozenDictionary<uint, AugustEffectDefinition> ByIdMap =",
        "        Definitions.ToFrozenDictionary(row => row.Id);",
        "",
        "    private static readonly FrozenDictionary<string, AugustEffectDefinition> ByNameMap =",
        "        Definitions.ToFrozenDictionary(row => row.Name, StringComparer.Ordinal);",
        "",
        "    /// <summary>Does this build have a definition for that id?</summary>",
        "    public static bool Contains(uint effectId) => ByIdMap.ContainsKey(effectId);",
        "",
        "    /// <summary>The definition for an id, or null when this build has none.</summary>",
        "    public static AugustEffectDefinition? ById(uint effectId) =>",
        "        ByIdMap.TryGetValue(effectId, out AugustEffectDefinition row) ? row : null;",
        "",
        "    /// <summary>The definition for one of the client's own effect names, or null.</summary>",
        "    public static AugustEffectDefinition? ByName(string name) =>",
        "        name is not null && ByNameMap.TryGetValue(name, out AugustEffectDefinition row)",
        "            ? row",
        "            : null;",
        "",
        "    /// <summary>",
        "    /// The id behind one of the client's own effect names. <b>This is how a sender should",
        "    /// name an effect</b> - a missing name is a build-time-grade mistake, so it throws.",
        "    /// </summary>",
        "    /// <exception cref=\"ArgumentOutOfRangeException\">This build has no such effect.</exception>",
        "    public static uint IdOf(string name)",
        "    {",
        "        ArgumentNullException.ThrowIfNull(name);",
        "        if (ByNameMap.TryGetValue(name, out AugustEffectDefinition row))",
        "        {",
        "            return row.Id;",
        "        }",
        "",
        "        throw new ArgumentOutOfRangeException(",
        "            nameof(name), name,",
        "            \"This client build's ActorCompositeEffectDefinitions.xml has no effect by that name.\");",
        "    }",
        "",
        "    /// <summary>The id behind an effect name, without throwing.</summary>",
        "    public static bool TryIdOf(string name, out uint effectId)",
        "    {",
        "        if (name is not null && ByNameMap.TryGetValue(name, out AugustEffectDefinition row))",
        "        {",
        "            effectId = row.Id;",
        "            return true;",
        "        }",
        "",
        "        effectId = 0;",
        "        return false;",
        "    }",
        "}",
        "",
    ]
    return "\n".join(lines)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--effects", type=Path, default=DEFAULT_EFFECTS)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    document = json.loads(args.effects.read_text(encoding="utf-8"))
    if document.get("schema") != "cranberry.derived.effects/1":
        raise SystemExit(f"{args.effects}: unexpected schema {document.get('schema')!r}")

    text = build(document)
    args.out_dir.mkdir(parents=True, exist_ok=True)
    destination = args.out_dir / FILE_NAME
    destination.write_text(text, encoding="utf-8", newline="\n")
    print(f"[gen-effect-catalog] {document['counts']['definitions']:,} composite effects "
          f"-> {destination}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
