#!/usr/bin/env python3
r"""Generate src/Cranberry.Zone/Combat/AugustAbilityFacts.g.cs from the August client's own
ClientItemDefinitions.txt (extracted to C:\Aug2017\out\data_aug).

One row per item whose ACTIVATABLE_ABILITY_ID (column 6) is non-zero.  Every value emitted is a
verbatim column of the client's own datasheet - nothing here is designed.  This is the table
Abilities.SetActivatableAbilityManager (0xa0 0x05) is built from, and it replaces the owner's
server reading the SAME column out of its 2016 sheet.  Derivation: docs/89-weapons-melee-port.md.
"""
import os
import sys
from pathlib import Path

# The one datasheet reader (docs/96); this file split on '^' by hand (S8 defect T3).
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "pipeline"))
from readers.sheet import read_rows  # noqa: E402

DATA = os.environ.get("AUG_DATA", r"C:\Aug2017\out\data_aug")
OUT = os.environ.get(
    "AUG_OUT",
    r"C:\Aug2017\Server\src\Cranberry.Zone\Combat\AugustAbilityFacts.g.cs")

ID = "ID"
ABILITY = "ACTIVATABLE_ABILITY_ID"   # the 6th column of ClientItemDefinitions.txt

rows = []
known = []
for r in read_rows(os.path.join(DATA, "ClientItemDefinitions.txt")):
    try:
        item = int(r[ID])
        ability = int(r[ABILITY])
    except (KeyError, ValueError):
        continue
    known.append(item)
    if ability != 0:
        rows.append((item, ability))

rows.sort()
known.sort()

lines = []
w = lines.append
w("// <auto-generated>")
w("// Generated by tools/data/gen-ability-facts.py from the August client's own datasheet")
w("// out\\data_aug\\ClientItemDefinitions.txt (build 0.0.118.208059). Do not edit by hand;")
w("// re-run the generator instead. Derivation and citations: docs/89-weapons-melee-port.md.")
w("// </auto-generated>")
w("")
w("#nullable enable")
w("")
w("using System.Collections.Frozen;")
w("")
w("namespace Cranberry.Zone.Combat;")
w("")
w("/// <summary>")
w("/// <c>ACTIVATABLE_ABILITY_ID</c> per item, straight out of the August client's own")
w("/// <c>ClientItemDefinitions.txt</c> (column 6). This is the column")
w("/// <c>Abilities.SetActivatableAbilityManager</c> (<c>a0 05</c>) is built from, and the one the")
w("/// owner's server reads out of its <b>2016</b> sheet - the single place his melee port and this")
w("/// build's own data disagree, so it is taken from the client that is actually running (docs/89")
w("/// &#167;3d). <b>Every value here is EXTRACTED</b>; nothing is a Cranberry choice.")
w("/// </summary>")
w("public static class AugustAbilityFacts")
w("{")
w("    /// <summary>Items carrying a non-zero <c>ACTIVATABLE_ABILITY_ID</c>.</summary>")
w("    public static int Count => ByItem.Count;")
w("")
w("    /// <summary>Every item id that has a <c>ClientItemDefinitions</c> row at all.</summary>")
w("    /// <remarks>")
w("    /// The client's own manager writer skips a loadout slot whose item definition it cannot")
w("    /// find, so the server must skip exactly the same ones or the two sides disagree on the")
w("    /// packet's length.")
w("    /// </remarks>")
w("    public static bool HasRow(uint itemDefinitionId) => Rows.Contains(itemDefinitionId);")
w("")
w("    /// <summary>")
w("    /// The item's activatable ability, or <c>0</c> when the sheet names none - which is most")
w("    /// items, including every gun and including item 85 \"Fists\".")
w("    /// </summary>")
w("    public static uint AbilityIdOf(uint itemDefinitionId) =>")
w("        ByItem.TryGetValue(itemDefinitionId, out uint ability) ? ability : 0u;")
w("")
w("    /// <summary>As <see cref=\"AbilityIdOf\"/>, in try-get form.</summary>")
w("    public static bool TryGet(uint itemDefinitionId, out uint abilityId) =>")
w("        ByItem.TryGetValue(itemDefinitionId, out abilityId);")
w("")
w("    private static readonly (uint Item, uint Ability)[] Pairs =")
w("    [")
for i in range(0, len(rows), 4):
    chunk = rows[i:i + 4]
    w("        " + " ".join(f"({a}u, {b}u)," for a, b in chunk))
w("    ];")
w("")
w("    private static readonly FrozenDictionary<uint, uint> ByItem =")
w("        Pairs.ToFrozenDictionary(p => p.Item, p => p.Ability);")
w("")
w("    private static readonly FrozenSet<uint> Rows = new uint[]")
w("    {")
for i in range(0, len(known), 12):
    chunk = known[i:i + 12]
    w("        " + " ".join(f"{v}u," for v in chunk))
w("    }.ToFrozenSet();")
w("}")
w("")

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", encoding="utf-8", newline="\r\n") as fh:
    fh.write("\n".join(lines))

print(f"{OUT}: {len(rows)} ability rows, {len(known)} item rows")
