#!/usr/bin/env python3
r"""
gen-string-hash-values.py - generate src/Cranberry.Zone/StringHashValues.g.cs from the client's
own StringHashToValue.txt (Assets_136.pack of the August client, extracted with the Pack1 tool
into C:\Aug2017\out\data_aug).

The client keeps these name/value pairs in its StringHashToValueManager (the global map
DAT_143f696d0): entries are keyed by a 32-bit hash of the name, hold the value string and its
atof() double, and are looked up by code with the hash baked in (e.g. FUN_14220be70 needs
0x8f15ddc2 = "Model.DescriptorReplaceString"). SendZoneDetails and StringHashToValueManager
(0xfb) carry the whole table on the wire; the parser FUN_140a4dc30 clears the map before
reading, so an empty list wipes the client's defaults and the model loader dereferences null.

The hash is the one in FUN_140b80030 (UpdateStringHashToValueManager): one-at-a-time with
signed shifts. The four constants the binary bakes in are verified here as a self-check.

Usage: python tools/data/gen-string-hash-values.py [StringHashToValue.txt] [output.cs]
"""
import sys
from pathlib import Path

# The one datasheet reader (docs/96); this file split on '^' by hand.
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "pipeline"))
from readers.sheet import read_rows  # noqa: E402

src = Path(sys.argv[1] if len(sys.argv) > 1 else r"C:\Aug2017\out\data_aug\StringHashToValue.txt")
dst = Path(sys.argv[2] if len(sys.argv) > 2 else
           Path(__file__).resolve().parents[2] / "src" / "Cranberry.Zone" / "StringHashValues.g.cs")


def sar32(x, n):
    x &= 0xFFFFFFFF
    return (x >> n) | ((0xFFFFFFFF << (32 - n)) & 0xFFFFFFFF) if x & 0x80000000 else x >> n


def client_hash(name):
    h = 0
    for c in name.encode("latin-1"):
        if c >= 128:
            c -= 256
        h = ((c + h) * 0x401) & 0xFFFFFFFF
        h ^= sar32(h, 6)
    t = (h * 9) & 0xFFFFFFFF
    return ((t ^ sar32(t, 11)) * 0x8001) & 0xFFFFFFFF


KNOWN = {
    "Model.DescriptorReplaceString": 0x8F15DDC2,   # FUN_14220be70
    "Network.KeepAlive": 0xC0DC29E7,               # FUN_140aee2a0 case 0x18
    "Audio.MinGrenadeBounceVelocity": 0x310129C3,  # FUN_140f034a0
    "Audio.GrenadeBounceEffectId": 0x294FC64C,     # FUN_140f034a0
    "PelletPatternsEnabled": 0xC8F2471F,           # FUN_140c7bb60
}
for name, expected in KNOWN.items():
    actual = client_hash(name)
    if actual != expected:
        sys.exit(f"hash self-check failed: {name} -> {actual:#x}, binary expects {expected:#x}")

rows = []
for row in read_rows(src, require_header=True):
    name, value = row["STRING"], row["VALUE"]
    # September 7: AugustShotgunPattern now supplies the native pattern and group rows.
    # Restore the August client's systematic branch after the D344 eight-pellet fallback.
    if name == "PelletPatternsEnabled":
        value = "1"
    # Owner request 2026-09-06: allow exiting at full vehicle speed. The client checks this
    # before sending DismountRequest, so removing only the server guard is insufficient.
    # Finite, far beyond any vehicle speed; zero is not assumed to mean "unlimited".
    if name == "Vehicle.DefaultMaxDismountSpeed":
        value = "10000.0"
    rows.append((client_hash(name), name, value))

if len(rows) != len({r[0] for r in rows}):
    sys.exit("hash collision inside the table")


def cs(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


out = [
    "// <auto-generated>",
    "// Generated by tools/data/gen-string-hash-values.py from the client's own StringHashToValue.txt",
    "// (Assets_136.pack, H1Z1.exe 0.0.118.208059). Hash = FUN_140b80030. Do not edit.",
    "// September 7: PelletPatternsEnabled=1 consumes the supplied systematic shotgun pattern.",
    "// </auto-generated>",
    "",
    "namespace Cranberry.Zone;",
    "",
    "/// <summary>",
    "/// The client's StringHashToValue table with documented local gameplay overrides.",
    f"/// Replaces StringHashToValueManager (DAT_143f696d0) with {len(rows)} entries.",
    "/// </summary>",
    "public static class StringHashValues",
    "{",
    "    public static readonly IReadOnlyList<StringHashValue> Entries =",
    "    [",
]
for h, name, value in rows:
    out.append(f"        new({cs(name)}, {cs(value)}, 0x{h:08X}),")
out += ["    ];", "}", ""]
dst.write_text("\n".join(out), encoding="utf-8", newline="\n")
print(f"wrote {dst} ({len(rows)} entries)")
