#!/usr/bin/env python3
r"""
gen-item-use-options.py - generate the item-action tables the client's own inventory UI drives.

INPUT   C:\Aug2017\out\data_aug\derived\loot.json - tools/data/derive_loot.py's join over
        ItemUseOptions.txt (74 rows -> ``useOptions``), ItemUseOptionGroups.txt (243 rows ->
        ``useOptionGroups``, ordered by DISPLAY_INDEX) and ItemIdUseOptionGroupId.txt
        (2,345 rows -> ``items[].useOptionGroupId``). docs/96 §4 pins that the three
        reconstructions are exact.

OUTPUT  src/Cranberry.Zone/Inventory/ItemUseOptions.g.cs

WHY (docs/63 section 1)

  The August client asks the server to drop, consume, salvage, unload, move or equip an item with
  Items::cItemPacketIdRequestUseItem - base 0xac, u8 sub 0x2c (out/registrations-1148.md line
  1793). The u32 at payload offset 10 is ItemUseOptions.ITEM_USE_OPTION_ID, and every value seen on
  the wire in this project's own captures is a real row of this sheet: 2, 3, 9, 99 ConsumeItem,
  4 DropItem, 5 PlaceItem, 6 and 63 SalvageItem, 7 UnloadWeapon, 12 RemoveItem. The two group
  sheets say which of them the client will even offer for a given item, which is the server's
  cheapest validation: an option that is not in the item's own group was never on that context
  menu.

DIALECT  the shared '^'-delimited reader documented in tools/data/sheet.py.

Usage: python tools/data/gen-item-use-options.py [data_dir] [output_dir]
"""
import json
import sys
from pathlib import Path

DATA = Path(sys.argv[1] if len(sys.argv) > 1 else r"C:\Aug2017\out\data_aug")
OUT = Path(sys.argv[2] if len(sys.argv) > 2 else
           Path(__file__).resolve().parents[2] / "src" / "Cranberry.Zone" / "Inventory")


def num(value, default=0):
    try:
        return int(value)
    except (TypeError, ValueError):
        return default


with (DATA / "derived" / "loot.json").open(encoding="utf-8") as _fh:
    loot = json.load(_fh)

options = [
    {"ITEM_USE_OPTION_ID": o["id"], "TYPE_NAME": o["typeName"],
     "TARGET_TYPE": o["targetType"], "BUSY_MSEC": o["busyMsec"],
     "NAME_ID": o["nameStringId"], "INTERACTION_ANIMATION_ID": o["interactionAnimationId"]}
    for o in loot["useOptions"]
]

kinds = sorted({r["TYPE_NAME"] for r in options if r["TYPE_NAME"]})
by_group = {}
for g in loot["useOptionGroups"]:
    by_group[num(g["id"])] = [
        option for _, option in
        sorted({(num(o["displayIndex"]), num(o["optionId"])) for o in g["options"]})
    ]

by_item = {}
for item in loot["items"]:
    group = num(item["useOptionGroupId"])
    if group:
        by_item[num(item["id"])] = group

out = []
w = out.append
w("// <auto-generated>")
w("// Generated by tools/data/gen-item-use-options.py from the August client's own datasheets")
w("// (Assets_*.pack, extracted to C:\\Aug2017\\out\\data_aug). Do not edit by hand; re-run the")
w("// generator instead. Derivation and citations: docs/63-inventory-complete.md.")
w("// </auto-generated>")
w("")
w("#nullable enable")
w("")
w("using System.Collections.Frozen;")
w("")
w("namespace Cranberry.Zone.Inventory;")
w("")
w("")
w("/// <summary>")
w("/// <c>ItemUseOptions.TYPE_NAME</c> - what the client is asking the server to DO with an item.")
w("/// The name is the client's own; the ids are <c>ITEM_USE_OPTION_ID</c>, which is the u32 at")
w("/// offset 10 of <c>Items.RequestUseItem</c> (0xac/0x2c).")
w("/// </summary>")
w("public enum ItemUseOptionKind")
w("{")
w("    /// <summary>The sheet has no row with this id.</summary>")
w("    Unknown,")
w("")
for k in kinds:
    w("    " + k + ",")
w("}")
w("")
w("")
w("/// <summary>One row of <c>ItemUseOptions.txt</c>.</summary>")
w("/// <param name=\"TargetType\">")
w("/// <c>TARGET_TYPE</c>: 0 = the item itself, 1 = a target the UI supplies, 2 = a world object")
w("/// (<c>StartVehicle</c> is the only 2 that matters outside this lane).")
w("/// </param>")
w("/// <param name=\"BusyMsec\">")
w("/// <c>BUSY_MSEC</c> - how long the client locks the character out while the action runs. Zero on")
w("/// every action this lane answers; the long ones are looting a corpse (20-30 s) and hot-wiring a")
w("/// car (7 s, docs/59).")
w("/// </param>")
w("public readonly record struct ItemUseOptionDefinition(")
w("    uint Id,")
w("    ItemUseOptionKind Kind,")
w("    uint TargetType,")
w("    int BusyMsec,")
w("    uint NameId,")
w("    uint InteractionAnimationId);")
w("")
w("")
w("/// <summary>The " + str(len(options)) + " rows of <c>ItemUseOptions.txt</c>, plus the item -&gt; legal-options join.</summary>")
w("public static class ItemUseOptionTable")
w("{")
w("    /// <summary>Every row, in sheet order.</summary>")
w("    public static IReadOnlyList<ItemUseOptionDefinition> All => Rows;")
w("")
w("    private static readonly ItemUseOptionDefinition[] Rows =")
w("    [")
for r in options:
    kind = r["TYPE_NAME"] if r["TYPE_NAME"] in kinds else "Unknown"
    w("        new(%du, ItemUseOptionKind.%s, %du, %d, %du, %du)," % (
        num(r["ITEM_USE_OPTION_ID"]), kind, num(r["TARGET_TYPE"]),
        num(r["BUSY_MSEC"]), num(r["NAME_ID"]), num(r["INTERACTION_ANIMATION_ID"])))
w("    ];")
w("")
w("    private static readonly FrozenDictionary<uint, ItemUseOptionDefinition> ById =")
w("        Rows.ToFrozenDictionary(row => row.Id);")
w("")
w("    /// <summary>Look one action up. An id outside the sheet is a malformed or hostile request.</summary>")
w("    public static bool TryGet(uint optionId, out ItemUseOptionDefinition option) =>")
w("        ById.TryGetValue(optionId, out option);")
w("")
w("    /// <summary>")
w("    /// The action an <c>ITEM_USE_OPTION_ID</c> names, or <see cref=\"ItemUseOptionKind.Unknown\"/>.")
w("    /// </summary>")
w("    public static ItemUseOptionKind KindOf(uint optionId) =>")
w("        ById.TryGetValue(optionId, out ItemUseOptionDefinition option)")
w("            ? option.Kind")
w("            : ItemUseOptionKind.Unknown;")
w("")
w("    /// <summary>")
w("    /// The options the client's context menu offers for an item, in <c>DISPLAY_INDEX</c> order -")
w("    /// <c>ItemIdUseOptionGroupId</c> joined onto <c>ItemUseOptionGroups</c>. An item the sheet does")
w("    /// not list has no menu at all.")
w("    /// </summary>")
w("    public static IReadOnlyList<uint> OptionsForItem(uint itemDefinitionId) =>")
w("        ItemOptions.TryGetValue(itemDefinitionId, out uint[]? options) ? options : [];")
w("")
w("    /// <summary>")
w("    /// True when the client could actually have offered <paramref name=\"optionId\"/> for this item.")
w("    /// The server's cheapest validation of a <c>RequestUseItem</c>: an option outside the item's own")
w("    /// group was never on that context menu.")
w("    /// </summary>")
w("    public static bool Allows(uint itemDefinitionId, uint optionId)")
w("    {")
w("        foreach (uint candidate in OptionsForItem(itemDefinitionId))")
w("        {")
w("            if (candidate == optionId)")
w("            {")
w("                return true;")
w("            }")
w("        }")
w("")
w("        return false;")
w("    }")
w("")
w("    private static readonly FrozenDictionary<uint, uint[]> ItemOptions =")
w("        new Dictionary<uint, uint[]>")
w("        {")
seen = 0
for item in sorted(by_item):
    opts = by_group.get(by_item[item])
    if not opts:
        continue
    seen += 1
    w("            [%du] = [%s]," % (item, ", ".join(str(o) + "u" for o in opts)))
w("        }.ToFrozenDictionary();")
w("}")
w("")

(OUT / "ItemUseOptions.g.cs").write_text("\n".join(out), encoding="utf-8")
print("ItemUseOptions.g.cs: %d options, %d kinds, %d items with a menu"
      % (len(options), len(kinds), seen))
