#!/usr/bin/env python3
r"""Generate AugustArmourFacts.g.cs from the August client's own ClientItemDefinitions.txt.

Emits every row the armour model can classify: ITEM_CLASS 25041 (body armour) and 25000
(head) with the client's own IS_ARMOR flag set, carrying that row's BULK. Nothing here is a
Cranberry design choice - the tiering rule that reads these numbers lives in ArmourModel.cs.

INPUT   C:\Aug2017\out\data_aug\derived\loot.json - tools/data/derive_loot.py's join over
        ClientItemDefinitions.txt. ``items[].isArmor`` / ``.itemClassId`` / ``.bulk`` /
        ``.modelName`` are the four columns this file reads; docs/96 §4 pins that they
        reproduce the sheet's 106 armour rows exactly.

Usage:  python tools/data/gen-armour-facts.py [derived/loot.json] [output.g.cs]
"""
import json, sys, pathlib

SRC = pathlib.Path(sys.argv[1] if len(sys.argv) > 1
                   else r"C:\Aug2017\out\data_aug\derived\loot.json")
DEST = pathlib.Path(sys.argv[2]) if len(sys.argv) > 2 else (
    pathlib.Path(__file__).resolve().parents[2] / "src" / "Cranberry.Zone" / "Combat"
    / "AugustArmourFacts.g.cs")

BODY_ARMOUR_CLASS = 25041
HEAD_CLASS = 25000

def main() -> int:
    with SRC.open(encoding="utf-8") as handle:
        items = json.load(handle)["items"]

    rows = []
    for r in items:
        cls, bulk, item = int(r["itemClassId"] or 0), int(r["bulk"] or 0), int(r["id"] or 0)
        if not r["isArmor"] or cls not in (BODY_ARMOUR_CLASS, HEAD_CLASS) or item == 0:
            continue
        rows.append((item, cls, bulk, (r["modelName"] or "").strip()))

    rows.sort()
    body = sum(1 for r in rows if r[1] == BODY_ARMOUR_CLASS)
    head = len(rows) - body

    out = []
    w = out.append
    w("// <auto-generated>")
    w("// Generated by tools/data/gen-armour-facts.py from the August client's own datasheet")
    w(r"// out\data_aug\ClientItemDefinitions.txt (build 0.0.118.208059). Do not edit by hand;")
    w("// re-run the generator instead. Derivation and citations: docs/81-z1-port-shooting.md.")
    w("// </auto-generated>")
    w("")
    w("#nullable enable")
    w("")
    w("using System.Collections.Frozen;")
    w("")
    w("namespace Cranberry.Zone.Combat;")
    w("")
    w("/// <summary>")
    w("/// One armour-bearing row of <c>ClientItemDefinitions.txt</c>: the three columns the armour")
    w("/// model reads. <b>Every value is EXTRACTED</b> - nothing here is a Cranberry design choice.")
    w("/// </summary>")
    w("/// <param name=\"ItemId\">The <c>ClientItemDefinitions</c> row id.</param>")
    w("/// <param name=\"ItemClass\"><c>ITEM_CLASS</c>: 25041 body armour, 25000 head.</param>")
    w("/// <param name=\"Bulk\"><c>BULK</c> - what separates the tiers.</param>")
    w("public readonly record struct AugustArmourFact(uint ItemId, uint ItemClass, uint Bulk);")
    w("")
    w("/// <summary>")
    w(f"/// The {len(rows)} rows the August client marks <c>IS_ARMOR</c> in classes 25041 ({body} body")
    w(f"/// armour) and 25000 ({head} head). A row absent from this table is not armour - which is")
    w("/// what keeps a beanie from stopping a rifle round.")
    w("/// </summary>")
    w("public static class AugustArmourFacts")
    w("{")
    w("    /// <summary><c>ItemClasses.BODY_ARMOR</c>.</summary>")
    w("    public const uint BodyArmourClass = 25041;")
    w("")
    w("    /// <summary>The head slot's item class; hats and masks live here too, without IS_ARMOR.</summary>")
    w("    public const uint HeadClass = 25000;")
    w("")
    w("    /// <summary>Every row, in item-id order.</summary>")
    w("    public static IReadOnlyList<AugustArmourFact> All => Rows;")
    w("")
    w("    /// <summary>Look one item up. An id the table does not carry is not an error.</summary>")
    w("    public static bool TryGet(uint itemDefinitionId, out AugustArmourFact fact) =>")
    w("        ById.TryGetValue(itemDefinitionId, out fact);")
    w("")
    w("    private static readonly AugustArmourFact[] Rows =")
    w("    [")
    for item, cls, bulk, model in rows:
        note = f"  // {model}" if model else ""
        w(f"        new({item}u, {cls}u, {bulk}u),{note}")
    w("    ];")
    w("")
    w("    private static readonly FrozenDictionary<uint, AugustArmourFact> ById =")
    w("        Rows.ToFrozenDictionary(row => row.ItemId);")
    w("}")
    w("")

    DEST.parent.mkdir(parents=True, exist_ok=True)
    DEST.write_text("\n".join(out), encoding="utf-8")
    print(f"{DEST}: {len(rows)} rows ({body} body armour, {head} head)")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
