#!/usr/bin/env python3
r"""gen-august-strings - src/Cranberry.Zone/Generated/AugustStrings.g.cs.

INPUT   C:\Aug2017\out\data_aug\derived\strings.json     (tools/data/derive_strings.py)
OUTPUT  src/Cranberry.Zone/Generated/AugustStrings.g.cs

WHAT IT IS (S8 section 4.3, overhaul plan section 3 lane 2B)

    Every locale string the server names, as a constant with the client's own en_us text in the
    doc comment beside it - the id and the text written by the same pass, out of the same
    document, so the two can never drift the way a hand comment beside a hand literal does.

    Two kinds of member per row:

      ``<Member>``       the datasheet string id (``uint``) - what a packet that carries an id
                         puts on the wire (``ce 0f`` label, ``09 2d`` prompt).
      ``<Member>Text``   the en_us text (``string``) - what a packet that carries a STRING puts
                         on the wire (``11 31 TextAlert``, which ships the sentence itself).

    The two placeholder tokens the client's own templates use are emitted as constants too, so
    the server-side expansion never types the markup either.

USAGE  python tools/data/gen-august-strings.py [--strings strings.json] [--out-dir DIR]
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

DEFAULT_STRINGS = Path(r"C:\Aug2017\out\data_aug\derived\strings.json")
DEFAULT_OUT_DIR = (
    Path(__file__).resolve().parents[2] / "src" / "Cranberry.Zone" / "Generated")
FILE_NAME = "AugustStrings.g.cs"

COUNT_TOKEN = "#count([*slot0*])"
SLOT_TOKEN = "[*slot0*]"

GROUP_DOC = {
    "Alerts": (
        "The <c>ClientUpdate.TextAlert</c> (<c>11 31</c>) sentences. <b>This channel carries a "
        "STRING, not an id</b> (dispatcher <c>FUN_140afc660</c> case <c>0x31</c> installs exactly "
        "one <c>SoeUtil::IString&lt;char&gt;</c> and displays it), so the wire value is the "
        "<c>...Text</c> member and the id is carried only as provenance."),
    "HudLabels": (
        "The <c>GameMode.Countdown</c> (<c>ce 0f</c>) label ids. This packet carries the ID, and "
        "<c>FUN_140bb67b0</c> gates the whole widget on <c>labelId &gt; 0</c> - a zero label "
        "silently blanks it."),
    "Prompts": (
        "The world-space <c>Command.InteractionString</c> (<c>09 2d</c>) prompt ids - the text on "
        "the <c>[F]</c> prompt. This packet carries the ID. None of these has a "
        "<c>CodeStringMappings.txt</c> row; each was resolved by inverting the locale key over "
        "its exact en_us text (docs/47 section 4e, reproduced in <c>derive_strings.py</c>). "
        "<b>Which id belongs on which object is Cranberry's choice</b>; that a given id carries a "
        "given text on this build is the client's fact."),
}

GROUP_ORDER = ["Alerts", "HudLabels", "Prompts"]


def escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace("\"", "\\\"")


def doc_escape(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def build(document: dict) -> str:
    rows = document["strings"]
    counts = document["counts"]
    sources = document["sources"]

    lines: list[str] = [
        "// <auto-generated>",
        "// Generated by tools/data/gen-august-strings.py from out/data_aug/derived/strings.json",
        "// (tools/data/derive_strings.py over the August client's own CodeStringMappings.txt and",
        "// Locale/en_us_data.dat). Do not edit. The provenance header above is written by",
        "// tools/pipeline/pipeline.py (docs/96).",
        "// </auto-generated>",
        "",
        "#nullable enable",
        "",
        "namespace Cranberry.Zone.Generated;",
        "",
        "/// <summary>One row of <see cref=\"AugustStrings\"/>, for the tests and the boot banner.</summary>",
        "/// <param name=\"Member\">The constant's name in this file.</param>",
        "/// <param name=\"Group\">Which nested class it lives in.</param>",
        "/// <param name=\"Id\">The datasheet string id.</param>",
        "/// <param name=\"LocaleKey\">jenkins_lookup2(\"Global.Text.\" + Id) - the key in the .dat archive.</param>",
        "/// <param name=\"Text\">The en_us text, verbatim, markup included.</param>",
        "/// <param name=\"CodeName\">The client's own <c>CodeStringMappings.txt</c> name, or null when it has none.</param>",
        "public readonly record struct AugustStringRow(",
        "    string Member, string Group, uint Id, uint LocaleKey, string Text, string? CodeName);",
        "",
        "/// <summary>",
        "/// Every locale string the server names, resolved out of the August client itself.",
        "/// <para>",
        "/// <b>Why (S8 section 4.3).</b> Four files in <c>src</c> carried these as decimal literals",
        "/// with the English in a comment beside them. A literal cannot be checked and neither can",
        "/// the comment. Here the id comes from the client's own",
        "/// <c>CodeStringMappings.txt</c> (by message name) or from inverting the locale key over the",
        "/// exact en_us text, and the text is read out of <c>Locale\\en_us_data.dat</c> in the same",
        "/// pass - so the doc comment below each constant is the client's own answer, not a note.",
        "/// </para>",
        "/// <para>",
        f"/// {counts['resolved']} strings: {counts['byCodeName']} anchored on a client message name, "
        f"{counts['byText']} on the exact",
        f"/// en_us text (of {counts['idsResolvingInScanRange']:,} datasheet ids in 0..{counts['scanLimit']:,} that resolve at all,",
        f"/// over {counts['localeRecords']:,} en_us records and {counts['codeStringMappings']:,} code-string mappings).",
        "/// </para>",
        "/// </summary>",
        "public static class AugustStrings",
        "{",
        "    /// <summary>",
        f"    /// The client's plural-count placeholder, <c>{doc_escape(COUNT_TOKEN)}</c>. <c>TextAlert</c> ships a",
        "    /// finished sentence, so the server expands this itself - exactly as the owner's server does.",
        "    /// </summary>",
        f"    public const string CountToken = \"{escape(COUNT_TOKEN)}\";",
        "",
        "    /// <summary>",
        f"    /// The client's plain substitution placeholder, <c>{doc_escape(SLOT_TOKEN)}</c>.",
        "    /// </summary>",
        f"    public const string SlotToken = \"{escape(SLOT_TOKEN)}\";",
        "",
        "    /// <summary>The sha256 of the two client files behind this table.</summary>",
        f"    public const string CodeStringMappingsSha256 = \"{sources[0]['sha256']}\";",
        "",
        "    /// <summary>The sha256 of the parsed en_us archive behind this table.</summary>",
        f"    public const string LocaleSha256 = \"{sources[1]['sha256']}\";",
        "",
    ]

    by_group: dict[str, list[dict]] = {}
    for row in rows:
        by_group.setdefault(row["group"], []).append(row)

    for group in GROUP_ORDER:
        group_rows = by_group.get(group, [])
        if not group_rows:
            continue
        lines.append("    /// <summary>")
        for chunk in wrap(GROUP_DOC[group], 96):
            lines.append(f"    /// {chunk}")
        lines.append("    /// </summary>")
        lines.append(f"    public static class {group}")
        lines.append("    {")
        for row in group_rows:
            member = row["member"]
            code = row["codeName"]
            named = f"<c>{code}</c> " if code else ""
            anchor = (f"code name <c>{code}</c>" if code
                      else f"en_us text (occurrence {row['occurrence']} of "
                           f"{len(row['idsCarryingThisText'])})")
            lines.append("        /// <summary>")
            lines.append(f"        /// {named}<b>{row['id']}</b>, locale key <c>{row['localeKey']}</c>:")
            lines.append(f"        /// <c>\"{doc_escape(row['text'])}\"</c>")
            lines.append("        /// <para>")
            note = row["note"]
            note = note[:1].upper() + note[1:] if note else ""
            if note and not note.endswith("."):
                note += "."
            for chunk in wrap(f"Resolved by {anchor}. {note} Consumer: {row['consumer']}.", 92):
                lines.append(f"        /// {chunk}")
            lines.append("        /// </para>")
            lines.append("        /// </summary>")
            lines.append(f"        public const uint {member} = {row['id']};")
            lines.append("")
            lines.append(f"        /// <summary>The en_us text of <see cref=\"{member}\"/>, verbatim.</summary>")
            lines.append(f"        public const string {member}Text = \"{escape(row['text'])}\";")
            lines.append("")
        # drop the trailing blank line inside the class
        if lines[-1] == "":
            lines.pop()
        lines.append("    }")
        lines.append("")

    lines += [
        "    /// <summary>Every row, for the pinning tests and the derivation report.</summary>",
        "    public static readonly IReadOnlyList<AugustStringRow> All =",
        "    [",
    ]
    for row in rows:
        code = "null" if row["codeName"] is None else f"\"{escape(row['codeName'])}\""
        lines.append(
            f"        new(\"{row['member']}\", \"{row['group']}\", {row['id']}u, "
            f"{row['localeKey']}u, \"{escape(row['text'])}\", {code}),")
    lines += [
        "    ];",
        "}",
        "",
    ]
    return "\n".join(lines)


def wrap(text: str, width: int) -> list[str]:
    words, line, out = text.split(), "", []
    for word in words:
        if line and len(line) + 1 + len(word) > width:
            out.append(line)
            line = word
        else:
            line = f"{line} {word}".strip()
    if line:
        out.append(line)
    return out


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--strings", type=Path, default=DEFAULT_STRINGS)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    document = json.loads(args.strings.read_text(encoding="utf-8"))
    if document.get("schema") != "cranberry.derived.strings/1":
        raise SystemExit(f"{args.strings}: unexpected schema {document.get('schema')!r}")

    for row in document["strings"]:
        if row["group"] not in GROUP_DOC:
            raise SystemExit(f"no group documentation for {row['group']!r}")

    # The two tokens must actually occur in the templates that need them, or the expansion
    # helpers in GasAlerts would be silently doing nothing.
    if not any(COUNT_TOKEN in row["text"] for row in document["strings"]):
        raise SystemExit("no template carries the #count([*slot0*]) token any more")
    if not any(SLOT_TOKEN in row["text"] for row in document["strings"]):
        raise SystemExit("no template carries the [*slot0*] token any more")

    text = build(document)
    args.out_dir.mkdir(parents=True, exist_ok=True)
    destination = args.out_dir / FILE_NAME
    destination.write_text(text, encoding="utf-8", newline="\n")
    print(f"[gen-august-strings] {len(document['strings'])} locale strings -> {destination}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
