#!/usr/bin/env python3
r"""
gen-inventory-slots.py - generate the Cranberry inventory slot map from the August client's own
datasheets.

INPUT   C:\Aug2017\out\data_aug\EquipmentSlotDefinitions.txt   (86 rows)  - the body slots
        C:\Aug2017\out\data_aug\EquipSlotItemClasses.txt       (18 rows)  - which classes stow where
        C:\Aug2017\out\data_aug\Loadouts.txt                   (17 rows)
        C:\Aug2017\out\data_aug\LoadoutSlots.txt              (146 rows)  - the UI slots
        C:\Aug2017\out\data_aug\LoadoutSlotItemClasses.txt    (236 rows)  - the auto-assign rule
        C:\Aug2017\out\data_aug\ContainerDefinitions.txt      (117 rows)  - capacities
        C:\Aug2017\out\data_aug\ClientItemDefinitions.txt   (2,643 rows)  - the nine item columns
                                                                           the resolver reads

OUTPUT  src/Cranberry.Zone/Inventory/InventorySlots.g.cs      - slots, loadouts, containers
        src/Cranberry.Zone/Inventory/InventoryItemFacts.g.cs  - the per-item columns

WHY THESE SHEETS AND NOT A HAND TABLE (docs/41 §2b)

  The client decides whether a loadout slot accepts an item in FUN_140d35510, reached from
  ClientLoadoutManager::FindFirstSupportingLoadoutSlotByItemId (FUN_140d36680, named by its own
  error string at 0x143143650). The predicate looks the slot definition up in a hash keyed
  (loadoutId ^ slotId) & 0xff, looks the item definition up in a hash keyed itemId & 0x3ff, reads
  the item's ITEM_CLASS from itemDef+0x40, and tests membership in the slot's class set at
  slotDef+0x100. That set is LoadoutSlotItemClasses.txt. So the server's auto-assign is only
  correct if it is driven by these exact sheets - a hand-written mapping would silently disagree
  with the client's own UI.

  EquipmentSlotDefinitions.ID is the SlotId of CharacterEquipmentAttachment and of
  EquipmentSlotRow (docs/36 W3). EquipSlotItemClasses.txt is what makes
  PASSIVE_EQUIP_SLOT_GROUP_ID = 1 resolvable: "pick a free slot from the set that accepts this
  item's ITEM_CLASS" (docs/41 1b).

DIALECT  the shared '^'-delimited reader documented in tools/data/sheet.py: '#' header, '*' key
         prefix, one trailing '^' per line, no quoting, latin-1.

Usage: python tools/data/gen-inventory-slots.py [data_dir] [output_dir]
"""
import sys
from pathlib import Path

# The one datasheet reader (docs/96). Three copies of read_sheet() and two hand '^' splits used
# to live in these generators; S8 defect T3 counted them. tools/pipeline/readers/sheet.py is now
# the only implementation, and tools/data/sheet.py re-exports it for the derive_*.py documents.
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "pipeline"))
from readers.sheet import read_rows  # noqa: E402

DATA = Path(sys.argv[1] if len(sys.argv) > 1 else r"C:\Aug2017\out\data_aug")
OUT = Path(sys.argv[2] if len(sys.argv) > 2 else
           Path(__file__).resolve().parents[2] / "src" / "Cranberry.Zone" / "Inventory")


def read_sheet(name):
    """One '^'-delimited client datasheet as a list of dicts (tools/pipeline/readers/sheet.py)."""
    return read_rows(DATA / name)


def num(value, default=0):
    value = (value or "").strip()
    try:
        return int(value)
    except ValueError:
        return default


def flag(value):
    return "true" if num(value) else "false"


def cs(value):
    """C# string literal for a datasheet cell (the sheets carry no quotes or backslashes)."""
    value = value or ""
    if '"' in value or "\\" in value:
        raise SystemExit(f"unexpected quoting in datasheet cell: {value!r}")
    return '"' + value + '"'


HEADER = """// <auto-generated>
// Generated by tools/data/gen-inventory-slots.py from the August client's own datasheets
// (Assets_*.pack, extracted to C:\\Aug2017\\out\\data_aug). Do not edit by hand; re-run the
// generator instead. Derivation and citations: docs/41-inventory-slots.md.
// </auto-generated>

#nullable enable

using System.Collections.Frozen;

namespace Cranberry.Zone.Inventory;
"""


# --------------------------------------------------------------------------------------------
# 1. Body / equipment slots - EquipmentSlotDefinitions.txt + EquipSlotItemClasses.txt
# --------------------------------------------------------------------------------------------
def gen_slots():
    slots = read_sheet("EquipmentSlotDefinitions.txt")
    stow = read_sheet("EquipSlotItemClasses.txt")
    loadouts = read_sheet("Loadouts.txt")
    loadout_slots = read_sheet("LoadoutSlots.txt")
    slot_classes = read_sheet("LoadoutSlotItemClasses.txt")
    containers = read_sheet("ContainerDefinitions.txt")

    equipment = {}
    for row in slots:
        equipment[num(row["ID"])] = row

    # class -> the equip slots that accept it, in sheet order (docs/41 1b).
    by_class = {}
    for row in stow:
        by_class.setdefault(num(row["ITEM_CLASS"]), []).append(num(row["EQUIP_SLOT_ID"]))

    # (loadout, slot) -> accepted item classes (docs/41 2b - the client's own predicate).
    by_slot = {}
    for row in slot_classes:
        by_slot.setdefault((num(row["LOADOUT_ID"]), num(row["SLOT"])), []).append(
            num(row["ITEM_CLASS"]))

    out = [HEADER]

    out.append('''
/// <summary>
/// One row of the client's <c>EquipmentSlotDefinitions.txt</c>. <see cref="Id"/> is the value that
/// travels on the wire as <c>CharacterEquipmentAttachment.SlotId</c> and as
/// <c>EquipmentSlotRow.SlotId</c> (docs/36 §W3, docs/41 §1).
/// </summary>
/// <param name="Id">The sheet's <c>ID</c> - the wire slot id.</param>
/// <param name="IsRequired">
/// <c>IS_REQUIRED</c>. Slot 1 (Head) is the <em>only</em> required slot with an empty
/// <see cref="DefaultAdr"/>, which is why clearing it produced client error G10 while clearing
/// 3/4/105 merely fell back to their default meshes (docs/41 §1d, docs/32).
/// </param>
/// <param name="IsEquipment">
/// <c>IS_EQUIPMENT</c>. A 0 here is not an attachment target - slot 85
/// (<c>spineUpper_BackStab</c>) is listed by <c>EquipSlotItemClasses.txt</c> but is not an
/// equipment slot, so it must not be chosen as a weapon stow slot.
/// </param>
/// <param name="GroupId">
/// <c>GROUP_ID</c>. 1 marks a <em>vehicle</em> hardpoint (slots 30-33, 41-73), not a weapon-stow
/// group; the stow group comes from <see cref="EquipmentSlotTable.StowSlotsForItemClass"/>
/// (docs/41 §1b).
/// </param>
public readonly record struct EquipmentSlotDefinition(
    uint Id,
    bool IsRequired,
    bool IsEquipment,
    bool StartHidden,
    uint GroupId,
    string SlotName,
    string DefaultAdr,
    string BoneAttachNameOverride,
    string AnimName);

/// <summary>The 86 rows of <c>EquipmentSlotDefinitions.txt</c>, plus the stow-group index.</summary>
public static class EquipmentSlotTable
{
    /// <summary>Every row, in sheet order.</summary>
    public static IReadOnlyList<EquipmentSlotDefinition> All => Rows;

    private static readonly EquipmentSlotDefinition[] Rows =
    [''')

    for row in slots:
        out.append(
            f'        new({num(row["ID"])}u, {flag(row["IS_REQUIRED"])}, '
            f'{flag(row["IS_EQUIPMENT"])}, {flag(row["START_HIDDEN"])}, '
            f'{num(row["GROUP_ID"])}u, {cs(row["SLOT_NAME"])}, {cs(row["DEFAULT_ADR"])}, '
            f'{cs(row["BONE_ATTACH_NAME_OVERRIDE"])}, {cs(row["ANIM_NAME"])}),')

    out.append('''    ];

    private static readonly FrozenDictionary<uint, EquipmentSlotDefinition> ById =
        Rows.ToFrozenDictionary(row => row.Id);

    /// <summary>Look one slot up by its wire id.</summary>
    public static bool TryGet(uint id, out EquipmentSlotDefinition definition) =>
        ById.TryGetValue(id, out definition);

    /// <summary>True when <paramref name="id"/> is a row of the sheet.</summary>
    public static bool Exists(uint id) => ById.ContainsKey(id);

    /// <summary>
    /// The equip slots that accept <paramref name="itemClass"/>, from
    /// <c>EquipSlotItemClasses.txt</c> in sheet order. This is the candidate set a long gun picks
    /// its stow slot from when <c>PASSIVE_EQUIP_SLOT_GROUP_ID = 1</c> (docs/41 §1b); rows whose
    /// slot is not <c>IS_EQUIPMENT</c> (slot 85) are excluded, because the client will not attach
    /// a mesh there.
    /// </summary>
    public static IReadOnlyList<uint> StowSlotsForItemClass(uint itemClass) =>
        StowGroups.TryGetValue(itemClass, out uint[]? slots) ? slots : [];

    private static readonly FrozenDictionary<uint, uint[]> StowGroups =
        new Dictionary<uint, uint[]>
        {''')

    for item_class in sorted(by_class):
        kept = [s for s in by_class[item_class]
                if num(equipment.get(s, {}).get("IS_EQUIPMENT", "0"))]
        dropped = [s for s in by_class[item_class] if s not in kept]
        note = f"   // sheet also lists {dropped}, excluded: IS_EQUIPMENT = 0" if dropped else ""
        out.append(f'            [{item_class}u] = [{", ".join(f"{s}u" for s in kept)}],{note}')

    out.append('''        }.ToFrozenDictionary();
}
''')

    # ---------------------------------------------------------------------------------------
    # Loadouts
    # ---------------------------------------------------------------------------------------
    out.append('''
/// <summary>
/// One row of <c>LoadoutSlots.txt</c> - a slot of the client's inventory panel. This is a different
/// id space from <see cref="EquipmentSlotDefinition"/>: the loadout slot is what the UI shows and
/// what <c>Loadouts.SetLoadoutSlot</c> (0x86/05) binds an item guid to, while
/// <see cref="EquipSlotId"/> is the body slot the mesh attaches to (docs/41 §2a).
/// </summary>
/// <param name="EquipSlotId">
/// <c>EQUIP_SLOT_ID</c>, a row of <see cref="EquipmentSlotTable"/>. Zero on the wheel slots,
/// because a slung weapon's body slot depends on the weapon rather than on the loadout slot.
/// </param>
/// <param name="ItemId">
/// <c>ITEM_ID</c> - the slot's default item. Loadout 3 slot 7 names item 85 ("Fists"), which the
/// client's own config corroborates as <c>Inventory.SpecialEmptyHandsItemId = 85</c>
/// (<c>StringHashValues.g.cs</c>).
/// </param>
/// <param name="AutoEquip">
/// <c>FLAG_AUTO_EQUIP</c> - the slot the server is expected to fill without being asked. Every
/// apparel slot, plus 7 (Fists) and 43 (the Inventory bag).
/// </param>
/// <param name="Wheelable">
/// <c>FLAG_IS_WHEELABLE</c> - one of the six hotbar slots (1, 3, 4, 7, 40, 41). This build's hotbar
/// is these slots and not an item flag: <c>FLAG_QUICK_USE</c> is 0 on all 2,643 item rows.
/// </param>
public readonly record struct LoadoutSlotDefinition(
    uint LoadoutId,
    uint SlotId,
    uint EquipSlotId,
    uint ItemId,
    bool AutoEquip,
    bool Required,
    bool Visible,
    bool Wheelable,
    bool CanRightHandEquip,
    uint DisplayIndex,
    string SlotUiTag,
    string SlotInputAction);

/// <summary>
/// <c>Loadouts.txt</c>, <c>LoadoutSlots.txt</c> and <c>LoadoutSlotItemClasses.txt</c>. The last of
/// those is the client's own auto-assign rule (docs/41 §2b): a slot supports an item <b>iff</b> the
/// item's <c>ITEM_CLASS</c> is listed for <c>(LOADOUT_ID, SLOT)</c>.
/// </summary>
public static class LoadoutSlotTable
{
    /// <summary>The survivor loadout - the one a KOTK player wears (docs/41 §2a).</summary>
    public const uint SurvivorLoadoutId = 3;

    /// <summary>Every loadout id present in <c>Loadouts.txt</c>.</summary>
    public static IReadOnlyList<uint> LoadoutIds => LoadoutIdRows;

    private static readonly uint[] LoadoutIdRows =
    [''')

    ids = sorted({num(r["ID"]) for r in loadouts})
    out.append("        " + ", ".join(f"{i}u" for i in ids) + ",")
    out.append('''    ];

    /// <summary>Every row of <c>LoadoutSlots.txt</c>, in sheet order.</summary>
    public static IReadOnlyList<LoadoutSlotDefinition> All => Rows;

    private static readonly LoadoutSlotDefinition[] Rows =
    [''')

    for row in loadout_slots:
        out.append(
            f'        new({num(row["LOADOUT_ID"])}u, {num(row["SLOT_ID"])}u, '
            f'{num(row["EQUIP_SLOT_ID"])}u, {num(row["ITEM_ID"])}u, '
            f'{flag(row["FLAG_AUTO_EQUIP"])}, {flag(row["FLAG_REQUIRED"])}, '
            f'{flag(row["FLAG_IS_VISIBLE"])}, {flag(row["FLAG_IS_WHEELABLE"])}, '
            f'{flag(row["FLAG_CAN_RHAND_EQUIP"])}, {num(row["DISPLAY_INDEX"])}u, '
            f'{cs(row["SLOT_UI_TAG"])}, {cs(row["SLOT_INPUT_ACTION"])}),')

    out.append('''    ];

    private static readonly FrozenDictionary<(uint Loadout, uint Slot), LoadoutSlotDefinition> BySlot =
        Rows.ToFrozenDictionary(row => (row.LoadoutId, row.SlotId));

    private static readonly FrozenDictionary<uint, LoadoutSlotDefinition[]> ByLoadout =
        Rows.GroupBy(row => row.LoadoutId)
            .ToFrozenDictionary(group => group.Key, group => group.ToArray());

    /// <summary>Look one loadout slot up.</summary>
    public static bool TryGet(uint loadoutId, uint slotId, out LoadoutSlotDefinition definition) =>
        BySlot.TryGetValue((loadoutId, slotId), out definition);

    /// <summary>Every slot of one loadout, in sheet order (which is ascending slot id).</summary>
    public static IReadOnlyList<LoadoutSlotDefinition> Slots(uint loadoutId) =>
        ByLoadout.TryGetValue(loadoutId, out LoadoutSlotDefinition[]? rows) ? rows : [];

    /// <summary>
    /// The item classes <c>(loadoutId, slotId)</c> accepts, ascending. Empty means the slot accepts
    /// nothing, which is how class 16053 (ammunition, bandages, first aid kits) ends up with no
    /// loadout slot at all under loadout 3 - those items are container-only (docs/41 §5c).
    /// </summary>
    public static IReadOnlyList<uint> ItemClasses(uint loadoutId, uint slotId) =>
        SlotClasses.TryGetValue((loadoutId, slotId), out uint[]? classes) ? classes : [];

    private static readonly FrozenDictionary<(uint Loadout, uint Slot), uint[]> SlotClasses =
        new Dictionary<(uint, uint), uint[]>
        {''')

    for (loadout, slot) in sorted(by_slot):
        classes = sorted(set(by_slot[(loadout, slot)]))
        out.append(f'            [({loadout}u, {slot}u)] = '
                   f'[{", ".join(f"{c}u" for c in classes)}],')

    out.append('''        }.ToFrozenDictionary();
}
''')

    # ---------------------------------------------------------------------------------------
    # Containers
    # ---------------------------------------------------------------------------------------
    out.append('''
/// <summary>
/// One row of <c>ContainerDefinitions.txt</c>. A worn container item names its row through
/// <c>ClientItemDefinitions.PARAM1</c>; <see cref="MaxBulk"/> is the capacity it contributes
/// (docs/41 §4a).
/// </summary>
/// <param name="IsDynamicBulk">
/// <c>IS_DYNAMIC_BULK</c>. Row 117 - the character's own "Inventory" bag - is the only row in the
/// sheet with this set, and its <see cref="MaxBulk"/> is 0: its capacity is <em>subsumed</em> from
/// the containers equipped on the character, which is what the client's own
/// <c>Container::SetBulkSubsummed: maxBulk=%d</c> (0x14360c358) and
/// <c>Container::ModifyMaxBulk: current=%d, delta=%d, new=%d</c> (0x14360c388) describe.
/// </param>
public readonly record struct ContainerDefinition(
    uint Id,
    int MaximumSlots,
    int MaxBulk,
    int MaxSlotBulk,
    bool RemoveWhenEmpty,
    bool WithdrawalOnly,
    bool DepositOnly,
    bool IsDynamicBulk,
    uint ItemSpawnerId,
    uint AllowedItemClassId);

/// <summary>The 117 rows of <c>ContainerDefinitions.txt</c>.</summary>
public static class ContainerDefinitionTable
{
    /// <summary>
    /// The character's base bag: container definition 117, provided by item 3156 "Inventory"
    /// (class 25068), auto-equipped into loadout-3 slot 43 (docs/41 §4b).
    /// </summary>
    public const uint BaseInventoryDefinitionId = 117;

    /// <summary>Item definition 3156 - the "Inventory" bag item that provides definition 117.</summary>
    public const uint BaseInventoryItemDefinitionId = 3156;

    /// <summary>Every row, in sheet order.</summary>
    public static IReadOnlyList<ContainerDefinition> All => Rows;

    private static readonly ContainerDefinition[] Rows =
    [''')

    for row in containers:
        out.append(
            f'        new({num(row["ID"])}u, {num(row["MAXIMUM_SLOTS"])}, '
            f'{num(row["MAX_BULK"])}, {num(row["MAX_SLOT_BULK"])}, '
            f'{flag(row["REMOVE_WHEN_EMPTY"])}, {flag(row["WITHDRAWAL_ONLY"])}, '
            f'{flag(row["DEPOSIT_ONLY"])}, {flag(row["IS_DYNAMIC_BULK"])}, '
            f'{num(row["ITEM_SPAWNER_ID"])}u, {num(row["ALLOWED_ITEM_CLASS_ID"])}u),')

    out.append('''    ];

    private static readonly FrozenDictionary<uint, ContainerDefinition> ById =
        Rows.ToFrozenDictionary(row => row.Id);

    /// <summary>Look one container definition up.</summary>
    public static bool TryGet(uint id, out ContainerDefinition definition) =>
        ById.TryGetValue(id, out definition);
}
''')

    return "\n".join(out) + "\n"


# --------------------------------------------------------------------------------------------
# 2. Item facts - the nine ClientItemDefinitions columns the resolver reads
# --------------------------------------------------------------------------------------------
def gen_items():
    rows = read_sheet("ClientItemDefinitions.txt")
    factories = sorted({(r["CODE_FACTORY_NAME"] or "None").strip() for r in rows})

    def ident(name):
        out = "".join(c for c in name if c.isalnum())
        return out or "None"

    out = [HEADER]
    out.append('''
/// <summary>
/// <c>ClientItemDefinitions.CODE_FACTORY_NAME</c> - the client-side class that builds the item
/// object. Only <see cref="EquippableContainer"/> matters to this lane: it is the marker that the
/// item <em>provides</em> a container whose definition is its <c>PARAM1</c> (docs/41 §4a).
/// </summary>
public enum ItemCodeFactory
{''')
    for name in factories:
        out.append(f"    {ident(name)},")
    out.append("}\n")

    out.append('''
/// <summary>
/// The nine <c>ClientItemDefinitions.txt</c> columns the inventory resolver reads, for all 2,643
/// item rows of build 0.0.118.208059 (docs/41 §5a).
/// </summary>
/// <param name="ItemClass">
/// <c>ITEM_CLASS</c> (column 9). The client reads this from <c>itemDef+0x40</c> in
/// <c>FUN_140d35510</c> and tests it against the loadout slot's class set - it is the whole of the
/// auto-assign decision (docs/41 §2b).
/// </param>
/// <param name="ActiveEquipSlotId">
/// <c>ACTIVE_EQUIP_SLOT_ID</c> - the body slot the item occupies while wielded. Across all 2,643
/// rows this is only ever 0 or 7 (RHand); 262 rows are wieldable.
/// </param>
/// <param name="PassiveEquipSlotId">
/// <c>PASSIVE_EQUIP_SLOT_ID</c> - the body slot the item occupies while worn or stowed.
/// </param>
/// <param name="PassiveEquipSlotGroupId">
/// <c>PASSIVE_EQUIP_SLOT_GROUP_ID</c>. 1 on the 82 long-gun rows and means "pick a free slot from
/// the group that accepts this item's class" rather than always using
/// <see cref="PassiveEquipSlotId"/> - which is how two rifles land on 76 and 80 instead of
/// colliding (docs/41 §1b).
/// </param>
/// <param name="Bulk">
/// <c>BULK</c> (column 61) - what one unit costs against a container's
/// <see cref="ContainerDefinition.MaxBulk"/> (docs/41 §4a).
/// </param>
/// <param name="Param1">
/// <c>PARAM1</c>. For an <see cref="ItemCodeFactory.EquippableContainer"/> row this is the
/// <c>ContainerDefinitions</c> row id of the container the item provides.
/// </param>
/// <param name="ModelName">
/// <c>MODEL_NAME</c> - the third-person attachment mesh, with the literal <c>&lt;gender&gt;</c>
/// token where the sheet carries one. Present on only <b>303</b> of the 2,643 rows: weapons, armour
/// and satchels name their mesh here, while hats, helmets and backpacks leave it empty and take
/// their mesh from the appearance/skin path instead. An empty value therefore means "no attachment
/// mesh from this sheet", never "no such item" - and it does not affect where the item goes, which
/// is decided by the loadout binding, not by the mesh.
/// </param>
public readonly record struct InventoryItemFact(
    uint DefinitionId,
    uint ItemClass,
    uint ActiveEquipSlotId,
    uint PassiveEquipSlotId,
    uint PassiveEquipSlotGroupId,
    bool CanEquip,
    int Bulk,
    int MaxStackSize,
    uint Param1,
    uint NameId,
    ItemCodeFactory CodeFactory,
    string ModelName);

/// <summary>All 2,643 item rows, keyed by definition id.</summary>
public static class InventoryItemFacts
{
    /// <summary>Every row, in sheet order.</summary>
    public static IReadOnlyList<InventoryItemFact> All => Rows;

    /// <summary>
    /// Look one item up. A definition id the sheet does not carry is not an error here - the caller
    /// decides (the resolver treats it as a plain, non-equippable, zero-bulk item).
    /// </summary>
    public static bool TryGet(uint definitionId, out InventoryItemFact fact) =>
        ById.TryGetValue(definitionId, out fact);

    // Rows is declared before ById: static field initialisers run in declaration order, so the
    // dictionary would see a null array the other way round.
    private static readonly InventoryItemFact[] Rows =
    [''')

    seen = set()
    for row in rows:
        item_id = num(row["ID"])
        if item_id in seen:
            raise SystemExit(f"duplicate ClientItemDefinitions row {item_id}")
        seen.add(item_id)
        factory = ident((row["CODE_FACTORY_NAME"] or "None").strip())
        out.append(
            f'        new({item_id}u, {num(row["ITEM_CLASS"])}u, '
            f'{num(row["ACTIVE_EQUIP_SLOT_ID"])}u, {num(row["PASSIVE_EQUIP_SLOT_ID"])}u, '
            f'{num(row["PASSIVE_EQUIP_SLOT_GROUP_ID"])}u, {flag(row["FLAG_CAN_EQUIP"])}, '
            f'{num(row["BULK"])}, {num(row["MAX_STACK_SIZE"])}, {num(row["PARAM1"])}u, '
            f'{num(row["NAME_ID"])}u, ItemCodeFactory.{factory}, {cs(row["MODEL_NAME"])}),')

    out.append('''    ];

    private static readonly FrozenDictionary<uint, InventoryItemFact> ById =
        Rows.ToFrozenDictionary(row => row.DefinitionId);
}''')
    return "\n".join(out) + "\n"


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    slots = gen_slots()
    items = gen_items()
    (OUT / "InventorySlots.g.cs").write_text(slots, encoding="utf-8", newline="\r\n")
    (OUT / "InventoryItemFacts.g.cs").write_text(items, encoding="utf-8", newline="\r\n")
    print(f"wrote {OUT / 'InventorySlots.g.cs'} ({len(slots):,} bytes)")
    print(f"wrote {OUT / 'InventoryItemFacts.g.cs'} ({len(items):,} bytes)")


if __name__ == "__main__":
    main()
