// <cranberry-provenance>
// Written by tools/pipeline/pipeline.py (docs/96). `pipeline.py check` recomputes every
// hash below and fails the build when one has moved; do not edit this block by hand.
// id: zone-opcodes
// grade: CLIENT
// clientBuild: 0.0.118.208059
// generator: tools/opcodes/gen-zone-opcodes.py sha256=364241ecb4e8749da6d6a672d2fdac6bf90a1fe8c6fba230e321b4ce60044153
// input: out/registrations-1148.json sha256=b915bf3863d7f392c0a9d23542efebc238bdbdcb743133cedf9181b6ab2c5aa2 crc32=46610c48 size=530515 grade=CLIENT
// input: out/ghidra-aug/doors-prompt-string/callers_14140c480/FUN_14129ad10_14129ad10.c sha256=f9c8e587b5ca6b28deee5bf946fde97dd338632f7d66b9c534dcaefafde9f038 crc32=85d114ae size=20435 grade=CLIENT
// input: out/ghidra-aug/character-dispatch/_140af9ca0/FUN_140af9ca0_140af9ca0.c sha256=6f546bbb45b8037d651d5f1d07d42f123b03d124433635d43885b11c2ff83884 crc32=629b2caa size=37031 grade=CLIENT
// input: out/ghidra-aug/loot-research/clientupdate-dispatch/_140afc660/FUN_140afc660_140afc660.c sha256=181e2782b822b7c6a2bfb3f658d265987e3b6ca5c4f831631c584bfc57f57edb crc32=84bcaecd size=75718 grade=CLIENT
// input: out/ghidra-aug/fable-character-login/_140b81830_1420cd050/FUN_140b81830_140b81830.c sha256=f398ee2db36752e8620e4b09c53e9e75a7b901094623905b90bf88152f6ffcdb crc32=9ac89c5a size=13158 grade=CLIENT
// input: out/inventory-research/loadout-packet/_140b03170/FUN_140d37650_140d37650.c sha256=90f7edfe71062f645dd12dc8902529be6ad2782371c89df94fd5f8ac323869d2 crc32=7962ada1 size=1230 grade=CLIENT
// input: out/ghidra-aug/matchflow-b5/_140bba510_14136ddf0_140c9e170_140a2d040_140a3ca40_140f25600/FUN_140bba510_140bba510.c sha256=63c2b4043617a8af138d5c29de2ea04874fe0fbde489f3f8f9c50ed406365a43 crc32=6102678d size=6655 grade=CLIENT
// rulings: D181
// generatedUtc: 2026-09-04T07:05:35Z
// </cranberry-provenance>
// <auto-generated>
// Generated by tools/opcodes/gen-zone-opcodes.py from registrations-1148.json (the client's own
// packet-id registrations, FUN_1413bfa90 and the 27 family registrars) and, for the
// sub-opcode widths, from six family dispatcher decompiles under C:\Aug2017\out.
// Do not edit.
// </auto-generated>

#nullable enable

namespace Cranberry.Zone;

/// <summary>
/// One family's sub-opcode framing, read off that family's own dispatcher.
/// </summary>
/// <param name="BaseOpcode">The first zone byte.</param>
/// <param name="Family">The client's registered family name, where it has one.</param>
/// <param name="Bytes">How wide the sub-opcode is: 1 or 2.</param>
/// <param name="PrefixBytes">Bytes between the base byte and the sub (0 everywhere but <c>0x82</c>, whose header is <c>u8 base; u32 gameTime; u8 sub</c>).</param>
/// <param name="Dispatcher">The client function the width was read from.</param>
/// <param name="Dump">The decompile it was read in, under <c>C:\Aug2017\out</c>.</param>
/// <param name="Evidence">The decompiled line that performs the read.</param>
public readonly record struct ZoneSubOpcodeWidth(
    byte BaseOpcode, string Family, int Bytes, int PrefixBytes,
    string Dispatcher, string Dump, string Evidence);

/// <summary>ClientProtocol_1148 base opcodes: the first byte of a zone packet.</summary>
public static class ZoneOpcodes
{
    public const byte BaseServerPacket = 0x01;
    public const byte ClientFinishedLoading = 0x02;
    public const byte SendSelfToClient = 0x03;
    public const byte ClientIsReady = 0x04;
    public const byte ZoneDoneSendingInitialData = 0x05;
    public const byte ChatBase = 0x06;
    public const byte ClientLogout = 0x07;
    public const byte TargetClientNotOnline = 0x08;
    public const byte CommandBase = 0x09;
    public const byte AdminBase = 0x0a;
    public const byte ClientBeginZoning = 0x0b;
    public const byte CombatBase = 0x0c;
    public const byte ProjectileDebug = 0x0d;
    public const byte MailBase = 0x0e;
    public const byte CharacterBase = 0x0f;
    public const byte AbilityBase = 0x10;
    public const byte ClientUpdateBase = 0x11;
    public const byte GroupsBase = 0x13;
    public const byte EncounterBase = 0x14;
    public const byte InventoryBase = 0x15;
    public const byte SendZoneDetails = 0x16;
    public const byte ReferenceData = 0x17;
    public const byte ObjectiveBase = 0x18;
    public const byte DebugBase = 0x19;
    public const byte UiBase = 0x1a;
    public const byte QuestBase = 0x1b;
    public const byte RewardBase = 0x1c;
    public const byte GameTimeSync = 0x1d;
    public const byte PetBase = 0x1e;
    public const byte PointOfInterestDefinitionRequest = 0x1f;
    public const byte PointOfInterestDefinitionReply = 0x20;
    public const byte WorldTeleportRequest = 0x21;
    public const byte TradeBase = 0x22;
    public const byte EscrowGivePackage = 0x23;
    public const byte EscrowGotPackage = 0x24;
    public const byte UpdateEncounterDataCommon = 0x25;
    public const byte RecipeBase = 0x26;
    public const byte InGamePurchaseBase = 0x27;
    public const byte QuickChatBase = 0x28;
    public const byte ReportBase = 0x29;
    public const byte AcquaintanceBase = 0x2a;
    public const byte ClientServerShuttingDown = 0x2b;
    public const byte FriendBase = 0x2c;
    public const byte BroadcastBase = 0x2d;
    public const byte ClientKickedFromServer = 0x2e;
    public const byte UpdateClientSessionData = 0x2f;
    public const byte BugSubmissionBase = 0x30;
    public const byte WorldDisplayInfo = 0x31;
    public const byte MOTD = 0x32;
    public const byte SetLocale = 0x33;
    public const byte SetClientArea = 0x34;
    public const byte ZoneTeleportRequest = 0x35;
    public const byte TradingCardBase = 0x36;
    public const byte WorldShutdownNotice = 0x37;
    public const byte LoadWelcomeScreen = 0x38;
    public const byte ShipCombatBase = 0x39;
    public const byte KeepAlive = 0x3b;
    public const byte ClientExitLaunchUri = 0x3c;
    public const byte ClientPath = 0x3d;
    public const byte ClientPendingKickFromServer = 0x3e;
    public const byte ClientMembershipActivation = 0x3f;
    public const byte LobbyBase = 0x40;
    public const byte LobbyGameDefinitionBase = 0x41;
    public const byte ShowSystemMessage = 0x42;
    public const byte POIChangeMessage = 0x43;
    public const byte ClientMetrics = 0x44;
    public const byte FirstTimeEventBase = 0x45;
    public const byte ClaimBase = 0x46;
    public const byte ClientLog = 0x47;
    public const byte IgnoreBase = 0x48;
    public const byte SnoopedPlayerBase = 0x49;
    public const byte PromotionalBase = 0x4a;
    public const byte AddClientPortraitCrc = 0x4b;
    public const byte ObjectiveTargetBase = 0x4c;
    public const byte CommerceSessionRequest = 0x4d;
    public const byte CommerceSessionResponse = 0x4e;
    public const byte TrackedEvent = 0x4f;
    public const byte ClientLoginFailed = 0x50;
    public const byte LoginToUChat = 0x51;
    public const byte ZoneSafeTeleportRequest = 0x52;
    public const byte RemoteInteractionRequest = 0x53;
    public const byte UpdateCamera = 0x56;
    public const byte GuildBase = 0x58;
    public const byte AdminGuildBase = 0x59;
    public const byte BattleMagesBase = 0x5a;
    public const byte WorldToWorldBase = 0x5b;
    public const byte PerformAction = 0x5c;
    public const byte EncounterMatchmakingBase = 0x5d;
    public const byte ClientLuaMetrics = 0x5e;
    public const byte RepeatingActivityBase = 0x5f;
    public const byte ClientGameSettings = 0x60;
    public const byte ClientTrialProfileUpsell = 0x61;
    public const byte ActivityManagerBase = 0x62;
    public const byte RequestSendItemDefinitionsToClient = 0x63;
    public const byte InspectBase = 0x64;
    public const byte AchievementBase = 0x65;
    public const byte PlayerTitleBase = 0x66;
    public const byte MatchHistoryBase = 0x67;
    public const byte UpdateUserAge = 0x68;
    public const byte LootBase = 0x69;
    public const byte ActionBarManagerBase = 0x6a;
    public const byte ClientTrialProfileUpsellRequest = 0x6b;
    public const byte CliLobbyPlayerReady = 0x6c;
    public const byte CoinStoreBase = 0x6d;
    public const byte InitializationParameters = 0x6e;
    public const byte ActivityBase = 0x6f;
    public const byte MountBase = 0x70;
    public const byte ClientInitializationDetails = 0x71;
    public const byte ClientAreaTimer = 0x72;
    public const byte LoyaltyRewardBase = 0x73;
    public const byte RatingBase = 0x74;
    public const byte ClientActivityLaunchBase = 0x75;
    public const byte ServerActivityLaunchBase = 0x76;
    public const byte ClientFlashTimer = 0x77;
    public const byte PlayerUpdatePosition = 0x78;
    public const byte InviteAndStartMiniGame = 0x79;
    public const byte QuizBase = 0x7a;
    public const byte PlayerUpdatePositionOnPlatform = 0x7b;
    public const byte ClientMembershipVipInfo = 0x7c;
    public const byte TargetBase = 0x7d;
    public const byte GuideStoneBase = 0x7f;
    public const byte RaidsBase = 0x80;
    public const byte VoiceBase = 0x81;
    public const byte WeaponBase = 0x82;
    public const byte MatchScheduleBase = 0x83;
    public const byte FacilityBase = 0x84;
    public const byte SkillsBase = 0x85;
    public const byte LoadoutsBase = 0x86;
    public const byte ExperienceBase = 0x87;
    public const byte VehicleBase = 0x88;
    public const byte GriefBase = 0x89;
    public const byte SpotPlayer = 0x8a;
    public const byte FactionsBase = 0x8b;
    public const byte Synchronization = 0x8c;
    public const byte ResourceEventBase = 0x8d;
    public const byte CollisionBase = 0x8e;
    public const byte LeaderboardBase = 0x8f;
    public const byte PlayerUpdateManagedPosition = 0x90;
    public const byte AddSimpleNpc = 0x91;
    public const byte PlayerUpdateVehicleWeapon = 0x92;
    public const byte ProfileStatsBase = 0x93;   // also registered as cProfileStatsPacketIdGetPlayerProfileStats
    public const byte EquipmentBase = 0x94;
    public const byte DefinitionFiltersBase = 0x95;
    public const byte ContinentBattleInfo = 0x96;
    public const byte GetContinentBattleInfo = 0x97;
    public const byte SendSecurityPacketAndSelfDestruct = 0x98;
    public const byte GetRespawnLocations = 0x99;
    public const byte WallOfDataBase = 0x9a;
    public const byte ImplantsBase = 0x9b;
    public const byte InGamePurchase = 0x9c;
    public const byte MissionsBase = 0x9d;
    public const byte EffectsBase = 0x9e;
    public const byte RewardBuffsBase = 0x9f;
    public const byte AbilitiesBase = 0xa0;
    public const byte DeployableBase = 0xa1;
    public const byte Security = 0xa2;
    public const byte MapRegionBase = 0xa3;
    public const byte HudManagerBase = 0xa4;
    public const byte AcquireTimersBase = 0xa5;
    public const byte LoginBase = 0xa6;
    public const byte ServerPopulationInfo = 0xa7;
    public const byte GetServerPopulationInfo = 0xa8;
    public const byte PlayerUpdateVehicleCollision = 0xa9;
    public const byte PlayerStop = 0xaa;
    public const byte CurrencyBase = 0xab;
    public const byte ItemsBase = 0xac;
    public const byte PlayerUpdateAttachObject = 0xad;
    public const byte PlayerUpdateDetachObject = 0xae;
    public const byte ClientSettings = 0xaf;
    public const byte RewardBuffInfo = 0xb0;
    public const byte GetRewardBuffInfo = 0xb1;
    public const byte CaisBase = 0xb2;
    public const byte ZoneSettingBase = 0xb3;
    public const byte RequestPromoEligibilityUpdate = 0xb4;
    public const byte PromoEligibilityReply = 0xb5;
    public const byte MetaGameEventBase = 0xb6;
    public const byte RequestWalletTopupUpdate = 0xb7;
    public const byte StationCashActivePromoRequestUpdate = 0xb8;
    public const byte OperationBase = 0xbb;
    public const byte WordFilterBase = 0xbc;
    public const byte StaticFacilityInfoBase = 0xbd;
    public const byte ProxiedPlayerBase = 0xbe;
    public const byte ResistsBase = 0xbf;
    public const byte InGamePurchasingBase = 0xc0;
    public const byte BusinessEnvironments = 0xc1;
    public const byte EmpireScorePacketBase = 0xc2;
    public const byte CharacterSelectSessionRequest = 0xc3;
    public const byte CharacterSelectSessionResponse = 0xc4;
    public const byte StatsBase = 0xc5;
    public const byte ScoreBase = 0xc6;
    public const byte ResourcesBase = 0xc7;
    public const byte ConstructionBase = 0xc9;
    public const byte UpdateWeatherData = 0xca;
    public const byte NavGenBase = 0xcb;
    public const byte LocksBase = 0xcc;
    public const byte RagdollBase = 0xcd;
    public const byte CharacterStateBase = 0xcf;
    public const byte TimedGrantBase = 0xd0;
    public const byte WeatherBase = 0xd1;
    public const byte GameEscrowBase = 0xd2;
    public const byte PlayCompositeEffect = 0xd3;
    public const byte SetSpotted = 0xd4;
    public const byte AddLightweightPc = 0xd5;
    public const byte AddLightweightNpc = 0xd6;
    public const byte AddLightweightVehicle = 0xd7;
    public const byte AddProxiedObject = 0xd8;
    public const byte LightweightToFullPc = 0xd9;
    public const byte LightweightToFullNpc = 0xda;
    public const byte LightweightToFullVehicle = 0xdb;
    public const byte CheckLocalValues = 0xdd;
    public const byte ChronicleBase = 0xde;
    public const byte GrinderBase = 0xdf;
    public const byte RequestObject = 0xe0;
    public const byte ScreenEffectBase = 0xe1;
    public const byte SpectatorBase = 0xe2;
    public const byte WhitelistBase = 0xe3;
    public const byte NpcFoundationPermissionsManagerBase = 0xe4;
    public const byte BattlEyeData = 0xe5;
    public const byte OnlineIdBase = 0xe6;
    public const byte Ps4PlayGoBase = 0xe7;
    public const byte SynchronizedTeleportBase = 0xe8;
    public const byte StaticViewBase = 0xe9;
    public const byte ReplicationBase = 0xea;   // also registered as cCreateRepData
    public const byte DatasheetsBase = 0xeb;
    public const byte PlayerWorldTransferRequest = 0xec;
    public const byte PlayerWorldTransferReply = 0xed;
    public const byte CancelQueueOnWorld = 0xee;
    public const byte DeclineEnterGameOnWorld = 0xef;
    public const byte AccessedCharacterBase = 0xf0;
    public const byte ShaderParameterOverrideBase = 0xf1;
    public const byte VehicleSkinBase = 0xf2;
    public const byte WeaponLagLockParameters = 0xf4;
    public const byte CrateOpeningBase = 0xf5;
    public const byte PlayerHeatWarning = 0xf6;
    public const byte AnimationBase = 0xf7;
    public const byte ProximateItemBase = 0xf8;
    public const byte GrantPSNTrophyRequest = 0xf9;
    public const byte PlayLength = 0xfa;
    public const byte StringHashToValueManager = 0xfb;
    public const byte UpdateStringHashToValueManager = 0xfc;
    public const byte TeamSpectateBase = 0xfd;

    private static readonly string?[] NamesById = BuildNames();

    /// <summary>The client's registered name for a base opcode, or null when none is registered.</summary>
    public static string? Name(byte opcode) => NamesById[opcode];

    private static string?[] BuildNames()
    {
        var names = new string?[256];
        names[0x01] = "BaseServerPacket";
        names[0x02] = "ClientFinishedLoading";
        names[0x03] = "SendSelfToClient";
        names[0x04] = "ClientIsReady";
        names[0x05] = "ZoneDoneSendingInitialData";
        names[0x06] = "ChatBase";
        names[0x07] = "ClientLogout";
        names[0x08] = "TargetClientNotOnline";
        names[0x09] = "CommandBase";
        names[0x0a] = "AdminBase";
        names[0x0b] = "ClientBeginZoning";
        names[0x0c] = "CombatBase";
        names[0x0d] = "ProjectileDebug";
        names[0x0e] = "MailBase";
        names[0x0f] = "CharacterBase";
        names[0x10] = "AbilityBase";
        names[0x11] = "ClientUpdateBase";
        names[0x13] = "GroupsBase";
        names[0x14] = "EncounterBase";
        names[0x15] = "InventoryBase";
        names[0x16] = "SendZoneDetails";
        names[0x17] = "ReferenceData";
        names[0x18] = "ObjectiveBase";
        names[0x19] = "DebugBase";
        names[0x1a] = "UiBase";
        names[0x1b] = "QuestBase";
        names[0x1c] = "RewardBase";
        names[0x1d] = "GameTimeSync";
        names[0x1e] = "PetBase";
        names[0x1f] = "PointOfInterestDefinitionRequest";
        names[0x20] = "PointOfInterestDefinitionReply";
        names[0x21] = "WorldTeleportRequest";
        names[0x22] = "TradeBase";
        names[0x23] = "EscrowGivePackage";
        names[0x24] = "EscrowGotPackage";
        names[0x25] = "UpdateEncounterDataCommon";
        names[0x26] = "RecipeBase";
        names[0x27] = "InGamePurchaseBase";
        names[0x28] = "QuickChatBase";
        names[0x29] = "ReportBase";
        names[0x2a] = "AcquaintanceBase";
        names[0x2b] = "ClientServerShuttingDown";
        names[0x2c] = "FriendBase";
        names[0x2d] = "BroadcastBase";
        names[0x2e] = "ClientKickedFromServer";
        names[0x2f] = "UpdateClientSessionData";
        names[0x30] = "BugSubmissionBase";
        names[0x31] = "WorldDisplayInfo";
        names[0x32] = "MOTD";
        names[0x33] = "SetLocale";
        names[0x34] = "SetClientArea";
        names[0x35] = "ZoneTeleportRequest";
        names[0x36] = "TradingCardBase";
        names[0x37] = "WorldShutdownNotice";
        names[0x38] = "LoadWelcomeScreen";
        names[0x39] = "ShipCombatBase";
        names[0x3b] = "KeepAlive";
        names[0x3c] = "ClientExitLaunchUri";
        names[0x3d] = "ClientPath";
        names[0x3e] = "ClientPendingKickFromServer";
        names[0x3f] = "ClientMembershipActivation";
        names[0x40] = "LobbyBase";
        names[0x41] = "LobbyGameDefinitionBase";
        names[0x42] = "ShowSystemMessage";
        names[0x43] = "POIChangeMessage";
        names[0x44] = "ClientMetrics";
        names[0x45] = "FirstTimeEventBase";
        names[0x46] = "ClaimBase";
        names[0x47] = "ClientLog";
        names[0x48] = "IgnoreBase";
        names[0x49] = "SnoopedPlayerBase";
        names[0x4a] = "PromotionalBase";
        names[0x4b] = "AddClientPortraitCrc";
        names[0x4c] = "ObjectiveTargetBase";
        names[0x4d] = "CommerceSessionRequest";
        names[0x4e] = "CommerceSessionResponse";
        names[0x4f] = "TrackedEvent";
        names[0x50] = "ClientLoginFailed";
        names[0x51] = "LoginToUChat";
        names[0x52] = "ZoneSafeTeleportRequest";
        names[0x53] = "RemoteInteractionRequest";
        names[0x56] = "UpdateCamera";
        names[0x58] = "GuildBase";
        names[0x59] = "AdminGuildBase";
        names[0x5a] = "BattleMagesBase";
        names[0x5b] = "WorldToWorldBase";
        names[0x5c] = "PerformAction";
        names[0x5d] = "EncounterMatchmakingBase";
        names[0x5e] = "ClientLuaMetrics";
        names[0x5f] = "RepeatingActivityBase";
        names[0x60] = "ClientGameSettings";
        names[0x61] = "ClientTrialProfileUpsell";
        names[0x62] = "ActivityManagerBase";
        names[0x63] = "RequestSendItemDefinitionsToClient";
        names[0x64] = "InspectBase";
        names[0x65] = "AchievementBase";
        names[0x66] = "PlayerTitleBase";
        names[0x67] = "MatchHistoryBase";
        names[0x68] = "UpdateUserAge";
        names[0x69] = "LootBase";
        names[0x6a] = "ActionBarManagerBase";
        names[0x6b] = "ClientTrialProfileUpsellRequest";
        names[0x6c] = "CliLobbyPlayerReady";
        names[0x6d] = "CoinStoreBase";
        names[0x6e] = "InitializationParameters";
        names[0x6f] = "ActivityBase";
        names[0x70] = "MountBase";
        names[0x71] = "ClientInitializationDetails";
        names[0x72] = "ClientAreaTimer";
        names[0x73] = "LoyaltyRewardBase";
        names[0x74] = "RatingBase";
        names[0x75] = "ClientActivityLaunchBase";
        names[0x76] = "ServerActivityLaunchBase";
        names[0x77] = "ClientFlashTimer";
        names[0x78] = "PlayerUpdatePosition";
        names[0x79] = "InviteAndStartMiniGame";
        names[0x7a] = "QuizBase";
        names[0x7b] = "PlayerUpdatePositionOnPlatform";
        names[0x7c] = "ClientMembershipVipInfo";
        names[0x7d] = "TargetBase";
        names[0x7f] = "GuideStoneBase";
        names[0x80] = "RaidsBase";
        names[0x81] = "VoiceBase";
        names[0x82] = "WeaponBase";
        names[0x83] = "MatchScheduleBase";
        names[0x84] = "FacilityBase";
        names[0x85] = "SkillsBase";
        names[0x86] = "LoadoutsBase";
        names[0x87] = "ExperienceBase";
        names[0x88] = "VehicleBase";
        names[0x89] = "GriefBase";
        names[0x8a] = "SpotPlayer";
        names[0x8b] = "FactionsBase";
        names[0x8c] = "Synchronization";
        names[0x8d] = "ResourceEventBase";
        names[0x8e] = "CollisionBase";
        names[0x8f] = "LeaderboardBase";
        names[0x90] = "PlayerUpdateManagedPosition";
        names[0x91] = "AddSimpleNpc";
        names[0x92] = "PlayerUpdateVehicleWeapon";
        names[0x93] = "ProfileStatsBase";
        names[0x94] = "EquipmentBase";
        names[0x95] = "DefinitionFiltersBase";
        names[0x96] = "ContinentBattleInfo";
        names[0x97] = "GetContinentBattleInfo";
        names[0x98] = "SendSecurityPacketAndSelfDestruct";
        names[0x99] = "GetRespawnLocations";
        names[0x9a] = "WallOfDataBase";
        names[0x9b] = "ImplantsBase";
        names[0x9c] = "InGamePurchase";
        names[0x9d] = "MissionsBase";
        names[0x9e] = "EffectsBase";
        names[0x9f] = "RewardBuffsBase";
        names[0xa0] = "AbilitiesBase";
        names[0xa1] = "DeployableBase";
        names[0xa2] = "Security";
        names[0xa3] = "MapRegionBase";
        names[0xa4] = "HudManagerBase";
        names[0xa5] = "AcquireTimersBase";
        names[0xa6] = "LoginBase";
        names[0xa7] = "ServerPopulationInfo";
        names[0xa8] = "GetServerPopulationInfo";
        names[0xa9] = "PlayerUpdateVehicleCollision";
        names[0xaa] = "PlayerStop";
        names[0xab] = "CurrencyBase";
        names[0xac] = "ItemsBase";
        names[0xad] = "PlayerUpdateAttachObject";
        names[0xae] = "PlayerUpdateDetachObject";
        names[0xaf] = "ClientSettings";
        names[0xb0] = "RewardBuffInfo";
        names[0xb1] = "GetRewardBuffInfo";
        names[0xb2] = "CaisBase";
        names[0xb3] = "ZoneSettingBase";
        names[0xb4] = "RequestPromoEligibilityUpdate";
        names[0xb5] = "PromoEligibilityReply";
        names[0xb6] = "MetaGameEventBase";
        names[0xb7] = "RequestWalletTopupUpdate";
        names[0xb8] = "StationCashActivePromoRequestUpdate";
        names[0xbb] = "OperationBase";
        names[0xbc] = "WordFilterBase";
        names[0xbd] = "StaticFacilityInfoBase";
        names[0xbe] = "ProxiedPlayerBase";
        names[0xbf] = "ResistsBase";
        names[0xc0] = "InGamePurchasingBase";
        names[0xc1] = "BusinessEnvironments";
        names[0xc2] = "EmpireScorePacketBase";
        names[0xc3] = "CharacterSelectSessionRequest";
        names[0xc4] = "CharacterSelectSessionResponse";
        names[0xc5] = "StatsBase";
        names[0xc6] = "ScoreBase";
        names[0xc7] = "ResourcesBase";
        names[0xc9] = "ConstructionBase";
        names[0xca] = "UpdateWeatherData";
        names[0xcb] = "NavGenBase";
        names[0xcc] = "LocksBase";
        names[0xcd] = "RagdollBase";
        names[0xcf] = "CharacterStateBase";
        names[0xd0] = "TimedGrantBase";
        names[0xd1] = "WeatherBase";
        names[0xd2] = "GameEscrowBase";
        names[0xd3] = "PlayCompositeEffect";
        names[0xd4] = "SetSpotted";
        names[0xd5] = "AddLightweightPc";
        names[0xd6] = "AddLightweightNpc";
        names[0xd7] = "AddLightweightVehicle";
        names[0xd8] = "AddProxiedObject";
        names[0xd9] = "LightweightToFullPc";
        names[0xda] = "LightweightToFullNpc";
        names[0xdb] = "LightweightToFullVehicle";
        names[0xdd] = "CheckLocalValues";
        names[0xde] = "ChronicleBase";
        names[0xdf] = "GrinderBase";
        names[0xe0] = "RequestObject";
        names[0xe1] = "ScreenEffectBase";
        names[0xe2] = "SpectatorBase";
        names[0xe3] = "WhitelistBase";
        names[0xe4] = "NpcFoundationPermissionsManagerBase";
        names[0xe5] = "BattlEyeData";
        names[0xe6] = "OnlineIdBase";
        names[0xe7] = "Ps4PlayGoBase";
        names[0xe8] = "SynchronizedTeleportBase";
        names[0xe9] = "StaticViewBase";
        names[0xea] = "ReplicationBase";
        names[0xeb] = "DatasheetsBase";
        names[0xec] = "PlayerWorldTransferRequest";
        names[0xed] = "PlayerWorldTransferReply";
        names[0xee] = "CancelQueueOnWorld";
        names[0xef] = "DeclineEnterGameOnWorld";
        names[0xf0] = "AccessedCharacterBase";
        names[0xf1] = "ShaderParameterOverrideBase";
        names[0xf2] = "VehicleSkinBase";
        names[0xf4] = "WeaponLagLockParameters";
        names[0xf5] = "CrateOpeningBase";
        names[0xf6] = "PlayerHeatWarning";
        names[0xf7] = "AnimationBase";
        names[0xf8] = "ProximateItemBase";
        names[0xf9] = "GrantPSNTrophyRequest";
        names[0xfa] = "PlayLength";
        names[0xfb] = "StringHashToValueManager";
        names[0xfc] = "UpdateStringHashToValueManager";
        names[0xfd] = "TeamSpectateBase";
        return names;
    }

    /// <summary>
    /// How wide each family's sub-opcode is, read off that family's own dispatcher.
    /// <para>
    /// The registration table lists members, not framing, so it cannot answer this; the
    /// dispatchers can, and do. Every number below is computed by
    /// <c>tools/opcodes/gen-zone-opcodes.py</c> from the C type at the read site in the cited
    /// decompile - a <c>byte *</c> is 1, a <c>ushort *</c> or an explicit <c>(short *)</c> cast
    /// is 2 - and the tool fails rather than guessing if the cited line moves.
    /// </para>
    /// </summary>
    public static class SubOpcodeWidth
    {
        /// <summary>
        /// <c>0x09</c> cPacketIdCommandBase: <b>2</b> byte sub-opcode.
        /// Read as <c>short *</c> in <c>FUN_14129ad10</c>
        /// (<c>ghidra-aug/doors-prompt-string/callers_14140c480/FUN_14129ad10_14129ad10.c</c>).
        /// <para>
        /// The Command dispatcher advances the cursor by 2 ((longlong)pfVar10 + 2U) and reads the
        /// selector through an explicit (short *) cast; case 0x2d is Command.InteractionString.
        /// </para>
        /// </summary>
        public const int Command = 2;

        /// <summary>
        /// <c>0x0f</c> cPacketIdCharacterBase: <b>1</b> byte sub-opcode.
        /// Read as <c>byte *</c> in <c>FUN_140af9ca0</c>
        /// (<c>ghidra-aug/character-dispatch/_140af9ca0/FUN_140af9ca0_140af9ca0.c</c>).
        /// <para>
        /// The Character dispatcher reads one byte at payload+1 and the u64 guid starts at payload+2,
        /// which is what makes RemovePlayer 12 bytes.
        /// </para>
        /// </summary>
        public const int Character = 1;

        /// <summary>
        /// <c>0x11</c> cPacketIdClientUpdateBase: <b>2</b> byte sub-opcode.
        /// Read as <c>ushort *</c> in <c>FUN_140afc660</c>
        /// (<c>ghidra-aug/loot-research/clientupdate-dispatch/_140afc660/FUN_140afc660_140afc660.c</c>).
        /// <para>
        /// The ClientUpdate dispatcher reads a ushort at payload+1; case 0x31 is TextAlert.
        /// </para>
        /// </summary>
        public const int ClientUpdate = 2;

        /// <summary>
        /// <c>0x82</c> cPacketIdWeaponBase: <b>1</b> byte sub-opcode, after 4 prefix byte(s).
        /// Read as <c>byte *</c> in <c>FUN_140b81830</c>
        /// (<c>ghidra-aug/fable-character-login/_140b81830_1420cd050/FUN_140b81830_140b81830.c</c>).
        /// <para>
        /// The weapon family header is u8 base; u32 gameTime; u8 sub - the pre-dispatch filter reads
        /// the u32 at payload+1 (pbVar15 = pbVar14 + 4) before dereferencing the sub as a byte (docs/84
        /// section 4).
        /// </para>
        /// </summary>
        public const int Weapon = 1;

        /// <summary>Bytes between the <c>0x82</c> base byte and its sub-opcode.</summary>
        public const int WeaponPrefixBytes = 4;

        /// <summary>
        /// <c>0x86</c> cPacketIdLoadoutsBase: <b>1</b> byte sub-opcode.
        /// Read as <c>byte *</c> in <c>FUN_140d37650</c>
        /// (<c>inventory-research/loadout-packet/_140b03170/FUN_140d37650_140d37650.c</c>).
        /// <para>
        /// The Loadouts handler reads one byte at payload+1 and then gates it with 6 &lt; bVar2 - 1,
        /// i.e. subs 1..7.
        /// </para>
        /// </summary>
        public const int Loadouts = 1;

        /// <summary>
        /// <c>0xce</c> (unregistered: the 0xce family has no base-id registration): <b>2</b> byte sub-opcode.
        /// Read as <c>ushort *</c> in <c>FUN_140bba510</c>
        /// (<c>ghidra-aug/matchflow-b5/_140bba510_14136ddf0_140c9e170_140a2d040_140a3ca40_140f25600/FUN_140bba510_140bba510.c</c>).
        /// <para>
        /// The GameMode/BR-HUD dispatcher reads a ushort at payload+1; this family is absent from
        /// registrations-1148.json, so 0xce has no ZoneOpcodes constant of its own.
        /// </para>
        /// </summary>
        public const int GameMode = 2;

        /// <summary>Every derived width, with the decompile each one was read in.</summary>
        public static readonly IReadOnlyList<ZoneSubOpcodeWidth> Derived =
        [
            new(0x09, "cPacketIdCommandBase", 2, 0, "FUN_14129ad10", "ghidra-aug/doors-prompt-string/callers_14140c480/FUN_14129ad10_14129ad10.c", "(local_1200 = (int)*(short *)pfVar10, pfVar9 <= pfVar1)"),
            new(0x0f, "cPacketIdCharacterBase", 1, 0, "FUN_140af9ca0", "ghidra-aug/character-dispatch/_140af9ca0/FUN_140af9ca0_140af9ca0.c", "uVar20 = (uint)*pbVar16;"),
            new(0x11, "cPacketIdClientUpdateBase", 2, 0, "FUN_140afc660", "ghidra-aug/loot-research/clientupdate-dispatch/_140afc660/FUN_140afc660_140afc660.c", "local_17d0 = (uint)*puVar19"),
            new(0x82, "cPacketIdWeaponBase", 1, 4, "FUN_140b81830", "ghidra-aug/fable-character-login/_140b81830_1420cd050/FUN_140b81830_140b81830.c", "switch((uint)*pbVar14) {"),
            new(0x86, "cPacketIdLoadoutsBase", 1, 0, "FUN_140d37650", "inventory-research/loadout-packet/_140b03170/FUN_140d37650_140d37650.c", "bVar2 = *pbVar5"),
            new(0xce, "(unregistered: the 0xce family has no base-id registration)", 2, 0, "FUN_140bba510", "ghidra-aug/matchflow-b5/_140bba510_14136ddf0_140c9e170_140a2d040_140a3ca40_140f25600/FUN_140bba510_140bba510.c", "local_70 = (uint)*puVar6"),
        ];

        /// <summary>The sub-opcode width of a family, or null when it has not been derived.</summary>
        public static int? For(byte baseOpcode)
        {
            foreach (ZoneSubOpcodeWidth row in Derived)
            {
                if (row.BaseOpcode == baseOpcode)
                {
                    return row.Bytes;
                }
            }

            return null;
        }
    }
}
