# Attach-mode zone-bootstrap trace. The August client crashes at 0x28097d4f4 within two
# seconds when it is *started* by gdb, so start it normally (run-client.ps1 -NoKey), attach with
#
#   gdb -batch -p <pid> -x C:\Aug2017\Server\tools\bootstrap-attach-trace.gdb > logs\gdb-bootstrap-<stamp>.out.log 2>&1
#
# then post the splash / title keys with press-client-key.ps1. Breakpoints: the SendSelfToClient
# outer parse and player creation (FUN_140af3950 case 3), the loader's return (no abort),
# PostInitialize's world init (FUN_140b36780 -> FUN_1423c7610), the heightfield world Init,
# zone asset opens and the local-actor creator (FUN_140acccd0). An access violation stops the
# run and prints the registers and a backtrace.
set pagination off
set confirm off
set breakpoint pending on
set print thread-events off
handle SIGILL nostop noprint pass
# The client uses handled access violations during startup (first-chance SIGSEGV with
# 0xfefefefe fill patterns seconds after attaching); pass them through and catch failures at
# their entry points instead.
handle SIGSEGV nostop noprint pass

# FUN_1409e1080: the self-record loader's exact-consumption assert (*(int*)0 = 0xbadbeef)
break *0x1409e1080
commands
  printf "TRACE ASSERT_BADBEEF consumed=%ld length=%ld flag=%d\n", *(long*)($stream+0x10) - *(long*)$stream, *(long*)($stream+8), *(char*)($stream+0x20)
  x/16xb *(long*)($stream+0x10)
  bt 12
  continue
end

# FUN_140b882b0(client, 1, 0x16, message, 0): fatal error -> shutdown ("... Exiting.")
break *0x140b882b0
commands
  printf "TRACE CLIENT_FATAL rdx=%d r8=%d msg=", $rdx, $r8d
  x/s $r9
  bt 10
  continue
end

# FUN_140b33f60: "Failed to load local player actor"
break *0x140b33f60
commands
  printf "TRACE ACTOR_LOAD_FAILED\n"
  bt 10
  continue
end

# FUN_140b36780: PostInitialize
break *0x140b36780
commands
  silent
  printf "TRACE POST_INITIALIZE\n"
  continue
end

break *0x140af4223
commands
  silent
  printf "TRACE SELF_PARSE_RETURN al=%u\n", $eax & 0xff
  continue
end

break *0x140af4286
commands
  silent
  printf "TRACE SELF_CREATED player=%p\n", $r15
  # From here on an access violation is worth a stop: the startup-phase ones are behind us.
  handle SIGSEGV stop print
  continue
end

break *0x140af4348
commands
  silent
  printf "TRACE SELF_LOADER_RETURNED\n"
  continue
end

break *0x140b3684d
commands
  silent
  printf "TRACE WORLD_CALL type=%d name=", $r8d
  x/s $rdx
  continue
end

break *0x140b36852
commands
  silent
  printf "TRACE WORLD_RETURN al=%u storedType=%d name=", $eax & 0xff, *(int *)($rdi+0x32298)
  x/s *(void **)($rdi+0x32288)
  continue
end

break *0x142220f80
commands
  silent
  printf "TRACE HEIGHTFIELD_INIT name="
  x/s $rdx
  continue
end

break *0x142221020
commands
  silent
  printf "TRACE HEIGHTFIELD_BASE_RETURN al=%u\n", $eax & 0xff
  continue
end

break *0x142d4f240
commands
  silent
  printf "TRACE ZONE_ASSET_OPEN name="
  x/s *(void **)($rcx+0x28)
  continue
end

break *0x142d4f2b5
commands
  silent
  printf "TRACE ZONE_ASSET_RESULT raw=%d\n", $eax
  continue
end

break *0x140acccd0
commands
  silent
  printf "TRACE ACTOR_CREATE rcx=%p rdx=%p\n", $rcx, $rdx
  continue
end


# --- generated by tools/selfschema/gen-subloader-trace.py: cursor offset at every sub-loader entry ---
break *0x140a31140
commands
  silent
  set $stream = $rdx
  printf "TRACE LOADER_ENTER stream=%p base=%p length=%ld\n", $stream, *(long*)$stream, *(long*)($stream+8)
  continue
end
break *0x140a40000
commands
  silent
  printf "TRACE ENTER FUN_140a40000 expected=109 consumed=%ld flag=%d\n", *(long*)($rdx+0x10) - *(long*)$rdx, *(char*)($rdx+0x20)
  continue
end
break *0x140a4d190
commands
  silent
  printf "TRACE ENTER FUN_140a4d190 expected=149 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end
break *0x140a331a0
commands
  silent
  printf "TRACE ENTER FUN_140a331a0 expected=241 consumed=%ld flag=%d\n", *(long*)($rdx+0x10) - *(long*)$rdx, *(char*)($rdx+0x20)
  continue
end
break *0x140a33b50
commands
  silent
  printf "TRACE ENTER FUN_140a33b50 expected=253 consumed=%ld flag=%d\n", *(long*)($rdx+0x10) - *(long*)$rdx, *(char*)($rdx+0x20)
  continue
end
break *0x140a30790
commands
  silent
  printf "TRACE ENTER FUN_140a30790 expected=274 consumed=%ld flag=%d\n", *(long*)($rdx+0x10) - *(long*)$rdx, *(char*)($rdx+0x20)
  continue
end
break *0x140a54bc0
commands
  silent
  printf "TRACE ENTER FUN_140a54bc0 expected=282 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end
break *0x140a4c970
commands
  silent
  printf "TRACE ENTER FUN_140a4c970 expected=291 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end
break *0x140a33390
commands
  silent
  printf "TRACE ENTER FUN_140a33390 expected=307 consumed=%ld flag=%d\n", *(long*)($rdx+0x10) - *(long*)$rdx, *(char*)($rdx+0x20)
  continue
end
break *0x140a4d020
commands
  silent
  printf "TRACE ENTER FUN_140a4d020 expected=315,391,395 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end
break *0x140a4caf0
commands
  silent
  printf "TRACE ENTER FUN_140a4caf0 expected=327,331 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end
break *0x140a5d190
commands
  silent
  printf "TRACE ENTER FUN_140a5d190 expected=335 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end
break *0x140a2b590
commands
  silent
  printf "TRACE ENTER FUN_140a2b590 expected=347 consumed=%ld flag=%d\n", *(long*)($rdx+0x10) - *(long*)$rdx, *(char*)($rdx+0x20)
  continue
end
break *0x140a55420
commands
  silent
  printf "TRACE ENTER FUN_140a55420 expected=347,351 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end
break *0x140a4ce90
commands
  silent
  printf "TRACE ENTER FUN_140a4ce90 expected=355 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end
break *0x140a2b650
commands
  silent
  printf "TRACE ENTER FUN_140a2b650 expected=359 consumed=%ld flag=%d\n", *(long*)($rdx+0x10) - *(long*)$rdx, *(char*)($rdx+0x20)
  continue
end
break *0x140a552e0
commands
  silent
  printf "TRACE ENTER FUN_140a552e0 expected=359,363,367,371 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end
break *0x140a56110
commands
  silent
  printf "TRACE ENTER FUN_140a56110 expected=383 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end
break *0x140a55c80
commands
  silent
  printf "TRACE ENTER FUN_140a55c80 expected=387 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end
break *0x140a2c000
commands
  silent
  printf "TRACE ENTER FUN_140a2c000 expected=399 consumed=%ld flag=%d\n", *(long*)($rdx+0x10) - *(long*)$rdx, *(char*)($rdx+0x20)
  continue
end
break *0x140a56530
commands
  silent
  printf "TRACE ENTER FUN_140a56530 expected=399 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end
break *0x140a5cac0
commands
  silent
  printf "TRACE ENTER FUN_140a5cac0 expected=403 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end
break *0x140a2eb50
commands
  silent
  printf "TRACE ENTER FUN_140a2eb50 expected=408 consumed=%ld flag=%d\n", *(long*)($rdx+0x10) - *(long*)$rdx, *(char*)($rdx+0x20)
  continue
end
break *0x140a2ec10
commands
  silent
  printf "TRACE ENTER FUN_140a2ec10 expected=412 consumed=%ld flag=%d\n", *(long*)($rdx+0x10) - *(long*)$rdx, *(char*)($rdx+0x20)
  continue
end
break *0x140a2ecc0
commands
  silent
  printf "TRACE ENTER FUN_140a2ecc0 expected=424 consumed=%ld flag=%d\n", *(long*)($rdx+0x10) - *(long*)$rdx, *(char*)($rdx+0x20)
  continue
end
break *0x140a30570
commands
  silent
  printf "TRACE ENTER FUN_140a30570 expected=444 consumed=%ld flag=%d\n", *(long*)($rdx+0x10) - *(long*)$rdx, *(char*)($rdx+0x20)
  continue
end
break *0x140a30370
commands
  silent
  printf "TRACE ENTER FUN_140a30370 expected=452 consumed=%ld flag=%d\n", *(long*)($rdx+0x10) - *(long*)$rdx, *(char*)($rdx+0x20)
  continue
end
break *0x140a30490
commands
  silent
  printf "TRACE ENTER FUN_140a30490 expected=472 consumed=%ld flag=%d\n", *(long*)($rdx+0x10) - *(long*)$rdx, *(char*)($rdx+0x20)
  continue
end
break *0x140a4d330
commands
  silent
  printf "TRACE ENTER FUN_140a4d330 expected=493 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end
break *0x140a37670
commands
  silent
  printf "TRACE ENTER FUN_140a37670 expected=497 consumed=%ld flag=%d\n", *(long*)($rdx+0x10) - *(long*)$rdx, *(char*)($rdx+0x20)
  continue
end
break *0x140a37720
commands
  silent
  printf "TRACE ENTER FUN_140a37720 expected=501 consumed=%ld flag=%d\n", *(long*)($rdx+0x10) - *(long*)$rdx, *(char*)($rdx+0x20)
  continue
end
break *0x140a55530
commands
  silent
  printf "TRACE ENTER FUN_140a55530 expected=517 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end
break *0x140a5a510
commands
  silent
  printf "TRACE ENTER FUN_140a5a510 expected=521 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end
break *0x140a5a320
commands
  silent
  printf "TRACE ENTER FUN_140a5a320 expected=525 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end
break *0x140a57220
commands
  silent
  printf "TRACE ENTER FUN_140a57220 expected=529 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end
break *0x140a57090
commands
  silent
  printf "TRACE ENTER FUN_140a57090 expected=533 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end
break *0x140a563e0
commands
  silent
  printf "TRACE ENTER FUN_140a563e0 expected=537 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end
break *0x140a4edb0
commands
  silent
  printf "TRACE ENTER FUN_140a4edb0 expected=541 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end
break *0x140a395e0
commands
  silent
  printf "TRACE ENTER FUN_140a395e0 expected=545 consumed=%ld flag=%d\n", *(long*)($rdx+0x10) - *(long*)$rdx, *(char*)($rdx+0x20)
  continue
end
break *0x140a39690
commands
  silent
  printf "TRACE ENTER FUN_140a39690 expected=549 consumed=%ld flag=%d\n", *(long*)($rdx+0x10) - *(long*)$rdx, *(char*)($rdx+0x20)
  continue
end
break *0x140a39f30
commands
  silent
  printf "TRACE ENTER FUN_140a39f30 expected=565 consumed=%ld flag=%d\n", *(long*)($rdx+0x10) - *(long*)$rdx, *(char*)($rdx+0x20)
  continue
end
break *0x140a55ae0
commands
  silent
  printf "TRACE ENTER FUN_140a55ae0 expected=577 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end
break *0x140a2b910
commands
  silent
  printf "TRACE ENTER FUN_140a2b910 expected=581 consumed=%ld flag=%d\n", *(long*)($rdx+0x10) - *(long*)$rdx, *(char*)($rdx+0x20)
  continue
end
break *0x140a57340
commands
  silent
  printf "TRACE ENTER FUN_140a57340 expected=581 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end
break *0x140a57530
commands
  silent
  printf "TRACE ENTER FUN_140a57530 expected=585 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end
break *0x140a57910
commands
  silent
  printf "TRACE ENTER FUN_140a57910 expected=589 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end
break *0x140a393b0
commands
  silent
  printf "TRACE ENTER FUN_140a393b0 expected=593 consumed=%ld flag=%d\n", *(long*)($rdx+0x10) - *(long*)$rdx, *(char*)($rdx+0x20)
  continue
end
break *0x140a57760
commands
  silent
  printf "TRACE ENTER FUN_140a57760 expected=593 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end
break *0x140a3af50
commands
  silent
  printf "TRACE ENTER FUN_140a3af50 expected=597 consumed=%ld flag=%d\n", *(long*)($rdx+0x10) - *(long*)$rdx, *(char*)($rdx+0x20)
  continue
end
break *0x140a3fa20
commands
  silent
  printf "TRACE ENTER FUN_140a3fa20 expected=597 consumed=%ld flag=%d\n", *(long*)($rdx+0x10) - *(long*)$rdx, *(char*)($rdx+0x20)
  continue
end
break *0x140a4f6f0
commands
  silent
  printf "TRACE ENTER FUN_140a4f6f0 expected=621 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end
break *0x140a3fb00
commands
  silent
  printf "TRACE ENTER FUN_140a3fb00 expected=625 consumed=%ld flag=%d\n", *(long*)($rdx+0x10) - *(long*)$rdx, *(char*)($rdx+0x20)
  continue
end
break *0x140a4f8c0
commands
  silent
  printf "TRACE ENTER FUN_140a4f8c0 expected=641 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end
break *0x140a4f560
commands
  silent
  printf "TRACE ENTER FUN_140a4f560 expected=645 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end
break *0x140a461b0
commands
  silent
  printf "TRACE ENTER FUN_140a461b0 expected=650 consumed=%ld flag=%d\n", *(long*)($rdx+0x10) - *(long*)$rdx, *(char*)($rdx+0x20)
  continue
end
break *0x140a507a0
commands
  silent
  printf "TRACE ENTER FUN_140a507a0 expected=662 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end
break *0x140a55700
commands
  silent
  printf "TRACE ENTER FUN_140a55700 expected=666 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end
break *0x140a56b50
commands
  silent
  printf "TRACE ENTER FUN_140a56b50 expected=670 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end
break *0x140a3bb00
commands
  silent
  printf "TRACE ENTER FUN_140a3bb00 expected=674 consumed=%ld flag=%d\n", *(long*)($rdx+0x10) - *(long*)$rdx, *(char*)($rdx+0x20)
  continue
end
break *0x140a55fa0
commands
  silent
  printf "TRACE ENTER FUN_140a55fa0 expected=678 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end
break *0x140a56280
commands
  silent
  printf "TRACE ENTER FUN_140a56280 expected=686 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end
break *0x140a495b0
commands
  silent
  printf "TRACE ENTER FUN_140a495b0 expected=690 consumed=%ld flag=%d\n", *(long*)($rdx+0x10) - *(long*)$rdx, *(char*)($rdx+0x20)
  continue
end
break *0x140a5b8e0
commands
  silent
  printf "TRACE ENTER FUN_140a5b8e0 expected=690 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end
break *0x140a5baa0
commands
  silent
  printf "TRACE ENTER FUN_140a5baa0 expected=694 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end
break *0x140a5bc60
commands
  silent
  printf "TRACE ENTER FUN_140a5bc60 expected=698 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end
break *0x140a5bfd0
commands
  silent
  printf "TRACE ENTER FUN_140a5bfd0 expected=702,706 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end
break *0x140a56700
commands
  silent
  printf "TRACE ENTER FUN_140a56700 expected=710 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end
break *0x140a45f80
commands
  silent
  printf "TRACE ENTER FUN_140a45f80 expected=714 consumed=%ld flag=%d\n", *(long*)($rdx+0x10) - *(long*)$rdx, *(char*)($rdx+0x20)
  continue
end
break *0x140a569c0
commands
  silent
  printf "TRACE ENTER FUN_140a569c0 expected=758 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end
break *0x140a55df0
commands
  silent
  printf "TRACE ENTER FUN_140a55df0 expected=762 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end
break *0x140a4eb30
commands
  silent
  printf "TRACE ENTER FUN_140a4eb30 expected=766 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end
break *0x140a56cd0
commands
  silent
  printf "TRACE ENTER FUN_140a56cd0 expected=770 consumed=%ld flag=%d\n", *(long*)($rcx+0x10) - *(long*)$rcx, *(char*)($rcx+0x20)
  continue
end

continue
printf "TRACE STOP1 pc=%p\n", $pc
info registers rip rsp rax rbx rcx rdx rsi rdi r8 r9 r10 r11 r12 r13 r14 r15
x/12i $pc-24
bt 25
# A second continue tells a handled first-chance exception from a fatal one.
continue
printf "TRACE STOP2 pc=%p\n", $pc
info registers rip rax rcx rdx
bt 12
