// <cranberry-provenance>
// Written by tools/pipeline/pipeline.py (docs/96). `pipeline.py check` recomputes every
// hash below and fails the build when one has moved; do not edit this block by hand.
// id: footwear
// grade: CLIENT
// clientBuild: 0.0.118.208059
// generator: tools/world/gen-footwear.py sha256=75aa43c1710257979a14d10b148dbba3b103276eae37de221da8f5560836e2e7
// input: out/data_aug/ClientItemDefinitions.txt sha256=638deb01b4eeb565d1c8fc2037e0169518a2c54dd23f19c776f25d3e39dab114 crc32=ffb21654 size=489792 grade=CLIENT
// rulings: D351
// generatedUtc: 2026-09-05T08:01:40Z
// </cranberry-provenance>
// Generated by tools/world/gen-footwear.py from August ClientItemDefinitions.txt.
// SHA256 638deb01b4eeb565d1c8fc2037e0169518a2c54dd23f19c776f25d3e39dab114
namespace Cranberry.Zone.Movement;

public static class FootwearItems
{
    public static IReadOnlyDictionary<uint, FootwearTier> Tiers { get; } = new Dictionary<uint, FootwearTier>
    {
        [2206] = FootwearTier.Sturdy,
        [2207] = FootwearTier.Sturdy,
        [2208] = FootwearTier.Sturdy,
        [2209] = FootwearTier.Sturdy,
        [2215] = FootwearTier.Fast,
        [2216] = FootwearTier.Fast,
        [2217] = FootwearTier.Fast,
        [2218] = FootwearTier.Fast,
        [2281] = FootwearTier.Sturdy,
        [2282] = FootwearTier.Sturdy,
        [2398] = FootwearTier.Fast,
        [2550] = FootwearTier.Stealth,
        [2563] = FootwearTier.Stealth,
        [2564] = FootwearTier.Stealth,
        [2565] = FootwearTier.Stealth,
        [2566] = FootwearTier.Stealth,
        [2567] = FootwearTier.Stealth,
        [2613] = FootwearTier.Sturdy,
        [2614] = FootwearTier.Sturdy,
        [2615] = FootwearTier.Sturdy,
        [2616] = FootwearTier.Sturdy,
        [2617] = FootwearTier.Sturdy,
        [2618] = FootwearTier.Sturdy,
        [2619] = FootwearTier.Sturdy,
        [2620] = FootwearTier.Sturdy,
        [2621] = FootwearTier.Sturdy,
        [2795] = FootwearTier.Fast,
        [3127] = FootwearTier.Fast,
        [3128] = FootwearTier.Fast,
        [3129] = FootwearTier.Fast,
        [3166] = FootwearTier.Fast,
        [3173] = FootwearTier.Stealth,
        [3180] = FootwearTier.Sturdy,
        [3212] = FootwearTier.Stealth,
        [3358] = FootwearTier.Sturdy,
        [3404] = FootwearTier.Fast,
        [3408] = FootwearTier.Sturdy,
        [3412] = FootwearTier.Stealth,
        [3464] = FootwearTier.Fast,
        [3466] = FootwearTier.Sturdy,
        [3485] = FootwearTier.Stealth,
        [3486] = FootwearTier.Stealth,
        [3493] = FootwearTier.Sturdy,
        [3508] = FootwearTier.Stealth,
        [3552] = FootwearTier.Sturdy,
        [3574] = FootwearTier.Fast,
        [3641] = FootwearTier.Sturdy,
        [3708] = FootwearTier.Stealth,
        [3709] = FootwearTier.Stealth,
        [3710] = FootwearTier.Stealth,
        [3711] = FootwearTier.Stealth,
        [3725] = FootwearTier.Sturdy,
        [3730] = FootwearTier.Stealth,
        [3735] = FootwearTier.Stealth,
        [3891] = FootwearTier.Fast,
        [3894] = FootwearTier.Fast,
        [3898] = FootwearTier.Fast,
        [3929] = FootwearTier.Fast,
        [3961] = FootwearTier.Sturdy,
        [4027] = FootwearTier.Sturdy,
        [4105] = FootwearTier.Fast,
        [4179] = FootwearTier.Sturdy,
        [4185] = FootwearTier.Fast,
    };
}
