using Cranberry.Zone.DevConsole;

namespace Cranberry.Tests.Zone.DevConsole;

/// <summary>
/// Pins the census of the August client's own console registry — the oracle that decides whether a
/// name Cranberry pushes will be refused by the client and become un-typeable.
/// <para>
/// The rows come from the binary (<c>ClientRegistry1148.g.cs</c>, generated by
/// <c>tools/devconsole/gen-client-registry.py</c> from the 2026-09-02 headless harvest); these tests
/// assert the shape of the census and the one property the console depends on — that none of
/// Cranberry's 50 names is already taken.
/// </para>
/// </summary>
public sealed class ClientRegistry1148Tests
{
    [Fact]
    public void HoldsTheWholeCensus()
    {
        Assert.Equal(1025, ClientRegistry1148.Entries.Count);
        Assert.Equal(1025, ClientRegistry1148.Hashes.Count);
    }

    [Fact]
    public void EveryNamedEntryHashesToItsOwnKey()
    {
        // The names are pre-images recovered by hashing every string in the exe, so they are only
        // as good as that search: this is the check that keeps a wrong pre-image out of an error
        // message. (Two hashes have no recovered name; they are still in the set, which is what
        // the lookup FUN_141e9d680 actually matches on.)
        foreach (ClientRegistryEntry entry in ClientRegistry1148.Entries)
        {
            if (entry.Name is not null)
            {
                Assert.Equal(entry.Hash, CommandHash.Compute(entry.Name));
            }
        }

        Assert.Equal(2, ClientRegistry1148.Entries.Count(entry => entry.Name is null));
    }

    [Theory]
    [InlineData("alias", 0x3a791e37u, "command-runtime")]
    [InlineData("clearcvar", 0xf4f9f519u, "command-runtime")]
    [InlineData("respawn", 0xddc66baeu, "command-builtin")]
    [InlineData("serverinfo", 0x8d547377u, "command-builtin")]
    [InlineData("netstats", 0x0fcc2872u, "command-builtin")]
    [InlineData("spectate", 0xfe71d25du, "command-builtin")]
    [InlineData("god", 0x6c9a59d0u, "alias-builtin")]
    [InlineData("actor_force_visible", 0x696413a4u, "cvar-static")]
    public void ContainsTheNamesTheClientOwns(string name, uint hash, string kind)
    {
        Assert.Equal(hash, CommandHash.Compute(name));
        Assert.True(ClientRegistry1148.Contains(hash));
        Assert.Equal($"{name} ({kind})", ClientRegistry1148.Describe(hash));
    }

    [Fact]
    public void TheFourKindsAreAllPresentInTheCensusedNumbers()
    {
        Dictionary<string, int> kinds = ClientRegistry1148.Entries
            .GroupBy(entry => entry.Kind)
            .ToDictionary(group => group.Key, group => group.Count());

        Assert.Equal(975, kinds["cvar-static"]);
        Assert.Equal(37, kinds["command-builtin"]);
        Assert.Equal(9, kinds["alias-builtin"]);
        Assert.Equal(4, kinds["command-runtime"]);
    }

    [Fact]
    public void NotOneOfCranberrysNamesIsAlreadyTakenByTheClient()
    {
        // A hit here is fatal to that verb: FUN_141280280 would log "conflicts with a local
        // command" to Client\Logs\AdminCommands.log, register nothing, and the client would then
        // emit no packet at all when the owner types it.
        foreach ((string name, uint hash) in ConsoleNameVectors.Appendix)
        {
            Assert.False(
                ClientRegistry1148.Contains(hash),
                $"/{name} collides with the client's {ClientRegistry1148.Describe(hash)}");
        }
    }

    [Fact]
    public void NoTwoCranberryNamesShareAHash()
    {
        // The server keys its own command table by the same hash, so a collision inside the burst
        // would make one of the two verbs unreachable on both sides.
        Assert.Equal(
            ConsoleNameVectors.Appendix.Count,
            ConsoleNameVectors.Appendix.Select(row => row.Hash).Distinct().Count());
    }

    [Fact]
    public void TheNamesTheDesignKeepsOffTheBurstAreTheOnesTheClientOwns()
    {
        // Why /god, /respawn, /vehicle, /item, /run and /goto are not Cranberry verbs.
        foreach (string name in new[] { "god", "serverinfo", "netstats", "spectate", "respawn", "vehicle", "item", "run", "goto" })
        {
            Assert.True(ClientRegistry1148.Contains(CommandHash.Compute(name)), name);
        }

        // ...and why say/kick/gm/version/location are kept off out of caution rather than proof:
        // they are not in the registry at all, the risk is the chat-word table the census cannot see.
        foreach (string name in new[] { "say", "kick", "gm", "version", "location", "help" })
        {
            Assert.False(ClientRegistry1148.Contains(CommandHash.Compute(name)), name);
        }
    }

    [Fact]
    public void DescribeNamesTheKindEvenWithoutAPreImageAndSaysSoForAStranger()
    {
        uint unnamed = ClientRegistry1148.Entries.First(entry => entry.Name is null).Hash;
        Assert.Equal($"0x{unnamed:x8} (cvar-static, name unknown)", ClientRegistry1148.Describe(unnamed));

        uint mine = CommandHash.Compute("godmode");
        Assert.Equal($"0x{mine:x8} (not registered by the client)", ClientRegistry1148.Describe(mine));
    }
}
