#!/usr/bin/env python3
"""Emit the working Z1 table's weapon presentation fields for August's known list-0 layout."""
import importlib.util
from pathlib import Path
import json

root = Path(__file__).resolve().parents[2]
spec = importlib.util.spec_from_file_location('decoder', Path(__file__).with_name('decode-friend-table.py'))
decoder = importlib.util.module_from_spec(spec)
spec.loader.exec_module(decoder)
report = decoder.decode(Path(r'C:\Z1\Server\Data\friendWeaponDefinitions.bin').read_bytes(), root,
                        r'C:\Z1\Server\Data\weaponDefinitionSchema.json')
if not report['walk1087']['clean']:
    raise SystemExit('Incomplete capture decode')
groups = {r['ID']: r['DATA'] for r in report['table1087']['FIRE_GROUP_DEFINITIONS']}
fields = ['WEAPON_GROUP_ID', 'EQUIP_MS', 'UNEQUIP_MS', 'TO_IRON_SIGHTS_MS', 'FROM_IRON_SIGHTS_MS', 'TO_IRON_SIGHTS_ANIM_MS',
          'FROM_IRON_SIGHTS_ANIM_MS', 'SPRINT_RECOVERY_MS']
lines = [
    '// <auto-generated> tools/weapons/gen-weapon-handling.py; do not edit.',
    '// Z1 capture body MD5: ' + report['header']['body_md5'],
    '// August field names/offsets: FUN_1421e63f0 and FUN_140a46ef0.',
    '// </auto-generated>',
    'using System.Collections.Frozen;', '', 'namespace Cranberry.Zone.Weapons;', '',
    'public readonly record struct CapturedWeaponHandling(',
    '    uint WeaponGroupId, uint EquipMs, uint UnequipMs, uint AimInMs, uint AimOutMs,',
    '    uint AimInAnimMs, uint AimOutAnimMs,',
    '    uint SprintRecoveryMs, string AnimationSetName, byte FireGroupFlags);', '',
    'public static class CapturedWeaponHandlingFacts', '{',
    '    public static FrozenDictionary<uint, CapturedWeaponHandling> ByWeaponId { get; } =',
    '        new Dictionary<uint, CapturedWeaponHandling>', '        {',
]
for row in sorted(report['table1087']['WEAPON_DEFINITIONS'], key=lambda x: x['ID']):
    d = row['DATA']
    if not d['FIRE_GROUPS']:
        continue
    g = groups.get(d['FIRE_GROUPS'][0]['FIRE_GROUP_ID'])
    if g is None:
        continue
    values = ', '.join(str(d[k]) + 'u' for k in fields)
    lines.append(f'            [{row["ID"]}u] = new({values}, {json.dumps(d["ANIMATION_SET_NAME"])}, {g["FLAGS"]}),')
lines.extend(['        }.ToFrozenDictionary();', '}', ''])
output = root / 'src/Cranberry.Zone/Weapons/CapturedWeaponHandlingFacts.cs'
output.write_text('\n'.join(lines), encoding='utf-8')
print(output)
