#!/usr/bin/env python3
"""Cross captured weapon audio hashes only when the August asset contains that object.

Run from the repository root. Reads packs, capture and schema; writes one C# facts file.
The protocol layouts are decoded by decode-friend-table.py. No client files are modified.
"""
import argparse
import hashlib
import importlib.util
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / 'pack'))
import packread


def module(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    result = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(result)
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source-root', type=Path, default=Path('.'))
    parser.add_argument('--assets', type=Path, default=packread.DEFAULT_ASSETS_DIR)
    parser.add_argument('--input', type=Path, default=Path(r'C:\Z1\Server\Data\friendWeaponDefinitions.bin'))
    parser.add_argument('--schema', default=r'C:\Z1\Server\Data\weaponDefinitionSchema.json')
    args = parser.parse_args()
    decoder = module('friend_table', HERE / 'decode-friend-table.py')
    hashes = module('client_hash', HERE.parent / 'devconsole' / 'gen-client-registry.py')
    report = decoder.decode(args.input.read_bytes(), args.source_root.resolve(), args.schema)
    if not report['walk1087']['clean']:
        raise SystemExit('Capture does not decode completely')

    entries = [entry for pack in sorted(args.assets.glob('Assets_*.pack'))
               for entry in packread.read_pack_index(pack)
               if entry.name == 'GameObjectInstances.xml']
    if len(entries) != 1:
        raise SystemExit('Expected exactly one GameObjectInstances.xml')
    entry = entries[0]
    with entry.pack.open('rb') as source:
        source.seek(entry.offset)
        raw = source.read(entry.size)
    import zlib
    if zlib.crc32(raw) != entry.crc32:
        raise SystemExit('GameObjectInstances.xml CRC mismatch')
    objects = {}
    for node in ET.fromstring(raw):
        if node.get('typeName') == 'WeaponAudioParams':
            key = hashes.command_hash(node.tag)  # same loop in FUN_1421e63f0
            if key in objects:
                raise SystemExit('Weapon audio object hash collision')
            objects[key] = node.tag

    rows = []
    unresolved = []
    for row in report['table1087']['WEAPON_DEFINITIONS']:
        key = row['DATA']['AUDIO_GAME_OBJECT']
        if key in objects:
            rows.append((row['ID'], key, objects[key]))
        elif key:
            unresolved.append(row['ID'])
    lines = [
        '// <auto-generated> tools/weapons/gen-weapon-audio.py; do not edit by hand.',
        '// Capture body MD5: ' + report['header']['body_md5'],
        '// August GameObjectInstances.xml SHA256: ' + hashlib.sha256(raw).hexdigest(),
        '// Only hashes resolving to August WeaponAudioParams objects are included.',
        '// </auto-generated>',
        'using System.Collections.Frozen;', '',
        'namespace Cranberry.Zone.Weapons;', '',
        '/// <summary>Capture weapon IDs joined to audio objects present in the August client.</summary>',
        'public static class CapturedWeaponAudioFacts', '{',
        '    public readonly record struct AudioObject(uint Hash, string Name);',
        '    public static FrozenDictionary<uint, AudioObject> ByWeaponDefinitionId { get; } =',
        '        new Dictionary<uint, AudioObject>', '        {',
    ]
    lines.extend(f'            [{weapon}u] = new({key}u, "{name}"),' for weapon, key, name in sorted(rows))
    lines.extend(['        }.ToFrozenDictionary();', '}', ''])
    target = args.source_root / 'src/Cranberry.Zone/Weapons/CapturedWeaponAudioFacts.cs'
    target.write_text('\n'.join(lines), encoding='utf-8')
    print(f'Wrote {target}: {len(rows)} verified joins; omitted {len(unresolved)} unresolved hashes')


if __name__ == '__main__':
    main()
