"""Translate the reviewed 12 September 1315 gun profile into August fields.

Usage: python gen-z1-live-gunplay.py <inflated-reference-weapons.bin>
The source hash and complete structural reader are mandatory. Cross-version
recoil correspondences are an adaptation, not proof of identical native feel.
No raw later-protocol records, audio IDs, or projectile identities are shipped.
"""
import hashlib
import importlib.util
import math
from pathlib import Path
import struct
import sys

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / 'tools/diagnostics/z1br-parity'))
from weapon_1315 import parse
from field_comparison import normalized, COLUMNS

SOURCE_SHA = '7305e622f12142dc690e95222bea238143cb670c15778627e3df515c0ca0f605'
# August ammo-bearing firearms, including aliases. Both 12GA IDs are excluded.
WEAPONS = (2, 6, 1337, 1373, 1388, 1400, 1401, 1405, 1424, 1432, 1434, 1435, 1455, 1456, 1457)
# The new record places angle and recovery after first-shot/horizontal increases.
# Its signed recovery delay is retained, including the M1911's -150 ms.
# Extra later-client recovery/curve fields have no August equivalent and are omitted.
RECOIL = (
 ('RECOIL_HORIZONTAL_TOLERANCE',85,'f'), ('RECOIL_HORIZONTAL_MIN',89,'f'),
 ('RECOIL_HORIZONTAL_MAX',93,'f'), ('RECOIL_MAGNITUDE_MIN',97,'f'),
 ('RECOIL_MAGNITUDE_MAX',101,'f'), ('RECOIL_SHOTS_AT_MIN_MAGNITUDE',105,'B'),
 ('RECOIL_MAX_TOTAL_MAGNITUDE',106,'f'), ('RECOIL_INCREASE',110,'f'),
 ('RECOIL_INCREASE_CROUCHED',114,'f'), ('RECOIL_FIRST_SHOT_MODIFIER',118,'f'),
 ('RECOIL_HORIZONTAL_MIN_INCREASE',122,'f'), ('RECOIL_HORIZONTAL_MAX_INCREASE',126,'f'),
 ('RECOIL_ANGLE_MIN',130,'f'), ('RECOIL_ANGLE_MAX',134,'f'),
 ('RECOIL_RECOVERY_DELAY_MS',138,'h'), ('RECOIL_RECOVERY_RATE',140,'f'),
 ('RECOIL_RECOVERY_ACCELERATION',144,'f'))

def main():
    body=Path(sys.argv[1]).read_bytes()
    assert hashlib.sha256(body).hexdigest()==SOURCE_SHA, 'Unreviewed reference body'
    table=parse(body)
    spec=importlib.util.spec_from_file_location('dft',ROOT/'tools/weapons/decode-friend-table.py')
    dft=importlib.util.module_from_spec(spec);spec.loader.exec_module(dft)
    offsets={name:off for off,cols in dft.load_fire_mode_columns(ROOT).items() for name,_,_ in cols}
    definitions={w['id']:w for w in table['lists'][0]}
    groups={g['id']:g for g in table['lists'][1]}
    modes={m['id']:m for m in table['lists'][2]}
    # The two supported hip/ADS modes; extra modern alternate modes remain explicit
    # in the reference audit and are not assigned speculative August input bindings.
    selected=sorted({mid for wid in WEAPONS for gid in definitions[wid]['groups'][:1]
                     for mid in groups[gid]['modes'][:2]})
    names=[c for c in COLUMNS if c[0] not in ('AMMO_ITEM_ID','FP_CAMERA_FOV')]+list(RECOIL)
    cone_ids=set();assist_ids=set()
    lines=['// <auto-generated> tools/weapons/gen-z1-live-gunplay.py',
           f'// Reference WeaponDefinitions SHA256 {SOURCE_SHA}',
           '// Inferred cross-version recoil adaptation; see docs/gameplay-followup-20260912.md.',
           '// </auto-generated>', 'namespace Cranberry.Zone.Weapons;', '',
           'public static class Z1LiveGunplayFacts', '{',
           '    public static IReadOnlyDictionary<uint, IReadOnlyDictionary<short, uint>> Modes { get; } =',
           '        new Dictionary<uint, IReadOnlyDictionary<short, uint>>', '        {']
    for mid in selected:
        n=normalized(body,modes[mid]);words={}
        for name,at,kind in names:
            value=struct.unpack_from('<'+kind,n,at)[0]
            assert not isinstance(value,float) or math.isfinite(value)
            if name=='PLAYER_STATE_GROUP_ID' and value:
                if value in {g['id'] for g in table['lists'][3]}:
                    cone_ids.add(value);value+=0x60000000
                else:
                    # The reference also contains dangling group links; use August's
                    # constructor fallback rather than manufacture an absent group.
                    value=0
            if name=='AIM_ASSIST_CONFIG' and value:
                assist_ids.add(value);value+=0x60000000
            words[offsets[name]]=struct.unpack('<I',struct.pack('<f',value))[0] if kind=='f' else value&0xffffffff
        words[0x22]=n[10]&0x60
        lines.append(f'            [{mid}u] = new Dictionary<short, uint> {{ '+', '.join(f'[0x{o:03x}] = 0x{v:08x}u' for o,v in sorted(words.items()))+' },')
    lines+=['        };', '', '    public static IReadOnlyDictionary<uint, uint[]> WeaponModes { get; } =',
            '        new Dictionary<uint, uint[]>', '        {']
    for wid in WEAPONS:
        mids=groups[definitions[wid]['groups'][0]]['modes'][:2]
        lines.append(f'            [{wid}u] = ['+', '.join(f'{i}u' for i in mids)+'],')
    lines+=['        };', '', '    public static IReadOnlyList<ConeOfFireRecord> Cones { get; } =', '    [']
    for g in table['lists'][3]:
        if g['id'] not in cone_ids:continue
        gid=g['id']+0x60000000
        lines.append(f'        new({gid}u, States: [')
        for s in g['states']:
            # 1315 adds a second shot-count word at index 5. August has one.
            words=[gid]+s['words'][:5]+s['words'][6:]
            assert len(words)==17
            lines.append(f'            new({s["id"]}u, ['+', '.join(f'0x{x:08x}u' for x in words)+f'], {s["flags"]}),')
        lines.append('        ]),')
    assert cone_ids.issubset({g['id'] for g in table['lists'][3]})
    lines+=['    ];', '', '    public static IReadOnlyList<AimAssistRecord> AimAssist { get; } =', '    [']
    for a in table['lists'][5]:
        if a['id'] not in assist_ids:continue
        lines.append(f'        new({a["id"]+0x60000000}u, ['+', '.join(f'0x{x:08x}u' for x in a['words'])+']),')
    assert assist_ids.issubset({a['id'] for a in table['lists'][5]})
    lines+=['    ];','}','']
    (ROOT/'src/Cranberry.Zone/Weapons/Z1LiveGunplayFacts.g.cs').write_text('\n'.join(lines),encoding='utf-8')
    print(f'Generated {len(WEAPONS)} firearm identities, {len(selected)} modes, {len(cone_ids)} isolated cone groups and {len(assist_ids)} aim-assist groups.')

if __name__=='__main__':main()
