#!/usr/bin/env python3
"""Index exact-build registrations and server source references, without inferring coverage.

This is a discovery aid, not a packet decoder or an implementation checker. Registration
levels are preserved as integers: they are NOT necessarily consecutive bytes on the wire.
"""
import argparse
import hashlib
import json
import re
from collections import Counter, defaultdict
from pathlib import Path


TARGET_HASH = "d949d39f45074f2b223257477803a8858b4970242c6963df9a213a169d8929dd"


def sha256(path):
    with path.open("rb") as source:
        return hashlib.file_digest(source, "sha256").hexdigest()


def inventory(registrations, server, executable):
    client_hash = sha256(executable)
    if client_hash != TARGET_HASH:
        raise ValueError("Executable is not the pinned August client; keep other-build research separate")

    generated = server / "src/Cranberry.Zone/ZoneOpcodes.g.cs"
    source = generated.read_text(encoding="utf-8-sig")
    expected = re.search(r"// input: out/registrations-1148\.json sha256=([0-9a-f]{64})", source)
    registration_hash = sha256(registrations)
    if expected is None or expected[1] != registration_hash:
        raise ValueError("Registration input does not match ZoneOpcodes.g.cs provenance")

    rows = json.loads(registrations.read_text(encoding="utf-8-sig"))
    if not isinstance(rows, list) or not rows:
        raise ValueError("Expected nonempty registration rows")
    for row in rows:
        levels = row["levels"]
        if not isinstance(levels, list) or not levels or not all(
                type(value) is int and value >= 0 for value in levels):
            raise ValueError("Invalid registration levels")
        for key in ("member", "family", "registeredIn"):
            if not isinstance(row[key], str):
                raise ValueError(f"Invalid registration field: {key}")

    names = {name: int(value, 16) for name, value in re.findall(
        r"public const byte (\w+) = 0x([0-9a-f]+);", source)}
    registered_bases = {row["levels"][0] for row in rows if len(row["levels"]) == 1}
    # Match gen-zone-opcodes.py: only ONE-level registrations establish its base
    # constants. Nested registrations may start with a larger metadata identity.
    if any(base > 255 for base in registered_bases):
        raise ValueError("A one-level registration cannot fit the generated byte base constants")
    if set(names.values()) != registered_bases:
        raise ValueError("Generated base constants differ from the registration inventory")

    # Copy the existing derived framing records with their citations. Re-derivation belongs
    # to gen-zone-opcodes.py; registration names alone cannot establish selector widths.
    framing = {}
    for match in re.finditer(
        r'new\(0x([0-9a-f]+), "([^"]+)", (\d+), (\d+), "([^"]+)", "([^"]+)", "([^"]+)"\)', source):
        base, family, width, prefix, dispatcher, dump, read = match.groups()
        framing[int(base, 16)] = {
            "family": family, "selectorBytes": int(width), "prefixBytes": int(prefix),
            "dispatcher": dispatcher, "export": dump, "readExpression": read,
            "status": "existing derived record; not re-derived by this indexer",
        }
    if len(framing) != 6:
        raise ValueError("Expected six existing framing records; review changed generator format")

    references = defaultdict(list)
    inputs = []
    decode_notes = []
    for path in sorted((server / "src").rglob("*.cs")):
        if path == generated or any(part in ("bin", "obj") for part in path.parts):
            continue
        raw = path.read_bytes()
        source_hash = hashlib.sha256(raw).hexdigest()
        relative_path = path.relative_to(server).as_posix()
        try:
            text = raw.decode("utf-8-sig")
        except UnicodeDecodeError:
            # Preserve ASCII identifiers and line breaks without guessing the encoding
            # of legacy comment bytes. The original source is never rewritten.
            text = raw.decode("utf-8-sig", errors="backslashreplace")
            decode_notes.append({
                "path": relative_path, "sha256": source_hash,
                "decoding": "UTF-8 with invalid bytes escaped; original encoding not inferred",
            })
        found = False
        for number, line in enumerate(text.splitlines(), 1):
            for name in sorted(set(re.findall(r"\bZoneOpcodes\.(\w+)", line))):
                if name not in names:
                    continue
                found = True
                references[names[name]].append({
                    "path": relative_path, "line": number,
                    "symbol": name, "text": line.strip(),
                })
        if found:
            inputs.append({"path": relative_path, "sha256": source_hash})

    grouped = defaultdict(list)
    unmapped = defaultdict(list)
    indexed_bases = registered_bases | set(framing)
    for row in rows:
        first_level = row["levels"][0]
        destination = grouped if first_level in indexed_bases else unmapped
        destination[first_level].append(row)
    bases = []
    for base in sorted(indexed_bases):
        bases.append({
            "baseOpcode": base, "hex": f"0x{base:02x}",
            "baseEvidence": ("one-level registration and generated constant"
                             if base in registered_bases else "existing derived framing record"),
            "serverSymbols": sorted(name for name, opcode in names.items() if opcode == base),
            "registrations": grouped[base], "framing": framing.get(base),
            "lexicalServerReferences": references.get(base, []),
            "direction": "not inferred", "modeApplicability": "not inferred",
            "implementationStatus": "not inferred", "validationStatus": "not inferred",
        })
    unmapped_groups = [{
        "firstLevel": first_level, "firstLevelHex": f"0x{first_level:x}",
        "registrations": unmapped[first_level],
        "wireMapping": "not established by a one-level registration or existing framing record",
        "direction": "not inferred", "modeApplicability": "not inferred",
        "implementationStatus": "not inferred", "validationStatus": "not inferred",
    } for first_level in sorted(unmapped)]
    return {
        "schemaVersion": 1,
        "target": {"date": "2017-08-05", "app": 433850, "depot": 433851,
                   "manifest": "6373368576374184611", "protocol": "ClientProtocol_1148",
                   "build": "0.0.118.208059", "executableSha256": client_hash},
        "inputs": {"registrationsSha256": registration_hash,
                   "zoneOpcodesSha256": sha256(generated), "serverFiles": inputs,
                   "sourceDecodingNotes": decode_notes},
        "counts": {"registrationRows": len(rows), "registeredBaseIdentities": len(registered_bases),
                   "registrationDepths": dict(sorted(Counter(len(row["levels"]) for row in rows).items())),
                   "indexedBaseIdentities": len(bases), "existingFramingRecords": len(framing),
                   "registrationsInBaseIndex": sum(len(group) for group in grouped.values()),
                   "unmappedRegistrationGroups": len(unmapped_groups),
                   "unmappedRegistrationRows": sum(len(group) for group in unmapped.values()),
                   "registrationRowsWithFirstLevelAboveByte": sum(
                       row["levels"][0] > 255 for row in rows),
                   "sourceFilesWithEscapedBytes": len(decode_notes),
                   "basesWithLexicalReferences": len(references),
                   "lexicalReferences": sum(len(hits) for hits in references.values())},
        "limits": [
            "Counts describe discovered metadata, never a percentage of game restoration.",
            "Registration levels and packed IDs are not a wire encoding or a direction.",
            "Base-index rows are grouped by first-level equality, not decoded wire layout.",
            "Unmapped groups retain original metadata; no masking or splitting into opcodes is inferred.",
            "Source hits include comments and do not prove active code or complete behavior.",
            "No hit does not mean missing: literals, other codecs and alternate routing are not indexed.",
            "An unregistered framing record is retained from evidence, not guessed from a numeric gap.",
            "Read compatibility-status.md and feature notes for separately reviewed status and behavior.",
        ],
        "bases": bases,
        "unmappedRegistrationGroups": unmapped_groups,
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--registrations", required=True, type=Path)
    parser.add_argument("--client-exe", required=True, type=Path)
    parser.add_argument("--server-root", type=Path, default=Path(__file__).resolve().parents[2])
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    result = inventory(args.registrations, args.server_root.resolve(), args.client_exe)
    output = args.output.resolve()
    if output in (args.registrations.resolve(), args.client_exe.resolve()):
        parser.error("Output must not overwrite an input")
    if output.suffix.lower() != ".json":
        parser.error("Output must be a separate .json artifact")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(result, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(json.dumps({"output": str(output), "counts": result["counts"]}))


if __name__ == "__main__":
    main()
