// <cranberry-provenance>
// Written by tools/pipeline/pipeline.py (docs/96). `pipeline.py check` recomputes every
// hash below and fails the build when one has moved; do not edit this block by hand.
// id: pickup-effects
// grade: Z1
// clientBuild: 0.0.118.208059
// generator: tools/data/gen-pickup-effects.py sha256=c9e6bb35fde0d345f4c5b4eef8918200884c318dc9e2094a309f92978d6d03ca
// input: C:/Z1/Data/2016/dataSources/ServerItemDefinitions.json sha256=e6af5f8e01d9b7355bd40fa2f697629f02471f768dbe711496db2db436ecfb2d crc32=9b3ec3a3 size=6017524 grade=Z1
// input: out/data_aug/ClientItemDefinitions.txt sha256=638deb01b4eeb565d1c8fc2037e0169518a2c54dd23f19c776f25d3e39dab114 crc32=ffb21654 size=489792 grade=CLIENT
// input: out/data_aug/ActorCompositeEffectDefinitions.xml sha256=3923b8ce2880fe039931663864e0299816dd5470479dd1706c0dfa5e44e8f709 crc32=dc68c048 size=412028 grade=CLIENT
// rulings: D329
// Z1: per-item PICKUP_EFFECT associations are adopted from the owner's local Z1 data
// CLIENT: item identity must match NAME_ID, ITEM_CLASS and CODE_FACTORY_NAME; all selected effects
//     must exist as SFX_Item_PickUp assets in August. IS_ARMOR corrects imported helmet sounds on
//     non-armour hats/clothing to clothing effect 5148. Generic 5151, clothing 5148 and helmet
//     5153 are verified by shipped name
// generatedUtc: 2026-09-06T11:03:54Z
// </cranberry-provenance>
// <auto-generated>
// Generator: tools/data/gen-pickup-effects.py
// Grade: ADOPTED Z1 mapping, validated against August item identities and effect assets.
// Correction: non-armour items (August IS_ARMOR=0) use clothing sound, not helmet sound.
// Source: C:/Z1/Data/2016/dataSources/ServerItemDefinitions.json sha256=e6af5f8e01d9b7355bd40fa2f697629f02471f768dbe711496db2db436ecfb2d
// Source: C:/Aug2017/out/data_aug/ClientItemDefinitions.txt sha256=638deb01b4eeb565d1c8fc2037e0169518a2c54dd23f19c776f25d3e39dab114
// Source: C:/Aug2017/out/data_aug/ActorCompositeEffectDefinitions.xml sha256=3923b8ce2880fe039931663864e0299816dd5470479dd1706c0dfa5e44e8f709
// </auto-generated>

namespace Cranberry.Zone.Loot;

/// <summary>One pickup sound per successful ground grant; unknown items use the August generic sound.</summary>
public static class PickupEffects
{
    public const uint GenericEffectId = 5151;

    public static uint ForItem(uint itemDefinitionId) => itemDefinitionId switch
    {
        // SFX_Item_PickUp_BackPack
        93u or 144u or 1355u or 1432u or 1602u or 1603u or 1605u or 1606u or
        1995u or 2038u or 2051u or 2072u or 2073u or 2074u or 2111u or 2112u or
        2113u or 2114u or 2115u or 2116u or 2117u or 2118u or 2119u or 2120u or
        2121u or 2122u or 2123u or 2124u or 2125u or 2393u or 2777u or 2778u or
        3042u or 3043u or 3044u or 3045u or 3046u or 3047u or 3169u or 3403u or
        3583u or 3643u or 3644u or 3742u or 3798u => 5139u,
        // SFX_Item_PickUp_Ammo
        1428u or 1429u or 1469u or 1511u or 1719u or 1992u or 1998u or 2325u or
        3373u or 3374u => 5140u,
        // SFX_Item_PickUp_Arrow
        112u or 138u or 1434u => 5141u,
        // SFX_Item_PickUp_Bat
        1721u or 1724u or 3061u => 5143u,
        // SFX_Item_PickUp_Blade
        3u or 49u or 58u or 83u or 84u or 110u or 1707u or 1708u or
        1745u or 2225u or 2228u or 2494u or 2495u or 3039u or 3062u or 3707u or
        3858u => 5144u,
        // SFX_Item_PickUp_Blunt_Weapon
        1448u or 1536u or 1538u or 1727u or 1903u => 5145u,
        // SFX_Item_PickUp_Clothing
        12u or 35u or 36u or 37u or 76u or 86u or 92u or 94u or
        95u or 1348u or 1657u or 1679u or 1693u or 1867u or 2027u or 2030u or
        2039u or 2040u or 2041u or 2046u or 2047u or 2048u or 2049u or 2050u or
        2052u or 2053u or 2054u or 2055u or 2056u or 2057u or 2058u or 2059u or
        2060u or 2061u or 2064u or 2065u or 2066u or 2067u or 2068u or 2069u or
        2070u or 2071u or 2075u or 2079u or 2080u or 2081u or 2082u or 2083u or
        2084u or 2085u or 2086u or 2087u or 2088u or 2089u or 2090u or 2091u or
        2092u or 2093u or 2094u or 2095u or 2096u or 2097u or 2098u or 2099u or
        2100u or 2101u or 2102u or 2103u or 2104u or 2105u or 2106u or 2107u or
        2108u or 2109u or 2110u or 2126u or 2127u or 2128u or 2129u or 2130u or
        2131u or 2132u or 2133u or 2134u or 2135u or 2137u or 2138u or 2139u or
        2140u or 2141u or 2142u or 2143u or 2144u or 2145u or 2146u or 2148u or
        2149u or 2150u or 2151u or 2152u or 2153u or 2154u or 2155u or 2156u or
        2157u or 2158u or 2159u or 2160u or 2161u or 2162u or 2163u or 2164u or
        2165u or 2166u or 2167u or 2173u or 2174u or 2175u or 2176u or 2177u or
        2178u or 2180u or 2181u or 2182u or 2183u or 2184u or 2185u or 2186u or
        2187u or 2188u or 2189u or 2190u or 2204u or 2205u or 2206u or 2207u or
        2208u or 2209u or 2211u or 2215u or 2216u or 2217u or 2218u or 2221u or
        2222u or 2226u or 2256u or 2257u or 2258u or 2259u or 2260u or 2261u or
        2262u or 2263u or 2265u or 2267u or 2271u or 2274u or 2278u or 2279u or
        2280u or 2281u or 2282u or 2283u or 2284u or 2285u or 2286u or 2287u or
        2288u or 2289u or 2291u or 2323u or 2324u or 2344u or 2346u or 2347u or
        2352u or 2354u or 2356u or 2365u or 2366u or 2373u or 2374u or 2375u or
        2376u or 2377u or 2378u or 2381u or 2382u or 2383u or 2384u or 2385u or
        2386u or 2398u or 2404u or 2405u or 2408u or 2409u or 2411u or 2414u or
        2415u or 2418u or 2427u or 2428u or 2429u or 2430u or 2431u or 2442u or
        2445u or 2463u or 2464u or 2465u or 2466u or 2467u or 2468u or 2469u or
        2470u or 2471u or 2472u or 2473u or 2474u or 2475u or 2476u or 2477u or
        2482u or 2484u or 2486u or 2487u or 2488u or 2489u or 2531u or 2532u or
        2533u or 2534u or 2535u or 2545u or 2546u or 2547u or 2548u or 2549u or
        2550u or 2551u or 2552u or 2553u or 2555u or 2556u or 2557u or 2558u or
        2559u or 2560u or 2561u or 2562u or 2563u or 2564u or 2565u or 2566u or
        2567u or 2568u or 2569u or 2570u or 2588u or 2589u or 2604u or 2605u or
        2606u or 2607u or 2608u or 2609u or 2613u or 2614u or 2615u or 2616u or
        2617u or 2618u or 2619u or 2620u or 2621u or 2649u or 2650u or 2651u or
        2652u or 2653u or 2654u or 2655u or 2656u or 2657u or 2658u or 2659u or
        2660u or 2667u or 2668u or 2681u or 2682u or 2683u or 2684u or 2685u or
        2686u or 2687u or 2688u or 2689u or 2690u or 2713u or 2714u or 2715u or
        2716u or 2717u or 2718u or 2719u or 2720u or 2721u or 2764u or 2765u or
        2766u or 2769u or 2770u or 2771u or 2775u or 2784u or 2786u or 2790u or
        2793u or 2795u or 2798u or 2799u or 2800u or 2801u or 2802u or 2803u or
        2804u or 2805u or 2806u or 2807u or 2808u or 2809u or 2819u or 2820u or
        2821u or 2822u or 2823u or 2824u or 2825u or 2826u or 2852u or 2853u or
        2860u or 2862u or 2863u or 2864u or 2865u or 2866u or 2869u or 2870u or
        2871u or 2872u or 2877u or 2878u or 2879u or 2880u or 2881u or 2887u or
        2889u or 2895u or 2896u or 2897u or 2898u or 2910u or 2911u or 2912u or
        2913u or 2914u or 2915u or 2923u or 2924u or 2925u or 2926u or 2927u or
        2928u or 2929u or 2930u or 2966u or 2967u or 2968u or 3029u or 3030u or
        3031u or 3032u or 3033u or 3078u or 3079u or 3080u or 3084u or 3085u or
        3086u or 3087u or 3088u or 3125u or 3126u or 3127u or 3128u or 3129u or
        3130u or 3131u or 3132u or 3133u or 3134u or 3135u or 3166u or 3168u or
        3170u or 3171u or 3173u or 3174u or 3175u or 3176u or 3177u or 3178u or
        3180u or 3182u or 3183u or 3184u or 3185u or 3212u or 3216u or 3218u or
        3237u or 3241u or 3245u or 3246u or 3247u or 3248u or 3249u or 3250u or
        3251u or 3252u or 3253u or 3254u or 3255u or 3256u or 3272u or 3358u or
        3360u or 3362u or 3372u or 3378u or 3383u or 3384u or 3385u or 3386u or
        3387u or 3388u or 3389u or 3390u or 3391u or 3404u or 3405u or 3406u or
        3407u or 3408u or 3410u or 3411u or 3412u or 3413u or 3415u or 3416u or
        3417u or 3437u or 3461u or 3462u or 3463u or 3464u or 3465u or 3466u or
        3467u or 3468u or 3483u or 3485u or 3486u or 3491u or 3493u or 3497u or
        3506u or 3507u or 3508u or 3526u or 3527u or 3528u or 3529u or 3530u or
        3531u or 3532u or 3533u or 3534u or 3535u or 3536u or 3537u or 3538u or
        3539u or 3540u or 3541u or 3542u or 3543u or 3544u or 3547u or 3548u or
        3549u or 3552u or 3574u or 3576u or 3577u or 3578u or 3579u or 3587u or
        3598u or 3634u or 3635u or 3636u or 3637u or 3638u or 3639u or 3640u or
        3641u or 3671u or 3708u or 3709u or 3710u or 3711u or 3722u or 3723u or
        3724u or 3725u or 3726u or 3728u or 3729u or 3730u or 3731u or 3733u or
        3734u or 3735u or 3736u or 3737u or 3738u or 3740u or 3741u or 3785u or
        3786u or 3787u or 3788u or 3789u or 3790u or 3859u or 3875u => 5148u,
        // SFX_Item_PickUp_FirstAid
        24u or 78u or 1717u or 1751u or 2202u or 2214u or 2380u or 2421u or
        2423u or 2424u or 2496u or 2514u => 5149u,
        // SFX_Item_PickUp_GasCan
        73u or 1384u => 5150u,
        // SFX_Item_PickUp_Grenade
        65u or 66u or 2235u or 2236u or 2237u or 2243u or 2416u or 3022u or
        3040u => 5152u,
        // SFX_Item_PickUp_Helmet
        2042u or 2043u or 2044u or 2045u or 2062u or 2063u or 2076u or 2077u or
        2078u or 2168u or 2169u or 2170u or 2171u or 2172u or 2227u or 2290u or
        2396u or 2745u or 2748u or 2750u or 2815u or 2817u or 2818u or 2827u or
        2828u or 2829u or 2830u or 2838u or 3064u or 3124u or 3159u or 3167u or
        3181u or 3366u or 3367u or 3409u or 3414u or 3439u or 3440u or 3441u or
        3451u or 3470u or 3474u or 3487u or 3545u or 3546u or 3551u or 3581u or
        3631u or 3721u or 3727u or 3732u or 3739u or 3862u => 5153u,
        // SFX_Item_PickUp_Molotov
        14u => 5154u,
        // SFX_Item_PickUp_Pistol
        2u or 67u or 68u or 100u or 1337u or 1416u or 1702u or 1718u or
        1776u or 1901u or 1991u or 1997u or 2422u or 2751u or 3356u or 3381u or
        3449u or 3481u or 3489u or 3495u or 3550u => 5156u,
        // SFX_Item_PickUp_Rifle
        10u or 1373u or 1374u or 1734u or 1889u or 1899u or 2229u or 2230u or
        2231u or 2232u or 2233u or 2239u or 2379u or 2399u or 2425u or 2446u or
        2480u or 2483u or 2586u or 2592u or 2593u or 2597u or 2600u or 2601u or
        2661u or 2662u or 2663u or 2664u or 2665u or 2666u or 2712u or 2731u or
        2788u or 2789u or 2834u or 2835u or 2859u or 2900u or 2901u or 2902u or
        2906u or 2907u or 2908u or 2909u or 3055u or 3056u or 3057u or 3066u or
        3123u or 3165u or 3172u or 3179u or 3369u or 3382u or 3401u or 3445u or
        3446u or 3448u or 3450u or 3475u or 3477u or 3584u or 3585u or 3586u or
        3718u or 3719u or 3720u or 3797u => 5157u,
        // SFX_Item_PickUp_WaterBottle
        1353u or 1778u => 5158u,
        // SFX_Item_PickUp_Milk_Jug
        6u or 1368u or 1370u or 1371u or 2358u or 2359u => 5159u,
        _ => GenericEffectId,
    };
}
