// <cranberry-provenance>
// Written by tools/pipeline/pipeline.py (docs/96). `pipeline.py check` recomputes every
// hash below and fails the build when one has moved; do not edit this block by hand.
// id: inventory-slots
// grade: CLIENT
// clientBuild: 0.0.118.208059
// generator: tools/data/gen-inventory-slots.py sha256=78bfa946be3c83ab50a73c5d887b8af5b3768ddec3598f3823da2f9f0b86a9ee
// input: out/data_aug/EquipmentSlotDefinitions.txt sha256=251e0546a73b6f6faa3bea3e42e099e6f172fc40f644ce2535f59187da38e6a1 crc32=10876961 size=4851 grade=CLIENT
// input: out/data_aug/EquipSlotItemClasses.txt sha256=d41d00742c27842166383e18adf07f356e474a7dc0d685a43c208842ce2d402e crc32=2a9bacf0 size=269 grade=CLIENT
// input: out/data_aug/Loadouts.txt sha256=ac4f565d733cf904c5e9aba83ba19f73e524311bdf44f788f903f00423088366 crc32=d1f12f10 size=85 grade=CLIENT
// input: out/data_aug/LoadoutSlots.txt sha256=a34439d648a525bb3b630d7cceaa180cf9ac83c1fe2cdad4e2126d9adc981e5a crc32=c747dd49 size=9369 grade=CLIENT
// input: out/data_aug/LoadoutSlotItemClasses.txt sha256=a98d75e85f77f65f7ca7420369f68a6430e13c43d4aa2953aaaeef3b46fa3ed0 crc32=e2665d9a size=3622 grade=CLIENT
// input: out/data_aug/ContainerDefinitions.txt sha256=4359cfd081c4641e567629e362932bd682fd5d4921b353b4deec18e7001980c4 crc32=3786510b size=3686 grade=CLIENT
// input: out/data_aug/ClientItemDefinitions.txt sha256=638deb01b4eeb565d1c8fc2037e0169518a2c54dd23f19c776f25d3e39dab114 crc32=ffb21654 size=489792 grade=CLIENT
// rulings: D33, D72, D141
// generatedUtc: 2026-09-08T18:58:04Z
// </cranberry-provenance>
// <auto-generated>
// Generated by tools/data/gen-inventory-slots.py from the August client's own datasheets
// (Assets_*.pack, extracted to C:\Aug2017\out\data_aug). Do not edit by hand; re-run the
// generator instead. Derivation and citations: docs/41-inventory-slots.md.
// </auto-generated>

#nullable enable

using System.Collections.Frozen;

namespace Cranberry.Zone.Inventory;


/// <summary>
/// One row of the client's <c>EquipmentSlotDefinitions.txt</c>. <see cref="Id"/> is the value that
/// travels on the wire as <c>CharacterEquipmentAttachment.SlotId</c> and as
/// <c>EquipmentSlotRow.SlotId</c> (docs/36 §W3, docs/41 §1).
/// </summary>
/// <param name="Id">The sheet's <c>ID</c> - the wire slot id.</param>
/// <param name="IsRequired">
/// <c>IS_REQUIRED</c>. Slot 1 (Head) is the <em>only</em> required slot with an empty
/// <see cref="DefaultAdr"/>, which is why clearing it produced client error G10 while clearing
/// 3/4/105 merely fell back to their default meshes (docs/41 §1d, docs/32).
/// </param>
/// <param name="IsEquipment">
/// <c>IS_EQUIPMENT</c>. A 0 here is not an attachment target - slot 85
/// (<c>spineUpper_BackStab</c>) is listed by <c>EquipSlotItemClasses.txt</c> but is not an
/// equipment slot, so it must not be chosen as a weapon stow slot.
/// </param>
/// <param name="GroupId">
/// <c>GROUP_ID</c>. 1 marks a <em>vehicle</em> hardpoint (slots 30-33, 41-73), not a weapon-stow
/// group; the stow group comes from <see cref="EquipmentSlotTable.StowSlotsForItemClass"/>
/// (docs/41 §1b).
/// </param>
public readonly record struct EquipmentSlotDefinition(
    uint Id,
    bool IsRequired,
    bool IsEquipment,
    bool StartHidden,
    uint GroupId,
    string SlotName,
    string DefaultAdr,
    string BoneAttachNameOverride,
    string AnimName);

/// <summary>The 86 rows of <c>EquipmentSlotDefinitions.txt</c>, plus the stow-group index.</summary>
public static class EquipmentSlotTable
{
    /// <summary>Every row, in sheet order.</summary>
    public static IReadOnlyList<EquipmentSlotDefinition> All => Rows;

    private static readonly EquipmentSlotDefinition[] Rows =
    [
        new(1u, true, true, false, 0u, "Head", "", "", ""),
        new(2u, false, true, false, 0u, "Hands", "", "", ""),
        new(3u, true, true, false, 0u, "Chest", "Survivor<gender>_Chest_Bra.adr", "", ""),
        new(4u, true, true, false, 0u, "Legs", "Survivor<gender>_Legs_Pants_Underwear.adr", "", ""),
        new(5u, false, true, false, 0u, "Feet", "", "", ""),
        new(6u, false, true, false, 0u, "Shoulders", "Head", "", ""),
        new(7u, false, true, false, 0u, "RHand", "", "", "WeaponSwitch"),
        new(8u, false, true, false, 0u, "LHand", "", "", "WeaponSwitch"),
        new(9u, false, true, true, 0u, "Wrist", "", "", ""),
        new(10u, false, true, false, 0u, "Backpack", "", "", ""),
        new(11u, false, true, false, 0u, "Belt", "", "", ""),
        new(12u, false, true, true, 0u, "Knife", "", "L_weapon", ""),
        new(13u, false, true, true, 0u, "QuickUse", "", "R_weapon", ""),
        new(14u, false, true, false, 0u, "Empty Hands", "", "", ""),
        new(15u, false, false, false, 0u, "CustomizationHead", "", "", ""),
        new(16u, false, true, false, 0u, "RedDot", "", "RedDot", ""),
        new(17u, false, true, false, 0u, "ForwardGrip", "0", "ForwardGrip", ""),
        new(18u, false, true, false, 0u, "Item1", "", "", ""),
        new(19u, false, true, false, 0u, "Item2", "", "", ""),
        new(26u, false, true, true, 0u, "Restraint", "", "", ""),
        new(27u, false, false, false, 0u, "Hair", "", "", ""),
        new(28u, false, true, false, 0u, "Face", "", "", ""),
        new(29u, false, true, false, 0u, "Eyes", "", "", ""),
        new(30u, false, true, false, 1u, "hardpoint1", "", "hardpoint1", ""),
        new(31u, false, true, false, 1u, "hardpoint2", "", "hardpoint2", ""),
        new(32u, false, true, false, 1u, "hardpoint3", "", "hardpoint3", ""),
        new(33u, false, true, false, 1u, "hardpoint4", "", "hardpoint4", ""),
        new(34u, false, true, false, 0u, "Clip", "", "", ""),
        new(35u, false, true, false, 0u, "Scope", "", "Scope", ""),
        new(36u, false, true, false, 0u, "IronSightFront", "", "IronSightFront", ""),
        new(37u, false, true, false, 0u, "IronSightBack", "", "IronSightBack", ""),
        new(38u, false, true, false, 0u, "BottomRail", "0", "BottomRail", ""),
        new(39u, false, true, false, 0u, "SideRail", "", "SideRail", ""),
        new(40u, false, true, false, 0u, "Barrel", "", "", ""),
        new(41u, false, true, false, 1u, "Afterburner", "", "", ""),
        new(42u, false, true, false, 1u, "Armor", "", "", ""),
        new(43u, false, true, false, 1u, "HoodOrnament", "", "", ""),
        new(44u, false, true, false, 1u, "Radar", "", "", ""),
        new(45u, false, true, false, 1u, "Headlights", "", "", ""),
        new(46u, false, true, false, 1u, "Hoverpad", "", "", ""),
        new(47u, false, true, false, 1u, "VehicleCosmetic", "", "", ""),
        new(48u, false, true, false, 1u, "Stabilizer", "", "", ""),
        new(49u, false, true, false, 1u, "Terminal", "", "", ""),
        new(50u, false, true, false, 1u, "Launcher", "", "", ""),
        new(51u, false, true, false, 1u, "Coaxial", "", "Coaxial", ""),
        new(52u, false, true, false, 1u, "Defensive", "", "", ""),
        new(53u, false, true, false, 1u, "Terminal2", "", "Terminal2", ""),
        new(55u, false, true, false, 1u, "AircraftWingWeapons", "", "COG", ""),
        new(56u, false, true, false, 1u, "Cert", "", "", ""),
        new(57u, false, true, false, 1u, "hardpoint5", "", "hardpoint5", ""),
        new(58u, false, true, false, 1u, "hardpoint6", "", "hardpoint6", ""),
        new(59u, false, true, false, 1u, "hardpoint7", "", "hardpoint7", ""),
        new(60u, false, true, false, 1u, "hardpoint8", "", "hardpoint8", ""),
        new(61u, false, true, true, 0u, "UnderSlung", "0", "UnderSlung", ""),
        new(62u, false, true, false, 0u, "LBottomRail", "0", "", ""),
        new(63u, false, true, false, 1u, "VehLightTrim", "", "", ""),
        new(64u, false, true, false, 1u, "VehAntenna", "", "", ""),
        new(65u, false, true, false, 1u, "VehTires", "", "", ""),
        new(66u, false, true, false, 1u, "GalaxyIntake", "", "", ""),
        new(67u, false, true, false, 1u, "VehExterior", "", "", ""),
        new(68u, false, true, false, 1u, "Motor", "", "", ""),
        new(69u, false, true, false, 1u, "Fuel", "", "", ""),
        new(70u, false, true, false, 1u, "Battery", "", "", ""),
        new(71u, false, true, false, 1u, "Sparkplugs", "", "", ""),
        new(72u, false, true, false, 1u, "LightBar", "", "", ""),
        new(73u, false, true, false, 1u, "Horn", "", "", ""),
        new(76u, false, true, false, 0u, "R_LongWeapon_1", "", "spineUpper_Rear_Right_Diag_Fan_1_Attach", ""),
        new(77u, false, true, false, 0u, "R_LongWeapon_2", "", "spineUpper_Rear_Right_Diag_Fan_2_Attach", ""),
        new(78u, false, true, false, 0u, "R_ShortWeapon_1", "", "pelvis_Right_Side_1_Attach", ""),
        new(79u, false, true, false, 0u, "R_ShortWeapon_2", "", "pelvis_Left_Side_1_Attach", ""),
        new(80u, false, true, false, 0u, "R_LongWeapon_3", "", "spineUpper_Rear_Right_Diag_Fan_3_Attach", ""),
        new(81u, false, true, false, 0u, "R_ShortWeapon_3", "", "R_hip_1_Attach", ""),
        new(82u, false, true, false, 0u, "R_bowWeapon_1", "", "spineUpper_Rear_1_Bow_Attach", ""),
        new(83u, false, true, false, 0u, "R_bowWeapon_2", "", "spineUpper_Rear_2_Bow_Attach", ""),
        new(84u, false, true, false, 0u, "R_bowWeapon_3", "", "spineUpper_Rear_3_Bow_Attach", ""),
        new(85u, false, false, false, 0u, "spineUpper_BackStab", "", "spineUpper_Rear_Center_1_Attach", ""),
        new(100u, false, true, false, 0u, "ChestArmor", "", "", ""),
        new(101u, false, true, false, 0u, "Jacket", "", "", ""),
        new(103u, false, true, false, 0u, "spineUpper_Rear_Center_1_Attach", "", "spineUpper_Rear_Center_1_Attach", ""),
        new(104u, false, true, false, 0u, "Radio", "", "", ""),
        new(105u, true, true, false, 0u, "", "Survivor<gender>_Eyes_01.adr", "", ""),
        new(106u, false, true, false, 0u, "R_MeleeWeapon_Rear_Melee_Diag", "", "spineUpper_Rear_Right_Diag_1_Melee_Attach", ""),
        new(107u, false, true, false, 0u, "L_MeleeWeapon_Rear_Melee_Diag", "", "spineUpper_Rear_Left_Diag_1_Melee_Attach", ""),
        new(108u, false, true, false, 0u, "C_MeleeWeapon_Rear", "", "spineUpper_Rear_Center_1_Melee_Attach", ""),
        new(109u, false, true, false, 0u, "R_MeleeWeapon_Waist", "", "pelvis_Right_Side_1_Melee_Attach", ""),
        new(110u, false, true, false, 0u, "L_MeleeWeapon_Waist", "", "pelvis_Left_Side_1_Melee_Attach", ""),
    ];

    private static readonly FrozenDictionary<uint, EquipmentSlotDefinition> ById =
        Rows.ToFrozenDictionary(row => row.Id);

    /// <summary>Look one slot up by its wire id.</summary>
    public static bool TryGet(uint id, out EquipmentSlotDefinition definition) =>
        ById.TryGetValue(id, out definition);

    /// <summary>True when <paramref name="id"/> is a row of the sheet.</summary>
    public static bool Exists(uint id) => ById.ContainsKey(id);

    /// <summary>
    /// The equip slots that accept <paramref name="itemClass"/>, from
    /// <c>EquipSlotItemClasses.txt</c> in sheet order. This is the candidate set a long gun picks
    /// its stow slot from when <c>PASSIVE_EQUIP_SLOT_GROUP_ID = 1</c> (docs/41 §1b); rows whose
    /// slot is not <c>IS_EQUIPMENT</c> (slot 85) are excluded, because the client will not attach
    /// a mesh there.
    /// </summary>
    public static IReadOnlyList<uint> StowSlotsForItemClass(uint itemClass) =>
        StowGroups.TryGetValue(itemClass, out uint[]? slots) ? slots : [];

    private static readonly FrozenDictionary<uint, uint[]> StowGroups =
        new Dictionary<uint, uint[]>
        {
            [4096u] = [78u, 79u, 81u],
            [4098u] = [78u, 79u, 81u],   // sheet also lists [85], excluded: IS_EQUIPMENT = 0
            [25036u] = [76u, 77u, 80u],
            [25037u] = [76u, 77u, 80u],   // sheet also lists [85], excluded: IS_EQUIPMENT = 0
            [25038u] = [82u, 83u, 84u],
            [25047u] = [103u],
        }.ToFrozenDictionary();
}


/// <summary>
/// One row of <c>LoadoutSlots.txt</c> - a slot of the client's inventory panel. This is a different
/// id space from <see cref="EquipmentSlotDefinition"/>: the loadout slot is what the UI shows and
/// what <c>Loadouts.SetLoadoutSlot</c> (0x86/05) binds an item guid to, while
/// <see cref="EquipSlotId"/> is the body slot the mesh attaches to (docs/41 §2a).
/// </summary>
/// <param name="EquipSlotId">
/// <c>EQUIP_SLOT_ID</c>, a row of <see cref="EquipmentSlotTable"/>. Zero on the wheel slots,
/// because a slung weapon's body slot depends on the weapon rather than on the loadout slot.
/// </param>
/// <param name="ItemId">
/// <c>ITEM_ID</c> - the slot's default item. Loadout 3 slot 7 names item 85 ("Fists"), which the
/// client's own config corroborates as <c>Inventory.SpecialEmptyHandsItemId = 85</c>
/// (<c>StringHashValues.g.cs</c>).
/// </param>
/// <param name="AutoEquip">
/// <c>FLAG_AUTO_EQUIP</c> - the slot the server is expected to fill without being asked. Every
/// apparel slot, plus 7 (Fists) and 43 (the Inventory bag).
/// </param>
/// <param name="Wheelable">
/// <c>FLAG_IS_WHEELABLE</c> - one of the six hotbar slots (1, 3, 4, 7, 40, 41). This build's hotbar
/// is these slots and not an item flag: <c>FLAG_QUICK_USE</c> is 0 on all 2,643 item rows.
/// </param>
public readonly record struct LoadoutSlotDefinition(
    uint LoadoutId,
    uint SlotId,
    uint EquipSlotId,
    uint ItemId,
    bool AutoEquip,
    bool Required,
    bool Visible,
    bool Wheelable,
    bool CanRightHandEquip,
    uint DisplayIndex,
    string SlotUiTag,
    string SlotInputAction);

/// <summary>
/// <c>Loadouts.txt</c>, <c>LoadoutSlots.txt</c> and <c>LoadoutSlotItemClasses.txt</c>. The last of
/// those is the client's own auto-assign rule (docs/41 §2b): a slot supports an item <b>iff</b> the
/// item's <c>ITEM_CLASS</c> is listed for <c>(LOADOUT_ID, SLOT)</c>.
/// </summary>
public static class LoadoutSlotTable
{
    /// <summary>The survivor loadout - the one a KOTK player wears (docs/41 §2a).</summary>
    public const uint SurvivorLoadoutId = 3;

    /// <summary>Every loadout id present in <c>Loadouts.txt</c>.</summary>
    public static IReadOnlyList<uint> LoadoutIds => LoadoutIdRows;

    private static readonly uint[] LoadoutIdRows =
    [
        3u, 4u, 5u, 6u, 7u, 8u, 9u, 10u, 11u, 12u, 14u, 15u, 17u, 18u, 19u, 20u, 21u,
    ];

    /// <summary>Every row of <c>LoadoutSlots.txt</c>, in sheet order.</summary>
    public static IReadOnlyList<LoadoutSlotDefinition> All => Rows;

    private static readonly LoadoutSlotDefinition[] Rows =
    [
        new(3u, 1u, 0u, 0u, false, false, true, true, true, 0u, "", "Slot2"),
        new(3u, 3u, 0u, 0u, false, false, true, true, true, 1u, "", "Slot3"),
        new(3u, 4u, 7u, 0u, false, false, true, true, true, 2u, "", "Slot4"),
        new(3u, 7u, 7u, 85u, true, true, false, true, true, 0u, "", "Slot1"),
        new(3u, 10u, 3u, 0u, true, false, true, false, false, 13u, "", ""),
        new(3u, 11u, 1u, 0u, true, false, true, false, false, 8u, "", ""),
        new(3u, 12u, 10u, 0u, true, false, true, false, false, 10u, "", ""),
        new(3u, 13u, 5u, 0u, true, false, true, false, false, 15u, "", ""),
        new(3u, 14u, 4u, 0u, true, false, true, false, false, 14u, "", ""),
        new(3u, 15u, 0u, 0u, false, false, false, false, false, 0u, "", ""),
        new(3u, 16u, 2u, 0u, true, false, true, false, false, 5u, "", ""),
        new(3u, 25u, 11u, 0u, true, false, true, false, false, 6u, "", ""),
        new(3u, 26u, 26u, 0u, false, false, false, false, false, 0u, "", ""),
        new(3u, 27u, 27u, 0u, true, false, false, false, false, 0u, "", ""),
        new(3u, 28u, 28u, 0u, true, false, true, false, false, 11u, "", ""),
        new(3u, 29u, 29u, 0u, true, false, true, false, false, 12u, "", ""),
        new(3u, 30u, 101u, 0u, true, false, false, false, false, 0u, "", ""),
        new(3u, 38u, 100u, 0u, true, false, true, false, false, 9u, "", ""),
        new(3u, 39u, 104u, 0u, false, false, false, false, false, 0u, "", ""),
        new(3u, 40u, 0u, 0u, false, false, true, true, false, 3u, "", "slot5"),
        new(3u, 41u, 0u, 0u, false, false, true, true, false, 4u, "", "slot6"),
        new(3u, 43u, 0u, 0u, true, false, false, false, false, 0u, "", ""),
        new(3u, 45u, 0u, 0u, true, false, false, false, false, 0u, "", ""),
        new(3u, 47u, 0u, 0u, true, false, false, false, false, 0u, "", ""),
        new(4u, 17u, 41u, 0u, false, false, true, false, false, 3u, "", ""),
        new(4u, 18u, 45u, 0u, false, false, true, false, false, 0u, "", ""),
        new(4u, 19u, 68u, 1344u, false, true, false, false, false, 0u, "", ""),
        new(4u, 32u, 0u, 1541u, false, true, false, false, false, 0u, "", ""),
        new(4u, 33u, 70u, 0u, false, false, true, false, false, 2u, "", ""),
        new(4u, 34u, 71u, 0u, false, false, true, false, false, 1u, "", ""),
        new(4u, 36u, 73u, 0u, false, false, false, false, false, 0u, "", ""),
        new(4u, 42u, 43u, 0u, true, false, false, false, false, 0u, "", ""),
        new(4u, 44u, 0u, 0u, false, false, false, false, false, 0u, "", ""),
        new(5u, 31u, 0u, 0u, false, false, false, false, false, 0u, "", ""),
        new(6u, 17u, 41u, 0u, false, false, true, false, false, 3u, "", ""),
        new(6u, 18u, 45u, 0u, false, false, true, false, false, 0u, "", ""),
        new(6u, 19u, 68u, 1712u, false, true, false, false, false, 0u, "", ""),
        new(6u, 32u, 0u, 1783u, false, true, false, false, false, 0u, "", ""),
        new(6u, 33u, 70u, 0u, false, false, true, false, false, 2u, "", ""),
        new(6u, 34u, 71u, 0u, false, false, true, false, false, 1u, "", ""),
        new(6u, 36u, 73u, 0u, false, false, false, false, false, 0u, "", ""),
        new(6u, 42u, 43u, 0u, true, false, false, false, false, 0u, "", ""),
        new(6u, 44u, 0u, 0u, false, false, false, false, false, 0u, "", ""),
        new(7u, 11u, 1u, 0u, true, false, false, false, false, 0u, "", ""),
        new(7u, 31u, 0u, 0u, true, false, false, false, false, 0u, "", ""),
        new(8u, 17u, 41u, 0u, false, false, true, false, false, 3u, "", ""),
        new(8u, 18u, 45u, 0u, false, false, true, false, false, 0u, "", ""),
        new(8u, 19u, 68u, 1722u, false, true, false, false, false, 0u, "", ""),
        new(8u, 32u, 0u, 1723u, false, true, false, false, false, 0u, "", ""),
        new(8u, 33u, 70u, 0u, false, false, true, false, false, 2u, "", ""),
        new(8u, 34u, 71u, 0u, false, false, true, false, false, 1u, "", ""),
        new(8u, 35u, 0u, 1732u, false, true, false, false, false, 0u, "", ""),
        new(8u, 36u, 73u, 0u, false, false, false, false, false, 0u, "", ""),
        new(8u, 44u, 0u, 0u, false, false, false, false, false, 0u, "", ""),
        new(9u, 31u, 0u, 0u, false, false, false, false, false, 0u, "", ""),
        new(10u, 36u, 73u, 0u, false, false, true, false, false, 0u, "", ""),
        new(11u, 36u, 73u, 0u, false, false, true, false, false, 0u, "", ""),
        new(12u, 3u, 0u, 0u, true, false, true, false, false, 0u, "", ""),
        new(12u, 4u, 7u, 0u, true, false, true, false, false, 0u, "", ""),
        new(12u, 11u, 1u, 0u, true, false, true, false, false, 0u, "", ""),
        new(12u, 12u, 10u, 0u, true, false, true, false, false, 0u, "", ""),
        new(12u, 26u, 26u, 0u, true, false, true, false, false, 0u, "", ""),
        new(12u, 27u, 27u, 0u, true, false, true, false, false, 0u, "", ""),
        new(12u, 28u, 28u, 0u, true, false, true, false, false, 0u, "", ""),
        new(12u, 29u, 29u, 0u, true, false, true, false, false, 0u, "", ""),
        new(12u, 31u, 0u, 0u, true, false, false, false, false, 0u, "", ""),
        new(12u, 38u, 100u, 0u, true, false, true, false, false, 0u, "", ""),
        new(14u, 17u, 41u, 0u, false, false, true, false, false, 3u, "", ""),
        new(14u, 18u, 45u, 0u, false, false, true, false, false, 0u, "", ""),
        new(14u, 19u, 68u, 2594u, false, true, false, false, false, 0u, "", ""),
        new(14u, 32u, 0u, 2728u, false, true, false, false, false, 0u, "", ""),
        new(14u, 33u, 70u, 0u, false, false, true, false, false, 2u, "", ""),
        new(14u, 34u, 71u, 0u, false, false, true, false, false, 1u, "", ""),
        new(14u, 36u, 73u, 0u, false, false, false, false, false, 0u, "", ""),
        new(14u, 44u, 0u, 0u, false, false, false, false, false, 0u, "", ""),
        new(15u, 3u, 0u, 0u, false, false, true, false, false, 0u, "", ""),
        new(15u, 4u, 7u, 0u, false, false, true, false, false, 0u, "", ""),
        new(15u, 10u, 3u, 0u, true, false, true, false, false, 0u, "", ""),
        new(15u, 11u, 1u, 0u, true, false, true, false, false, 0u, "", ""),
        new(15u, 12u, 10u, 0u, true, false, true, false, false, 0u, "", ""),
        new(15u, 13u, 5u, 0u, true, false, true, false, false, 0u, "", ""),
        new(15u, 14u, 4u, 0u, true, false, true, false, false, 0u, "", ""),
        new(15u, 16u, 2u, 0u, true, false, true, false, false, 0u, "", ""),
        new(15u, 27u, 27u, 0u, true, false, true, false, false, 0u, "", ""),
        new(15u, 28u, 28u, 0u, true, false, true, false, false, 0u, "", ""),
        new(15u, 29u, 29u, 0u, true, false, true, false, false, 0u, "", ""),
        new(15u, 30u, 101u, 0u, true, false, true, false, false, 0u, "", ""),
        new(15u, 31u, 0u, 0u, true, false, false, false, false, 0u, "", ""),
        new(15u, 38u, 100u, 0u, true, false, true, false, false, 0u, "", ""),
        new(17u, 1u, 0u, 0u, false, false, true, true, true, 3u, "", "Slot1"),
        new(17u, 2u, 0u, 0u, false, false, true, true, true, 9u, "", "Slot2"),
        new(17u, 4u, 7u, 0u, false, false, true, true, true, 15u, "", "Slot3"),
        new(17u, 5u, 7u, 0u, true, false, true, true, true, 11u, "", "Slot5"),
        new(17u, 7u, 7u, 85u, true, true, true, true, true, 10u, "", "Slot4"),
        new(17u, 10u, 3u, 0u, true, false, true, false, false, 7u, "", ""),
        new(17u, 11u, 1u, 0u, true, false, true, false, false, 2u, "", ""),
        new(17u, 12u, 10u, 0u, true, false, true, false, false, 16u, "", ""),
        new(17u, 13u, 5u, 0u, true, false, true, false, false, 14u, "", ""),
        new(17u, 14u, 4u, 0u, true, false, true, false, false, 13u, "", ""),
        new(17u, 16u, 2u, 0u, true, false, true, false, false, 6u, "", ""),
        new(17u, 25u, 11u, 0u, true, false, true, false, false, 17u, "", ""),
        new(17u, 27u, 27u, 0u, true, false, false, false, false, 0u, "", ""),
        new(17u, 28u, 28u, 0u, true, false, true, false, false, 0u, "", ""),
        new(17u, 29u, 29u, 0u, true, false, true, false, false, 1u, "", ""),
        new(17u, 38u, 100u, 0u, true, false, true, false, false, 8u, "", ""),
        new(17u, 40u, 0u, 0u, false, false, true, false, false, 4u, "", "ConsumeItem1"),
        new(17u, 41u, 0u, 0u, false, false, true, false, false, 5u, "", "ConsumeItem2"),
        new(17u, 43u, 0u, 0u, true, false, false, false, false, 0u, "", ""),
        new(17u, 45u, 0u, 0u, true, false, false, false, false, 0u, "", ""),
        new(17u, 47u, 0u, 0u, true, false, false, false, false, 0u, "", ""),
        new(17u, 48u, 0u, 0u, true, false, true, false, false, 12u, "", ""),
        new(18u, 17u, 41u, 0u, false, false, true, false, false, 3u, "", ""),
        new(18u, 18u, 45u, 0u, false, false, false, false, false, 0u, "", ""),
        new(18u, 19u, 68u, 2594u, false, true, false, false, false, 0u, "", ""),
        new(18u, 32u, 0u, 2728u, false, true, false, false, false, 0u, "", ""),
        new(18u, 33u, 70u, 0u, false, false, true, false, false, 2u, "", ""),
        new(18u, 34u, 71u, 0u, false, false, true, false, false, 1u, "", ""),
        new(18u, 36u, 73u, 0u, false, false, false, false, false, 0u, "", ""),
        new(18u, 44u, 0u, 0u, false, false, false, false, false, 0u, "", ""),
        new(19u, 17u, 41u, 0u, false, false, true, false, false, 3u, "", ""),
        new(19u, 18u, 45u, 0u, false, false, false, false, false, 0u, "", ""),
        new(19u, 19u, 68u, 1344u, false, true, false, false, false, 0u, "", ""),
        new(19u, 32u, 0u, 1541u, false, true, false, false, false, 0u, "", ""),
        new(19u, 33u, 70u, 0u, false, false, true, false, false, 2u, "", ""),
        new(19u, 34u, 71u, 0u, false, false, true, false, false, 1u, "", ""),
        new(19u, 36u, 73u, 0u, false, false, false, false, false, 0u, "", ""),
        new(19u, 42u, 43u, 0u, true, false, false, false, false, 0u, "", ""),
        new(19u, 44u, 0u, 0u, false, false, false, false, false, 0u, "", ""),
        new(20u, 17u, 41u, 0u, false, false, true, false, false, 3u, "", ""),
        new(20u, 18u, 45u, 0u, false, false, false, false, false, 0u, "", ""),
        new(20u, 19u, 68u, 1712u, false, true, false, false, false, 0u, "", ""),
        new(20u, 32u, 0u, 1783u, false, true, false, false, false, 0u, "", ""),
        new(20u, 33u, 70u, 0u, false, false, true, false, false, 2u, "", ""),
        new(20u, 34u, 71u, 0u, false, false, true, false, false, 1u, "", ""),
        new(20u, 36u, 73u, 0u, false, false, false, false, false, 0u, "", ""),
        new(20u, 42u, 43u, 0u, true, false, false, false, false, 0u, "", ""),
        new(20u, 44u, 0u, 0u, false, false, false, false, false, 0u, "", ""),
        new(21u, 17u, 41u, 0u, false, false, true, false, false, 3u, "", ""),
        new(21u, 18u, 45u, 0u, false, false, false, false, false, 0u, "", ""),
        new(21u, 19u, 68u, 1722u, false, true, false, false, false, 0u, "", ""),
        new(21u, 32u, 0u, 1723u, false, true, false, false, false, 0u, "", ""),
        new(21u, 33u, 70u, 0u, false, false, true, false, false, 2u, "", ""),
        new(21u, 34u, 71u, 0u, false, false, true, false, false, 1u, "", ""),
        new(21u, 35u, 0u, 1732u, false, true, false, false, false, 0u, "", ""),
        new(21u, 36u, 73u, 0u, false, false, false, false, false, 0u, "", ""),
        new(21u, 44u, 0u, 0u, false, false, false, false, false, 0u, "", ""),
    ];

    private static readonly FrozenDictionary<(uint Loadout, uint Slot), LoadoutSlotDefinition> BySlot =
        Rows.ToFrozenDictionary(row => (row.LoadoutId, row.SlotId));

    private static readonly FrozenDictionary<uint, LoadoutSlotDefinition[]> ByLoadout =
        Rows.GroupBy(row => row.LoadoutId)
            .ToFrozenDictionary(group => group.Key, group => group.ToArray());

    /// <summary>Look one loadout slot up.</summary>
    public static bool TryGet(uint loadoutId, uint slotId, out LoadoutSlotDefinition definition) =>
        BySlot.TryGetValue((loadoutId, slotId), out definition);

    /// <summary>Every slot of one loadout, in sheet order (which is ascending slot id).</summary>
    public static IReadOnlyList<LoadoutSlotDefinition> Slots(uint loadoutId) =>
        ByLoadout.TryGetValue(loadoutId, out LoadoutSlotDefinition[]? rows) ? rows : [];

    /// <summary>
    /// The item classes <c>(loadoutId, slotId)</c> accepts, ascending. Empty means the slot accepts
    /// nothing, which is how class 16053 (ammunition, bandages, first aid kits) ends up with no
    /// loadout slot at all under loadout 3 - those items are container-only (docs/41 §5c).
    /// </summary>
    public static IReadOnlyList<uint> ItemClasses(uint loadoutId, uint slotId) =>
        SlotClasses.TryGetValue((loadoutId, slotId), out uint[]? classes) ? classes : [];

    private static readonly FrozenDictionary<(uint Loadout, uint Slot), uint[]> SlotClasses =
        new Dictionary<(uint, uint), uint[]>
        {
            [(3u, 1u)] = [383u, 4096u, 4098u, 25031u, 25036u, 25037u, 25038u, 25047u, 25078u],
            [(3u, 3u)] = [383u, 4096u, 4098u, 25031u, 25036u, 25037u, 25038u, 25047u],
            [(3u, 4u)] = [383u, 4096u, 4098u, 25031u, 25036u, 25037u, 25038u, 25047u, 25078u],
            [(3u, 7u)] = [25006u, 25044u],
            [(3u, 10u)] = [25002u],
            [(3u, 11u)] = [25000u],
            [(3u, 12u)] = [25004u],
            [(3u, 13u)] = [25005u],
            [(3u, 14u)] = [25003u],
            [(3u, 15u)] = [4096u, 4098u, 25036u, 25037u],
            [(3u, 16u)] = [25008u],
            [(3u, 25u)] = [25013u],
            [(3u, 26u)] = [25031u],
            [(3u, 27u)] = [25039u],
            [(3u, 28u)] = [25040u],
            [(3u, 29u)] = [25045u],
            [(3u, 30u)] = [25046u],
            [(3u, 38u)] = [25041u],
            [(3u, 39u)] = [25053u],
            [(3u, 40u)] = [25054u],
            [(3u, 41u)] = [25054u],
            [(3u, 43u)] = [25068u],
            [(3u, 45u)] = [25077u],
            [(3u, 47u)] = [25079u],
            [(4u, 17u)] = [20012u, 25069u],
            [(4u, 18u)] = [20011u, 25072u],
            [(4u, 19u)] = [25007u],
            [(4u, 32u)] = [25019u],
            [(4u, 33u)] = [25020u],
            [(4u, 34u)] = [25021u],
            [(4u, 36u)] = [25035u],
            [(4u, 42u)] = [25062u],
            [(4u, 44u)] = [25075u],
            [(5u, 31u)] = [25016u],
            [(6u, 17u)] = [25026u, 25069u],
            [(6u, 18u)] = [25025u, 25072u],
            [(6u, 19u)] = [25022u],
            [(6u, 32u)] = [25032u],
            [(6u, 33u)] = [25020u],
            [(6u, 34u)] = [25021u],
            [(6u, 36u)] = [25035u],
            [(6u, 42u)] = [25062u],
            [(6u, 44u)] = [25075u],
            [(7u, 11u)] = [25000u],
            [(7u, 31u)] = [25016u],
            [(8u, 17u)] = [25028u, 25069u],
            [(8u, 18u)] = [25027u, 25072u],
            [(8u, 19u)] = [25023u],
            [(8u, 32u)] = [25024u],
            [(8u, 33u)] = [25020u],
            [(8u, 34u)] = [25021u],
            [(8u, 35u)] = [25029u],
            [(8u, 36u)] = [25035u],
            [(8u, 44u)] = [25075u],
            [(9u, 31u)] = [25016u],
            [(10u, 36u)] = [25035u],
            [(11u, 36u)] = [25035u],
            [(12u, 3u)] = [4096u, 4098u, 25036u, 25037u, 25038u, 25047u],
            [(12u, 4u)] = [4096u, 4098u, 25036u, 25037u, 25038u, 25047u],
            [(12u, 11u)] = [25000u],
            [(12u, 12u)] = [25004u],
            [(12u, 26u)] = [25031u],
            [(12u, 27u)] = [25039u],
            [(12u, 28u)] = [25040u, 25042u, 25043u],
            [(12u, 29u)] = [25045u],
            [(12u, 31u)] = [25016u],
            [(12u, 38u)] = [25041u],
            [(14u, 17u)] = [25060u, 25069u],
            [(14u, 18u)] = [25058u, 25072u],
            [(14u, 19u)] = [25057u],
            [(14u, 32u)] = [25061u],
            [(14u, 33u)] = [25020u],
            [(14u, 34u)] = [25021u],
            [(14u, 36u)] = [25035u],
            [(14u, 44u)] = [25075u],
            [(15u, 3u)] = [383u, 4096u, 4098u, 25031u, 25036u, 25037u, 25038u, 25047u],
            [(15u, 4u)] = [383u, 4096u, 4098u, 25031u, 25036u, 25037u, 25038u, 25047u],
            [(15u, 10u)] = [25002u],
            [(15u, 11u)] = [25000u],
            [(15u, 12u)] = [25004u],
            [(15u, 13u)] = [25005u],
            [(15u, 14u)] = [25003u],
            [(15u, 16u)] = [25008u],
            [(15u, 27u)] = [25039u],
            [(15u, 28u)] = [25040u],
            [(15u, 29u)] = [25045u],
            [(15u, 30u)] = [25046u],
            [(15u, 31u)] = [25016u],
            [(15u, 38u)] = [25041u],
            [(17u, 1u)] = [4096u, 4098u, 25036u, 25037u, 25038u, 25047u, 25078u],
            [(17u, 2u)] = [4096u, 4098u, 25036u, 25037u, 25038u, 25047u, 25078u],
            [(17u, 4u)] = [4096u, 4098u, 25036u, 25037u, 25038u, 25047u, 25078u],
            [(17u, 5u)] = [25081u],
            [(17u, 7u)] = [25006u],
            [(17u, 10u)] = [25002u, 25046u],
            [(17u, 11u)] = [25000u, 25059u],
            [(17u, 12u)] = [25004u],
            [(17u, 13u)] = [25005u],
            [(17u, 14u)] = [25003u],
            [(17u, 16u)] = [25008u, 25051u],
            [(17u, 25u)] = [25013u],
            [(17u, 27u)] = [25039u],
            [(17u, 28u)] = [25040u],
            [(17u, 29u)] = [25045u],
            [(17u, 38u)] = [25041u],
            [(17u, 40u)] = [25080u],
            [(17u, 41u)] = [25009u],
            [(17u, 43u)] = [25068u],
            [(17u, 45u)] = [25077u],
            [(17u, 47u)] = [25079u],
            [(17u, 48u)] = [25095u],
            [(18u, 17u)] = [25060u, 25069u],
            [(18u, 18u)] = [25058u, 25072u],
            [(18u, 19u)] = [25057u],
            [(18u, 32u)] = [25061u],
            [(18u, 33u)] = [25020u],
            [(18u, 34u)] = [25021u],
            [(18u, 36u)] = [25035u],
            [(18u, 44u)] = [25075u],
            [(19u, 17u)] = [20012u, 25069u],
            [(19u, 18u)] = [20011u, 25072u],
            [(19u, 19u)] = [25007u],
            [(19u, 32u)] = [25019u],
            [(19u, 33u)] = [25020u],
            [(19u, 34u)] = [25021u],
            [(19u, 36u)] = [25035u],
            [(19u, 42u)] = [25062u],
            [(19u, 44u)] = [25075u],
            [(20u, 17u)] = [25026u, 25069u],
            [(20u, 18u)] = [25025u, 25072u],
            [(20u, 19u)] = [25022u],
            [(20u, 32u)] = [25032u],
            [(20u, 33u)] = [25020u],
            [(20u, 34u)] = [25021u],
            [(20u, 36u)] = [25035u],
            [(20u, 42u)] = [25062u],
            [(20u, 44u)] = [25075u],
            [(21u, 17u)] = [25028u, 25069u],
            [(21u, 18u)] = [25027u, 25072u],
            [(21u, 19u)] = [25023u],
            [(21u, 32u)] = [25024u],
            [(21u, 33u)] = [25020u],
            [(21u, 34u)] = [25021u],
            [(21u, 35u)] = [25029u],
            [(21u, 36u)] = [25035u],
            [(21u, 44u)] = [25075u],
        }.ToFrozenDictionary();
}


/// <summary>
/// One row of <c>ContainerDefinitions.txt</c>. A worn container item names its row through
/// <c>ClientItemDefinitions.PARAM1</c>; <see cref="MaxBulk"/> is the capacity it contributes
/// (docs/41 §4a).
/// </summary>
/// <param name="IsDynamicBulk">
/// <c>IS_DYNAMIC_BULK</c>. Row 117 - the character's own "Inventory" bag - is the only row in the
/// sheet with this set, and its <see cref="MaxBulk"/> is 0: its capacity is <em>subsumed</em> from
/// the containers equipped on the character, which is what the client's own
/// <c>Container::SetBulkSubsummed: maxBulk=%d</c> (0x14360c358) and
/// <c>Container::ModifyMaxBulk: current=%d, delta=%d, new=%d</c> (0x14360c388) describe.
/// </param>
public readonly record struct ContainerDefinition(
    uint Id,
    int MaximumSlots,
    int MaxBulk,
    int MaxSlotBulk,
    bool RemoveWhenEmpty,
    bool WithdrawalOnly,
    bool DepositOnly,
    bool IsDynamicBulk,
    uint ItemSpawnerId,
    uint AllowedItemClassId);

/// <summary>The 117 rows of <c>ContainerDefinitions.txt</c>.</summary>
public static class ContainerDefinitionTable
{
    /// <summary>
    /// The character's base bag: container definition 117, provided by item 3156 "Inventory"
    /// (class 25068), auto-equipped into loadout-3 slot 43 (docs/41 §4b).
    /// </summary>
    public const uint BaseInventoryDefinitionId = 117;

    /// <summary>Item definition 3156 - the "Inventory" bag item that provides definition 117.</summary>
    public const uint BaseInventoryItemDefinitionId = 3156;

    /// <summary>Every row, in sheet order.</summary>
    public static IReadOnlyList<ContainerDefinition> All => Rows;

    private static readonly ContainerDefinition[] Rows =
    [
        new(1u, 2, 0, 0, false, false, false, false, 3u, 0u),
        new(2u, 4, 0, 0, false, false, false, false, 21u, 0u),
        new(3u, 9999, 2000, 2000, false, false, false, false, 0u, 0u),
        new(4u, 2, 0, 0, false, true, false, false, 7u, 0u),
        new(5u, 3, 0, 0, false, false, false, false, 11u, 0u),
        new(6u, 1, 0, 0, false, false, false, false, 11u, 0u),
        new(7u, 3, 0, 0, false, false, false, false, 11u, 0u),
        new(8u, 4, 0, 0, false, false, false, false, 11u, 0u),
        new(9u, 2, 0, 0, false, false, false, false, 51u, 0u),
        new(10u, 6, 0, 0, false, false, false, false, 10u, 0u),
        new(11u, 2, 0, 0, false, false, false, false, 20u, 0u),
        new(12u, 16, 0, 0, false, false, false, false, 20u, 0u),
        new(13u, 2, 0, 0, false, false, false, false, 11u, 0u),
        new(14u, 2, 0, 0, false, false, false, false, 31u, 0u),
        new(15u, 2, 0, 0, false, false, false, false, 26u, 0u),
        new(16u, 25, 0, 0, true, true, false, false, 0u, 0u),
        new(17u, 9999, 0, 0, false, false, false, false, 0u, 0u),
        new(18u, 6, 0, 0, false, false, false, false, 0u, 0u),
        new(19u, 4, 0, 0, false, false, false, false, 16u, 0u),
        new(20u, 3, 0, 0, false, false, false, false, 17u, 0u),
        new(21u, 9999, 50, 50, false, false, false, false, 0u, 0u),
        new(22u, 9999, 1000, 1000, false, false, false, false, 0u, 0u),
        new(23u, 9999, 0, 0, false, false, false, false, 0u, 0u),
        new(24u, 0, 0, 0, false, false, false, false, 0u, 0u),
        new(25u, 9999, 2000, 2000, false, false, false, false, 0u, 0u),
        new(26u, 2, 0, 0, false, false, false, false, 0u, 0u),
        new(27u, 9999, 1600, 1600, false, false, false, false, 0u, 0u),
        new(28u, 9999, 2000, 2000, false, false, false, false, 0u, 0u),
        new(29u, 9999, 50, 50, false, false, false, false, 0u, 0u),
        new(30u, 2, 0, 0, false, false, false, false, 0u, 0u),
        new(31u, 9999, 300, 300, false, false, false, false, 0u, 0u),
        new(32u, 9999, 1200, 1200, false, false, false, false, 0u, 0u),
        new(33u, 4, 0, 0, false, false, false, false, 21u, 0u),
        new(34u, 2, 0, 0, false, false, false, false, 3u, 0u),
        new(35u, 10, 0, 0, false, false, false, false, 25u, 0u),
        new(36u, 9999, 0, 0, false, false, false, false, 8u, 0u),
        new(37u, 4, 0, 0, false, false, false, false, 30u, 0u),
        new(38u, 6, 0, 0, false, false, false, false, 46u, 0u),
        new(39u, 2, 0, 0, false, false, false, false, 47u, 0u),
        new(40u, 1, 0, 0, false, false, false, false, 33u, 0u),
        new(41u, 2, 0, 0, false, false, false, false, 34u, 0u),
        new(42u, 2, 0, 0, false, false, false, false, 34u, 0u),
        new(43u, 1, 0, 0, false, false, false, false, 38u, 0u),
        new(44u, 2, 0, 0, false, false, false, false, 32u, 0u),
        new(45u, 9999, 300, 300, false, false, false, false, 0u, 0u),
        new(46u, 6, 0, 0, true, true, false, false, 40u, 0u),
        new(47u, 2, 0, 0, false, false, false, false, 38u, 0u),
        new(48u, 9999, 2000, 2000, false, false, false, false, 0u, 0u),
        new(49u, 9999, 100, 100, false, false, false, false, 0u, 0u),
        new(50u, 50, 0, 0, false, false, false, false, 2u, 0u),
        new(51u, 100, 0, 0, true, true, false, false, 0u, 0u),
        new(52u, 2, 0, 0, false, false, false, false, 11u, 0u),
        new(53u, 2, 0, 0, false, false, false, false, 11u, 0u),
        new(54u, 2, 0, 0, false, false, false, false, 11u, 0u),
        new(55u, 1, 0, 0, false, false, false, false, 16u, 0u),
        new(56u, 4, 0, 0, false, false, false, false, 16u, 0u),
        new(57u, 50, 0, 0, true, true, false, false, 0u, 0u),
        new(58u, 4, 0, 0, false, false, false, false, 48u, 0u),
        new(59u, 2, 0, 0, false, false, false, false, 31u, 0u),
        new(60u, 3, 0, 0, false, false, false, false, 11u, 0u),
        new(61u, 9999, 0, 0, false, false, false, false, 0u, 0u),
        new(62u, 40, 0, 0, false, false, false, false, 0u, 0u),
        new(63u, 2, 0, 0, false, false, false, false, 52u, 0u),
        new(65u, 2, 0, 0, false, false, false, false, 50u, 0u),
        new(66u, 2, 0, 0, false, false, false, false, 50u, 0u),
        new(67u, 3, 0, 0, false, false, false, false, 49u, 0u),
        new(68u, 2, 0, 0, false, false, false, false, 49u, 0u),
        new(69u, 1, 0, 0, false, false, false, false, 49u, 0u),
        new(70u, 3, 0, 0, false, false, false, false, 49u, 0u),
        new(71u, 4, 0, 0, false, false, false, false, 49u, 0u),
        new(72u, 3, 0, 0, false, false, false, false, 49u, 0u),
        new(74u, 9999, 100000, 100000, false, false, false, false, 0u, 0u),
        new(75u, 9999, 1400, 1400, false, false, false, false, 0u, 0u),
        new(76u, 9999, 1200, 1200, false, false, false, false, 0u, 0u),
        new(77u, 9999, 0, 0, false, false, false, false, 0u, 0u),
        new(78u, 3, 0, 0, false, false, false, false, 53u, 0u),
        new(79u, 2, 0, 0, false, false, false, false, 54u, 0u),
        new(80u, 2, 0, 0, false, false, false, false, 55u, 0u),
        new(81u, 4, 0, 0, false, false, false, false, 0u, 0u),
        new(82u, 9999, 0, 0, false, false, false, false, 0u, 0u),
        new(83u, 1, 0, 0, false, false, false, false, 0u, 0u),
        new(84u, 15, 0, 0, false, false, false, false, 11u, 0u),
        new(85u, 15, 0, 0, false, false, false, false, 11u, 0u),
        new(86u, 15, 0, 0, false, false, false, false, 11u, 0u),
        new(87u, 15, 0, 0, false, false, false, false, 11u, 0u),
        new(88u, 15, 0, 0, false, false, false, false, 11u, 0u),
        new(89u, 15, 0, 0, false, false, false, false, 11u, 0u),
        new(90u, 15, 0, 0, false, false, false, false, 11u, 0u),
        new(91u, 15, 0, 0, false, false, false, false, 11u, 0u),
        new(92u, 15, 0, 0, false, false, false, false, 11u, 0u),
        new(93u, 15, 0, 0, false, false, false, false, 11u, 0u),
        new(94u, 15, 0, 0, false, false, false, false, 11u, 0u),
        new(95u, 20, 0, 0, true, true, false, false, 0u, 0u),
        new(96u, 9999, 300, 300, false, false, false, false, 0u, 0u),
        new(97u, 9999, 0, 0, false, false, false, false, 0u, 0u),
        new(98u, 999, 5000, 5000, true, true, false, false, 134u, 0u),
        new(99u, 6, 0, 0, false, false, false, false, 136u, 0u),
        new(100u, 9999, 0, 0, false, false, false, false, 0u, 0u),
        new(101u, 9999, 9999999, 9999999, false, false, false, false, 0u, 0u),
        new(102u, 9999, 0, 0, false, false, false, false, 0u, 25063u),
        new(103u, 9999, 25, 25, false, false, false, false, 0u, 0u),
        new(104u, 9999, 0, 0, false, false, false, false, 0u, 0u),
        new(105u, 4, 0, 0, false, false, false, false, 2012u, 0u),
        new(106u, 8, 0, 0, false, false, false, false, 2012u, 0u),
        new(107u, 24, 0, 0, false, false, false, false, 2012u, 0u),
        new(108u, 12, 0, 0, false, false, false, false, 2012u, 0u),
        new(109u, 8, 0, 0, false, false, false, false, 2012u, 0u),
        new(110u, 3, 0, 0, false, false, false, false, 2012u, 0u),
        new(111u, 4, 25, 5, false, false, false, false, 0u, 0u),
        new(112u, 4, 25, 5, false, false, false, false, 0u, 0u),
        new(113u, 50, 0, 0, true, true, false, false, 0u, 0u),
        new(114u, 10, 0, 0, false, false, false, false, 0u, 0u),
        new(115u, 9999, 0, 0, false, false, false, false, 0u, 0u),
        new(116u, 9999, 0, 0, true, true, false, false, 0u, 0u),
        new(117u, 9999, 0, 0, false, false, false, true, 0u, 0u),
        new(118u, 100, 0, 0, true, true, false, false, 0u, 0u),
        new(119u, 9999, 0, 0, false, false, false, false, 0u, 0u),
    ];

    private static readonly FrozenDictionary<uint, ContainerDefinition> ById =
        Rows.ToFrozenDictionary(row => row.Id);

    /// <summary>Look one container definition up.</summary>
    public static bool TryGet(uint id, out ContainerDefinition definition) =>
        ById.TryGetValue(id, out definition);
}

