// <cranberry-provenance>
// Written by tools/pipeline/pipeline.py (docs/96). `pipeline.py check` recomputes every
// hash below and fails the build when one has moved; do not edit this block by hand.
// id: item-class-mappings
// grade: CLIENT
// clientBuild: 0.0.118.208059
// generator: tools/data/gen-item-class-mappings.py sha256=0b21c19a9421c2bcc4942901f254def7b55a40586d10d1580f3e32a424d01f8b
// input: out/data_aug/derived/loot.json sha256=8023e21b5f864e8d4b9e95e6e4f6dc9199e3a5a6543fad95ee2a828538cdae79 crc32=9d37015d size=2419885 grade=CLIENT
// rulings: D72
// generatedUtc: 2026-09-04T07:05:31Z
// </cranberry-provenance>
// <auto-generated>
// Generated by tools/data/gen-item-class-mappings.py from the August client's own
// ItemClassMappings.txt (Assets_*.pack, extracted to C:\Aug2017\out\data_aug). Do not edit by
// hand; re-run the generator instead. Derivation: docs/78 4.5, docs/26 168.
// </auto-generated>

#nullable enable

using System.Collections.Frozen;

namespace Cranberry.Zone.Inventory;

/// <summary>
/// <b>The August client's SECOND item to class table</b> - <c>ItemClassMappings.txt</c>,
/// 482 many-to-many pairs over 311 items, against
/// <c>ClientItemDefinitions.ITEM_CLASS</c>'s one class per item.
/// <para>
/// <b>Why it has to be folded into the class set a loadout slot tests.</b> Loadout 17 names three
/// slots by class - 40 (<c>ConsumeItem1</c>, Q) wants class 25080, 41 (<c>ConsumeItem2</c>, E) wants
/// 25009, 5 wants 25081 - and classes <b>25080 and 25081 have zero rows in
/// <c>ClientItemDefinitions</c> carrying them as <c>ITEM_CLASS</c></b>. They are satisfiable only
/// through this table. A client that did not fold it in could never put anything in loadout 17's Q
/// tile or its binoculars tile, in any build; so it folds it in, and so must the server, or the two
/// disagree about where a picked-up item went.
/// </para>
/// <para>
/// What it costs in practice: item 2423 (Field Bandage) and 2424 (Tactical First Aid Kit) are
/// <c>ITEM_CLASS</c> <b>16053</b>, a 168-row generic bucket no loadout slot in either August loadout
/// accepts. This table additionally gives them 25009, 25054 and 25080 - the quick-use tiles. The
/// owner's own server hit the identical trap at 1087 and called this file
/// <i>"the sheet nobody had read"</i> (docs/78 4.5).
/// </para>
/// <para>
/// <b>Shape.</b> One flat sorted array of classes plus a 311-entry index, rather than a set
/// per item: only 311 of the 2,643 item rows carry a mapping at all, so a per-row
/// <c>FrozenSet</c> would allocate 2,643 collections to express 482 facts. The lookup for an
/// unmapped item is one dictionary miss and no allocation.
/// </para>
/// </summary>
public static class ItemClassMappings
{
    private readonly record struct ClassRange(int Start, int Count);

    /// <summary>Total <c>(ITEM_ID, CLASS_ID)</c> pairs in the sheet.</summary>
    public const int PairCount = 482;

    /// <summary>Items carrying at least one mapping.</summary>
    public const int MappedItemCount = 311;

    /// <summary>
    /// The classes <c>ItemClassMappings.txt</c> gives <paramref name="itemDefinitionId"/>, ascending,
    /// <b>not</b> including the item's own <c>ITEM_CLASS</c>. Empty for the 2,332 items with no
    /// mapping, and the returned span is a view over static data - it allocates nothing.
    /// </summary>
    public static ReadOnlySpan<uint> For(uint itemDefinitionId) =>
        ByItem.TryGetValue(itemDefinitionId, out ClassRange range)
            ? Classes.AsSpan(range.Start, range.Count)
            : ReadOnlySpan<uint>.Empty;

    /// <summary>
    /// Does <paramref name="itemDefinitionId"/> belong to <paramref name="classId"/> under the full
    /// rule - its own <c>ITEM_CLASS</c> <b>or</b> any row of this sheet?
    /// </summary>
    public static bool Matches(uint itemDefinitionId, uint primaryClass, uint classId)
    {
        if (primaryClass == classId)
        {
            return true;
        }

        foreach (uint mapped in For(itemDefinitionId))
        {
            if (mapped == classId)
            {
                return true;
            }
        }

        return false;
    }

    // Classes is declared before ByItem: static field initialisers run in declaration order, so the
    // dictionary's ranges would index a null array the other way round.
    private static readonly uint[] Classes =
    [
        16053u, 25049u, 25050u, 25085u, 25088u, 25050u, 25070u, 25074u, 25092u, 25049u, 25050u, 25085u,
        25086u, 25088u, 25088u, 25063u, 25054u, 25063u, 25070u, 25070u, 25050u, 25070u, 25074u, 25088u,
        25088u, 16050u, 16053u, 25050u, 25070u, 25050u, 25071u, 25074u, 25088u, 25050u, 25070u, 25074u,
        25088u, 25089u, 25091u, 25063u, 25063u, 25085u, 25050u, 25063u, 25067u, 25063u, 25063u, 25070u,
        25049u, 25050u, 25085u, 25049u, 25050u, 25085u, 25088u, 25050u, 25085u, 25085u, 25050u, 25050u,
        25085u, 25085u, 25081u, 25050u, 25070u, 25070u, 25081u, 25090u, 25094u, 25050u, 25074u, 25050u,
        25074u, 25050u, 25049u, 25050u, 25088u, 25050u, 25085u, 25050u, 25050u, 25050u, 25092u, 25091u,
        25092u, 25091u, 25050u, 25050u, 25093u, 25054u, 16050u, 25050u, 25074u, 25050u, 25074u, 25085u,
        25056u, 25093u, 25044u, 25049u, 25050u, 25049u, 25050u, 25050u, 25050u, 25088u, 25049u, 25050u,
        25088u, 25049u, 25050u, 25087u, 25088u, 25059u, 25059u, 25059u, 25059u, 25059u, 25059u, 25059u,
        25059u, 25059u, 25085u, 25085u, 25085u, 25059u, 25059u, 25059u, 25059u, 25059u, 16053u, 25044u,
        25054u, 25059u, 25050u, 25071u, 25074u, 25049u, 25050u, 25088u, 25049u, 25050u, 25049u, 25050u,
        25049u, 25050u, 25049u, 25050u, 25088u, 25088u, 25088u, 25049u, 25050u, 25063u, 25049u, 25050u,
        25088u, 25059u, 25054u, 25082u, 25082u, 25082u, 25082u, 25082u, 25082u, 25059u, 25049u, 25050u,
        25009u, 25054u, 25080u, 25009u, 25054u, 25080u, 25085u, 25049u, 25050u, 25049u, 25050u, 25049u,
        25050u, 25049u, 25050u, 25050u, 25074u, 25054u, 25054u, 25085u, 25049u, 25050u, 25049u, 25050u,
        25086u, 25049u, 25050u, 25086u, 25049u, 25050u, 25049u, 25050u, 25049u, 25050u, 25086u, 25049u,
        25050u, 25049u, 25050u, 25049u, 25050u, 25049u, 25050u, 25049u, 25050u, 25086u, 25049u, 25050u,
        25086u, 25049u, 25050u, 25049u, 25050u, 25059u, 25059u, 25085u, 25059u, 25049u, 25050u, 25086u,
        25049u, 25050u, 25086u, 25049u, 25050u, 25086u, 25059u, 25085u, 25059u, 25059u, 25059u, 25059u,
        25059u, 25059u, 25049u, 25050u, 25086u, 25049u, 25050u, 25086u, 25059u, 25049u, 25050u, 25086u,
        25082u, 25082u, 25082u, 25082u, 25082u, 25082u, 25049u, 25050u, 25049u, 25050u, 25049u, 25050u,
        25049u, 25050u, 25049u, 25050u, 25049u, 25050u, 25049u, 25050u, 25050u, 25050u, 25050u, 25050u,
        25050u, 25082u, 25082u, 25082u, 25082u, 25082u, 25049u, 25050u, 25049u, 25050u, 25086u, 25049u,
        25050u, 25059u, 25049u, 25050u, 25049u, 25050u, 25059u, 25059u, 25059u, 25091u, 25092u, 25049u,
        25050u, 25059u, 25049u, 25050u, 25049u, 25050u, 25086u, 25059u, 25049u, 25050u, 275u, 25059u,
        25059u, 25049u, 25050u, 25050u, 25009u, 25054u, 25080u, 25049u, 25050u, 25087u, 25049u, 25050u,
        25050u, 25082u, 25059u, 25059u, 25082u, 25059u, 25059u, 25059u, 25059u, 25050u, 25095u, 25059u,
        25059u, 25085u, 25059u, 25049u, 25050u, 25086u, 25049u, 25050u, 25050u, 25049u, 25050u, 25059u,
        25049u, 25050u, 25049u, 25050u, 25093u, 25093u, 25049u, 25050u, 25086u, 25059u, 25059u, 25082u,
        25049u, 25050u, 25059u, 25059u, 25049u, 25050u, 25049u, 25050u, 25086u, 25049u, 25050u, 25086u,
        25059u, 25049u, 25050u, 25059u, 25059u, 25059u, 25059u, 25082u, 25049u, 25050u, 25059u, 25059u,
        25059u, 25082u, 25049u, 25050u, 25049u, 25050u, 25082u, 25059u, 25059u, 25059u, 25059u, 25059u,
        25082u, 25049u, 25050u, 25049u, 25050u, 25049u, 25050u, 25049u, 25050u, 25049u, 25050u, 25049u,
        25050u, 25049u, 25050u, 25082u, 25082u, 25082u, 25082u, 25082u, 25082u, 25082u, 25082u, 25082u,
        25082u, 25059u, 25059u, 25059u, 25082u, 25059u, 25082u, 25049u, 25050u, 25049u, 25050u, 25049u,
        25050u, 25085u, 25086u, 25088u, 25049u, 25050u, 25088u, 25049u, 25050u, 25085u, 25088u, 25049u,
        25050u, 25088u, 25050u, 25088u, 25049u, 25050u, 25088u, 25049u, 25050u, 25085u, 25088u, 25049u,
        25050u, 25087u, 25088u, 25049u, 25050u, 25088u, 25049u, 25050u, 25085u, 25082u, 25059u, 25082u,
        25082u, 25082u, 25082u, 25082u, 25082u, 25082u, 25082u, 25082u, 25082u, 25082u, 25082u, 25082u,
        25082u, 25059u,
    ];

    private static readonly FrozenDictionary<uint, ClassRange> ByItem =
        new Dictionary<uint, ClassRange>
        {
        { 1u, new ClassRange(0, 1) },
        { 2u, new ClassRange(1, 4) },
        { 3u, new ClassRange(5, 3) },
        { 9u, new ClassRange(8, 1) },
        { 10u, new ClassRange(9, 5) },
        { 14u, new ClassRange(14, 1) },
        { 16u, new ClassRange(15, 1) },
        { 24u, new ClassRange(16, 1) },
        { 46u, new ClassRange(17, 2) },
        { 47u, new ClassRange(19, 1) },
        { 58u, new ClassRange(20, 4) },
        { 65u, new ClassRange(24, 1) },
        { 79u, new ClassRange(25, 2) },
        { 82u, new ClassRange(27, 2) },
        { 83u, new ClassRange(29, 4) },
        { 84u, new ClassRange(33, 4) },
        { 90u, new ClassRange(37, 2) },
        { 109u, new ClassRange(39, 1) },
        { 111u, new ClassRange(40, 1) },
        { 112u, new ClassRange(41, 1) },
        { 113u, new ClassRange(42, 1) },
        { 114u, new ClassRange(43, 1) },
        { 124u, new ClassRange(44, 1) },
        { 135u, new ClassRange(45, 1) },
        { 141u, new ClassRange(46, 1) },
        { 1354u, new ClassRange(47, 1) },
        { 1373u, new ClassRange(48, 3) },
        { 1374u, new ClassRange(51, 4) },
        { 1382u, new ClassRange(55, 1) },
        { 1428u, new ClassRange(56, 1) },
        { 1429u, new ClassRange(57, 1) },
        { 1442u, new ClassRange(58, 1) },
        { 1448u, new ClassRange(59, 1) },
        { 1469u, new ClassRange(60, 1) },
        { 1511u, new ClassRange(61, 1) },
        { 1530u, new ClassRange(62, 1) },
        { 1536u, new ClassRange(63, 2) },
        { 1538u, new ClassRange(65, 1) },
        { 1542u, new ClassRange(66, 1) },
        { 1696u, new ClassRange(67, 1) },
        { 1701u, new ClassRange(68, 1) },
        { 1707u, new ClassRange(69, 2) },
        { 1708u, new ClassRange(71, 2) },
        { 1716u, new ClassRange(73, 1) },
        { 1718u, new ClassRange(74, 3) },
        { 1720u, new ClassRange(77, 2) },
        { 1721u, new ClassRange(79, 1) },
        { 1724u, new ClassRange(80, 1) },
        { 1727u, new ClassRange(81, 1) },
        { 1728u, new ClassRange(82, 1) },
        { 1729u, new ClassRange(83, 1) },
        { 1730u, new ClassRange(84, 1) },
        { 1731u, new ClassRange(85, 1) },
        { 1733u, new ClassRange(86, 1) },
        { 1734u, new ClassRange(87, 1) },
        { 1735u, new ClassRange(88, 1) },
        { 1741u, new ClassRange(89, 1) },
        { 1743u, new ClassRange(90, 1) },
        { 1745u, new ClassRange(91, 2) },
        { 1747u, new ClassRange(93, 2) },
        { 1803u, new ClassRange(95, 1) },
        { 1835u, new ClassRange(96, 1) },
        { 1858u, new ClassRange(97, 1) },
        { 1885u, new ClassRange(98, 1) },
        { 1889u, new ClassRange(99, 2) },
        { 1899u, new ClassRange(101, 2) },
        { 1903u, new ClassRange(103, 1) },
        { 1986u, new ClassRange(104, 2) },
        { 1991u, new ClassRange(106, 3) },
        { 1997u, new ClassRange(109, 4) },
        { 2042u, new ClassRange(113, 1) },
        { 2043u, new ClassRange(114, 1) },
        { 2044u, new ClassRange(115, 1) },
        { 2045u, new ClassRange(116, 1) },
        { 2062u, new ClassRange(117, 1) },
        { 2063u, new ClassRange(118, 1) },
        { 2076u, new ClassRange(119, 1) },
        { 2077u, new ClassRange(120, 1) },
        { 2078u, new ClassRange(121, 1) },
        { 2120u, new ClassRange(122, 1) },
        { 2121u, new ClassRange(123, 1) },
        { 2122u, new ClassRange(124, 1) },
        { 2168u, new ClassRange(125, 1) },
        { 2169u, new ClassRange(126, 1) },
        { 2170u, new ClassRange(127, 1) },
        { 2171u, new ClassRange(128, 1) },
        { 2172u, new ClassRange(129, 1) },
        { 2202u, new ClassRange(130, 1) },
        { 2213u, new ClassRange(131, 1) },
        { 2214u, new ClassRange(132, 1) },
        { 2227u, new ClassRange(133, 1) },
        { 2228u, new ClassRange(134, 3) },
        { 2229u, new ClassRange(137, 3) },
        { 2230u, new ClassRange(140, 2) },
        { 2231u, new ClassRange(142, 2) },
        { 2232u, new ClassRange(144, 2) },
        { 2233u, new ClassRange(146, 2) },
        { 2235u, new ClassRange(148, 1) },
        { 2236u, new ClassRange(149, 1) },
        { 2237u, new ClassRange(150, 1) },
        { 2239u, new ClassRange(151, 2) },
        { 2244u, new ClassRange(153, 1) },
        { 2246u, new ClassRange(154, 3) },
        { 2290u, new ClassRange(157, 1) },
        { 2342u, new ClassRange(158, 1) },
        { 2373u, new ClassRange(159, 1) },
        { 2374u, new ClassRange(160, 1) },
        { 2375u, new ClassRange(161, 1) },
        { 2376u, new ClassRange(162, 1) },
        { 2377u, new ClassRange(163, 1) },
        { 2378u, new ClassRange(164, 1) },
        { 2396u, new ClassRange(165, 1) },
        { 2399u, new ClassRange(166, 2) },
        { 2423u, new ClassRange(168, 3) },
        { 2424u, new ClassRange(171, 4) },
        { 2425u, new ClassRange(175, 2) },
        { 2446u, new ClassRange(177, 2) },
        { 2480u, new ClassRange(179, 2) },
        { 2483u, new ClassRange(181, 2) },
        { 2494u, new ClassRange(183, 2) },
        { 2496u, new ClassRange(185, 1) },
        { 2514u, new ClassRange(186, 1) },
        { 2570u, new ClassRange(187, 1) },
        { 2586u, new ClassRange(188, 2) },
        { 2592u, new ClassRange(190, 3) },
        { 2593u, new ClassRange(193, 3) },
        { 2597u, new ClassRange(196, 2) },
        { 2600u, new ClassRange(198, 2) },
        { 2601u, new ClassRange(200, 3) },
        { 2661u, new ClassRange(203, 2) },
        { 2662u, new ClassRange(205, 2) },
        { 2663u, new ClassRange(207, 2) },
        { 2664u, new ClassRange(209, 2) },
        { 2665u, new ClassRange(211, 3) },
        { 2666u, new ClassRange(214, 3) },
        { 2712u, new ClassRange(217, 2) },
        { 2731u, new ClassRange(219, 2) },
        { 2745u, new ClassRange(221, 1) },
        { 2748u, new ClassRange(222, 1) },
        { 2749u, new ClassRange(223, 1) },
        { 2750u, new ClassRange(224, 1) },
        { 2781u, new ClassRange(225, 3) },
        { 2788u, new ClassRange(228, 3) },
        { 2789u, new ClassRange(231, 3) },
        { 2815u, new ClassRange(234, 1) },
        { 2816u, new ClassRange(235, 1) },
        { 2817u, new ClassRange(236, 1) },
        { 2818u, new ClassRange(237, 1) },
        { 2827u, new ClassRange(238, 1) },
        { 2828u, new ClassRange(239, 1) },
        { 2829u, new ClassRange(240, 1) },
        { 2830u, new ClassRange(241, 1) },
        { 2834u, new ClassRange(242, 3) },
        { 2835u, new ClassRange(245, 3) },
        { 2838u, new ClassRange(248, 1) },
        { 2859u, new ClassRange(249, 3) },
        { 2877u, new ClassRange(252, 1) },
        { 2878u, new ClassRange(253, 1) },
        { 2879u, new ClassRange(254, 1) },
        { 2880u, new ClassRange(255, 1) },
        { 2881u, new ClassRange(256, 1) },
        { 2889u, new ClassRange(257, 1) },
        { 2900u, new ClassRange(258, 2) },
        { 2901u, new ClassRange(260, 2) },
        { 2902u, new ClassRange(262, 2) },
        { 2906u, new ClassRange(264, 2) },
        { 2907u, new ClassRange(266, 2) },
        { 2908u, new ClassRange(268, 2) },
        { 2909u, new ClassRange(270, 2) },
        { 2961u, new ClassRange(272, 1) },
        { 2962u, new ClassRange(273, 1) },
        { 2963u, new ClassRange(274, 1) },
        { 2964u, new ClassRange(275, 1) },
        { 2965u, new ClassRange(276, 1) },
        { 3029u, new ClassRange(277, 1) },
        { 3030u, new ClassRange(278, 1) },
        { 3031u, new ClassRange(279, 1) },
        { 3032u, new ClassRange(280, 1) },
        { 3033u, new ClassRange(281, 1) },
        { 3055u, new ClassRange(282, 2) },
        { 3056u, new ClassRange(284, 3) },
        { 3057u, new ClassRange(287, 2) },
        { 3064u, new ClassRange(289, 1) },
        { 3066u, new ClassRange(290, 2) },
        { 3123u, new ClassRange(292, 2) },
        { 3124u, new ClassRange(294, 1) },
        { 3159u, new ClassRange(295, 1) },
        { 3160u, new ClassRange(296, 1) },
        { 3162u, new ClassRange(297, 1) },
        { 3164u, new ClassRange(298, 1) },
        { 3165u, new ClassRange(299, 2) },
        { 3167u, new ClassRange(301, 1) },
        { 3172u, new ClassRange(302, 2) },
        { 3179u, new ClassRange(304, 3) },
        { 3181u, new ClassRange(307, 1) },
        { 3356u, new ClassRange(308, 2) },
        { 3364u, new ClassRange(310, 1) },
        { 3366u, new ClassRange(311, 1) },
        { 3367u, new ClassRange(312, 1) },
        { 3369u, new ClassRange(313, 2) },
        { 3371u, new ClassRange(315, 1) },
        { 3375u, new ClassRange(316, 3) },
        { 3381u, new ClassRange(319, 3) },
        { 3401u, new ClassRange(322, 2) },
        { 3402u, new ClassRange(324, 1) },
        { 3405u, new ClassRange(325, 1) },
        { 3409u, new ClassRange(326, 1) },
        { 3414u, new ClassRange(327, 1) },
        { 3416u, new ClassRange(328, 1) },
        { 3439u, new ClassRange(329, 1) },
        { 3440u, new ClassRange(330, 1) },
        { 3441u, new ClassRange(331, 1) },
        { 3451u, new ClassRange(332, 1) },
        { 3454u, new ClassRange(333, 1) },
        { 3460u, new ClassRange(334, 1) },
        { 3468u, new ClassRange(335, 1) },
        { 3470u, new ClassRange(336, 1) },
        { 3473u, new ClassRange(337, 1) },
        { 3474u, new ClassRange(338, 1) },
        { 3475u, new ClassRange(339, 3) },
        { 3477u, new ClassRange(342, 2) },
        { 3479u, new ClassRange(344, 1) },
        { 3481u, new ClassRange(345, 2) },
        { 3487u, new ClassRange(347, 1) },
        { 3489u, new ClassRange(348, 2) },
        { 3495u, new ClassRange(350, 2) },
        { 3509u, new ClassRange(352, 1) },
        { 3510u, new ClassRange(353, 1) },
        { 3513u, new ClassRange(354, 3) },
        { 3545u, new ClassRange(357, 1) },
        { 3546u, new ClassRange(358, 1) },
        { 3548u, new ClassRange(359, 1) },
        { 3550u, new ClassRange(360, 2) },
        { 3551u, new ClassRange(362, 1) },
        { 3581u, new ClassRange(363, 1) },
        { 3584u, new ClassRange(364, 2) },
        { 3585u, new ClassRange(366, 3) },
        { 3586u, new ClassRange(369, 3) },
        { 3631u, new ClassRange(372, 1) },
        { 3720u, new ClassRange(373, 2) },
        { 3721u, new ClassRange(375, 1) },
        { 3727u, new ClassRange(376, 1) },
        { 3732u, new ClassRange(377, 1) },
        { 3739u, new ClassRange(378, 1) },
        { 3740u, new ClassRange(379, 1) },
        { 3797u, new ClassRange(380, 2) },
        { 3862u, new ClassRange(382, 1) },
        { 3886u, new ClassRange(383, 1) },
        { 3899u, new ClassRange(384, 1) },
        { 3900u, new ClassRange(385, 1) },
        { 3903u, new ClassRange(386, 2) },
        { 3904u, new ClassRange(388, 2) },
        { 3928u, new ClassRange(390, 1) },
        { 3933u, new ClassRange(391, 1) },
        { 4013u, new ClassRange(392, 1) },
        { 4018u, new ClassRange(393, 1) },
        { 4023u, new ClassRange(394, 1) },
        { 4029u, new ClassRange(395, 1) },
        { 4030u, new ClassRange(396, 1) },
        { 4031u, new ClassRange(397, 2) },
        { 4032u, new ClassRange(399, 2) },
        { 4033u, new ClassRange(401, 2) },
        { 4066u, new ClassRange(403, 2) },
        { 4072u, new ClassRange(405, 2) },
        { 4073u, new ClassRange(407, 2) },
        { 4074u, new ClassRange(409, 2) },
        { 4116u, new ClassRange(411, 1) },
        { 4117u, new ClassRange(412, 1) },
        { 4118u, new ClassRange(413, 1) },
        { 4119u, new ClassRange(414, 1) },
        { 4120u, new ClassRange(415, 1) },
        { 4121u, new ClassRange(416, 1) },
        { 4122u, new ClassRange(417, 1) },
        { 4123u, new ClassRange(418, 1) },
        { 4124u, new ClassRange(419, 1) },
        { 4125u, new ClassRange(420, 1) },
        { 4166u, new ClassRange(421, 1) },
        { 4170u, new ClassRange(422, 1) },
        { 4175u, new ClassRange(423, 1) },
        { 4176u, new ClassRange(424, 1) },
        { 4182u, new ClassRange(425, 1) },
        { 4184u, new ClassRange(426, 1) },
        { 4186u, new ClassRange(427, 2) },
        { 4187u, new ClassRange(429, 2) },
        { 4246u, new ClassRange(431, 5) },
        { 4247u, new ClassRange(436, 3) },
        { 4248u, new ClassRange(439, 4) },
        { 4249u, new ClassRange(443, 3) },
        { 4250u, new ClassRange(446, 2) },
        { 4251u, new ClassRange(448, 3) },
        { 4252u, new ClassRange(451, 4) },
        { 4253u, new ClassRange(455, 4) },
        { 4254u, new ClassRange(459, 3) },
        { 4264u, new ClassRange(462, 3) },
        { 4266u, new ClassRange(465, 1) },
        { 4269u, new ClassRange(466, 1) },
        { 4436u, new ClassRange(467, 1) },
        { 4437u, new ClassRange(468, 1) },
        { 4438u, new ClassRange(469, 1) },
        { 4439u, new ClassRange(470, 1) },
        { 4440u, new ClassRange(471, 1) },
        { 4441u, new ClassRange(472, 1) },
        { 4442u, new ClassRange(473, 1) },
        { 4443u, new ClassRange(474, 1) },
        { 4444u, new ClassRange(475, 1) },
        { 4445u, new ClassRange(476, 1) },
        { 4456u, new ClassRange(477, 1) },
        { 4457u, new ClassRange(478, 1) },
        { 4461u, new ClassRange(479, 1) },
        { 4462u, new ClassRange(480, 1) },
        { 4567u, new ClassRange(481, 1) },
        }.ToFrozenDictionary();
}
