// Generated by tools/world/gen-vehicle-skins.py; direct owned item ids (140d10090).
// VehicleSkinMods.txt: SHA256 76441772d3536e473ba2865850cbdaa36d4cdf693120f5a108fc396f2b9f05ef
// ClientItemDefinitions.txt: SHA256 638deb01b4eeb565d1c8fc2037e0169518a2c54dd23f19c776f25d3e39dab114
namespace Cranberry.Zone.Vehicles;

public readonly record struct VehicleSkinChoice(uint VehicleId, uint ModPoint, uint ItemId, uint ShaderGroupId);

/// <summary>August VehicleSkinMods and ClientItemDefinitions.PARAM1.</summary>
public static class VehicleSkinCatalog
{
    public static readonly VehicleSkinChoice[] All =
    [
        new(1, 1, 3801, 838),
        new(1, 1, 3802, 840),
        new(1, 1, 3803, 842),
        new(1, 1, 3804, 843),
        new(1, 1, 3857, 861),
        new(1, 1, 3932, 924),
        new(13, 1, 4055, 484),
        new(13, 1, 4056, 492),
        new(13, 1, 4057, 491),
        new(2, 1, 4286, 898),
        new(2, 1, 4296, 1129),
        new(2, 1, 4297, 1131),
        new(2, 1, 4299, 1133),
        new(5, 1, 4302, 229),
        new(5, 1, 4303, 667),
        new(5, 1, 4304, 690),
        new(5, 1, 4305, 925),
        new(1, 1, 4367, 1143),
        new(1, 1, 4368, 1148),
        new(1, 1, 4369, 1146),
    ];
    public static VehicleSkinChoice? Find(uint vehicle, uint modPoint, uint item) =>
        All.Where(s => s.VehicleId == vehicle && s.ModPoint == modPoint && s.ItemId == item)
            .Select(s => (VehicleSkinChoice?)s).FirstOrDefault();
}
