using System.Numerics;
using Cranberry.Zone.World.Doors;

namespace Cranberry.Tests.Zone.Doors;

/// <summary>
/// The shipped Z2 door dataset (docs/42 §7, generated by <c>tools/data/gen-doors.py</c>).
/// <para>
/// These are transcription tests, not behaviour tests: every number below was measured on the
/// August client's own <c>Z2.zone</c> and <c>Models.txt</c>, so a failure here means the data file
/// stopped being a transcription of that client — not that a threshold wants retuning.
/// </para>
/// </summary>
public sealed class Z2DoorsTests
{
    private static readonly Lazy<Z2Doors> Doors = new(Z2Doors.LoadDefault);

    /// <summary>
    /// docs/42 §7b with docs/114 §1–§2: <b>4,147</b> invisible door-placement markers — the eight
    /// <c>Common_DPO_DoorProxy_*</c> families and the three <c>Hospital_*_Placer</c> families — and
    /// every one of them is playable.
    /// <para>
    /// It was 4,103 until 2026-09-03: the 39 hospital markers were not in the generator's family
    /// list at all, and the five lobby doors were discarded by a height filter that called them an
    /// off-map set piece. Both are corrected, and every one of the 4,103 rows that were already
    /// here is unchanged field for field.
    /// </para>
    /// </summary>
    [Fact]
    public void TheShippedDoorFileLoadsWithItsOwnHeaderGrid()
    {
        Z2Doors doors = Doors.Value;

        Assert.Equal(Z2Doors.Z2PlayableDoorCount, doors.Count);
        Assert.Equal(4147, doors.Count);
        Assert.Equal(11, doors.Kinds.Length);
        Assert.Equal(128, doors.Dimension);
        Assert.Equal(64f, doors.CellMetres);
        Assert.Equal(-4096f, doors.OriginX);
        Assert.Equal(-4096f, doors.OriginZ);
    }

    /// <summary>
    /// docs/42 §7d. Seven of the eight proxy→mesh pairings are exact name matches in
    /// <c>Models.txt</c>; <c>Office → Doors_Commercial_01</c> is the one reached by elimination and
    /// is still marked a lead in the doc. The counts are the measured Z2 census.
    /// </summary>
    [Theory]
    [InlineData("ResidentialFront", 9906u, 9904u, 1262)]
    [InlineData("Office", 9882u, 9884u, 905)]           // [lead] pairing
    [InlineData("Camper", 10054u, 10055u, 463)]
    [InlineData("Residential", 9883u, 9905u, 429)]
    [InlineData("CommercialGlass", 9907u, 9897u, 393)]
    [InlineData("Industrial", 9881u, 9903u, 369)]       // docs/114 §1: 364 + the 5 lobby doors
    [InlineData("Cabin", 9908u, 9901u, 286)]
    [InlineData("BathroomStall", 10082u, 10083u, 1)]
    // docs/114 §2. Marker id → mesh id, both resolved by NAME out of Models.txt. Each _Placer
    // row sits immediately after the mesh row it places and shares its base name (rows 943-948),
    // which is the client's own confirmation of the owner's Z1 map (D53).
    [InlineData("HospitalSingle", 9888u, 9887u, 25)]
    [InlineData("HospitalDouble", 9890u, 9889u, 10)]
    [InlineData("HospitalDoubleMetal", 9892u, 9891u, 4)]
    public void EachProxyFamilyCarriesItsDerivedModelIdsAndCensus(
        string name, uint proxyModelId, uint modelId, int expectedCount)
    {
        Z2Doors doors = Doors.Value;
        int kindIndex = doors.KindIndexOf(name);
        Assert.True(kindIndex >= 0, $"the dataset has no '{name}' family");

        DoorKind kind = doors.Kinds[kindIndex];
        Assert.Equal(proxyModelId, kind.ProxyModelId);
        Assert.Equal(modelId, kind.ModelId);

        // docs/42 §6c: Doors.txt selects the swing SOUND and nothing else, so the row id is
        // Cranberry's choice — but it must be > 0, because the client reads 0 at +0x19c as
        // "not a door" and would spawn inert scenery with no controller.
        Assert.True(kind.DoorTableId > 0, $"'{name}' has door id 0, which is 'not a door'");

        int count = 0;
        foreach (DoorPlacement door in doors.Doors)
        {
            if (door.KindIndex == kindIndex)
            {
                count++;
            }
        }

        Assert.Equal(expectedCount, count);
    }

    /// <summary>
    /// docs/42 §7b: all 4,147 ZONE instance ids are distinct, which is what makes the instance id a
    /// stable per-door key — the thing <see cref="MatchDoors"/> hangs the open/closed bit on so it
    /// survives a stream-out and a re-spawn with fresh guids.
    /// </summary>
    [Fact]
    public void EveryDoorHasItsOwnZoneInstanceId()
    {
        Z2Doors doors = Doors.Value;
        var seen = new HashSet<uint>(doors.Count);

        foreach (DoorPlacement door in doors.Doors)
        {
            Assert.True(seen.Add(door.InstanceId), $"instance id {door.InstanceId} appears twice");
        }

        Assert.Equal(doors.Count, seen.Count);
    }

    /// <summary>
    /// <b>REVERSED by docs/114 §1.</b> The five Industrial proxies at y ≈ 506 are not an "off-map
    /// set piece": they are the pre-match LOBBY's own doors, standing 48–57 m from where this
    /// server puts the player, and they are the only five doors the friend's live server is on
    /// record spawning. Nothing else on the map is above 400 m, so the shape of the old assertion
    /// is kept and only its exemption list is new — a sixth door up there would still be a client
    /// change this test has to catch.
    /// </summary>
    [Fact]
    public void TheOnlyDoorsAboveTheMapAreTheFiveLobbyDoors()
    {
        var lobby = new HashSet<uint>
        {
            1796604819, 1796604901, 1796604902, 1796604910, 1435455604,
        };
        var found = new HashSet<uint>();

        foreach (DoorPlacement door in Doors.Value.Doors)
        {
            if (door.Y <= 400f)
            {
                continue;
            }

            Assert.True(
                lobby.Contains(door.InstanceId),
                $"door {door.InstanceId} is at y = {door.Y} and is not one of the lobby five");
            found.Add(door.InstanceId);
        }

        Assert.Equal(Z2Doors.Z2LobbyDoorCount, found.Count);
        Assert.Equal(lobby, found);
    }

    /// <summary>
    /// Every door's yaw is a finite radian value — the <b>closed</b> pose, which the client's own
    /// controller turns into <c>open = yaw + π/2</c> (docs/42 §6a). A NaN here would put a door at an
    /// undefined angle with no error anywhere.
    /// </summary>
    [Fact]
    public void EveryDoorCarriesAFiniteClosedYaw()
    {
        foreach (DoorPlacement door in Doors.Value.Doors)
        {
            Assert.True(float.IsFinite(door.Yaw), $"door {door.InstanceId} has yaw {door.Yaw}");
            Assert.True(float.IsFinite(door.X) && float.IsFinite(door.Y) && float.IsFinite(door.Z));
        }
    }

    /// <summary>
    /// <c>QueryNearest</c> and <c>Query</c> count the same disc; only the retained set differs. The
    /// nearest overload must come back sorted, because a streaming burst truncates it at a cap and a
    /// grid-order truncation keeps a band at the far edge of the disc instead of the house in front
    /// of the player.
    /// </summary>
    [Fact]
    public void QueryNearestReturnsTheClosestDoorsInAscendingDistance()
    {
        Z2Doors doors = Doors.Value;
        Vector3 centre = BusiestNeighbourhood(doors, out int expected);
        Assert.True(expected > 16, $"the busiest 128 m disc holds only {expected} doors");

        Span<int> nearest = stackalloc int[16];
        int matched = doors.QueryNearest(centre, 128f, nearest);

        Span<int> scanOrder = stackalloc int[16];
        Assert.Equal(matched, doors.Query(centre, 128f, scanOrder));
        Assert.Equal(expected, matched);

        float previous = -1f;
        foreach (int index in nearest)
        {
            float distance = Distance(doors, index, centre);
            Assert.True(distance >= previous, "QueryNearest came back out of order");
            Assert.True(distance <= 128f);
            previous = distance;
        }

        // The nearest 16 must beat the farthest of them against every door in the disc.
        int[] everything = new int[expected];
        doors.Query(centre, 128f, everything);
        int closerThanTheWorstKept = 0;
        foreach (int index in everything)
        {
            if (Distance(doors, index, centre) < previous)
            {
                closerThanTheWorstKept++;
            }
        }

        Assert.True(closerThanTheWorstKept <= 16, $"{closerThanTheWorstKept} doors are nearer than the kept 16");
    }

    /// <summary>
    /// <c>TryFindNearest</c> at a door's own position finds a door at zero distance — the lookup a
    /// toggle request falls back on when it names a guid the match does not know.
    /// </summary>
    [Fact]
    public void TryFindNearestResolvesADoorStoodOn()
    {
        Z2Doors doors = Doors.Value;
        DoorPlacement door = doors[doors.Count / 2];

        Assert.True(doors.TryFindNearest(door.Position, 1f, out int index, out float distance));
        Assert.Equal(0f, distance, 3);
        Assert.Equal(door.Position, doors[index].Position);
    }

    /// <summary>An empty patch of map resolves to nothing rather than to the nearest door anywhere.</summary>
    [Fact]
    public void TryFindNearestRefusesAnEmptyPatchOfMap()
    {
        Z2Doors doors = Doors.Value;
        var faraway = new Vector3(-4000f, 0f, 4000f);

        // Only assert the negative if the corner really is empty; the point of the test is the
        // bounded search, not the map's contents.
        Span<int> none = stackalloc int[1];
        if (doors.Query(faraway, 50f, none) == 0)
        {
            Assert.False(doors.TryFindNearest(faraway, 50f, out _, out _));
        }
    }

    /// <summary>
    /// The area labels come from the same <c>Z2Areas.xml</c> containment rule the loot lane uses, so
    /// a door and the loot inside the same POI report the same name — which is what makes a live log
    /// line readable.
    /// </summary>
    [Fact]
    public void DoorsAreLabelledWithTheSamePoiVocabularyAsLoot()
    {
        Z2Doors doors = Doors.Value;
        int labelled = 0;

        foreach (DoorPlacement door in doors.Doors)
        {
            string? area = doors.AreaNameOf(door);
            if (area is null)
            {
                Assert.False(door.HasArea);
                continue;
            }

            Assert.True(door.HasArea);
            Assert.NotEmpty(area);
            labelled++;
        }

        Assert.True(labelled > 0, "no door fell inside a named area");
        Assert.True(doors.Areas.Length > 0);
    }

    /// <summary>A corrupt or truncated file is refused with its own name in the message, not read half-way.</summary>
    [Fact]
    public void ParseRefusesAFileThatIsNotADoorSet()
    {
        Assert.Throws<InvalidDataException>(() => Z2Doors.Parse(new byte[64], "not-a-door-file"));
        Assert.Throws<InvalidDataException>(() => Z2Doors.Parse(new byte[3], "too-short"));
    }

    private static float Distance(Z2Doors doors, int index, in Vector3 centre)
    {
        DoorPlacement door = doors[index];
        float dx = door.X - centre.X;
        float dz = door.Z - centre.Z;
        return MathF.Sqrt((dx * dx) + (dz * dz));
    }

    /// <summary>
    /// The busiest 128 m disc in the set, found by sampling every 64th door. Picking the centre out
    /// of the data rather than hard-coding a POI keeps the query tests meaningful if the map data is
    /// ever regenerated.
    /// </summary>
    private static Vector3 BusiestNeighbourhood(Z2Doors doors, out int count)
    {
        Vector3 best = doors[0].Position;
        count = 0;

        for (int i = 0; i < doors.Count; i += 64)
        {
            Vector3 centre = doors[i].Position;
            int matched = doors.Query(centre, 128f, []);
            if (matched > count)
            {
                count = matched;
                best = centre;
            }
        }

        return best;
    }
}
