#!/usr/bin/env python3
r"""
gen-z1-opcode-map.py - generate src/Cranberry.Protocol/Z1OpcodeMap.g.cs from the bridge map.

The point of this file is that a Z1 (ClientProtocol_1087) packet writer can be ported into
Cranberry without hand-editing its opcode constants: keep the Z1 ids in the ported code, run
them through Z1OpcodeMap.Translate, and the August (1148) ids come out. A packet that no longer
exists in August is reported rather than silently mistranslated.

Usage: python tools/bridge/gen-z1-opcode-map.py [map.json] [out.cs]
"""
import json
import sys
from pathlib import Path

src = Path(sys.argv[1] if len(sys.argv) > 1
           else r"C:\Aug2017\out\wave9-bridge\opcode-map-1087-to-1148.json")
dst = Path(sys.argv[2] if len(sys.argv) > 2 else
           Path(__file__).resolve().parents[2] / "src" / "Cranberry.Protocol" / "Z1OpcodeMap.g.cs")

doc = json.load(open(src, encoding="utf-8"))
rows = doc["rows"]


def key(levels):
    """(base, sub) packed into a u32. A base/leaf packet has sub 0."""
    base = levels[0]
    sub = levels[1] if len(levels) > 1 else 0
    return (base << 16) | sub


pairs = {}
for r in rows:
    if r["verdict"] in ("deleted", "new") or not r["z1_1087"] or not r["aug_1148"]:
        continue
    k, v = key(r["z1_1087"]), key(r["aug_1148"])
    # A duplicate key means two members share a 1087 id; they must agree on the translation.
    if k in pairs and pairs[k] != v:
        raise SystemExit(f"conflicting translation for {r['z1_hex']}: {pairs[k]:#x} vs {v:#x}")
    pairs[k] = v

deleted = [(r["member"], key(r["z1_1087"])) for r in rows if r["verdict"] == "deleted"]

lines = [
    "// <auto-generated>",
    "// Generated by tools/bridge/gen-z1-opcode-map.py from",
    f"// {src.name} - the join of the Z1 client's packet-id registrations",
    "// (ClientProtocol_1087) against the August client's (ClientProtocol_1148). Do not edit.",
    "// </auto-generated>",
    "",
    "#nullable enable",
    "using System.Collections.Frozen;",
    "",
    "namespace Cranberry.Protocol;",
    "",
    "/// <summary>",
    "/// Translates a Z1 (<c>ClientProtocol_1087</c>) zone opcode into its August",
    "/// (<c>ClientProtocol_1148</c>) equivalent, so a packet writer ported from the owner's Z1",
    "/// server can keep its original ids and still put the right bytes on an August wire.",
    "/// <para>",
    f"/// {len(pairs)} packets translate. {len(deleted)} were deleted from the August client and",
    "/// cannot be translated at all - <see cref=\"IsDeleted\"/> names them, and",
    "/// <see cref=\"Translate\"/> throws rather than inventing an id, because a silently wrong",
    "/// opcode is the single most expensive kind of bug this project has.",
    "/// </para>",
    "/// <para>",
    "/// The shape of the change: every base shift in the whole table is exactly <b>-1</b>, and",
    "/// sub shifts are <c>+1</c> or <c>+2</c> inside a family. It is a renumbering, not a redesign.",
    "/// </para>",
    "/// </summary>",
    "public static class Z1OpcodeMap",
    "{",
    "    /// <summary>Packs a base opcode and sub opcode into the table's key. A base/leaf",
    "    /// packet - one with no sub level - uses sub 0.</summary>",
    "    public static uint Key(byte baseOpcode, ushort subOpcode) =>",
    "        ((uint)baseOpcode << 16) | subOpcode;",
    "",
    f"    /// <summary>Packets that survive the 1087 -> 1148 renumbering: {len(pairs)}.</summary>",
    "    public static int TranslatableCount => Table.Count;",
    "",
    "    private static readonly FrozenDictionary<uint, uint> Table = BuildTable();",
    "",
    "    private static readonly FrozenDictionary<uint, string> DeletedTable = BuildDeleted();",
    "",
    "    /// <summary>",
    "    /// The August (base, sub) for a Z1 (base, sub). Returns false for an id the August client",
    "    /// deleted and for one that was never registered in 1087.",
    "    /// </summary>",
    "    public static bool TryTranslate(byte z1Base, ushort z1Sub,"
    " out byte augustBase, out ushort augustSub)",
    "    {",
    "        if (Table.TryGetValue(Key(z1Base, z1Sub), out uint packed))",
    "        {",
    "            augustBase = (byte)(packed >> 16);",
    "            augustSub = (ushort)packed;",
    "            return true;",
    "        }",
    "",
    "        augustBase = 0;",
    "        augustSub = 0;",
    "        return false;",
    "    }",
    "",
    "    /// <summary>",
    "    /// As <see cref=\"TryTranslate\"/>, but throws for an untranslatable id. Use this on a",
    "    /// ported code path: a packet that cannot be translated must stop the build or the",
    "    /// request, never go out as a guess.",
    "    /// </summary>",
    "    public static (byte Base, ushort Sub) Translate(byte z1Base, ushort z1Sub)",
    "    {",
    "        if (TryTranslate(z1Base, z1Sub, out byte b, out ushort s))",
    "        {",
    "            return (b, s);",
    "        }",
    "",
    "        string deleted = IsDeleted(z1Base, z1Sub, out string? name)",
    "            ? $\" - it was DELETED from the August client ({name})\"",
    "            : \" - it is not a registered 1087 opcode\";",
    "        throw new ArgumentOutOfRangeException(",
    "            nameof(z1Base),",
    "            $\"Z1 opcode 0x{z1Base:x2} 0x{z1Sub:x2} has no August equivalent{deleted}.\");",
    "    }",
    "",
    "    /// <summary>True when the August client removed this packet outright.</summary>",
    "    public static bool IsDeleted(byte z1Base, ushort z1Sub, out string? member) =>",
    "        DeletedTable.TryGetValue(Key(z1Base, z1Sub), out member);",
    "",
    "    /// <summary>The member names of every packet the August client deleted.</summary>",
    "    public static IReadOnlyCollection<string> DeletedMembers => DeletedTable.Values;",
    "",
    "    private static FrozenDictionary<uint, uint> BuildTable()",
    "    {",
    "        // key, value pairs: (z1Base << 16 | z1Sub) -> (augBase << 16 | augSub)",
    "        uint[] packed =",
    "        [",
]
for k in sorted(pairs):
    lines.append(f"            0x{k:06x}, 0x{pairs[k]:06x},")
lines += [
    "        ];",
    "",
    "        var map = new Dictionary<uint, uint>(packed.Length / 2);",
    "        for (int i = 0; i < packed.Length; i += 2)",
    "        {",
    "            map[packed[i]] = packed[i + 1];",
    "        }",
    "",
    "        return map.ToFrozenDictionary();",
    "    }",
    "",
    "    private static FrozenDictionary<uint, string> BuildDeleted() =>",
    "        new Dictionary<uint, string>",
    "        {",
]
for member, k in sorted(deleted, key=lambda t: t[1]):
    lines.append(f"            [0x{k:06x}] = \"{member}\",")
lines += [
    "        }.ToFrozenDictionary();",
    "}",
    "",
]
dst.parent.mkdir(parents=True, exist_ok=True)
dst.write_text("\n".join(lines), encoding="utf-8")
print(f"wrote {dst}  ({len(pairs)} translations, {len(deleted)} deleted)")
