// <cranberry-provenance>
// Written by tools/pipeline/pipeline.py (docs/96). `pipeline.py check` recomputes every
// hash below and fails the build when one has moved; do not edit this block by hand.
// id: weapon-lists
// grade: CLIENT+RULING
// clientBuild: 0.0.118.208059
// generator: tools/data/gen-weapon-lists.py sha256=c3c4b1e2ce16dd27bd7a711701a536ab9b5841ecdae2cca7dd3696e0e66ffbcb
// input: out/data_aug/derived/weapon-lists.json sha256=607d3680384ec715f14b585c2629a2bc0bf1efc32b0d13ccc7d324fc2f96aa0b crc32=e338ebb0 size=35925 grade=CLIENT
// rulings: D143, D159, D212, D230, D231, D232, D233, D234
// generatedUtc: 2026-09-04T07:05:31Z
// </cranberry-provenance>
// <auto-generated>
// Generated by tools/data/gen-weapon-lists.py from the August client's own datasheets
// (build 0.0.118.208059), read through out\data_aug\derived\weapon-lists.json. Do not
// edit by hand; re-run the generator instead. Derivation: docs/99-weapon-lists.md.
// </auto-generated>

#nullable enable

using System.Collections.Frozen;

namespace Cranberry.Zone.Weapons;

/// <summary>
/// One fire mode Cranberry ships in <c>WeaponDefinitions</c> list 2.
/// <para>
/// <b>Every timing here is the August client's own</b> - <paramref name="RefireTimeMs"/>
/// is <c>REFIRE_TIME_MS</c>, <paramref name="ReloadTimeMs"/> is <c>RELOAD_TIME_MS</c> and
/// <paramref name="ClipSize"/> is <c>CLIP_SIZE</c>, all from the
/// <c>ClientItemDatasheetData</c> row of the lowest-numbered item that names the fire group.
/// The <paramref name="FireModeId"/> is the one server-chosen number: the client ships no
/// fire-mode table, so D159 numbers them <c>fireGroupId * 2 + index</c>.
/// </para>
/// </summary>
/// <param name="FireModeId">The list-2 hash key (<c>rec+0x378</c>) - D159.</param>
/// <param name="FireGroupId">The list-1 record that names this mode.</param>
/// <param name="ModeIndex">0 or 1; <c>FUN_1411ceca0</c>'s melee branch asks for index 1.</param>
/// <param name="SourceItemId">The datasheet row the timings came from.</param>
/// <param name="DefinitionId">
/// <c>rec+0x18</c> - the fire mode's OWN id, and the primary key of list 4. Equal to
/// <paramref name="FireModeId"/>; see <c>FireModeRecord.DefinitionId</c> for the three
/// functions that read it.
/// </param>
/// <param name="RefireTimeMs"><c>rec+0x40</c> <c>FireMode.RefireTime</c> [P].</param>
/// <param name="ReloadTimeMs"><c>rec+0x60</c> <c>FireMode.ReloadTime</c> [P].</param>
/// <param name="ClipSize">
/// The client's own <c>CLIP_SIZE</c> for the group's first item - what the weapon
/// definition's ammo slot carries as <c>AmmoSlot.ClipSize</c>.
/// </param>
/// <param name="IronSights">
/// <c>rec+0x20</c> bit <c>0x04</c> <c>IRON_SIGHTS</c> [P]. RULING: mode index 1 is the ADS
/// mode - it is the index the August client's own right-click sends in all 145 captured
/// <c>82 0c</c> packets, and the owner's Z1 reads the same index as aim-down.
/// </param>
/// <param name="AmmoSlot"><c>rec+0x30</c> <c>AMMO_SLOT</c> [P]. One slot per gun, so 0.</param>
/// <param name="EffectGroup">
/// <c>rec+0x104</c> <c>EFFECT_GROUP</c> - the <c>FireModeEffectGroups</c> GROUP_ID the client
/// resolves to a fire composite effect (the muzzle flash and the gunshot audio) when this fire
/// group FIRES. It is the fire-group id itself, shipped only for a group with a non-zero
/// <c>fire</c> row (groups 1..21/23/24); a group with no row (every group &gt; 24, e.g. the
/// AK-47's 51) is a gap and ships 0. Shipping 0 was the owner's "no noise of being shot" -
/// the client logs "missing effect definition for Id #0". RULING D234.
/// </param>
public readonly record struct AugustFireModeFact(
    uint FireModeId,
    uint FireGroupId,
    int ModeIndex,
    uint SourceItemId,
    uint DefinitionId,
    int RefireTimeMs,
    int ReloadTimeMs,
    int ClipSize,
    bool IronSights,
    int AmmoSlot,
    uint EffectGroup);

/// <summary>
/// The 120 fire modes of the 60 fire groups the client's own
/// <c>ClientItemDatasheetData.txt</c> names, in (fire group, mode index) order.
/// </summary>
public static class AugustFireModeFacts
{
    /// <summary>Modes per fire group - D159, and <c>AugustWeaponTable.FireModesPerGroup</c>.</summary>
    public const int ModesPerGroup = 2;

    /// <summary>
    /// <b>RULING - the ADS zoom multiplier</b> Cranberry writes into <c>rec+0x128</c>
    /// (<c>DEFAULT_ZOOM</c> / <c>FireMode.DefaultZoom</c>) on the iron-sights mode of an
    /// ARMED fire group. <c>1.0f</c> is the client's own preset and means "no zoom".
    /// <para>
    /// The mechanism is [P] - <c>FUN_141488490</c> reads that offset under the key whose
    /// initialiser string is <c>"FireMode.DefaultZoom"</c> and <c>FUN_1411c8740</c>
    /// interpolates the character's <c>+0x55a4</c> toward it - but NO August sheet carries a
    /// zoom column, so the number is Cranberry's: the midpoint of the <c>(1.0, 2.0]</c> band
    /// the client itself uses to choose <c>ADSMouseSensitivity</c> over
    /// <c>scopedMouseSensitivity</c> (<c>_DAT_143275150 = 2.0f</c> in <c>FUN_140e40090</c>
    /// and <c>FUN_140e4a010</c>). <c>CRANBERRY_WEAPON_ADS_ZOOM</c> overrides it and
    /// <c>CRANBERRY_WEAPON_ADS_FOV=0</c> reverts every mode to <c>1.0f</c>.
    /// </para>
    /// </summary>
    public const float AdsZoom = 1.2f;

    /// <summary>
    /// <b>RULING - the ADS FIRST-PERSON switch.</b> <c>FORCE_FP_SCOPE</c>
    /// (<c>rec+0x2dc</c>) on the PRIMARY mode of an ARMED fire group. [P]:
    /// <c>FUN_14158ad50:17</c> reads that byte off the LIVE fire-mode record and
    /// <c>FUN_14158b700</c> - the <c>Infantry</c> / <c>SecondaryFire</c> handler, bound to
    /// <c>Mouse_1</c> as <c>UI.WeaponOptic</c> - branches on it: set, it calls
    /// <c>FUN_14158ab50</c>, which switches the camera to <c>0x1e</c> (first person) while
    /// the button is held and back to <c>0x24</c> on release; clear, it calls the aim
    /// vtable slot <c>+0x370</c> instead, which is the <c>82 0c SwitchFireModeRequest</c>
    /// path. The two are EXCLUSIVE (<c>14158bb2d JZ 14158bc1f</c>), so this suppresses the
    /// iron-sights mode - and with it <see cref="AdsZoom"/> - while it is on.
    /// </summary>
    public const bool AdsFirstPerson = false;

    /// <summary>
    /// <b>RULING - the aimed first-person field of view, in DEGREES</b>, for
    /// <c>FP_CAMERA_FOV</c> / <c>FP_CR_CAMERA_FOV</c> / <c>FP_PR_CAMERA_FOV</c>
    /// (<c>rec+0x2d0</c>, <c>+0x2d4</c>, <c>+0x2d8</c>) behind the gate
    /// <c>FP_FORCE_CAMERA_OVERRIDES</c> (<c>rec+0x2cd</c>) that <c>FUN_140e3fff0</c> tests.
    /// With <see cref="AdsFirstPerson"/> on this is the ONLY field of view the aimed
    /// view has. The number is the client's own default vertical FOV - <c>65</c>, the
    /// default <c>FUN_1413a3e30:233-236</c> hands the <c>[Rendering] VerticalFOV</c> ini
    /// read, whose clamp maximum there is <c>74</c> - over <see cref="AdsZoom"/>.
    /// <c>CRANBERRY_WEAPON_ADS_FP_FOV=0</c> clears the gate.
    /// </summary>
    public const float AdsFpCameraFov = 54.1667f;

    /// <summary>
    /// <b>ADOPTED under D53</b> from the owner's own Z1
    /// (<c>C:\Z1\Server\Zone\ZoneWeaponDefinitions.cs:1358-1361</c>): the aim-in and
    /// aim-out times, in ms, for <c>Weapon.ToIronSightsTime</c> (<c>def+0x38</c>) and
    /// <c>Weapon.FromIronSightsTime</c> (<c>def+0x3c</c>), which <c>FUN_1422935d0:70-76</c>
    /// takes when the mode switch is not silent. <c>0</c> means instant.
    /// </summary>
    public const int IronSightsTimeMs = 266;

    /// <summary>Every mode, in (fire group, mode index) order.</summary>
    public static IReadOnlyList<AugustFireModeFact> All => Rows;

    /// <summary>Lookup by fire-mode id.</summary>
    public static bool TryGet(uint fireModeId, out AugustFireModeFact fact) =>
        ByModeId.TryGetValue(fireModeId, out fact);

    private static readonly AugustFireModeFact[] Rows =
    [
        new(4u, 2u, 0, 2u, 4u, 200, 1700, 7, false, 0, 2u),
        new(5u, 2u, 1, 2u, 5u, 200, 1700, 7, true, 0, 2u),
        new(6u, 3u, 0, 3u, 6u, 500, 3200, 1, false, 0, 3u),
        new(7u, 3u, 1, 3u, 7u, 500, 3200, 1, true, 0, 3u),
        new(8u, 4u, 0, 4u, 8u, 500, 3200, 1, false, 0, 4u),
        new(9u, 4u, 1, 4u, 9u, 500, 3200, 1, true, 0, 4u),
        new(10u, 5u, 0, 5u, 10u, 500, 3200, 1, false, 0, 0u),
        new(11u, 5u, 1, 5u, 11u, 500, 3200, 1, true, 0, 0u),
        new(12u, 6u, 0, 10u, 12u, 120, 2800, 30, false, 0, 6u),
        new(13u, 6u, 1, 10u, 13u, 120, 2800, 30, true, 0, 6u),
        new(14u, 7u, 0, 14u, 14u, 150, 950, 1, false, 0, 7u),
        new(15u, 7u, 1, 14u, 15u, 150, 950, 1, true, 0, 7u),
        new(16u, 8u, 0, 58u, 16u, 25, 3200, 1, false, 0, 0u),
        new(17u, 8u, 1, 58u, 17u, 25, 3200, 1, true, 0, 0u),
        new(18u, 9u, 0, 82u, 18u, 250, 3200, 0, false, 0, 0u),
        new(19u, 9u, 1, 82u, 19u, 250, 3200, 0, true, 0, 0u),
        new(20u, 10u, 0, 83u, 20u, 450, 3200, 0, false, 0, 0u),
        new(21u, 10u, 1, 83u, 21u, 450, 3200, 0, true, 0, 0u),
        new(22u, 11u, 0, 84u, 22u, 125, 3200, 0, false, 0, 0u),
        new(23u, 11u, 1, 84u, 23u, 125, 3200, 0, true, 0, 0u),
        new(24u, 12u, 0, 85u, 24u, 500, 3200, 0, false, 0, 12u),
        new(25u, 12u, 1, 85u, 25u, 500, 3200, 0, true, 0, 12u),
        new(26u, 13u, 0, 119u, 26u, 250, 3200, 1, false, 0, 13u),
        new(27u, 13u, 1, 119u, 27u, 250, 3200, 1, true, 0, 13u),
        new(28u, 14u, 0, 113u, 28u, 75, 1700, 1, false, 0, 14u),
        new(29u, 14u, 1, 113u, 29u, 75, 1700, 1, true, 0, 14u),
        new(30u, 15u, 0, 1373u, 30u, 1800, 2400, 5, false, 0, 15u),
        new(31u, 15u, 1, 1373u, 31u, 1800, 2400, 5, true, 0, 15u),
        new(32u, 16u, 0, 1374u, 32u, 750, 800, 6, false, 0, 16u),
        new(33u, 16u, 1, 1374u, 33u, 750, 800, 6, true, 0, 16u),
        new(34u, 17u, 0, 1380u, 34u, 75, 3200, 0, false, 0, 17u),
        new(35u, 17u, 1, 1380u, 35u, 75, 3200, 0, true, 0, 17u),
        new(36u, 18u, 0, 1382u, 36u, 75, 1700, 1, false, 0, 18u),
        new(37u, 18u, 1, 1382u, 37u, 75, 1700, 1, true, 0, 18u),
        new(38u, 19u, 0, 100u, 38u, 75, 100, 9999999, false, 0, 19u),
        new(39u, 19u, 1, 100u, 39u, 75, 100, 9999999, true, 0, 19u),
        new(42u, 21u, 0, 1542u, 42u, 75, 3200, 0, false, 0, 0u),
        new(43u, 21u, 1, 1542u, 43u, 75, 3200, 0, true, 0, 0u),
        new(44u, 22u, 0, 1695u, 44u, 75, 3200, 0, false, 0, 0u),
        new(45u, 22u, 1, 1695u, 45u, 75, 3200, 0, true, 0, 0u),
        new(46u, 23u, 0, 1707u, 46u, 25, 3200, 0, false, 0, 23u),
        new(47u, 23u, 1, 1707u, 47u, 25, 3200, 0, true, 0, 23u),
        new(48u, 24u, 0, 1708u, 48u, 500, 3200, 0, false, 0, 24u),
        new(49u, 24u, 1, 1708u, 49u, 500, 3200, 0, true, 0, 24u),
        new(50u, 25u, 0, 1710u, 50u, 75, 1700, 1, false, 0, 0u),
        new(51u, 25u, 1, 1710u, 51u, 75, 1700, 1, true, 0, 0u),
        new(52u, 26u, 0, 1716u, 52u, 75, 1700, 1, false, 0, 0u),
        new(53u, 26u, 1, 1716u, 53u, 75, 1700, 1, true, 0, 0u),
        new(54u, 27u, 0, 1718u, 54u, 450, 1700, 6, false, 0, 0u),
        new(55u, 27u, 1, 1718u, 55u, 450, 1700, 6, true, 0, 0u),
        new(56u, 28u, 0, 1725u, 56u, 500, 3200, 0, false, 0, 0u),
        new(57u, 28u, 1, 1725u, 57u, 500, 3200, 0, true, 0, 0u),
        new(58u, 29u, 0, 1737u, 58u, 500, 3200, 0, false, 0, 0u),
        new(59u, 29u, 1, 1737u, 59u, 500, 3200, 0, true, 0, 0u),
        new(62u, 31u, 0, 1733u, 62u, 1, 3200, 0, false, 0, 0u),
        new(63u, 31u, 1, 1733u, 63u, 1, 3200, 0, true, 0, 0u),
        new(64u, 32u, 0, 1442u, 64u, 25, 3200, 0, false, 0, 0u),
        new(65u, 32u, 1, 1442u, 65u, 25, 3200, 0, true, 0, 0u),
        new(66u, 33u, 0, 1448u, 66u, 25, 3200, 0, false, 0, 0u),
        new(67u, 33u, 1, 1448u, 67u, 25, 3200, 0, true, 0, 0u),
        new(68u, 34u, 0, 1536u, 68u, 500, 3200, 0, false, 0, 0u),
        new(69u, 34u, 1, 1536u, 69u, 500, 3200, 0, true, 0, 0u),
        new(70u, 35u, 0, 1776u, 70u, 20, 1700, 999, false, 0, 0u),
        new(71u, 35u, 1, 1776u, 71u, 20, 1700, 999, true, 0, 0u),
        new(72u, 36u, 0, 1903u, 72u, 25, 3200, 0, false, 0, 0u),
        new(73u, 36u, 1, 1903u, 73u, 25, 3200, 0, true, 0, 0u),
        new(74u, 37u, 0, 1986u, 74u, 75, 1700, 1, false, 0, 0u),
        new(75u, 37u, 1, 1986u, 75u, 75, 1700, 1, true, 0, 0u),
        new(76u, 38u, 0, 1991u, 76u, 135, 1700, 7, false, 0, 0u),
        new(77u, 38u, 1, 1991u, 77u, 135, 1700, 7, true, 0, 0u),
        new(78u, 39u, 0, 1997u, 78u, 150, 1700, 15, false, 0, 0u),
        new(79u, 39u, 1, 1997u, 79u, 150, 1700, 15, true, 0, 0u),
        new(84u, 42u, 0, 2235u, 84u, 150, 950, 1, false, 0, 0u),
        new(85u, 42u, 1, 2235u, 85u, 150, 950, 1, true, 0, 0u),
        new(86u, 43u, 0, 2236u, 86u, 150, 950, 1, false, 0, 0u),
        new(87u, 43u, 1, 2236u, 87u, 150, 950, 1, true, 0, 0u),
        new(88u, 44u, 0, 2237u, 88u, 150, 950, 1, false, 0, 0u),
        new(89u, 44u, 1, 2237u, 89u, 150, 950, 1, true, 0, 0u),
        new(92u, 46u, 0, 2246u, 92u, 500, 2500, 1, false, 0, 0u),
        new(93u, 46u, 1, 2246u, 93u, 500, 2500, 1, true, 0, 0u),
        new(94u, 47u, 0, 1538u, 94u, 25, 3200, 0, false, 0, 0u),
        new(95u, 47u, 1, 1538u, 95u, 25, 3200, 0, true, 0, 0u),
        new(98u, 49u, 0, 2268u, 98u, 75, 1700, 1, false, 0, 0u),
        new(99u, 49u, 1, 2268u, 99u, 75, 1700, 1, true, 0, 0u),
        new(102u, 51u, 0, 2229u, 102u, 160, 3900, 30, false, 0, 0u),
        new(103u, 51u, 1, 2229u, 103u, 160, 3900, 30, true, 0, 0u),
        new(110u, 55u, 0, 1778u, 110u, 0, 0, 1, false, 0, 0u),
        new(111u, 55u, 1, 1778u, 111u, 0, 0, 1, true, 0, 0u),
        new(132u, 66u, 0, 1743u, 132u, 25, 1, 0, false, 0, 0u),
        new(133u, 66u, 1, 1743u, 133u, 25, 1, 0, true, 0, 0u),
        new(136u, 68u, 0, 1717u, 136u, 25, 1, 0, false, 0, 0u),
        new(137u, 68u, 1, 1717u, 137u, 25, 1, 0, true, 0, 0u),
        new(150u, 75u, 0, 2379u, 150u, 25, 3200, 1, false, 0, 0u),
        new(151u, 75u, 1, 2379u, 151u, 25, 3200, 1, true, 0, 0u),
        new(152u, 76u, 0, 2380u, 152u, 100, 0, 999, false, 0, 0u),
        new(153u, 76u, 1, 2380u, 153u, 100, 0, 999, true, 0, 0u),
        new(154u, 77u, 0, 2399u, 154u, 160, 3900, 30, false, 0, 0u),
        new(155u, 77u, 1, 2399u, 155u, 160, 3900, 30, true, 0, 0u),
        new(158u, 79u, 0, 2416u, 158u, 100, 1125, 1, false, 0, 0u),
        new(159u, 79u, 1, 2416u, 159u, 100, 1125, 1, true, 0, 0u),
        new(162u, 81u, 0, 1889u, 162u, 120, 2800, 30, false, 0, 0u),
        new(163u, 81u, 1, 1889u, 163u, 120, 2800, 30, true, 0, 0u),
        new(164u, 82u, 0, 2712u, 164u, 120, 3900, 30, false, 0, 0u),
        new(165u, 82u, 1, 2712u, 165u, 120, 3900, 30, true, 0, 0u),
        new(170u, 85u, 0, 2859u, 170u, 120, 2800, 30, false, 0, 0u),
        new(171u, 85u, 1, 2859u, 171u, 120, 2800, 30, true, 0, 0u),
        new(172u, 86u, 0, 2961u, 172u, 450, 3200, 0, false, 0, 0u),
        new(173u, 86u, 1, 2961u, 173u, 450, 3200, 0, true, 0, 0u),
        new(174u, 87u, 0, 3039u, 174u, 1450, 850, 1, false, 0, 0u),
        new(175u, 87u, 1, 3039u, 175u, 1450, 850, 1, true, 0, 0u),
        new(176u, 88u, 0, 3022u, 176u, 150, 950, 1, false, 0, 0u),
        new(177u, 88u, 1, 3022u, 177u, 150, 950, 1, true, 0, 0u),
        new(178u, 89u, 0, 3061u, 178u, 25, 3200, 0, false, 0, 0u),
        new(179u, 89u, 1, 3061u, 179u, 25, 3200, 0, true, 0, 0u),
        new(180u, 90u, 0, 200u, 180u, 135, 100, 9999, false, 0, 0u),
        new(181u, 90u, 1, 200u, 181u, 135, 100, 9999, true, 0, 0u),
        new(182u, 91u, 0, 3062u, 182u, 5025, 5200, 1, false, 0, 0u),
        new(183u, 91u, 1, 3062u, 183u, 5025, 5200, 1, true, 0, 0u),
        new(184u, 92u, 0, 3066u, 184u, 120, 2800, 30, false, 0, 0u),
        new(185u, 92u, 1, 3066u, 185u, 120, 2800, 30, true, 0, 0u),
    ];

    private static readonly FrozenDictionary<uint, AugustFireModeFact> ByModeId =
        Rows.ToFrozenDictionary(row => row.FireModeId);
}
