// <cranberry-provenance>
// Written by tools/pipeline/pipeline.py (docs/96). `pipeline.py check` recomputes every
// hash below and fails the build when one has moved; do not edit this block by hand.
// id: weapon-firegroups
// grade: CLIENT
// clientBuild: 0.0.118.208059
// generator: tools/data/gen-weapon-firegroups.py sha256=dd580d63cec498df965cc0e8108da86155ba879069a57535be79001d2597d9fd
// input: out/data_aug/derived/weapons.json sha256=47e291d088242274dbb38f0b544040c0f33b7d0331ff8f6a8cb60feaa66203b1 crc32=7856763c size=570305 grade=CLIENT
// rulings: D46, D94
// generatedUtc: 2026-09-04T07:05:31Z
// </cranberry-provenance>
// <auto-generated>
// Generated by tools/data/gen-weapon-firegroups.py from the August client's own datasheet
// out\data_aug\ClientItemDatasheetData.txt (build 0.0.118.208059). Do not edit by hand;
// re-run the generator instead. Derivation and citations: docs/60-weapon-firegroups.md.
// </auto-generated>

#nullable enable

using System.Collections.Frozen;

namespace Cranberry.Zone.Weapons;

/// <summary>
/// One row of <c>ClientItemDatasheetData.txt</c> - the client's own per-item weapon numbers.
/// The header is
/// <c>ITEM_ID^DATASHEET_ID^WEAPON_ID^FIRE_GROUP_ID^DIRECT_DAMAGE^INDIRECT_DAMAGE^DAMAGE_FALLOFF^
/// REFIRE_TIME_MS^RELOAD_TIME_MS^CLIP_SIZE^RANGE_STRING_ID^MIN_CONE_OF_FIRE^</c>; the six columns
/// kept here are the ones the fire-group wire needs. <b>Every value is EXTRACTED</b> - nothing in
/// this file is a Cranberry design choice.
/// </summary>
/// <param name="ItemId"><c>ITEM_ID</c> - a <c>ClientItemDefinitions</c> row id.</param>
/// <param name="WeaponId">
/// <c>WEAPON_ID</c>. Equal to the item row's <c>PARAM1</c> on every weapon checked, which is the
/// id <c>ClientPlayerItemManager::CreateItem</c> hashes into the weapon-definition manager
/// (docs/58 §2 step 10). <c>AugustWeaponFactsTests</c> pins that equality across the whole sheet.
/// </param>
/// <param name="FireGroupId">
/// <c>FIRE_GROUP_ID</c> - the key of the <c>WeaponDefinitions</c> list-1 record the crash site
/// dereferences (docs/58 §4c). <b>0 means the sheet names no fire group</b>; such an item can
/// never be cleared for the active hand.
/// </param>
/// <param name="RefireTimeMs"><c>REFIRE_TIME_MS</c>.</param>
/// <param name="ReloadTimeMs"><c>RELOAD_TIME_MS</c>.</param>
/// <param name="ClipSize"><c>CLIP_SIZE</c>. 0 on melee rows and on the fists (item 85).</param>
public readonly record struct AugustWeaponFact(
    uint ItemId,
    uint WeaponId,
    uint FireGroupId,
    int RefireTimeMs,
    int ReloadTimeMs,
    int ClipSize);

/// <summary>
/// All 160 rows of <c>ClientItemDatasheetData.txt</c>, keyed by item definition id, plus the 60
/// distinct non-zero fire-group ids they name.
/// </summary>
public static class AugustWeaponFacts
{
    /// <summary>Every row, in item-id order.</summary>
    public static IReadOnlyList<AugustWeaponFact> All => Rows;

    /// <summary>
    /// The distinct non-zero <c>FIRE_GROUP_ID</c>s, ascending. This is exactly the set of records
    /// the <c>WeaponDefinitions</c> list-1 table must carry for every weapon in the client's own
    /// data to resolve.
    /// </summary>
    public static IReadOnlyList<uint> FireGroupIds => Groups;

    /// <summary>Look one item up. A definition id the sheet does not carry is not an error.</summary>
    public static bool TryGet(uint itemDefinitionId, out AugustWeaponFact fact) =>
        ById.TryGetValue(itemDefinitionId, out fact);

    // Rows is declared before ById: static field initialisers run in declaration order.
    private static readonly AugustWeaponFact[] Rows =
    [
        new(2u, 2u, 2u, 200, 1700, 7),
        new(3u, 3u, 3u, 500, 3200, 1),
        new(4u, 4u, 4u, 500, 3200, 1),
        new(5u, 5u, 5u, 500, 3200, 1),
        new(10u, 6u, 6u, 120, 2800, 30),
        new(14u, 7u, 7u, 150, 950, 1),
        new(49u, 3u, 3u, 500, 3200, 1),
        new(58u, 8u, 8u, 25, 3200, 1),
        new(65u, 1404u, 0u, 0, 0, 1),
        new(66u, 1429u, 0u, 0, 0, 1),
        new(67u, 6u, 6u, 120, 2800, 30),
        new(68u, 6u, 6u, 120, 2800, 30),
        new(82u, 9u, 9u, 250, 3200, 0),
        new(83u, 10u, 10u, 450, 3200, 0),
        new(84u, 11u, 11u, 125, 3200, 0),
        new(85u, 12u, 12u, 500, 3200, 0),
        new(100u, 1383u, 19u, 75, 100, 9999999),
        new(113u, 113u, 14u, 75, 1700, 1),
        new(119u, 119u, 13u, 250, 3200, 1),
        new(200u, 1440u, 90u, 135, 100, 9999),
        new(1337u, 1337u, 2u, 200, 1700, 50000000),
        new(1367u, 5u, 5u, 500, 3200, 1),
        new(1373u, 1373u, 15u, 1800, 2400, 5),
        new(1374u, 1374u, 16u, 750, 800, 6),
        new(1380u, 1375u, 17u, 75, 3200, 0),
        new(1382u, 1382u, 18u, 75, 1700, 1),
        new(1389u, 5u, 5u, 500, 3200, 1),
        new(1442u, 1394u, 32u, 25, 3200, 0),
        new(1448u, 1395u, 33u, 25, 3200, 0),
        new(1530u, 1375u, 17u, 75, 3200, 0),
        new(1536u, 1396u, 34u, 500, 3200, 0),
        new(1538u, 1415u, 47u, 25, 3200, 0),
        new(1542u, 1384u, 21u, 75, 3200, 0),
        new(1695u, 1385u, 22u, 75, 3200, 0),
        new(1702u, 2u, 2u, 200, 1700, 7),
        new(1707u, 13u, 23u, 25, 3200, 0),
        new(1708u, 14u, 24u, 500, 3200, 0),
        new(1710u, 1386u, 25u, 75, 1700, 1),
        new(1716u, 1387u, 26u, 75, 1700, 1),
        new(1717u, 1419u, 68u, 25, 1, 0),
        new(1718u, 1388u, 27u, 450, 1700, 6),
        new(1720u, 1387u, 26u, 75, 1700, 1),
        new(1721u, 1394u, 32u, 25, 3200, 0),
        new(1724u, 1394u, 32u, 25, 3200, 0),
        new(1725u, 1389u, 28u, 500, 3200, 0),
        new(1727u, 1395u, 33u, 25, 3200, 0),
        new(1733u, 1393u, 31u, 1, 3200, 0),
        new(1734u, 1374u, 16u, 750, 800, 6),
        new(1737u, 1391u, 29u, 500, 3200, 0),
        new(1738u, 1402u, 0u, 0, 0, 0),
        new(1739u, 10u, 10u, 450, 3200, 0),
        new(1741u, 1375u, 17u, 75, 3200, 0),
        new(1743u, 1418u, 66u, 25, 1, 0),
        new(1745u, 8u, 8u, 25, 3200, 1),
        new(1747u, 14u, 24u, 500, 3200, 0),
        new(1776u, 1397u, 35u, 20, 1700, 999),
        new(1778u, 1403u, 55u, 0, 0, 1),
        new(1889u, 1431u, 81u, 120, 2800, 30),
        new(1899u, 1373u, 15u, 1800, 2400, 5),
        new(1901u, 2u, 2u, 200, 1700, 7),
        new(1902u, 113u, 14u, 75, 1700, 1),
        new(1903u, 1398u, 36u, 25, 3200, 0),
        new(1986u, 1399u, 37u, 75, 1700, 1),
        new(1991u, 1400u, 38u, 135, 1700, 7),
        new(1997u, 1401u, 39u, 150, 1700, 15),
        new(2202u, 1403u, 55u, 0, 0, 1),
        new(2228u, 10u, 10u, 450, 3200, 0),
        new(2229u, 1405u, 51u, 160, 3900, 30),
        new(2230u, 1406u, 0u, 0, 0, 0),
        new(2231u, 1407u, 0u, 0, 0, 0),
        new(2232u, 1409u, 0u, 0, 0, 0),
        new(2233u, 1408u, 0u, 0, 0, 0),
        new(2235u, 1410u, 42u, 150, 950, 1),
        new(2236u, 1411u, 43u, 150, 950, 1),
        new(2237u, 1412u, 44u, 150, 950, 1),
        new(2239u, 6u, 6u, 120, 2800, 30),
        new(2243u, 1413u, 0u, 0, 0, 1),
        new(2246u, 1414u, 46u, 500, 2500, 1),
        new(2268u, 1416u, 49u, 75, 1700, 1),
        new(2357u, 1403u, 55u, 0, 0, 1),
        new(2358u, 1403u, 55u, 0, 0, 1),
        new(2359u, 1403u, 55u, 0, 0, 1),
        new(2360u, 1403u, 55u, 0, 0, 1),
        new(2379u, 1422u, 75u, 25, 3200, 1),
        new(2380u, 1423u, 76u, 100, 0, 999),
        new(2399u, 1424u, 77u, 160, 3900, 30),
        new(2416u, 1425u, 79u, 100, 1125, 1),
        new(2422u, 1423u, 76u, 100, 0, 999),
        new(2425u, 6u, 6u, 120, 2800, 30),
        new(2446u, 1374u, 16u, 750, 800, 6),
        new(2480u, 1405u, 51u, 160, 3900, 30),
        new(2483u, 1424u, 77u, 160, 3900, 30),
        new(2494u, 11u, 11u, 125, 3200, 0),
        new(2586u, 1374u, 16u, 750, 800, 6),
        new(2592u, 6u, 6u, 120, 2800, 30),
        new(2593u, 6u, 6u, 120, 2800, 30),
        new(2597u, 1374u, 16u, 750, 800, 6),
        new(2600u, 1405u, 51u, 160, 3900, 30),
        new(2601u, 6u, 6u, 120, 2800, 30),
        new(2661u, 1405u, 51u, 160, 3900, 30),
        new(2662u, 1405u, 51u, 160, 3900, 30),
        new(2663u, 1374u, 16u, 750, 800, 6),
        new(2664u, 1374u, 16u, 750, 800, 6),
        new(2665u, 6u, 6u, 120, 2800, 30),
        new(2666u, 6u, 6u, 120, 2800, 30),
        new(2712u, 1432u, 82u, 120, 3900, 30),
        new(2731u, 1433u, 0u, 0, 0, 6),
        new(2751u, 1434u, 0u, 0, 0, 21),
        new(2781u, 6u, 6u, 120, 2800, 30),
        new(2788u, 6u, 6u, 120, 2800, 30),
        new(2789u, 6u, 6u, 120, 2800, 30),
        new(2834u, 6u, 6u, 120, 2800, 30),
        new(2835u, 6u, 6u, 120, 2800, 30),
        new(2859u, 1435u, 85u, 120, 2800, 30),
        new(2900u, 1373u, 15u, 1800, 2400, 5),
        new(2901u, 1373u, 15u, 1800, 2400, 5),
        new(2902u, 1373u, 15u, 1800, 2400, 5),
        new(2906u, 1373u, 15u, 1800, 2400, 5),
        new(2907u, 1373u, 15u, 1800, 2400, 5),
        new(2908u, 1373u, 15u, 1800, 2400, 5),
        new(2909u, 1373u, 15u, 1800, 2400, 5),
        new(2961u, 1436u, 86u, 450, 3200, 0),
        new(2962u, 1436u, 86u, 450, 3200, 0),
        new(2963u, 1436u, 86u, 450, 3200, 0),
        new(2964u, 1436u, 86u, 450, 3200, 0),
        new(2965u, 1436u, 86u, 450, 3200, 0),
        new(2977u, 5u, 5u, 500, 3200, 1),
        new(2978u, 5u, 5u, 500, 3200, 1),
        new(2979u, 5u, 5u, 500, 3200, 1),
        new(2981u, 5u, 5u, 500, 3200, 1),
        new(2982u, 5u, 5u, 500, 3200, 1),
        new(2983u, 5u, 5u, 500, 3200, 1),
        new(2984u, 5u, 5u, 500, 3200, 1),
        new(2985u, 5u, 5u, 500, 3200, 1),
        new(2986u, 5u, 5u, 500, 3200, 1),
        new(3010u, 5u, 5u, 500, 3200, 1),
        new(3011u, 5u, 5u, 500, 3200, 1),
        new(3012u, 5u, 5u, 500, 3200, 1),
        new(3013u, 5u, 5u, 500, 3200, 1),
        new(3014u, 5u, 5u, 500, 3200, 1),
        new(3015u, 5u, 5u, 500, 3200, 1),
        new(3016u, 5u, 5u, 500, 3200, 1),
        new(3017u, 5u, 5u, 500, 3200, 1),
        new(3018u, 5u, 5u, 500, 3200, 1),
        new(3019u, 5u, 5u, 500, 3200, 1),
        new(3020u, 5u, 5u, 500, 3200, 1),
        new(3021u, 5u, 5u, 500, 3200, 1),
        new(3022u, 1438u, 88u, 150, 950, 1),
        new(3039u, 1437u, 87u, 1450, 850, 1),
        new(3055u, 1405u, 51u, 160, 3900, 30),
        new(3056u, 6u, 6u, 120, 2800, 30),
        new(3057u, 1374u, 16u, 750, 800, 6),
        new(3061u, 1439u, 89u, 25, 3200, 0),
        new(3062u, 1441u, 91u, 5025, 5200, 1),
        new(3066u, 1442u, 92u, 120, 2800, 30),
        new(3123u, 1374u, 16u, 750, 800, 6),
        new(3165u, 1374u, 16u, 750, 800, 6),
        new(3172u, 1373u, 15u, 1800, 2400, 5),
        new(3179u, 6u, 6u, 120, 2800, 30),
        new(3213u, 1399u, 37u, 75, 1700, 1),
    ];

    private static readonly uint[] Groups =
    [
        2u, 3u, 4u, 5u, 6u, 7u, 8u, 9u, 10u, 11u, 12u, 13u,
        14u, 15u, 16u, 17u, 18u, 19u, 21u, 22u, 23u, 24u, 25u, 26u,
        27u, 28u, 29u, 31u, 32u, 33u, 34u, 35u, 36u, 37u, 38u, 39u,
        42u, 43u, 44u, 46u, 47u, 49u, 51u, 55u, 66u, 68u, 75u, 76u,
        77u, 79u, 81u, 82u, 85u, 86u, 87u, 88u, 89u, 90u, 91u, 92u,
    ];

    private static readonly FrozenDictionary<uint, AugustWeaponFact> ById =
        Rows.ToFrozenDictionary(row => row.ItemId);
}
