// <cranberry-provenance>
// Written by tools/pipeline/pipeline.py (docs/96). `pipeline.py check` recomputes every
// hash below and fails the build when one has moved; do not edit this block by hand.
// id: weapon-lists
// grade: CLIENT+RULING
// clientBuild: 0.0.118.208059
// generator: tools/data/gen-weapon-lists.py sha256=c3c4b1e2ce16dd27bd7a711701a536ab9b5841ecdae2cca7dd3696e0e66ffbcb
// input: out/data_aug/derived/weapon-lists.json sha256=607d3680384ec715f14b585c2629a2bc0bf1efc32b0d13ccc7d324fc2f96aa0b crc32=e338ebb0 size=35925 grade=CLIENT
// rulings: D143, D159, D212, D230, D231, D232, D233, D234
// generatedUtc: 2026-09-04T07:05:31Z
// </cranberry-provenance>
// <auto-generated>
// Generated by tools/data/gen-weapon-lists.py from the August client's own datasheets
// (build 0.0.118.208059), read through out\data_aug\derived\weapon-lists.json. Do not
// edit by hand; re-run the generator instead. Derivation: docs/99-weapon-lists.md.
// </auto-generated>

#nullable enable

namespace Cranberry.Zone.Weapons;

/// <summary>
/// The projectile ids the August client's own <c>ProjectileToPenTypes.txt</c> names, and the
/// penetration type each maps to.
/// <para>
/// These are the keys <c>ReferenceData "ProjectileDefinitions"</c> is built on. Nothing here
/// is invented: the client's data names these ids. What the client's data does <b>not</b>
/// carry is the 55-column definition body, which is why that table ships off by default
/// (<c>WeaponStageOptions.SendProjectileDefinitions</c>, docs/99 section 4.3).
/// </para>
/// </summary>
/// <param name="ProjectileId"><c>PROJECTILE_ID</c>.</param>
/// <param name="PenTypeId"><c>PEN_TYPE_ID</c>.</param>
/// <param name="PenTypeName"><c>PenTypes.DESCRIPTION</c> for that id.</param>
public readonly record struct AugustProjectileFact(
    uint ProjectileId,
    int PenTypeId,
    string PenTypeName);

/// <summary>
/// All 14 rows of <c>ProjectileToPenTypes.txt</c>, in ascending projectile-id order.
/// </summary>
public static class AugustProjectileFacts
{
    /// <summary>Every row.</summary>
    public static IReadOnlyList<AugustProjectileFact> All => Rows;

    /// <summary>Just the ids, ascending.</summary>
    public static IReadOnlyList<uint> ProjectileIds => Ids;

    private static readonly AugustProjectileFact[] Rows =
    [
        new(19000u, 5, ".45 ACP"),
        new(19002u, 3, ".223"),
        new(70038u, 2, "MetalTippedHandmadeArrow"),
        new(70039u, 1, "MetalTippedLargeWoodSpear"),
        new(70040u, 4, "12GA shotgun"),
        new(70041u, 8, ".308 FMJ"),
        new(70046u, 2, "MetalTippedHandmadeArrow"),
        new(70047u, 6, ".44 Magnum"),
        new(70053u, 7, ".380"),
        new(70054u, 2, "MetalTippedHandmadeArrow"),
        new(70055u, 9, ".9mm"),
        new(70061u, 2, "MetalTippedHandmadeArrow"),
        new(70063u, 10, "Rifle.AK47.762Bullet"),
        new(70075u, 2, "MetalTippedHandmadeArrow"),
    ];

    private static readonly uint[] Ids =
    [
        19000u, 19002u, 70038u, 70039u, 70040u, 70041u,
        70046u, 70047u, 70053u, 70054u, 70055u, 70061u,
        70063u, 70075u,
    ];
}
