// <cranberry-provenance>
// Written by tools/pipeline/pipeline.py (docs/96). `pipeline.py check` recomputes every
// hash below and fails the build when one has moved; do not edit this block by hand.
// id: authored-appearance
// grade: CLIENT+RULING
// clientBuild: 0.0.118.208059
// generator: tools/appearance/gen-authored-appearance.py sha256=e8326481883e1969144c9c013601423cb8d640caff9e7c77dd51be561c71548a
// input: out/data_aug/Models.txt sha256=1a7d89d3b84ccbdb0dc40c3351583116ddee801a3b365117447ec91b360b33c1 crc32=06ba7c27 size=95822 grade=CLIENT
// input: out/data_aug/TintSemanticTables.txt sha256=d4b43425b1eb7a2c683c2e4476f6dad4eab6582c498a11e8278b7bab60d7cda4 crc32=ae1c6d9e size=8335 grade=CLIENT
// input: out/data_aug/derived/loot.json sha256=8023e21b5f864e8d4b9e95e6e4f6dc9199e3a5a6543fad95ee2a828538cdae79 crc32=9d37015d size=2419885 grade=CLIENT
// input: out/data_aug/adr/SurvivorMale_Back_Backpack_Mansport_Tintable.adr sha256=c64d0f9943a98056bc0879f8dc6742bdf5b7065ab0d04c7a991d03dbc53efb68 crc32=f833b29f size=1875 grade=CLIENT
// input: out/data_aug/adr/SurvivorFemale_Back_Backpack_Mansport_Tintable.adr sha256=96af32446cd1057c55d2bd13152b3fc4cc29a45e8065fc741c1e707e98123a0b crc32=1d871e97 size=1894 grade=CLIENT
// input: out/data_aug/adr/SurvivorMale_Chest_Shirt_TintTshirt.adr sha256=56802da69ff5f47d3ddd302b9f2cef258c1b4c29e71a166a1528cc65a551900e crc32=71eb8bf1 size=1846 grade=CLIENT
// input: out/data_aug/adr/SurvivorFemale_Chest_Shirt_TintTshirt.adr sha256=02757365935cd7d12a0b875c27b5a119294c253882f54c23724eb91504648590 crc32=a604a5fc size=1906 grade=CLIENT
// input: out/data_aug/adr/SurvivorMale_Head_Helmet_Motorcycle_Tintable.adr sha256=dfceac7369df712e52c4465c65c0b7f7e2a18cec4eab93581d4e992dc5feebaa crc32=2465a8b4 size=2019 grade=CLIENT
// input: out/data_aug/adr/SurvivorFemale_Head_Helmet_Motorcycle_Tintable.adr sha256=c1f324d289cd692b48b046d4e4265c066116fe6c5a1f74067510603d14aeb6a7 crc32=d3e0a20f size=2023 grade=CLIENT
// input: out/data_aug/adr/SurvivorMale_Feet_Conveys_Tintable.adr sha256=584bf45943c25541cdf12d4353a59e0df36ac5b8e19b3449bdc103f0f5190ee4 crc32=37db4f5f size=1872 grade=CLIENT
// input: out/data_aug/adr/SurvivorFemale_Feet_Conveys_Tintable.adr sha256=981cf0332a48131c2b69203de19f247c1359a8f4874f02ddc89ab26e4c021045 crc32=80529d0f size=1870 grade=CLIENT
// input: out/appearance-tints/SurvivorMale_Back_Backpack_ManSport_C.dds sha256=28787b0443ee669fed877c44d5e16f107c901b1bc798a61723c9942645368eb8 crc32=faba19e7 size=174904 grade=CLIENT
// input: out/appearance-tints/SurvivorMale_Chest_Shirt_TintTshirt_Plain_C.dds sha256=1d2c56f337fb3a5e0b9ea90aa82a2e2f28c949e4171e1bf02ed24973701b538e crc32=e0ed3ff1 size=699192 grade=CLIENT
// input: out/appearance-tints/SurvivorMale_Head_Helmet_MotorCycleHelmet_C.dds sha256=94dba6ec3de383121d384943fc1ddfa5ba53ed4ee9e87a59f332b3ef7cfd7831 crc32=bac86389 size=174904 grade=CLIENT
// input: out/appearance-tints/SurvivorMale_Feet_Conveys_Tintable_C.dds sha256=e4c41368a6a895d06cf452771c2278b336a6d874e8c4f32138fddd93a53ca208 crc32=38a8693e size=174904 grade=CLIENT
// rulings: D22, D190, D203
// RULING: the HUE of each of the thirteen colourways (PALETTE in the generator) and the roster of
//     which item wears which mesh. The August client ships every one of these items' NAME - "Black
//     Backpack", "Green Backpack" - and no colourway at all, because the colourway was
//     server-authored in retail (docs/106 §5). D203 is the owner decision that Cranberry authors
//     its own rather than importing the capture's
// generatedUtc: 2026-09-04T07:05:35Z
// </cranberry-provenance>
// <auto-generated>
// Generated by tools/appearance/gen-authored-appearance.py. Do not edit.
//
// CRANBERRY-AUTHORED DynamicAppearance rows for the 13 ground-loot wearables the boot
// census reports as GREY. Nothing here is copied from the D22-gated capture or from any other
// server's table: the mesh, its model id and its gender are the August client's own Models.txt;
// the ramp SHAPE is measured off the mesh's own colour map by tools/appearance/ddstint.py; the
// HUE is Cranberry's reading of the item's own name in the client's locale (D203). Client build
// 0.0.118.208059.
//
// measured colour maps:
//   SurvivorMale_Back_Backpack_ManSport_C.dds  DXT1 512x512  mean RGB 79,78,78  near-white 0.0%  luminance p08/p50/p92 0.141/0.315/0.477
//     sha256 28787b0443ee669fed877c44d5e16f107c901b1bc798a61723c9942645368eb8
//   SurvivorMale_Chest_Shirt_TintTshirt_Plain_C.dds  DXT1 1024x1024  mean RGB 172,168,164  near-white 27.9%  luminance p08/p50/p92 0.450/0.701/0.811
//     sha256 1d2c56f337fb3a5e0b9ea90aa82a2e2f28c949e4171e1bf02ed24973701b538e
//   SurvivorMale_Head_Helmet_MotorCycleHelmet_C.dds  DXT1 512x512  mean RGB 189,189,189  near-white 65.9%  luminance p08/p50/p92 0.224/0.882/1.000
//     sha256 94dba6ec3de383121d384943fc1ddfa5ba53ed4ee9e87a59f332b3ef7cfd7831
//   SurvivorMale_Feet_Conveys_Tintable_C.dds  DXT1 512x512  mean RGB 147,142,139  near-white 14.5%  luminance p08/p50/p92 0.260/0.543/0.784
//     sha256 e4c41368a6a895d06cf452771c2278b336a6d874e8c4f32138fddd93a53ca208
// </auto-generated>

#nullable enable

using System.Collections.Immutable;
using System.Numerics;

namespace Cranberry.Zone.Appearance;

/// <summary>
/// One Cranberry-authored appearance row: the same five fields
/// <see cref="AugustAppearanceRow"/> carries, before it reaches the wire.
/// </summary>
/// <param name="RowId">Cranberry's own row id (0x43525200 + ordinal); it can collide with no captured id.</param>
/// <param name="ItemDefinitionId">The item this row dresses.</param>
/// <param name="ModelId">A <c>Models.txt</c> row - the client's own id for the worn mesh.</param>
/// <param name="GenderId">1 male, 2 female - the <c>GENDER</c> column of that same row.</param>
/// <param name="ShaderParameterGroupId">Cranberry's own colourway (0x43524210 + ordinal).</param>
public readonly record struct AugustAuthoredAppearanceRow(
    uint RowId,
    uint ItemDefinitionId,
    uint ModelId,
    uint GenderId,
    uint ShaderParameterGroupId);

/// <summary>
/// The authored rows and their shader parameters, added to the transmitted appearance table when
/// <c>CRANBERRY_APPEARANCE_AUTHORED_ROWS</c> is on (the default).
/// </summary>
public static class AugustAuthoredAppearance
{
    /// <summary>The 13 items the boot census names, in ascending id order.</summary>
    public static readonly ImmutableArray<uint> Items = [2112, 2113, 2115, 2117, 2127, 2137, 2139, 2141, 2142, 2145, 2168, 2171, 2218];

    /// <summary>Two rows per item - one per body - in ascending row id.</summary>
    public static readonly ImmutableArray<AugustAuthoredAppearanceRow> Rows =
    [
        // 2112 Black Backpack - SurvivorMale_Back_Backpack_Mansport_Tintable.adr
        new(0x43525200, 2112, 10031, 1, 0x43524210),
        // 2112 Black Backpack - SurvivorFemale_Back_Backpack_Mansport_Tintable.adr
        new(0x43525201, 2112, 10032, 2, 0x43524210),
        // 2113 Blue Backpack - SurvivorMale_Back_Backpack_Mansport_Tintable.adr
        new(0x43525202, 2113, 10031, 1, 0x43524211),
        // 2113 Blue Backpack - SurvivorFemale_Back_Backpack_Mansport_Tintable.adr
        new(0x43525203, 2113, 10032, 2, 0x43524211),
        // 2115 Green Backpack - SurvivorMale_Back_Backpack_Mansport_Tintable.adr
        new(0x43525204, 2115, 10031, 1, 0x43524212),
        // 2115 Green Backpack - SurvivorFemale_Back_Backpack_Mansport_Tintable.adr
        new(0x43525205, 2115, 10032, 2, 0x43524212),
        // 2117 Red Backpack - SurvivorMale_Back_Backpack_Mansport_Tintable.adr
        new(0x43525206, 2117, 10031, 1, 0x43524213),
        // 2117 Red Backpack - SurvivorFemale_Back_Backpack_Mansport_Tintable.adr
        new(0x43525207, 2117, 10032, 2, 0x43524213),
        // 2127 Green Army Shirt - SurvivorMale_Chest_Shirt_TintTshirt.adr
        new(0x43525208, 2127, 9525, 1, 0x43524214),
        // 2127 Green Army Shirt - SurvivorFemale_Chest_Shirt_TintTshirt.adr
        new(0x43525209, 2127, 9530, 2, 0x43524214),
        // 2137 Blue and Orange T-Shirt - SurvivorMale_Chest_Shirt_TintTshirt.adr
        new(0x4352520A, 2137, 9525, 1, 0x43524215),
        // 2137 Blue and Orange T-Shirt - SurvivorFemale_Chest_Shirt_TintTshirt.adr
        new(0x4352520B, 2137, 9530, 2, 0x43524215),
        // 2139 Gray Camo T-Shirt - SurvivorMale_Chest_Shirt_TintTshirt.adr
        new(0x4352520C, 2139, 9525, 1, 0x43524216),
        // 2139 Gray Camo T-Shirt - SurvivorFemale_Chest_Shirt_TintTshirt.adr
        new(0x4352520D, 2139, 9530, 2, 0x43524216),
        // 2141 Grey Blue T-Shirt - SurvivorMale_Chest_Shirt_TintTshirt.adr
        new(0x4352520E, 2141, 9525, 1, 0x43524217),
        // 2141 Grey Blue T-Shirt - SurvivorFemale_Chest_Shirt_TintTshirt.adr
        new(0x4352520F, 2141, 9530, 2, 0x43524217),
        // 2142 Gray and Blue Striped Tee - SurvivorMale_Chest_Shirt_TintTshirt.adr
        new(0x43525210, 2142, 9525, 1, 0x43524218),
        // 2142 Gray and Blue Striped Tee - SurvivorFemale_Chest_Shirt_TintTshirt.adr
        new(0x43525211, 2142, 9530, 2, 0x43524218),
        // 2145 Navy T-Shirt - SurvivorMale_Chest_Shirt_TintTshirt.adr
        new(0x43525212, 2145, 9525, 1, 0x43524219),
        // 2145 Navy T-Shirt - SurvivorFemale_Chest_Shirt_TintTshirt.adr
        new(0x43525213, 2145, 9530, 2, 0x43524219),
        // 2168 Black Motorcycle Helmet - SurvivorMale_Head_Helmet_Motorcycle_Tintable.adr
        new(0x43525214, 2168, 9645, 1, 0x4352421A),
        // 2168 Black Motorcycle Helmet - SurvivorFemale_Head_Helmet_Motorcycle_Tintable.adr
        new(0x43525215, 2168, 9647, 2, 0x4352421A),
        // 2171 White Motorcycle Helmet - SurvivorMale_Head_Helmet_Motorcycle_Tintable.adr
        new(0x43525216, 2171, 9645, 1, 0x4352421B),
        // 2171 White Motorcycle Helmet - SurvivorFemale_Head_Helmet_Motorcycle_Tintable.adr
        new(0x43525217, 2171, 9647, 2, 0x4352421B),
        // 2218 White Conveys Sneakers - SurvivorMale_Feet_Conveys_Tintable.adr
        new(0x43525218, 2218, 9632, 1, 0x4352421C),
        // 2218 White Conveys Sneakers - SurvivorFemale_Feet_Conveys_Tintable.adr
        new(0x43525219, 2218, 9633, 2, 0x4352421C),
    ];

    /// <summary>
    /// Six shader parameters per authored group: the measured ramp on branch A, and either a
    /// second measured ramp (a two-colour item) or the client's own <c>Default</c> neutral on
    /// branch B.
    /// </summary>
    public static readonly ImmutableArray<DynamicAppearanceShaderValue> ShaderValues =
    [
        // 2112 Black Backpack: backpack map p92/p50/p08 ramp x (0.055, 0.055, 0.060)
        new(0x43524210, "BaseTintHighlightA", new Vector4(0.083132f, 0.083132f, 0.090689f, 0.500000f)),
        new(0x43524210, "BaseTintMidtoneA", new Vector4(0.055000f, 0.055000f, 0.060000f, 0.500000f)),
        new(0x43524210, "BaseTintShadowA", new Vector4(0.024618f, 0.024618f, 0.026855f, 0.500000f)),
        new(0x43524210, "BaseTintHighlightB", new Vector4(1.000000f, 1.000000f, 1.000000f, 0.500000f)),
        new(0x43524210, "BaseTintMidtoneB", new Vector4(0.500000f, 0.500000f, 0.500000f, 0.500000f)),
        new(0x43524210, "BaseTintShadowB", new Vector4(0.000000f, 0.000000f, 0.000000f, 0.500000f)),
        // 2113 Blue Backpack: backpack map p92/p50/p08 ramp x (0.145, 0.290, 0.640)
        new(0x43524211, "BaseTintHighlightA", new Vector4(0.219166f, 0.438332f, 0.967354f, 0.500000f)),
        new(0x43524211, "BaseTintMidtoneA", new Vector4(0.145000f, 0.290000f, 0.640000f, 0.500000f)),
        new(0x43524211, "BaseTintShadowA", new Vector4(0.064901f, 0.129801f, 0.286458f, 0.500000f)),
        new(0x43524211, "BaseTintHighlightB", new Vector4(1.000000f, 1.000000f, 1.000000f, 0.500000f)),
        new(0x43524211, "BaseTintMidtoneB", new Vector4(0.500000f, 0.500000f, 0.500000f, 0.500000f)),
        new(0x43524211, "BaseTintShadowB", new Vector4(0.000000f, 0.000000f, 0.000000f, 0.500000f)),
        // 2115 Green Backpack: backpack map p92/p50/p08 ramp x (0.150, 0.400, 0.180)
        new(0x43524212, "BaseTintHighlightA", new Vector4(0.226724f, 0.604597f, 0.272068f, 0.500000f)),
        new(0x43524212, "BaseTintMidtoneA", new Vector4(0.150000f, 0.400000f, 0.180000f, 0.500000f)),
        new(0x43524212, "BaseTintShadowA", new Vector4(0.067139f, 0.179036f, 0.080566f, 0.500000f)),
        new(0x43524212, "BaseTintHighlightB", new Vector4(1.000000f, 1.000000f, 1.000000f, 0.500000f)),
        new(0x43524212, "BaseTintMidtoneB", new Vector4(0.500000f, 0.500000f, 0.500000f, 0.500000f)),
        new(0x43524212, "BaseTintShadowB", new Vector4(0.000000f, 0.000000f, 0.000000f, 0.500000f)),
        // 2117 Red Backpack: backpack map p92/p50/p08 ramp x (0.610, 0.105, 0.100)
        new(0x43524213, "BaseTintHighlightA", new Vector4(0.922010f, 0.158707f, 0.151149f, 0.500000f)),
        new(0x43524213, "BaseTintMidtoneA", new Vector4(0.610000f, 0.105000f, 0.100000f, 0.500000f)),
        new(0x43524213, "BaseTintShadowA", new Vector4(0.273030f, 0.046997f, 0.044759f, 0.500000f)),
        new(0x43524213, "BaseTintHighlightB", new Vector4(1.000000f, 1.000000f, 1.000000f, 0.500000f)),
        new(0x43524213, "BaseTintMidtoneB", new Vector4(0.500000f, 0.500000f, 0.500000f, 0.500000f)),
        new(0x43524213, "BaseTintShadowB", new Vector4(0.000000f, 0.000000f, 0.000000f, 0.500000f)),
        // 2127 Green Army Shirt: shirt map p92/p50/p08 ramp x (0.290, 0.310, 0.170)
        new(0x43524214, "BaseTintHighlightA", new Vector4(0.335207f, 0.358325f, 0.196501f, 0.500000f)),
        new(0x43524214, "BaseTintMidtoneA", new Vector4(0.290000f, 0.310000f, 0.170000f, 0.500000f)),
        new(0x43524214, "BaseTintShadowA", new Vector4(0.185985f, 0.198811f, 0.109025f, 0.500000f)),
        new(0x43524214, "BaseTintHighlightB", new Vector4(1.000000f, 1.000000f, 1.000000f, 0.500000f)),
        new(0x43524214, "BaseTintMidtoneB", new Vector4(0.500000f, 0.500000f, 0.500000f, 0.500000f)),
        new(0x43524214, "BaseTintShadowB", new Vector4(0.000000f, 0.000000f, 0.000000f, 0.500000f)),
        // 2137 Blue and Orange T-Shirt: shirt map p92/p50/p08 ramp x (0.145, 0.290, 0.640) with a second branch
        new(0x43524215, "BaseTintHighlightA", new Vector4(0.167603f, 0.335207f, 0.739767f, 0.500000f)),
        new(0x43524215, "BaseTintMidtoneA", new Vector4(0.145000f, 0.290000f, 0.640000f, 0.500000f)),
        new(0x43524215, "BaseTintShadowA", new Vector4(0.092992f, 0.185985f, 0.410449f, 0.500000f)),
        new(0x43524215, "BaseTintHighlightB", new Vector4(0.994062f, 0.479693f, 0.104030f, 0.500000f)),
        new(0x43524215, "BaseTintMidtoneB", new Vector4(0.860000f, 0.415000f, 0.090000f, 0.500000f)),
        new(0x43524215, "BaseTintShadowB", new Vector4(0.551540f, 0.266150f, 0.057719f, 0.500000f)),
        // 2139 Gray Camo T-Shirt: shirt map p92/p50/p08 ramp x (0.440, 0.440, 0.455) with a second branch
        new(0x43524216, "BaseTintHighlightA", new Vector4(0.508590f, 0.508590f, 0.525928f, 0.500000f)),
        new(0x43524216, "BaseTintMidtoneA", new Vector4(0.440000f, 0.440000f, 0.455000f, 0.500000f)),
        new(0x43524216, "BaseTintShadowA", new Vector4(0.282183f, 0.282183f, 0.291803f, 0.500000f)),
        new(0x43524216, "BaseTintHighlightB", new Vector4(0.279724f, 0.279724f, 0.289260f, 0.500000f)),
        new(0x43524216, "BaseTintMidtoneB", new Vector4(0.242000f, 0.242000f, 0.250250f, 0.500000f)),
        new(0x43524216, "BaseTintShadowB", new Vector4(0.155201f, 0.155201f, 0.160492f, 0.500000f)),
        // 2141 Grey Blue T-Shirt: shirt map p92/p50/p08 ramp x (0.440, 0.440, 0.455) with a second branch
        new(0x43524217, "BaseTintHighlightA", new Vector4(0.508590f, 0.508590f, 0.525928f, 0.500000f)),
        new(0x43524217, "BaseTintMidtoneA", new Vector4(0.440000f, 0.440000f, 0.455000f, 0.500000f)),
        new(0x43524217, "BaseTintShadowA", new Vector4(0.282183f, 0.282183f, 0.291803f, 0.500000f)),
        new(0x43524217, "BaseTintHighlightB", new Vector4(0.167603f, 0.335207f, 0.739767f, 0.500000f)),
        new(0x43524217, "BaseTintMidtoneB", new Vector4(0.145000f, 0.290000f, 0.640000f, 0.500000f)),
        new(0x43524217, "BaseTintShadowB", new Vector4(0.092992f, 0.185985f, 0.410449f, 0.500000f)),
        // 2142 Gray and Blue Striped Tee: shirt map p92/p50/p08 ramp x (0.440, 0.440, 0.455) with a second branch
        new(0x43524218, "BaseTintHighlightA", new Vector4(0.508590f, 0.508590f, 0.525928f, 0.500000f)),
        new(0x43524218, "BaseTintMidtoneA", new Vector4(0.440000f, 0.440000f, 0.455000f, 0.500000f)),
        new(0x43524218, "BaseTintShadowA", new Vector4(0.282183f, 0.282183f, 0.291803f, 0.500000f)),
        new(0x43524218, "BaseTintHighlightB", new Vector4(0.167603f, 0.335207f, 0.739767f, 0.500000f)),
        new(0x43524218, "BaseTintMidtoneB", new Vector4(0.145000f, 0.290000f, 0.640000f, 0.500000f)),
        new(0x43524218, "BaseTintShadowB", new Vector4(0.092992f, 0.185985f, 0.410449f, 0.500000f)),
        // 2145 Navy T-Shirt: shirt map p92/p50/p08 ramp x (0.075, 0.110, 0.270)
        new(0x43524219, "BaseTintHighlightA", new Vector4(0.086691f, 0.127147f, 0.312089f, 0.500000f)),
        new(0x43524219, "BaseTintMidtoneA", new Vector4(0.075000f, 0.110000f, 0.270000f, 0.500000f)),
        new(0x43524219, "BaseTintShadowA", new Vector4(0.048099f, 0.070546f, 0.173158f, 0.500000f)),
        new(0x43524219, "BaseTintHighlightB", new Vector4(1.000000f, 1.000000f, 1.000000f, 0.500000f)),
        new(0x43524219, "BaseTintMidtoneB", new Vector4(0.500000f, 0.500000f, 0.500000f, 0.500000f)),
        new(0x43524219, "BaseTintShadowB", new Vector4(0.000000f, 0.000000f, 0.000000f, 0.500000f)),
        // 2168 Black Motorcycle Helmet: helmet map p92/p50/p08 ramp x (0.055, 0.055, 0.060)
        new(0x4352421A, "BaseTintHighlightA", new Vector4(0.062333f, 0.062333f, 0.068000f, 0.500000f)),
        new(0x4352421A, "BaseTintMidtoneA", new Vector4(0.055000f, 0.055000f, 0.060000f, 0.500000f)),
        new(0x4352421A, "BaseTintShadowA", new Vector4(0.013933f, 0.013933f, 0.015200f, 0.500000f)),
        new(0x4352421A, "BaseTintHighlightB", new Vector4(1.000000f, 1.000000f, 1.000000f, 0.500000f)),
        new(0x4352421A, "BaseTintMidtoneB", new Vector4(0.500000f, 0.500000f, 0.500000f, 0.500000f)),
        new(0x4352421A, "BaseTintShadowB", new Vector4(0.000000f, 0.000000f, 0.000000f, 0.500000f)),
        // 2171 White Motorcycle Helmet: helmet map p92/p50/p08 ramp x (0.900, 0.900, 0.905)
        new(0x4352421B, "BaseTintHighlightA", new Vector4(1.000000f, 1.000000f, 1.000000f, 0.500000f)),
        new(0x4352421B, "BaseTintMidtoneA", new Vector4(0.900000f, 0.900000f, 0.905000f, 0.500000f)),
        new(0x4352421B, "BaseTintShadowA", new Vector4(0.228000f, 0.228000f, 0.229266f, 0.500000f)),
        new(0x4352421B, "BaseTintHighlightB", new Vector4(1.000000f, 1.000000f, 1.000000f, 0.500000f)),
        new(0x4352421B, "BaseTintMidtoneB", new Vector4(0.500000f, 0.500000f, 0.500000f, 0.500000f)),
        new(0x4352421B, "BaseTintShadowB", new Vector4(0.000000f, 0.000000f, 0.000000f, 0.500000f)),
        // 2218 White Conveys Sneakers: footwear map p92/p50/p08 ramp x (0.900, 0.900, 0.905)
        new(0x4352421C, "BaseTintHighlightA", new Vector4(1.000000f, 1.000000f, 1.000000f, 0.500000f)),
        new(0x4352421C, "BaseTintMidtoneA", new Vector4(0.900000f, 0.900000f, 0.905000f, 0.500000f)),
        new(0x4352421C, "BaseTintShadowA", new Vector4(0.430649f, 0.430649f, 0.433041f, 0.500000f)),
        new(0x4352421C, "BaseTintHighlightB", new Vector4(1.000000f, 1.000000f, 1.000000f, 0.500000f)),
        new(0x4352421C, "BaseTintMidtoneB", new Vector4(0.500000f, 0.500000f, 0.500000f, 0.500000f)),
        new(0x4352421C, "BaseTintShadowB", new Vector4(0.000000f, 0.000000f, 0.000000f, 0.500000f)),
    ];
}
