// <cranberry-provenance>
// Written by tools/pipeline/pipeline.py (docs/96). `pipeline.py check` recomputes every
// hash below and fails the build when one has moved; do not edit this block by hand.
// id: appearance-catalog
// grade: CAPTURED  thirdParty: true
// clientBuild: 0.0.118.208059
// generator: tools/appearance/gen-appearance-catalog.py sha256=a665667973f6be0268293447b5025effab49075e19d010ae5302fba7827298de
// input: out/data_aug/Models.txt sha256=1a7d89d3b84ccbdb0dc40c3351583116ddee801a3b365117447ec91b360b33c1 crc32=06ba7c27 size=95822 grade=CLIENT
// input: out/data_aug/pack-index-aug.tsv sha256=f48b6cc515289cfbf7ae54d5a4a0dfd25e659096722a1fa17fb98d048b14b336 crc32=5e09083b size=3624885 grade=CLIENT
// input: out/appearance-tints/z1-appearance-parsed.json sha256=a33b5ef93d433b8aa20e2f5a3d3c2f9bffb12601c25f73f16bd1b2c163c6a17b crc32=6940ef6f size=168955 grade=CAPTURED  thirdParty: true
// input: src/Cranberry.Zone/Data/Loot/z2-loot-tables.json sha256=b581d3f24b107452abe20ac7b8247ff634f9179ffd999a08f1b27972877c6d0f crc32=780ad7e5 size=49179 grade=CLIENT+RULING
// rulings: D22, D44, D84
// generatedUtc: 2026-09-08T18:13:06Z
// </cranberry-provenance>
// <auto-generated>
// Generated by tools/appearance/gen-appearance-catalog.py. The item-to-model association is the
// ModelId column of the D22-gated dynamic-appearance source (inflated 6,625,396 bytes, md5
// 59d33ecb0580512fa13c4a78d69d084b - the same gate AugustDynamicAppearanceTable enforces at
// runtime); every model id is resolved to a file through the August Models.txt and every file is
// confirmed present in the August asset packs. H1Z1.exe 0.0.118.208059. Do not edit.
// </auto-generated>

#nullable enable

namespace Cranberry.Zone.Appearance;

/// <summary>
/// The third-person mesh the August client wants on a character for one item, per gender, and
/// the shader parameter group that colours it.
/// </summary>
/// <param name="ItemDefinitionId"><c>ClientItemDefinitions</c> <c>*ID</c>.</param>
/// <param name="MaleModelId">Male <c>Models.txt</c> row.</param>
/// <param name="FemaleModelId">Female <c>Models.txt</c> row.</param>
/// <param name="MaleModelName">Male <c>.adr</c>, resolved through August <c>Models.txt</c>.</param>
/// <param name="FemaleModelName">Female <c>.adr</c>.</param>
/// <param name="ShaderParameterGroupId">
/// The colourway. docs/54 s1.3: this is the <em>only</em> live colour lever in this build - the
/// same mesh is Green (804), Black (805) and Red (812) backpack and nothing but this id tells
/// them apart. Wave 8 (docs/80 edit 3) puts it on the wire for a worn attachment when - and only
/// when - the transmitted appearance table defines parameter rows for the group, which is what
/// <c>AugustDynamicAppearanceTable.DefinesShaderGroup</c> answers; the 26 wearables the filter
/// discards still travel at 0, so docs/54 I4 remains its own experiment.
/// </param>
public readonly record struct AugustWornMesh(
    uint ItemDefinitionId,
    uint MaleModelId,
    uint FemaleModelId,
    string MaleModelName,
    string FemaleModelName,
    uint ShaderParameterGroupId)
{
    /// <summary>The mesh for a body of <paramref name="gender"/> (2 = female).</summary>
    public string ModelNameFor(uint gender) =>
        gender == CharacterVisuals.Female ? FemaleModelName : MaleModelName;
}

/// <summary>
/// Every item in Cranberry's Z2 loot roster that the dynamic-appearance table gives a worn mesh
/// for - 54 of the 72 distinct ids in <c>z2-loot-tables.json</c>.
/// <para>
/// The other 18 are ammunition, throwables, medical items, duct tape, the waist pack and
/// the machete, and every one of those that can be held carries a
/// <c>ClientItemDefinitions.MODEL_NAME</c> instead. The two resolvers are exactly complementary,
/// which is why <see cref="AugustWornVisuals"/> tries this one first and falls back to the sheet
/// (docs/54 s3.3).
/// </para>
/// </summary>
public static class AugustWornMeshCatalog
{
    /// <summary>Distinct item ids in <c>z2-loot-tables.json</c> at generation time.</summary>
    public const int RosterItemCount = 72;

    public static readonly IReadOnlyList<AugustWornMesh> Entries =
    [
        new(2, 9991, 9991, "Weapon_Pistol_45Auto_3P.adr", "Weapon_Pistol_45Auto_3P.adr", 745),
        new(10, 9591, 9591, "Weapon_M16A4_3P.adr", "Weapon_M16A4_3P.adr", 168),
        new(84, 9535, 9535, "Weapons_CombatKnife01_3P.adr", "Weapons_CombatKnife01_3P.adr", 73),
        new(1374, 9519, 9519, "Weapons_PumpShotgun01_3P.adr", "Weapons_PumpShotgun01_3P.adr", 29),
        new(1718, 9840, 9840, "Weapons_Pistol_44Magnum01_3P.adr", "Weapons_Pistol_44Magnum01_3P.adr", 1747),
        new(1986, 9880, 9880, "Weapons_Bow01_3P.adr", "Weapons_Bow01_3P.adr", 639),
        new(1991, 9886, 9886, "Weapon_Pistol_380Auto_3P.adr", "Weapon_Pistol_380Auto_3P.adr", 656),
        new(1997, 9848, 9848, "Weapons_M9Auto_3P.adr", "Weapons_M9Auto_3P.adr", 1919),
        new(2096, 9798, 9799, "SurvivorMale_Head_Hat_BaseballCap.adr", "SurvivorFemale_Head_Hat_BaseballCap.adr", 502),
        new(2100, 9798, 9799, "SurvivorMale_Head_Hat_BaseballCap.adr", "SurvivorFemale_Head_Hat_BaseballCap.adr", 500),
        new(2102, 9798, 9799, "SurvivorMale_Head_Hat_BaseballCap.adr", "SurvivorFemale_Head_Hat_BaseballCap.adr", 501),
        new(2104, 9798, 9799, "SurvivorMale_Head_Hat_BaseballCap.adr", "SurvivorFemale_Head_Hat_BaseballCap.adr", 508),
        new(2105, 9798, 9799, "SurvivorMale_Head_Hat_BaseballCap.adr", "SurvivorFemale_Head_Hat_BaseballCap.adr", 511),
        new(2106, 9798, 9799, "SurvivorMale_Head_Hat_BaseballCap.adr", "SurvivorFemale_Head_Hat_BaseballCap.adr", 512),
        new(2112, 10031, 10032, "SurvivorMale_Back_Backpack_Mansport_Tintable.adr", "SurvivorFemale_Back_Backpack_Mansport_Tintable.adr", 805),
        new(2113, 10031, 10032, "SurvivorMale_Back_Backpack_Mansport_Tintable.adr", "SurvivorFemale_Back_Backpack_Mansport_Tintable.adr", 806),
        new(2114, 10031, 10032, "SurvivorMale_Back_Backpack_Mansport_Tintable.adr", "SurvivorFemale_Back_Backpack_Mansport_Tintable.adr", 807),
        new(2115, 10031, 10032, "SurvivorMale_Back_Backpack_Mansport_Tintable.adr", "SurvivorFemale_Back_Backpack_Mansport_Tintable.adr", 804),
        new(2116, 10031, 10032, "SurvivorMale_Back_Backpack_Mansport_Tintable.adr", "SurvivorFemale_Back_Backpack_Mansport_Tintable.adr", 811),
        new(2117, 10031, 10032, "SurvivorMale_Back_Backpack_Mansport_Tintable.adr", "SurvivorFemale_Back_Backpack_Mansport_Tintable.adr", 812),
        new(2124, 9622, 9623, "SurvivorMale_Back_Backpack_Military.adr", "SurvivorFemale_Back_Backpack_Military.adr", 237),
        new(2127, 9525, 9530, "SurvivorMale_Chest_Shirt_TintTshirt.adr", "SurvivorFemale_Chest_Shirt_TintTshirt.adr", 592),
        new(2128, 9525, 9530, "SurvivorMale_Chest_Shirt_TintTshirt.adr", "SurvivorFemale_Chest_Shirt_TintTshirt.adr", 597),
        new(2137, 9525, 9530, "SurvivorMale_Chest_Shirt_TintTshirt.adr", "SurvivorFemale_Chest_Shirt_TintTshirt.adr", 595),
        new(2138, 9525, 9530, "SurvivorMale_Chest_Shirt_TintTshirt.adr", "SurvivorFemale_Chest_Shirt_TintTshirt.adr", 609),
        new(2139, 9525, 9530, "SurvivorMale_Chest_Shirt_TintTshirt.adr", "SurvivorFemale_Chest_Shirt_TintTshirt.adr", 768),
        new(2140, 9525, 9530, "SurvivorMale_Chest_Shirt_TintTshirt.adr", "SurvivorFemale_Chest_Shirt_TintTshirt.adr", 611),
        new(2141, 9525, 9530, "SurvivorMale_Chest_Shirt_TintTshirt.adr", "SurvivorFemale_Chest_Shirt_TintTshirt.adr", 794),
        new(2142, 9525, 9530, "SurvivorMale_Chest_Shirt_TintTshirt.adr", "SurvivorFemale_Chest_Shirt_TintTshirt.adr", 619),
        new(2143, 9525, 9530, "SurvivorMale_Chest_Shirt_TintTshirt.adr", "SurvivorFemale_Chest_Shirt_TintTshirt.adr", 797),
        new(2145, 9525, 9530, "SurvivorMale_Chest_Shirt_TintTshirt.adr", "SurvivorFemale_Chest_Shirt_TintTshirt.adr", 801),
        new(2162, 10113, 10114, "SurvivorMale_Head_Hat_Beanie.adr", "SurvivorFemale_Head_Hat_Beanie.adr", 944),
        new(2166, 10113, 10114, "SurvivorMale_Head_Hat_Beanie.adr", "SurvivorFemale_Head_Hat_Beanie.adr", 943),
        new(2168, 9645, 9647, "SurvivorMale_Head_Helmet_Motorcycle_Tintable.adr", "SurvivorFemale_Head_Helmet_Motorcycle_Tintable.adr", 601),
        new(2169, 9645, 9647, "SurvivorMale_Head_Helmet_Motorcycle_Tintable.adr", "SurvivorFemale_Head_Helmet_Motorcycle_Tintable.adr", 599),
        new(2170, 9645, 9647, "SurvivorMale_Head_Helmet_Motorcycle_Tintable.adr", "SurvivorFemale_Head_Helmet_Motorcycle_Tintable.adr", 600),
        new(2171, 9645, 9647, "SurvivorMale_Head_Helmet_Motorcycle_Tintable.adr", "SurvivorFemale_Head_Helmet_Motorcycle_Tintable.adr", 594),
        new(2172, 9636, 9637, "SurvivorMale_Head_Helmet_Tactical_ChipsScratches.adr", "SurvivorFemale_Head_Helmet_Tactical_ChipsScratches.adr", 271),
        new(2173, 10006, 10007, "SurvivorMale_Legs_Pants_StraightLeg.adr", "SurvivorFemale_Legs_Pants_StraightLeg.adr", 761),
        new(2174, 10006, 10007, "SurvivorMale_Legs_Pants_StraightLeg.adr", "SurvivorFemale_Legs_Pants_StraightLeg.adr", 760),
        new(2175, 10006, 10007, "SurvivorMale_Legs_Pants_StraightLeg.adr", "SurvivorFemale_Legs_Pants_StraightLeg.adr", 762),
        new(2176, 10006, 10007, "SurvivorMale_Legs_Pants_StraightLeg.adr", "SurvivorFemale_Legs_Pants_StraightLeg.adr", 757),
        new(2177, 10006, 10007, "SurvivorMale_Legs_Pants_StraightLeg.adr", "SurvivorFemale_Legs_Pants_StraightLeg.adr", 758),
        new(2178, 10006, 10007, "SurvivorMale_Legs_Pants_StraightLeg.adr", "SurvivorFemale_Legs_Pants_StraightLeg.adr", 759),
        new(2206, 9794, 9793, "SurvivorMale_Feet_Workboots.adr", "SurvivorFemale_Feet_Workboots.adr", 479),
        new(2207, 9794, 9793, "SurvivorMale_Feet_Workboots.adr", "SurvivorFemale_Feet_Workboots.adr", 482),
        new(2208, 9794, 9793, "SurvivorMale_Feet_Workboots.adr", "SurvivorFemale_Feet_Workboots.adr", 480),
        new(2209, 9794, 9793, "SurvivorMale_Feet_Workboots.adr", "SurvivorFemale_Feet_Workboots.adr", 481),
        new(2215, 9632, 9633, "SurvivorMale_Feet_Conveys_Tintable.adr", "SurvivorFemale_Feet_Conveys_Tintable.adr", 268),
        new(2216, 9632, 9633, "SurvivorMale_Feet_Conveys_Tintable.adr", "SurvivorFemale_Feet_Conveys_Tintable.adr", 266),
        new(2217, 9632, 9633, "SurvivorMale_Feet_Conveys_Tintable.adr", "SurvivorFemale_Feet_Conveys_Tintable.adr", 267),
        new(2218, 9632, 9633, "SurvivorMale_Feet_Conveys_Tintable.adr", "SurvivorFemale_Feet_Conveys_Tintable.adr", 268),
        new(2229, 9534, 9534, "Weapon_AK47_3P.adr", "Weapon_AK47_3P.adr", 71),
        new(2271, 9627, 9629, "SurvivorMale_Armor_Kevlar_Basic_Velcro.adr", "SurvivorFemale_Armor_Kevlar_Basic_Velcro.adr", 254),
    ];

    private static readonly Dictionary<uint, AugustWornMesh> ByItem =
        Entries.ToDictionary(entry => entry.ItemDefinitionId);

    /// <summary>The worn mesh for one item, or <c>false</c> when the appearance table has no
    /// row for it.</summary>
    public static bool TryGet(uint itemDefinitionId, out AugustWornMesh mesh) =>
        ByItem.TryGetValue(itemDefinitionId, out mesh);
}
