// <cranberry-provenance>
// Written by tools/pipeline/pipeline.py (docs/96). `pipeline.py check` recomputes every
// hash below and fails the build when one has moved; do not edit this block by hand.
// id: armour-facts
// grade: CLIENT
// clientBuild: 0.0.118.208059
// generator: tools/data/gen-armour-facts.py sha256=edd55c0967d89050e8cb9fd7f87b362f1c8c2da92751ad4565f3aa567b570efa
// input: out/data_aug/derived/loot.json sha256=8023e21b5f864e8d4b9e95e6e4f6dc9199e3a5a6543fad95ee2a828538cdae79 crc32=9d37015d size=2419885 grade=CLIENT
// rulings: D92
// generatedUtc: 2026-09-04T07:05:31Z
// </cranberry-provenance>
// <auto-generated>
// Generated by tools/data/gen-armour-facts.py from the August client's own datasheet
// out\data_aug\ClientItemDefinitions.txt (build 0.0.118.208059). Do not edit by hand;
// re-run the generator instead. Derivation and citations: docs/81-z1-port-shooting.md.
// </auto-generated>

#nullable enable

using System.Collections.Frozen;

namespace Cranberry.Zone.Combat;

/// <summary>
/// One armour-bearing row of <c>ClientItemDefinitions.txt</c>: the three columns the armour
/// model reads. <b>Every value is EXTRACTED</b> - nothing here is a Cranberry design choice.
/// </summary>
/// <param name="ItemId">The <c>ClientItemDefinitions</c> row id.</param>
/// <param name="ItemClass"><c>ITEM_CLASS</c>: 25041 body armour, 25000 head.</param>
/// <param name="Bulk"><c>BULK</c> - what separates the tiers.</param>
public readonly record struct AugustArmourFact(uint ItemId, uint ItemClass, uint Bulk);

/// <summary>
/// The 106 rows the August client marks <c>IS_ARMOR</c> in classes 25041 (38 body
/// armour) and 25000 (68 head). A row absent from this table is not armour - which is
/// what keeps a beanie from stopping a rifle round.
/// </summary>
public static class AugustArmourFacts
{
    /// <summary><c>ItemClasses.BODY_ARMOR</c>.</summary>
    public const uint BodyArmourClass = 25041;

    /// <summary>The head slot's item class; hats and masks live here too, without IS_ARMOR.</summary>
    public const uint HeadClass = 25000;

    /// <summary>Every row, in item-id order.</summary>
    public static IReadOnlyList<AugustArmourFact> All => Rows;

    /// <summary>Look one item up. An id the table does not carry is not an error.</summary>
    public static bool TryGet(uint itemDefinitionId, out AugustArmourFact fact) =>
        ById.TryGetValue(itemDefinitionId, out fact);

    private static readonly AugustArmourFact[] Rows =
    [
        new(2042u, 25000u, 250u),
        new(2043u, 25000u, 250u),
        new(2044u, 25000u, 250u),
        new(2045u, 25000u, 250u),
        new(2062u, 25000u, 250u),
        new(2063u, 25000u, 250u),
        new(2076u, 25000u, 250u),
        new(2077u, 25000u, 250u),
        new(2078u, 25000u, 250u),
        new(2168u, 25000u, 250u),
        new(2169u, 25000u, 250u),
        new(2170u, 25000u, 250u),
        new(2171u, 25000u, 250u),
        new(2172u, 25000u, 250u),
        new(2204u, 25041u, 50u),  // Survivor<gender>_Armor_Makeshift_Wood.adr
        new(2205u, 25041u, 50u),  // Survivor<gender>_Armor_Makeshift_WoodMetal.adr
        new(2227u, 25000u, 250u),
        new(2271u, 25041u, 1000u),
        new(2274u, 25041u, 1000u),
        new(2290u, 25000u, 250u),
        new(2396u, 25000u, 250u),
        new(2477u, 25041u, 1000u),
        new(2545u, 25041u, 1000u),
        new(2546u, 25041u, 1000u),
        new(2547u, 25041u, 1000u),
        new(2745u, 25000u, 250u),
        new(2748u, 25000u, 250u),
        new(2750u, 25000u, 250u),  // Survivor<gender>_Head_Mask_Scarecrow.adr
        new(2775u, 25041u, 1000u),
        new(2784u, 25041u, 1000u),
        new(2815u, 25000u, 250u),  // Survivor<gender>_Head_Helmet_TacticalSantaHat.adr
        new(2817u, 25000u, 250u),  // Survivor<gender>_Head_Helmet_TacticalAntlers.adr
        new(2818u, 25000u, 250u),  // Survivor<gender>_Head_Helmet_TacticalSantaHat.adr
        new(2827u, 25000u, 250u),
        new(2828u, 25000u, 250u),
        new(2829u, 25000u, 250u),
        new(2830u, 25000u, 250u),
        new(2838u, 25000u, 250u),
        new(2860u, 25041u, 1000u),
        new(2862u, 25041u, 1000u),
        new(2863u, 25041u, 1000u),
        new(2864u, 25041u, 1000u),
        new(2865u, 25041u, 1000u),
        new(2866u, 25041u, 1000u),
        new(2966u, 25041u, 1000u),
        new(2967u, 25041u, 1000u),
        new(2968u, 25041u, 1000u),
        new(3064u, 25000u, 250u),
        new(3124u, 25000u, 250u),
        new(3125u, 25041u, 1000u),
        new(3126u, 25041u, 1000u),
        new(3159u, 25000u, 250u),
        new(3160u, 25000u, 250u),
        new(3167u, 25000u, 250u),
        new(3175u, 25041u, 1000u),
        new(3181u, 25000u, 250u),
        new(3182u, 25041u, 1000u),
        new(3366u, 25000u, 250u),
        new(3367u, 25000u, 250u),
        new(3378u, 25041u, 325u),
        new(3409u, 25000u, 250u),
        new(3413u, 25041u, 1000u),
        new(3414u, 25000u, 250u),
        new(3439u, 25000u, 250u),
        new(3440u, 25000u, 250u),
        new(3441u, 25000u, 250u),
        new(3451u, 25000u, 250u),
        new(3470u, 25000u, 250u),  // SurvivorMale_Head_Mask_UncleSam.adr
        new(3474u, 25000u, 250u),  // Survivor<gender>_Head_Mask_UncleSam.adr
        new(3483u, 25041u, 1000u),
        new(3487u, 25000u, 250u),
        new(3545u, 25000u, 250u),
        new(3546u, 25000u, 250u),
        new(3549u, 25041u, 1000u),
        new(3551u, 25000u, 250u),
        new(3581u, 25000u, 250u),
        new(3587u, 25041u, 1000u),
        new(3631u, 25000u, 250u),
        new(3721u, 25000u, 250u),
        new(3722u, 25041u, 1000u),
        new(3727u, 25000u, 250u),
        new(3732u, 25000u, 250u),  // Survivor<gender>_Head_Mask_Pig.adr
        new(3739u, 25000u, 250u),
        new(3862u, 25000u, 250u),
        new(3886u, 25000u, 250u),
        new(3892u, 25041u, 1000u),
        new(3899u, 25000u, 250u),
        new(3901u, 25041u, 1000u),
        new(3933u, 25000u, 250u),
        new(4013u, 25000u, 250u),
        new(4017u, 25041u, 1000u),
        new(4018u, 25000u, 250u),
        new(4022u, 25041u, 325u),
        new(4023u, 25000u, 250u),
        new(4026u, 25041u, 1000u),
        new(4029u, 25000u, 250u),
        new(4068u, 25041u, 325u),
        new(4166u, 25000u, 250u),
        new(4169u, 25041u, 1000u),
        new(4170u, 25000u, 250u),
        new(4173u, 25041u, 1000u),
        new(4175u, 25000u, 250u),
        new(4182u, 25000u, 250u),
        new(4183u, 25041u, 325u),
        new(4269u, 25000u, 250u),
        new(4567u, 25000u, 250u),
    ];

    private static readonly FrozenDictionary<uint, AugustArmourFact> ById =
        Rows.ToFrozenDictionary(row => row.ItemId);
}
