using Cranberry.Zone.Vehicles;

namespace Cranberry.Tests.Zone.Vehicles;

/// <summary>
/// The shipped roster and anchor set (<c>src/Cranberry.Zone/Data/Vehicles</c>, generated by
/// <c>tools/world/vehicle_anchors.py</c> from the client's own datasheets and world file).
///
/// <para>These tests pin the four client vehicle ids, their models and seats, and the current
/// reference/geometry join. See docs/vehicle-spawns-20260905.md for location provenance.</para>
/// </summary>
public sealed class VehicleRosterTests
{
    private static readonly Lazy<VehicleRoster> Roster = new(VehicleRoster.LoadDefault);
    private static readonly Lazy<VehicleAnchorSet> Anchors = new(VehicleAnchorSet.LoadDefault);

    /// <summary>
    /// Four drivable vehicles, not eight: 13 is the parachute, 1337 the observer, and
    /// <b>15/16 are the <i>Ignition match-mode</i> variants, not hotwire variants</b> — the
    /// correction docs/43 §2.1 made from the binary's own strings.
    /// </summary>
    [Fact]
    public void TheRosterIsTheFourDrivableLandVehiclesWithTheirClientModelIds()
    {
        VehicleRoster roster = Roster.Value;

        Assert.Equal(4, roster.Count);
        Assert.Equal(new uint[] { 1, 2, 3, 5 }, roster.Vehicles.Select(v => v.VehicleId).ToArray());

        Assert.Equal(10060u, roster.Require(1).ModelId);
        Assert.Equal(9258u, roster.Require(2).ModelId);
        Assert.Equal(9301u, roster.Require(3).ModelId);
        Assert.Equal(9588u, roster.Require(5).ModelId);

        Assert.Equal(7226u, roster.Require(1).DestroyedModelId);
        Assert.Equal(9315u, roster.Require(2).DestroyedModelId);
        Assert.Equal(9316u, roster.Require(3).DestroyedModelId);
        Assert.Equal(9593u, roster.Require(5).DestroyedModelId);

        // The Ignition variants and the parachute must not be spawnable as cars.
        Assert.False(roster.TryGet(13, out _));
        Assert.False(roster.TryGet(15, out _));
        Assert.False(roster.TryGet(16, out _));
        Assert.Throws<KeyNotFoundException>(() => roster.Require(15));
    }

    [Fact]
    public void SeatCountsAndDriverSeatsMatchTheClientSeatTables()
    {
        VehicleRoster roster = Roster.Value;

        Assert.Equal(5, roster.Require(1).SeatCount);
        Assert.Equal(7, roster.Require(2).SeatCount);
        Assert.Equal(5, roster.Require(3).SeatCount);
        Assert.Equal(2, roster.Require(5).SeatCount);

        foreach (VehicleDefinition definition in roster.Vehicles)
        {
            Assert.Equal(0, definition.DriverSeat.Index);

            // "The driver seat never has CAN_FIRE" (docs/43 §5.1) — and every land seat can bail.
            Assert.False(definition.DriverSeat.CanFire);
            Assert.All(definition.Seats, seat => Assert.True(seat.CanBail));
            Assert.Single(definition.Seats.Where(seat => seat.IsDriver).ToArray());

            for (int index = 0; index < definition.SeatCount; index++)
            {
                Assert.True(definition.TryGetSeat(index, out VehicleSeatDefinition? seat));
                Assert.Equal(index, seat.Index);
            }

            Assert.False(definition.TryGetSeat(definition.SeatCount, out _));
            Assert.False(definition.TryGetSeat(-1, out _));
        }
    }

    /// <summary>
    /// Only the PickupTruck's exposed bed uses <c>SEAT_LOOP_NEXT_SEAT_ID</c>, and it forms two
    /// pairs: seats 2↔5 and 3↔6 (SeatInfo 7→26→7 and 16→27→16).
    /// </summary>
    [Fact]
    public void OnlyThePickupTruckBedFormsSeatLoopsAndTheyArePairs()
    {
        VehicleRoster roster = Roster.Value;

        foreach (VehicleDefinition definition in roster.Vehicles.Where(v => v.VehicleId != 2))
        {
            Assert.All(definition.Seats, seat => Assert.Equal(-1, seat.LoopNextSeatIndex));
        }

        VehicleDefinition truck = roster.Require(2);
        Assert.Equal(5, truck.Seats[2].LoopNextSeatIndex);
        Assert.Equal(6, truck.Seats[3].LoopNextSeatIndex);
        Assert.Equal(2, truck.Seats[5].LoopNextSeatIndex);
        Assert.Equal(3, truck.Seats[6].LoopNextSeatIndex);
    }

    /// <summary>
    /// The eight <c>MoveInfo</c> ordinals of docs/43 §2.2, including the two facts the damage map
    /// rests on: ordinal 5 is the only row with <c>MAX_FORWARD</c> 0, and the PoliceCar is the
    /// fastest vehicle in the roster at 105.
    /// </summary>
    [Fact]
    public void EveryVehicleHasEightDriveModesWithOrdinalFiveImmobilised()
    {
        VehicleRoster roster = Roster.Value;

        foreach (VehicleDefinition definition in roster.Vehicles)
        {
            Assert.Equal(8, definition.DriveModes.Count);
            Assert.Equal(new[] { 0, 1, 2, 3, 4, 5, 6, 7 }, definition.DriveModes.Select(m => m.Ordinal).ToArray());
            Assert.Equal(new uint[] { 1, 2, 9, 8, 10, 10, 11, 12 }, definition.DriveModes.Select(m => m.MovementMode).ToArray());

            Assert.Equal(0f, definition.DriveModes[5].MaxForward);
            Assert.Equal(85f, definition.DriveModes[0].MaxForward);
            Assert.Equal(65f, definition.DriveModes[6].MaxForward);
        }

        Assert.Equal(105f, roster.Require(3).TopMaxForward);
        Assert.Equal(90f, roster.Require(1).TopMaxForward);
        Assert.Equal(100f, roster.Require(5).TopMaxForward);
    }

    /// <summary>
    /// <c>MAX_DISMOUNT_SPEED_OVERRIDE</c> is 0 on all four land rows, so the build's own
    /// <c>Vehicle.DefaultMaxDismountSpeed</c> of 12 applies to every one of them — and the client
    /// enforces the same number, so the server must too.
    /// </summary>
    [Fact]
    public void TheBuildsNamedVehicleConstantsAreCarriedThrough()
    {
        VehicleRoster roster = Roster.Value;

        Assert.Equal(1000, roster.Constants.InteractionCooldownMs);
        Assert.Equal(250, roster.Constants.SeatSwapCooldownMs);
        Assert.Equal(12f, roster.Constants.DefaultMaxDismountSpeed);
        Assert.Equal(10f, roster.Constants.DefaultMinDismountDamageSpeed);
        Assert.All(roster.Vehicles, v => Assert.Equal(12f, v.MaxDismountSpeed));
    }

    [Fact]
    public void ARosterWithTheWrongSchemaOrAGappySeatRunIsRejected()
    {
        Assert.Throws<InvalidDataException>(() =>
            VehicleRoster.Parse("""{"schema":"cranberry/vehicle-roster/0"}"""u8, "test"));

        const string gappySeats = """
        {
          "schema": "cranberry/vehicle-roster/1",
          "constants": {"interactionCooldownMs":1000,"seatSwapCooldownMs":250,
                        "defaultMaxDismountSpeed":12,"defaultMinDismountDamageSpeed":10},
          "vehicles": [{
            "id":1,"name":"OffRoader","nameId":16,"modelId":7225,"modelFile":"x.adr",
            "destroyedModelId":7226,"physicsFamily":10,"decaySeconds":1,"maxDismountSpeed":12,
            "seats":[{"index":0,"seatInfoId":1,"isDriver":true,"canFire":false,"canBail":true,
                      "enclosed":true,"kickCorpse":false,"loopNextSeatIndex":-1},
                     {"index":2,"seatInfoId":3,"isDriver":false,"canFire":true,"canBail":true,
                      "enclosed":true,"kickCorpse":false,"loopNextSeatIndex":-1}],
            "driveModes":[]
          }]
        }
        """;

        // The seat index is an array position on the wire, so a gap is a hard error, not a warning.
        InvalidDataException gap = Assert.Throws<InvalidDataException>(() =>
            VehicleRoster.Parse(System.Text.Encoding.UTF8.GetBytes(gappySeats), "test"));
        Assert.Contains("dense", gap.Message, StringComparison.Ordinal);
    }

    // --- the anchor set ------------------------------------------------------------------------

    [Fact]
    public void ShippedCatalogueCompletelyReplacesLegacyLocationsAcrossTheWholeMap()
    {
        VehicleAnchorSet anchors = Anchors.Value;
        Assert.Equal(550, anchors.Count);
        Assert.Equal(550, anchors.TotalSpaces);
        Assert.Equal(85, anchors.AreaCount);
        Assert.Equal(347, anchors.Anchors.ToArray().Count(a => a.HasArea));
        Assert.All(anchors.Anchors.ToArray(), a => Assert.True(a.InstanceId > 406));
        Assert.Equal(4, anchors.Anchors.ToArray().Select(a => (a.Position.X >= 0, a.Position.Z >= 0)).Distinct().Count());
        Assert.Equal(124, anchors.Anchors.ToArray().Count(a => a.VehicleId == 1));
        Assert.Equal(120, anchors.Anchors.ToArray().Count(a => a.VehicleId == 2));
        Assert.Equal(115, anchors.Anchors.ToArray().Count(a => a.VehicleId == 3));
        Assert.Equal(191, anchors.Anchors.ToArray().Count(a => a.VehicleId == 5));
        Assert.NotEqual(VehicleAnchorSet.NoArea, anchors.AreaIndexOf("PVCommercialEast"));
        Assert.Equal(VehicleAnchorSet.NoArea, anchors.AreaIndexOf("NotAPlace"));
    }

    [Fact]
    public void KnownRetailLocationsInsideAugustBuildingsOrTerrainAreExcluded()
    {
        var anchors = Anchors.Value.Anchors.ToArray();
        // Exact retail pickup X/Z intersects Res_HouseSm_1A in August; two northern
        // markers are tens of metres beneath the August terrain. Never relocate them.
        Assert.DoesNotContain(anchors, a => a.InstanceId == 3175691724);
        Assert.DoesNotContain(anchors, a => a.InstanceId == 2992194313);
        Assert.DoesNotContain(anchors, a => a.InstanceId == 696231865);
    }

    /// <summary>
    /// Every accepted location retains a finite authored origin and heading.
    /// </summary>
    [Fact]
    public void EveryAnchorCarriesAFiniteGroundHeightAndAYaw()
    {
        VehicleAnchorSet anchors = Anchors.Value;

        foreach (VehicleAnchor anchor in anchors.Anchors)
        {
            Assert.True(float.IsFinite(anchor.Position.X));
            Assert.True(float.IsFinite(anchor.Position.Y));
            Assert.True(float.IsFinite(anchor.Position.Z));
            Assert.True(float.IsFinite(anchor.Yaw));
            Assert.True(float.IsFinite(anchor.Pitch));
            Assert.True(float.IsFinite(anchor.Roll));
            Assert.InRange(anchor.Spaces, 1, 17);
            Assert.InRange(anchor.AreaIndex, VehicleAnchorSet.NoArea, anchors.AreaCount - 1);
        }
    }

    /// <summary>A seeded plan is only reproducible if the anchor order is, so the loader insists.</summary>
    [Fact]
    public void AnUnsortedOrEmptyAnchorFileIsRejected()
    {
        const string unsorted = """
        {"schema":"cranberry/vehicle-anchors/1","anchors":[
          {"id":9,"x":0,"y":0,"z":0,"yaw":0,"spaces":1,"area":null},
          {"id":2,"x":0,"y":0,"z":0,"yaw":0,"spaces":1,"area":null}]}
        """;
        InvalidDataException error = Assert.Throws<InvalidDataException>(() =>
            VehicleAnchorSet.Parse(System.Text.Encoding.UTF8.GetBytes(unsorted), "test"));
        Assert.Contains("reproducible", error.Message, StringComparison.Ordinal);

        Assert.Throws<InvalidDataException>(() =>
            VehicleAnchorSet.Parse("""{"schema":"cranberry/vehicle-anchors/1","anchors":[]}"""u8, "test"));
    }
}
