#!/usr/bin/env python3
"""
gen-subloader-trace.py - emit gdb breakpoint commands that print the stream cursor offset at the
entry of every sub-loader of the SendSelfToClient record, from selfschema.py's JSON output.

At each sub-loader entry the stream pointer is in the argument register the caller uses
(arg 0 -> rcx, arg 1 -> rdx, arg 2 -> r8), and `cursor - base` is the number of record bytes
consumed so far. Comparing that with the offset the extractor predicted pinpoints the first
loader whose byte consumption differs from the static derivation.

Usage: python gen-subloader-trace.py <selfschema.json> <base.gdb> <out.gdb>
"""
import json
import re
import sys

json_path, base_path, out_path = sys.argv[1:4]
data = json.load(open(json_path, encoding="utf-8"))
REG = {0: "rcx", 1: "rdx", 2: "r8", 3: "r9"}

# one breakpoint per function; expected offsets are listed in call order in the message
expected: dict[str, list[int]] = {}
regs: dict[str, str] = {}
for row in data["rows"]:
    if row["kind"] != "enter":
        continue
    fn = row["func"]
    expected.setdefault(fn, []).append(row["offset"])
    m = re.search(r"stream at arg (\d)", row["note"])
    # the enter rows do not carry the arg index; take it from the per-function trees below
regs_by_fn: dict[str, int] = {}
for line in open(re.sub(r"\.json$", ".md", json_path), encoding="utf-8"):
    m = re.match(r"\s*call\s+(FUN_[0-9a-f]{9})\s+\(stream at arg (\d)", line)
    if m and m.group(1) not in regs_by_fn:
        regs_by_fn[m.group(1)] = int(m.group(2))

base = open(base_path, encoding="utf-8").read()
# insert the sub-loader breakpoints before the first top-level `continue` of the base script
# (the one that starts the traced run; the STOP1/STOP2 blocks follow it)
head, sep, tail = base.partition("\ncontinue\nprintf \"TRACE STOP1")
tail = "printf \"TRACE STOP1" + tail
lines = [head, "", "# --- generated by tools/selfschema/gen-subloader-trace.py: cursor offset at every sub-loader entry ---"]
lines.append("break *0x140a31140")
lines.append("commands")
lines.append("  silent")
lines.append("  set $stream = $rdx")
lines.append('  printf "TRACE LOADER_ENTER stream=%p base=%p length=%ld\\n", $stream, *(long*)$stream, *(long*)($stream+8)')
lines.append("  continue")
lines.append("end")
for fn, offs in expected.items():
    addr = "0x" + fn[4:]
    reg = REG.get(regs_by_fn.get(fn, 1), "rdx")
    exp = ",".join(str(o) for o in offs)
    lines.append(f"break *{addr}")
    lines.append("commands")
    lines.append("  silent")
    lines.append(f'  printf "TRACE ENTER {fn} expected={exp} consumed=%ld flag=%d\\n", *(long*)(${reg}+0x10) - *(long*)${reg}, *(char*)(${reg}+0x20)')
    lines.append("  continue")
    lines.append("end")
lines.append("")
# make the assert breakpoint report the stream state
out = "\n".join(lines) + "\ncontinue\n" + tail
out = out.replace(
    '  printf "TRACE ASSERT_BADBEEF\\n"',
    '  printf "TRACE ASSERT_BADBEEF consumed=%ld length=%ld flag=%d\\n", *(long*)($stream+0x10) - *(long*)$stream, *(long*)($stream+8), *(char*)($stream+0x20)\n'
    '  x/16xb *(long*)($stream+0x10)')
open(out_path, "w", encoding="utf-8", newline="\n").write(out)
print(f"[gen-subloader-trace] {len(expected)} sub-loader breakpoints -> {out_path}")
