#!/usr/bin/env python3
r"""gen-asset-index - the set of .adr actor files the August client actually ships.

WHY THIS TOOL EXISTS (docs/80 edit 11)

  AugustModelCatalog answers "does the file behind Models.txt row N ship?".  It cannot
  answer "does the file behind this NAME ship?", because a name can reach the wire without
  ever having been a Models.txt row: ClientItemDefinitions.MODEL_NAME is a filename column,
  and AugustWornVisuals.TryResolveMesh falls back to it for every roster item the dynamic
  appearance table has no row for.  Item 83 (Machete) is exactly that case, and the sheet
  spells its mesh ``Weapons_Machete01_3p.adr`` while the pack spells it
  ``Weapons_Machete01_3P.adr`` - a body slot (106) that wave 8 has just started dressing.

  So this emits the .adr half of the pack index: 3,406 names, a case-insensitive membership
  test, and a Canonical() that returns the pack's own spelling.  The generated server has no
  runtime dependency on the pack index itself.

INPUT
    ``C:\Aug2017\out\data_aug\pack-index-aug.tsv``   index of all 256 Assets_*.pack archives,
                                                     50,502 assets (August 0.0.118.208059)

OUTPUT
    ``src/Cranberry.Zone/Appearance/AugustAssetIndex.g.cs``
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

EXPECTED_PACK_ASSETS = 50_502


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data", type=Path, default=Path(r"C:\Aug2017\out\data_aug"))
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("src/Cranberry.Zone/Appearance/AugustAssetIndex.g.cs"),
    )
    args = parser.parse_args()

    lines = (args.data / "pack-index-aug.tsv").read_text(
        encoding="latin-1").splitlines()[1:]
    if len(lines) != EXPECTED_PACK_ASSETS:
        sys.exit(f"pack index has {len(lines)} assets, expected {EXPECTED_PACK_ASSETS}")

    # One row per NAME; the same .adr can appear in more than one pack, and when it does the
    # spellings agree (asserted below) so either row is the canonical one.
    canonical: dict[str, str] = {}
    for line in lines:
        name = line.split("\t")[0]
        if not name.lower().endswith(".adr"):
            continue
        key = name.lower()
        if key in canonical and canonical[key] != name:
            sys.exit(f"pack index spells {key} two ways: {canonical[key]} and {name}")
        canonical[key] = name

    names = sorted(canonical.values(), key=str.lower)
    out = args.out
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", encoding="utf-8", newline="\r\n") as handle:
        handle.write(f"""// <auto-generated>
// Generated by tools/appearance/gen-asset-index.py from an index of all 256 August
// Assets_*.pack archives ({EXPECTED_PACK_ASSETS:,} assets, H1Z1.exe 0.0.118.208059).
// Do not edit by hand; re-run the generator instead. Derivation: docs/80 edit 11.
// </auto-generated>

#nullable enable

using System.Collections.Frozen;

namespace Cranberry.Zone.Appearance;

/// <summary>
/// Every <c>.adr</c> actor file present in the August client's asset packs, by name.
/// <para>
/// <see cref="AugustModelCatalog"/> answers the same question keyed by <c>Models.txt</c> row id,
/// which is the right key for a spawner. It is the wrong key for an <em>attachment</em>: the
/// wire carries a file name, and <c>ClientItemDefinitions.MODEL_NAME</c> can name a file that has
/// no <c>Models.txt</c> row at all - item 83 (Machete) is one, and its slot 106 is a slot wave 8
/// has just started dressing. So this is the name-keyed half, and it is what makes a mesh the
/// client cannot load a boot-time census line rather than an invisible attachment.
/// </para>
/// </summary>
public static class AugustAssetIndex
{{
    /// <summary>Assets indexed across all 256 <c>Assets_*.pack</c> archives.</summary>
    public const int IndexedAssetCount = {EXPECTED_PACK_ASSETS};

    /// <summary><c>.adr</c> files among them.</summary>
    public const int ActorFileCount = {len(names)};

    /// <summary>
    /// Name to the pack's own spelling, case-insensitive. The sheet writes <c>_3p</c> where the
    /// packs write <c>_3P</c>, so the lookup must be insensitive and the value must be the pack's.
    /// </summary>
    private static readonly FrozenDictionary<string, string> ByName =
        new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {{
""")
        for name in names:
            handle.write(f'            ["{name}"] = "{name}",\n')
        handle.write("""        }.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase);

    /// <summary>True when a file of this name is in one of the asset packs.</summary>
    public static bool Ships(string? fileName) =>
        !string.IsNullOrEmpty(fileName) && ByName.ContainsKey(fileName);

    /// <summary>
    /// The pack's own spelling of <paramref name="fileName"/>, or <paramref name="fileName"/>
    /// unchanged when nothing of that name ships. Returning the input rather than an empty string
    /// is deliberate: this index covers <c>.adr</c> files only, and a caller that resolved a mesh
    /// some other way must not have it silently deleted.
    /// </summary>
    public static string Canonical(string fileName) =>
        string.IsNullOrEmpty(fileName)
            ? fileName
            : ByName.TryGetValue(fileName, out string? packed) ? packed : fileName;
}
""")

    print(f"{out}: {len(names):,} .adr names")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
