namespace Cranberry.Zone.World.Doors;

/// <summary>
/// Where <c>z2-doors.bin</c> is found at run time. Deliberately the same probe shape as
/// <c>Loot.LootDataPaths</c> — a deployed build reads <c>&lt;BaseDirectory&gt;/Data/Doors</c>, and a
/// plain <c>dotnet run</c> or <c>dotnet test</c> from the tree walks up to
/// <c>src/Cranberry.Zone/Data/Doors</c>, so the repository works with no deployment step.
/// <para>
/// It is a separate type rather than a call into <c>LootDataPaths</c> because the two datasets are
/// independent: a host may point <see cref="Override"/> at a hand-regenerated door file without
/// moving its loot tables, and the door data is generated by a different tool
/// (<c>tools/data/gen-doors.py</c>).
/// </para>
/// </summary>
public static class DoorDataPaths
{
    private const string RelativeInOutput = "Data/Doors";
    private const string RelativeInRepository = "src/Cranberry.Zone/Data/Doors";

    /// <summary>Set by the host to point at an explicit data directory; null uses the probe.</summary>
    public static string? Override { get; set; }

    /// <summary>Every directory the probe will look in, in order.</summary>
    public static IEnumerable<string> Candidates()
    {
        if (!string.IsNullOrEmpty(Override))
        {
            yield return Override;
        }

        string baseDirectory = AppContext.BaseDirectory;
        yield return Path.Combine(baseDirectory, RelativeInOutput);

        foreach (string root in new[] { baseDirectory, Directory.GetCurrentDirectory() })
        {
            DirectoryInfo? directory = new(root);
            while (directory is not null)
            {
                yield return Path.Combine(directory.FullName, RelativeInRepository);
                directory = directory.Parent;
            }
        }
    }

    /// <summary>First existing file of that name, or null.</summary>
    public static string? Find(string fileName)
    {
        foreach (string directory in Candidates())
        {
            string candidate = Path.Combine(directory, fileName);
            if (File.Exists(candidate))
            {
                return candidate;
            }
        }

        return null;
    }

    /// <summary>As <see cref="Find"/>, but throws with the whole probe list when nothing matches.</summary>
    public static string Require(string fileName) =>
        Find(fileName)
        ?? throw new FileNotFoundException(
            $"Door data file '{fileName}' not found. Looked in: " + string.Join(", ", Candidates()),
            fileName);
}
